cli/CHANGELOG.md, cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/backend/assets/default-schema.graphql, cli/crates/backend/src/consts.rs, cli/crates/cli/Cargo.toml, cli/crates/cli/src/dev.rs, cli/crates/cli/src/errors.rs, cli/crates/cli/src/main.rs, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml
- Adds a hint when `init` is run in an initialized project
- Fixes the CLI header being printed when printing completions
- Cleans up the CLI `main.rs` file
- Moves the default GraphQL schema to a file
=> Hint, completion fix, cleanup

cli/CHANGELOG.md, cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/backend/assets/default-schema.graphql, cli/crates/cli/Cargo.toml, cli/crates/cli/src/output.rs, cli/crates/cli/src/watercolor.rs, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/crates/server/src/consts.rs, cli/crates/server/src/servers.rs
- Outputs playground and endpoint links on `dev`
- Exports embedded files when downgrading a version as well as upgrading
- Updates the default schema to add a field other than id
=> allow downgrading CLI version

examples/nextjs/.gitignore
Thank you for providing a very great services.
When using the sample project, the `schema.grapql` file was listed in the `.gitignore` file and needed to be edited when deploying.
I thought it would be easier to use the example if it was removed from the target.
Thank you.
=> docs(examples/nextjs): remove schema.grapql from .gitignore

examples/nextjs/README.md
Use the correct codesandbox link.
=> fix: use correct codesandbox link in nextjs example

cli/crates/cli/tests/unique.rs, cli/crates/cli/tests/utils/environment.rs, cli/crates/cli/tests/utils/kill_with_children.rs, cli/rust-toolchain.toml
- Updates Rust to `1.63.0`
- Misc. Clippy fixes
=> clippy fixes, upgrade rust

cli/.gitignore, cli/about.hbs, cli/about.toml
- Adds the [`cargo-about`](https://github.com/EmbarkStudios/cargo-about) templates and allowed licenses to simplify license information creation
- Usage: `cargo about generate  -o "licenses.html" about.hbs`
=> Add cargo about template

cli/Cargo.lock, cli/crates/cli/Cargo.toml, cli/crates/cli/tests/concurrency-process.rs, cli/crates/cli/tests/concurrency-thread.rs, cli/crates/cli/tests/concurrency.rs, cli/crates/cli/tests/graphql/concurrency/mutation.graphql, cli/crates/cli/tests/graphql/concurrency/query.graphql, cli/crates/cli/tests/graphql/concurrency/schema.graphql, cli/crates/cli/tests/graphql/introspection.graphql, cli/crates/cli/tests/utils/async_client.rs, cli/crates/cli/tests/utils/client.rs, cli/crates/cli/tests/utils/consts.rs, cli/crates/cli/tests/utils/environment.rs, cli/crates/cli/tests/utils/macros.rs, cli/crates/cli/tests/utils/mod.rs
- Adds a concurrency test (disabled due to being long running, but can be used manually)
- Adds an async client for `Environment`
- Allows to create an environment from a different environment (same directory, different port)
- Updates path macros to version used in API (with optional and typing)
=> Add concurrency test

cli/Cargo.lock, cli/crates/server/Cargo.toml, cli/crates/server/src/servers.rs
This enables support for environment variables inferred from the environment of the process + .env files as supported by the [`dotenv`](https://crates.io/crates/dotenv) package.
=> GB-2050: Infer environment variables from the standard environment and `dotenv`

cli/crates/server/src/consts.rs, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- Bump the minimal supported Node.js version to `16.13.0` to match miniflare's new versions
=> Bump min node version

cli/crates/cli/src/output.rs
Hello! Noticed a small typo from the CLI when running the `init` command.
=> Fix init output typo

cli/Cargo.lock, cli/crates/cli/Cargo.toml, cli/crates/cli/src/cli_input.rs, cli/crates/cli/src/completions.rs, cli/crates/cli/src/main.rs
- Reverts the update to clap 4 as it crashes when built in release mode
=> revert clap 4 update

cli/changelog/0.11.0.md, cli/crates/cli/src/main.rs
- Prints the CLI header when running the `reset` command
=> Add reset to commands

cli/crates/server/src/servers.rs, cli/rust-toolchain.toml
- Clippy fixes for version `1.65.0`
- Update Rust to version `1.65.0`
=> update rust to 1.65.0

.github/actions/init_rust_job/action.yml
CI for MacOS didn't install `cargo-nextest` anymore, it only worked because we're re-using previous jobs cache. I also removed what seemed unnecessary for Linux. Not sure how it worked before without `musl-tools` though... ¯\\_(ツ)_/¯
=> fix(ci): Fix missing cargo-nextest for MacOS

.github/workflows/cli.yml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, flake.nix
Not specifying the "v4" feature worked when compiling the whole
workspace, but not for server package alone. So this blocked
`cargo publish` which only runs for a single package.
I'm adding an additional step to the CI to ensure we won't encounter
the same error.
=> fix release

cli/CHANGELOG.md, cli/changelog/0.14.1.md
The release 0.14.0 was a failure and we pushed 0.14.1 instead.
=> Rename change 0.14.0 to 0.14.1

cli/changelog/0.15.0.md, cli/rust-toolchain.toml
=> Set rust toolchain to 1.66

cli/Cargo.lock, cli/crates/cli/Cargo.toml, cli/crates/cli/tests/scalars.rs, cli/rust-toolchain.toml
- Updates Rust to version `1.67`
- Fixes related clippy warnings
- Updates `indoc` and `toml`
=> Update rust and deps

cli/crates/backend/src/server_api.rs, cli/crates/cli/src/cli_input.rs, cli/crates/cli/src/dev.rs, cli/crates/cli/src/main.rs, cli/crates/server/src/servers.rs
Use the inherited stdout, stderr for the miniflare process when the CLI is started with `--trace 2`.
To preserve current behavior (debug messages of CLI), use `--trace 1` . Passing `2` will print miniflare logs as well.
=> Print miniflare logs when tracing is enabled

cli/crates/server/src/servers.rs
If an error occurs e.g. during sqlite initialization, `Event::BridgeReady` is never sent.
=> Fail on bridge startup error instead of hanging forever

.github/workflows/cli.yml, cli/Cargo.lock, cli/crates/cli/tests/search.rs, cli/crates/server/Cargo.toml, cli/crates/server/src/errors.rs, cli/crates/server/src/servers.rs
The JS script will now store the complete parser result under the path provided, not just the schema registry. The parser result will contain additional properties such as resolvers detected in the schema.
=> Rework the interaction between the CLI and the schema parsing invocation

cli/crates/cli/tests/auth.rs, cli/crates/cli/tests/coercion.rs, cli/crates/cli/tests/concurrency_process.rs, cli/crates/cli/tests/concurrency_thread.rs, cli/crates/cli/tests/default_directive.rs, cli/crates/cli/tests/dev.rs, cli/crates/cli/tests/dev_watch.rs, cli/crates/cli/tests/length.rs, cli/crates/cli/tests/pagination.rs, cli/crates/cli/tests/relations.rs, cli/crates/cli/tests/reserved_dates.rs, cli/crates/cli/tests/scalars.rs, cli/crates/cli/tests/search.rs, cli/crates/cli/tests/unique.rs, cli/crates/cli/tests/utils/async_client.rs, cli/crates/cli/tests/utils/client.rs
Our tests currently contain _a lot_ of hand coded GQL JSON request bodies.  Seems a bit much to be typing these out every single time we want to make a GQL call, so I've put together a super simple builder API instead.
Thoughts?
=> Refactor the `Client::gql` functions in tests

.github/workflows/cli-partial-release.yml, .github/workflows/cli.yml
Checks if `beta`, `alpha` or `rc` are in the tag associated with the release.  If so, marks the GitHub release as prerelease and updates the `next` tag on npm instead of `latest`.
=> Update cli-partial-release to support prereleases

cli/about.toml
The build of 0.18.0-rc.1 failed because it found two licenses that weren't explicitly allowed.  I've added them to the list so that the build works.
=> Add Unlicese & zlib-acknowledgement to accepted licenses

cli/crates/server/src/consts.rs
The `@openapi` directive work requires NodeJS versions that support `fetch`.  This was stable from 18 onwards, so I'm increasing the MIN_NODE_VERSION to that so we get warnings when a user is on an older version instead of an obscure error.
=> Bump the minimum node version to 18

cli/Cargo.lock, cli/crates/cli/Cargo.toml, cli/crates/cli/tests/auth.rs, cli/crates/cli/tests/coercion.rs, cli/crates/cli/tests/concurrency_process.rs, cli/crates/cli/tests/concurrency_thread.rs, cli/crates/cli/tests/default_directive.rs, cli/crates/cli/tests/dev.rs, cli/crates/cli/tests/dev_watch.rs, cli/crates/cli/tests/environment_file.rs, cli/crates/cli/tests/environment_process.rs, cli/crates/cli/tests/init.rs, cli/crates/cli/tests/length.rs, cli/crates/cli/tests/openapi/main.rs, cli/crates/cli/tests/pagination.rs, cli/crates/cli/tests/relations.rs, cli/crates/cli/tests/reserved_dates.rs, cli/crates/cli/tests/reset.rs, cli/crates/cli/tests/scalars.rs, cli/crates/cli/tests/search.rs, cli/crates/cli/tests/unique.rs, cli/crates/cli/tests/utils/environment.rs
This used the [fslock](https://docs.rs/fslock) package to synchronise the access to the counter.
=> Introduce a synchronised file-based counter for the port number used in tests

packages/standalone/src/App.tsx
=> GB-3463: Add a dummy x-api-key header for local playground

cli/Cargo.lock
=> Downgrade cacache to 11.1.0 to get rid of the reflink dependency

.github/workflows/cli.yml, cli/crates/cli/tests/custom_resolvers.rs, cli/crates/cli/tests/snapshots/custom_resolvers__field_resolver_7_1.snap, cli/crates/cli/tests/utils/client.rs
Exposes `{ request { headers } }` as the third argument to resolvers.
=> GB-3487: Inject `request` into `context` with a `headers` field

cli/Cargo.lock, cli/crates/cli/src/dev.rs, cli/crates/cli/src/errors.rs, cli/crates/cli/tests/compilation_error.rs, cli/crates/cli/tests/environment_file.rs, cli/crates/cli/tests/environment_process.rs, cli/crates/cli/tests/graphql/compilation_error/query.graphql, cli/crates/cli/tests/graphql/compilation_error/resolver-mutation.graphql, cli/crates/cli/tests/graphql/compilation_error/resolver-schema.graphql, cli/crates/cli/tests/graphql/compilation_error/schema.graphql, cli/crates/cli/tests/graphql/search/create-person.graphql, cli/crates/cli/tests/scalars.rs, cli/crates/cli/tests/utils/async_client.rs, cli/crates/cli/tests/utils/client.rs, cli/crates/cli/tests/utils/consts.rs, cli/crates/cli/tests/utils/environment.rs, cli/crates/server/Cargo.toml, cli/crates/server/src/error_server.rs, cli/crates/server/src/error_server/error-page.html, cli/crates/server/src/error_server/server.rs, cli/crates/server/src/event.rs, cli/crates/server/src/file_watcher.rs, cli/crates/server/src/lib.rs, cli/crates/server/src/servers.rs, cli/crates/server/src/types.rs
- Continues the reload cycle on compilation errors, displays an error page instead of the playground and a GQL response instead of the endpoint containing the error
=> Keep reloading on compilation errors

cli/crates/backend/src/api/create.rs, cli/crates/backend/src/api/errors.rs
- Fixes an issue when no `.grafbase` folder exists in the project while running `create`
=> Fix create when no dot grafbase folder exists

cli/Cargo.lock, cli/crates/backend/src/api/consts.rs, cli/crates/backend/src/api/deploy.rs, cli/crates/backend/src/project.rs, cli/crates/cli/src/output/report.rs, cli/crates/cli/tests/utils/environment.rs, cli/crates/common/src/consts.rs, cli/crates/common/src/environment.rs, cli/crates/server/Cargo.toml, cli/crates/server/src/custom_resolvers.rs, cli/crates/server/src/servers.rs
This adds an mtime-based freshness check that enables the dev mode loop to avoid recompiling some of the resolvers (not the newly attached ones, for one) on schema.graphql changes.
Right now the check is very limited, but it will cut out a large share of unnecessary rebuilds. We could be smarter if we were aware of all the files that a particular resolver's build depends on, but that'd require analysing the module dependency graph. To be investigated in the future.
=> GB-3507: Add a short circuit to avoid resolvers getting rebuilt if only the schema.graphql file changes

.github/workflows/cli-partial-release.yml
We appear to always be marking releases as pre-release.  Not entirely sure why, but this is an attempt at a fix.
=> Try to fix the npm prerelease conditional

cli/crates/cli/src/cli_input.rs
Allow using `--trace` flag in release builds to ease debugging.
=> GB-3599: Make --trace available in release mode

cli/crates/cli/src/login.rs, cli/crates/cli/src/panic_hook/mod.rs, cli/crates/cli/src/panic_hook/report.rs, cli/crates/server/src/custom_resolvers.rs, cli/crates/server/src/servers.rs, cli/rust-toolchain.toml
- Updates to Rust 1.69
- Fixes related Clippy issues
=> GB-3654 - Update to Rust 1.69 and fix related Clippy issues

.github/workflows/cli.yml, cli/crates/cli/tests/openapi/main.rs, cli/crates/cli/tests/openapi/remote_union_spec.json, cli/crates/cli/tests/openapi/remote_unions.rs
This adds a test of the `@openapi` union fixes I've been working on over the past week and a bit.  Quite hard to test these thoroughly in the `api` repo right now (although I want to work on that), so at least wanted to get a test in this repo in the meantime.
=> Add a test of `@openapi` unions

cli/Makefile.toml
- Adds a script to bump the CLI versions to a specific semver
=> GB-3577 - Add bump script

cli/crates/server/src/file_watcher.rs, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- Converts the watcher to async to prevent it from hanging when encountering external errors
- Removes the engine requirement when installing the CLI as it's enforced by the CLI itself with a clearer error message
=> GB-3701 - async watcher

cli/Makefile.toml
- Fixes the `release` scripts in cases with `@` in the path
=> Fix release if you have a @ in your path

.github/actions/sanitize/action.yml, cli/.config/nextest.toml, cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/cli/tests/README.md, cli/crates/cli/tests/concurrency_process.rs, cli/crates/cli/tests/concurrency_thread.rs, cli/crates/cli/tests/openapi/main.rs, cli/crates/cli/tests/search.rs, cli/crates/cli/tests/utils/environment.rs, cli/crates/server/Cargo.toml, cli/crates/server/src/bridge/search.rs, cli/crates/server/src/servers.rs
Introduce feature `dynamodb` that is used for selecting between sqlite and dynamodb test harness. 
DynamoDB tests run the following steps:
1. `Environment.init` creates a new DynamoDB table
2. `grafbase dev` is called with the env var  `DYNAMODB_TABLE_NAME` and the inherited env vars.
3. After the test finishes, the table is dropped. In async context this must be done by the test.
=> GB-3604: Allow running CLI integration tests with DynamoDB Local

cli/crates/cli/tests/README.md, cli/crates/cli/tests/openapi/remote_unions.rs
Switch the test to `multi_thread` flavor and call `Environment::init_async` instead of `init` so that dynamodb cleanup routine in `Environment::drop` works.
=> Fix remote_unions_test when running with dynamodb

cli/crates/backend/src/api/create.rs, cli/crates/cli/src/cli_input.rs, cli/crates/cli/src/create.rs, cli/crates/cli/src/deploy.rs, cli/crates/cli/src/errors.rs, cli/crates/cli/src/main.rs, cli/crates/cli/src/output/report.rs, cli/crates/cli/src/reset.rs
- Allows passing arguments to `create` rather than using interactive input|
```
Usage: grafbase create [OPTIONS]
Options:
-n, --name <name>       The name to use for the new project
-a, --account <slug>    The slug of the account in which the new project should be created
-r, --regions <region>  The regions in which the database for the new project should be created
-h, --help              Print help
```
- Fixes a few cases of output to STDERR instead of STDOUT
=> GB-3397 - Add argument support for `create`

cli/crates/cli/tests/utils/macros.rs
A small thing, but makes it a bit easier to spot problems when this fails.
=> Update `dot_get!` in the tests to pretty print.

cli/Cargo.lock, cli/Makefile.toml, cli/changelog/0.19.0.md, cli/crates/backend/Cargo.toml, cli/crates/backend/src/api/client.rs, cli/crates/backend/src/api/consts.rs, cli/crates/backend/src/api/errors.rs, cli/crates/cli/Cargo.toml, cli/crates/cli/src/errors.rs, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- Supports passing a `GRAFBASE_ACCESS_TOKEN` environment variable rather than logging in (e.g. for CI environments)
- Note: being logged in via `grafbase login` takes precedence over supplying `GRAFBASE_ACCESS_TOKEN`
- Version bumps and changelog for `0.19.0`
- `touch "changelog/$VERSION.md"` when running the `bump` script
=> GB-3729 - Support passing the access token via an env var

cli/crates/backend/src/server_api.rs, cli/crates/cli/src/dev.rs
Usually it's better in Rust to not nest too many layers with blocks. With this, we cut two nested blocks out, having more valuable horizontal space and better readability.
=> Flatten dev blocks for better readability

.github/actions/cdn_assets/action.yml, .github/actions/init_rust_job/action.yml, .github/actions/sanitize/action.yml, .github/workflows/cli-partial-release.yml, .github/workflows/cli.yml, cli/Cargo.lock, cli/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/cli/src/panic_hook/mod.rs, cli/crates/cli/src/panic_hook/report.rs, cli/crates/server/Cargo.toml, cli/crates/server/src/servers.rs, cli/crates/server/src/types.rs
CI for the CLI seems to take 25-30 minutes _most of the time_.  It's a bit
ridiculous.  This PR has a bunch of changes that seem to improve things:
1. Release builds on my laptop are also excruciatingly slow.  From some testing
this seems to be related to `RustEmbed` - I'm not sure whether it's the
compression rust embed is doing or the fact that it's including every binary
blob separately, but embedding a single `.tar.gz` manually halved release
compile time on my laptop.
2. The size of the assets we're embedding seem to have a direct impact on
compile times (probably due to [this rust issue](https://github.com/rust-lang/rust/issues/65818)).  A `.tar.gz` was a
good 30% smaller than a `.zip` so I'll have a separate PR to the `api` repo
to output one of these.  We could get some more …
=> Speed up CI for the CLI

packages/grafbase-sdk/src/grafbase-schema.ts, packages/grafbase-sdk/src/query.ts, packages/grafbase-sdk/tests/unit/queries.test.ts
Instead of having one block such as:
```graphql
extend type Query {
greet(name: String!): String! @resolver(name: "hello")
}
extend type Query {
sweet(name: String!): String! @resolver(name: "jello")
}
```
We should render them in one extend block:
```graphql
extend type Query {
greet(name: String!): String! @resolver(name: "hello")
sweet(name: String!): String! @resolver(name: "jello")
}
```
Same with mutations.
=> Gather all queries and mutations in one extend block per query type

packages/grafbase-sdk/README.md, packages/grafbase-sdk/src/grafbase-schema.ts, packages/grafbase-sdk/src/index.ts, packages/grafbase-sdk/src/openapi.ts, packages/grafbase-sdk/tests/unit/defaults.test.ts, packages/grafbase-sdk/tests/unit/interface.test.ts, packages/grafbase-sdk/tests/unit/openapi.test.ts, packages/grafbase-sdk/tests/unit/relation.test.ts
Allows creating OpenAPI connectors in the SDK config generator.
=> GB-3774: Implement OpenAPI connector(s) in the SDK

packages/grafbase-sdk/README.md, packages/grafbase-sdk/src/connector/graphql.ts, packages/grafbase-sdk/src/connector/header.ts, packages/grafbase-sdk/src/connector/openapi.ts, packages/grafbase-sdk/src/grafbase-schema.ts, packages/grafbase-sdk/src/index.ts, packages/grafbase-sdk/tests/unit/graphql.test.ts
Allows creating GraphQL connectors in the SDK config generator.
=> GB-3775: Implement GraphQL connector(s) in the SDK

cli/Cargo.lock, cli/crates/server/Cargo.toml, cli/crates/server/src/servers.rs
`tar-rs` has an issue where it won't overwrite files if they're stored as hard links in the tar.  We install our asset `node_modules` with pnpm, which uses hard links to deduplicate content.  This means `grafbase dev` will refuse to overwrite some existing files on startup.
I've [fixed this and PRd it](https://github.com/alexcrichton/tar-rs/pull/319), this pulls the fix in the meantime.
=> Pull in tar-rs fork to work around startup issue.

cli/crates/server/src/custom_resolvers.rs
Ensures the wrangler installation in Grafbase.com doesn't pull in 3.x.
This will go away when and if we drop the wrangler dependency.
=> Pin wrangler to 2.x

packages/grafbase-sdk/src/connector/openapi.ts, packages/grafbase-sdk/src/field/list.ts, packages/grafbase-sdk/src/index.ts, packages/grafbase-sdk/src/relation.ts, packages/grafbase-sdk/tests/unit/relation.test.ts
With the following config:
```typescript
const post = g.model('Post', {
title: g.string(),
content: g.string(),
author: g.relation(user).name('userPosts'),
comments: g.relation(() => comment).name('postComments').list()
})
const comment = g.model('Comment', {
comment: g.string(),
post: g.relation(post).name('postComments'),
author: g.relation(user).name('userComments')
})
```
The `comments` relation in the `Post` model rendered wrong SDL:
```graphql
comments: [Comment! @relation(name: "postComments")]!
```
This patch will render the `@relation` attribute correctly outside of the list.
=> Render relation name correctly outside of the list

packages/grafbase-sdk/README.md, packages/grafbase-sdk/package.json, packages/grafbase-sdk/src/cache.ts, packages/grafbase-sdk/src/model.ts, packages/grafbase-sdk/src/type.ts, packages/grafbase-sdk/src/typedefs/auth.ts, packages/grafbase-sdk/src/typedefs/cache.ts, packages/grafbase-sdk/src/typedefs/default.ts, packages/grafbase-sdk/src/typedefs/length-limited-string.ts, packages/grafbase-sdk/src/typedefs/resolver.ts, packages/grafbase-sdk/src/typedefs/scalar.ts, packages/grafbase-sdk/src/typedefs/search.ts, packages/grafbase-sdk/src/typedefs/unique.ts, packages/grafbase-sdk/tests/unit/cache.test.ts, packages/grafbase-sdk/tests/unit/model.test.ts, packages/grafbase-sdk/tests/unit/types.test.ts
Adds and fixes a few things in SDK caches:
- `fields` and `staleWhileRevalidate` are now optional
- Introduces `mutationInvalidation` param to global and type-level caches
Examples can be read from the [README](https://github.com/grafbase/grafbase/blob/sdk/cache-fixes/packages/grafbase-sdk/README.md#caching).
=> fix(sdk): Make fields and staleWhileRevalidate optional in global cache, introduce invalidation params

packages/grafbase-sdk/README.md, packages/grafbase-sdk/package.json, packages/grafbase-sdk/src/grafbase-schema.ts, packages/grafbase-sdk/src/type.ts, packages/grafbase-sdk/tests/unit/enum.test.ts, packages/grafbase-sdk/tests/unit/interface.test.ts, packages/grafbase-sdk/tests/unit/model.test.ts, packages/grafbase-sdk/tests/unit/types.test.ts
Closes: GB-3817
Allows extending types with custom resolvers. Either types that exist in the schema, or types introspected from connectors.
See README for usage.
=> feat(sdk): Extending internal and external types

.github/workflows/cli-partial-release.yml, .github/workflows/cli.yml, .github/workflows/packages.yml, cli/Makefile.toml, packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/RELEASING.md, packages/grafbase-sdk/changelog/0.0.15.md, packages/grafbase-sdk/package.json, packages/grafbase-sdk/scripts/bump-version.js, packages/grafbase-sdk/scripts/release.js, pnpm-lock.yaml
Closes: GB-3871
To bump `@grafbase/sdk`:
- `cd packages/grafbase-sdk`
- `npm run bump-patch|minor|major`
- `git commit -m "chore(sdk): Bump to version X.X.X`
- `git push`
To release `@grafbase/sdk`:
- `cd packages/grafbase/sdk`
- `npm run release`
The tags are now split into two:
- `cli-0.x.x` triggers CLI deployments
- `sdk-0.x.x` triggers SDK deployments
=> chore: Split cli and sdk tags. Implement sdk publish pipeline

.github/workflows/sdk.yml, packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.0.18.md, packages/grafbase-sdk/package.json
Authentication should be run in the project root for it to work.
=> fix(sdk): Run npm authentication in project root

.github/workflows/cli-partial-release.yml, .github/workflows/cli.yml, cli/Cargo.lock, cli/changelog/0.22.0-rc.2.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Fixes the Rudderstack variables and binary names from the first rc.
=> chore(cli): Bump to 0.22.0-rc.2

.github/workflows/cli.yml, cli/Cargo.lock, cli/changelog/0.22.0-rc.3.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Windows binaries were not generated correctly due to different handling of env vars. We now run it in bash to make it work similarly to Linux and macOS.
=> chore(cli): Bump to 0.22.0-rc.3

.github/workflows/cli-partial-release.yml
It tries to find it from `changelog/cli-version.md` instead of `changelog/version.md`.
=> fix(ci): Changelog name should be taken without the cli- prefix

cli/crates/common/src/analytics.rs
- Fixes the naming of the "Command Executed" event fields
=> Event-field-naming

cli/crates/cli/src/main.rs, cli/crates/common/src/analytics.rs
- Turns `commandArguments` in the `"Command Executed"` event to a comma separated string
=> Turn event args to a comma separated string

cli/crates/cli/tests/search.rs, cli/crates/server/src/bridge/api_counterfeit/search/query_builder.rs
- Fixes an issue resulting in failed searches when whitespace was present at the beginning or end of a query string
=> fix(search): Did not trim whitespace in the query

cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/backend/build.rs, cli/crates/backend/src/api/create.rs, cli/crates/backend/src/api/graphql/types.rs
I released a new version of cynic over the weekend.  Renovate has already pulled in the code, but it enables a few bits of cleanup in our code.
1. I added the a concept of "registering" a schema in `build.rs` which can save you passing the path to the schema file to every single derive.
2. Related to the above there's an rkyv feature flag that speeds up the derives somewhat (they don't have to parse the schema over and over again).
3. Most of the derives support generic params now, so you can use reference types for variables.  Simplifies the code in a few places.
=> Updates for cynic 3.0.0

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.0.20.md, packages/grafbase-sdk/package.json, packages/grafbase-sdk/src/typedefs/length-limited-string.ts, packages/grafbase-sdk/src/typedefs/list.ts, packages/grafbase-sdk/tests/unit/model.test.ts
Fixes: GB-3924
```ts
g.model('User', {
name: g.string().list().length({ min: 2, max: 255 })
})
```
```graphql
type User @model {
name: [String!]! @length(min: 2, max: 255)
}
```
=> fix(sdk): Length should be allowed on string list fields

cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/backend/src/api/deploy.rs, cli/crates/backend/src/api/errors.rs
- Ignores blacklisted files when building the deployment archive
=> GB-3734 - Ignore deployment files from blacklist

packages/grafbase-sdk/README.md, packages/grafbase-sdk/package.json, packages/grafbase-sdk/src/connector/graphql.ts, packages/grafbase-sdk/src/grafbase-schema.ts, packages/grafbase-sdk/src/index.ts, packages/grafbase-sdk/tests/unit/env.test.ts, pnpm-lock.yaml
Adds `g.env()` for easy env var support. In addition of the unit tests, also tested manually by generating a GitHub token, and then running a project with the following config:
```ts
import { g, config, connector } from '@grafbase/sdk'
const github = connector.GraphQL({
url: 'https://api.github.com/graphql',
headers: (headers) => {
headers.static('Authorization', `Bearer ${g.env('GITHUB_TOKEN')}`),
headers.introspection('Authorization', `Bearer ${g.env('GITHUB_TOKEN')}`)
}
})
g.datasource(github, { namespace: 'GitHub' })
export default config({ schema: g })
```
```fish
❯ env GITHUB_TOKEN="<REDACTED>" npx grafbase dev
```
And it works as it should. If using bash, go with:
```bash
❯ GITHUB_TOKEN="<REDACTED>" npx grafbase dev
```
Also adds support for `.env` file, which should now work.
=> feat(sdk): Add a convenient way to use env vars

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.0.21.md, packages/grafbase-sdk/package.json, packages/grafbase-sdk/scripts/bump-version.js, packages/grafbase-sdk/src/connector/openapi.ts, packages/grafbase-sdk/src/index.ts, packages/grafbase-sdk/tests/unit/openapi.test.ts
```ts
transforms: 'OPERATION_ID'
```
to
```ts
transforms: { queryNaming: 'OPERATION_ID' }
```
Bump to 0.0.21.
=> fix(sdk): Make transforms to take an object instead of a string

renovate.json
This change to the Renovate configuration will allow us to track updates to the CLI dependencies & the other things located in this repository separately.
=> chore: Add `additionalBranchPrefix` to renovate.json to force separate PRs for the CLI & the rest

packages/grafbase-sdk/src/query.ts, packages/grafbase-sdk/src/typedefs/default.ts, packages/grafbase-sdk/tests/unit/queries.test.ts
```ts
it('generates a resolver with input default value', () => {
g.query('greet', {
args: { name: g.string().default('Bob') },
returns: g.string(),
resolver: 'hello'
})
expect(renderGraphQL(config({ schema: g }))).toMatchInlineSnapshot(`
"extend type Query {
greet(name: String! = "Bob"): String! @resolver(name: "hello")
}"
`)
})
```
=> fix(sdk): Input type default values

.github/workflows/cli.yml, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.23.0-rc.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Allows for customers to omit GraphQL connector namespacing. Proper changelog will follow once we're done with the RC process.
=> release 0.23.0-rc.1

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.0.23.md, packages/grafbase-sdk/package.json, packages/grafbase-sdk/src/connector/graphql.ts, packages/grafbase-sdk/src/connector/openapi.ts, packages/grafbase-sdk/src/grafbase-schema.ts, packages/grafbase-sdk/src/query.ts, packages/grafbase-sdk/src/typedefs/resolver.ts, packages/grafbase-sdk/src/typedefs/search.ts, packages/grafbase-sdk/tests/unit/env.test.ts, packages/grafbase-sdk/tests/unit/graphql.test.ts, packages/grafbase-sdk/tests/unit/openapi.test.ts
If a field is using a resolver, you can't use the search attribute to it or the field cannot be unique. We prevent this in type-level.
=> fix(sdk): Resolver fields are _not_ searchable or unique. Make openapi/graphql namespace optional and rename it to namespace

cli/crates/cli/tests/init_ts.rs, cli/crates/common/src/environment.rs, cli/crates/common/src/errors.rs
When running `grafbase init` for the first time, and choosing `TypeScript` as the config type. If `package.json` is not found from the current directory, it will run `npm init -y` before continuing.
=> fix(cli): grafbase init should run 'npm init' if 'package.json' not found

packages/grafbase-sdk/README.md
This PR updates the README for the Grafbase SDK to reference the use of `g.env()`, optional `namespace` and a missing field type `g.phoneNumber()`.
=> docs(sdk): update readme env/namespace usage

cli/Cargo.lock, cli/crates/cli/tests/compilation_error.rs, cli/crates/cli/tests/custom_resolvers.rs, cli/crates/server/Cargo.toml, cli/crates/server/src/custom_resolvers.rs, cli/crates/server/src/errors.rs
Fix npm/pnpm/yarn search on Windows.
Translate the main resolver module path in to use POSIX-style slashes.
=> fix(resolvers): Fix custom resolvers on Windows

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.0.24.md, packages/grafbase-sdk/package.json, packages/grafbase-sdk/src/auth.ts, packages/grafbase-sdk/tests/unit/auth.openid.test.ts
If having a public auth rule, there is no reason to enforce a provider.
=> fix(sdk): Make auth provider optional (for public rules)

cli/Cargo.lock, cli/crates/server/Cargo.toml, cli/crates/server/src/bridge/errors.rs, cli/crates/server/src/bridge/resolvers.rs, cli/crates/server/src/bridge/server.rs, cli/crates/server/src/custom_resolvers.rs, cli/crates/server/src/errors.rs
This removes a single point of locking that was mistakenly introduced in https://github.com/grafbase/grafbase/pull/357.
Also, let miniflare pick the port for a worker on its own (--port 0) rather than speculatively pick a port from a range which is racy with multiple miniflare instances starting concurrently.
=> fix(resolvers): Ensure resolvers get compiled concurrently when multiple fields are queried

.github/workflows/cli.yml, cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.23.0.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- Make GraphQL Connector namespacing optional
- Add replace payment method endpoint to allow clients to change their payment
method
- Move to lazy compilation of resolvers in local dev
- Add an error message if package.json missing while grafbase.config.ts present
- Resolve issues with namespace-less GraphQL connector queries
- Make error message verification more generic
- Fix custom resolvers on Windows
- Ignore deployment files from blacklist
- Adds new error variants to the create operation
- Output the name of unknown API errors
=> chore(cli): Bump to 0.23.0

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.0.25.md, packages/grafbase-sdk/package.json, packages/grafbase-sdk/src/connector/openapi.ts, packages/grafbase-sdk/tests/unit/openapi.test.ts
Closes: GB-3963
A few OpenAPI fixes:
- Do not render empty introspectionHeaders
- Render namespace as name until we change that in the backend
=> fix(sdk): Do not render empty introspectionHeaders, name/namespace (openapi)

cli/crates/cli/tests/init.rs, cli/crates/cli/tests/init_ts.rs, cli/crates/cli/tests/utils/environment.rs, cli/crates/common/src/environment.rs, cli/crates/common/src/errors.rs
Steps to reproduce:
```
$ mkdir .some
$ cd .some
$ grafbase --trace 2 init -c typescript
2023-06-20T08:04:17.108970Z TRACE grafbase: subcommand: init
Grafbase CLI 0.23.0
Error: could not open the project 'package.json':
Caused by: No such file or directory (os error 2)
```
The problem is that `npm init -y` inside of such folders fails.
This fix replaces the npm call with the package json content taken from a successful call.
=> Fix grafbase init -c typescript on folders starting with a dot

flake.lock, flake.nix
The local development workflow needs dynein for database handling. This was not available in nixpkgs, so I added that in this PR:
https://github.com/NixOS/nixpkgs/pull/238762
We should switch using it from master or unstable when it's merged and available.
=> chore: Add dynein for nix users

.github/workflows/cli.yml, cli/crates/cli/tests/openapi/introspection_headers.rs, cli/crates/cli/tests/openapi/main.rs, cli/crates/cli/tests/openapi/remote_unions.rs, packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.0.26.md, packages/grafbase-sdk/package.json, packages/grafbase-sdk/src/connector/openapi.ts, packages/grafbase-sdk/tests/unit/openapi.test.ts, templates/openapi-github/grafbase/schema.graphql, templates/openapi-mux/grafbase/schema.graphql, templates/openapi-neon/grafbase/schema.graphql, templates/openapi-openai/grafbase/schema.graphql, templates/openapi-stripe/grafbase/schema.graphql, templates/openapi-tinybird/grafbase/schema.graphql
OpenAPI SDL name is renamed to namespace, and it's now optional.
=> fix(api): OpenAPI name renamed to namespace (and made optional)

cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.24.0.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- OpenAPI name attribute is now namespace, and is optional
- Fix grafbase init -c typescript on folders starting with a dot
- Fix the CLI failing to start in server mode on some Windows installations
=> chore(cli): Bump to 0.24.0

.github/workflows/cli.yml, cli/crates/cli/tests/auth.rs, cli/crates/cli/tests/graphql/auth/authorizer/authorizer.graphql, cli/crates/cli/tests/snapshots/auth__authorizer_with_headers_should_work__todo_creation_should_succeed.snap, cli/crates/cli/tests/snapshots/auth__authorizer_with_no_headers_should_work__todo_creation_should_succeed.snap, cli/crates/cli/tests/snapshots/auth__authorizer_with_public_access_should_work__todo_creation_should_succeed.snap, cli/crates/cli/tests/snapshots/auth__authorizer_with_public_access_should_work__todo_creation_with_public_access_should_fail.snap, cli/crates/cli/tests/snapshots/auth__authorizer_with_public_access_should_work__todo_list_should_succeed.snap, cli/crates/cli/tests/utils/consts.rs, cli/crates/cli/tests/utils/environment.rs, cli/crates/common/src/consts.rs, cli/crates/common/src/environment.rs, cli/crates/common/src/types.rs, cli/crates/server/src/bridge/udf.rs, cli/crates/server/src/errors.rs, cli/crates/server/src/servers.rs, cli/crates/server/src/udf_builder.rs
Add new UdfKind::Authorizer, running the custom auth provider. Use `requires_udf` flag to install wrangler. Add tests for authorizer.
=> feat(auth): GB-3994: Add authorizer runtime

.github/workflows/cli-partial-release.yml, .github/workflows/cli.yml
We were putting the arm & x64 releases into the same path.
=> Fix linux release

cli/.config/nextest.toml
Allow restarting tests that get stuck for any reason.
=> chore(ci): GB-4011: Add nextest configuration to terminate slow tests after 1 minute

.github/workflows/cli.yml, cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.25.3.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Contains a few fixes I've made:
- Fixed `allOf` schema support in `@openapi`
- `JSON` scalars will now accept any literal `Value` in documents
=> Release 0.25.3

cli/crates/cli/src/dev.rs, cli/crates/cli/src/output/report.rs, cli/crates/cli/tests/custom_resolvers.rs, cli/crates/cli/tests/snapshots/custom_resolvers__query_mutation_resolver_3_1.snap, cli/crates/common/src/consts.rs, cli/crates/common/src/environment.rs, cli/crates/common/src/types.rs, cli/crates/server/src/bridge/server.rs, cli/crates/server/src/servers.rs, cli/crates/server/src/types.rs, cli/crates/server/src/udf_builder.rs
This eliminates the needless copying of the UDFs entrypoint files that we were doing prior to compiling them. Moving the entrypoint module to another directory would break the imports of files relative to the entrypoint module. This PR fixes that by compiling UDFs in-place, which is also more intuitive.
We've also decided to share the dependency installation step and let it happen synchronously rather than lazily to avoid needless locking of one UDF build against another. In the future we may merge this installation step with that required for the support of TypeScript config.
=> fix(udf): Fix the way we compile UDFs to ensure you can import from local modules defined in separate files

cli/crates/server/src/consts.rs, cli/crates/server/src/environment.rs, cli/crates/server/src/file_watcher.rs, cli/crates/server/src/udf_builder.rs
Fix an issue with the file watcher picking up changes in the lock file. I've added the lock file names to the blocklists and redid the inclusion/exclusion logic a bit for more clarity.
=> Fix the file watcher rules to avoid the infinite loop on dependency installation when package.json is located in grafbase

cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.26.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- Fixes an issue introduced in 0.26.1 that would cause an infinite reinstallation of dependencies if package.json was located in the grafbase/ directory.
=> Release 0.26.1.

packages/grafbase-sdk/src/connector/header.ts, packages/grafbase-sdk/tests/unit/graphql.test.ts, packages/grafbase-sdk/tests/unit/openapi.test.ts, packages/grafbase-sdk/tsconfig.json
We're adding the ability to forward headers from a users request to openapi & graphql connectors.  This adds support for these to TS config.
As part of this we've deprecated the old `headers.static` method in favour of a new `headers.set` method that supports static headers and forwarded headers.
=> feat: update tsconfig with support for header forwarding.

cli/crates/server/src/bridge/errors.rs, cli/crates/server/src/bridge/server.rs, cli/crates/server/src/bridge/udf.rs, cli/crates/server/src/errors.rs, cli/crates/server/src/udf_builder.rs
When we introduced lazy loading for resolvers – the inner workings of which include spawning a separate miniflare instance for each resolver – we started allocating ports to miniflare instances dynamically by passing `--port 0` to spawn command. Later, we would parse the miniflare output to look for a line containing the port the instance is bound to, to establish the mapping between resolver names and port numbers.
This has broken our handling of errors happening at miniflare spawn time, including errors related to initialisation of the resolver module or any code running in the initialisation of dependencies in the global scope.
=> Fix the way we handle miniflare's output to ensure we expose errors happening at spawn time

.github/workflows/cli.yml, cli/.cargo/config.toml, cli/Cargo.lock, cli/Cargo.toml, cli/crates/cli/src/cli_input.rs, cli/crates/cli/src/dev.rs, cli/crates/cli/src/main.rs, cli/crates/cli/src/output/report.rs, cli/crates/common/Cargo.toml, cli/crates/common/src/types.rs, cli/crates/server/Cargo.toml, cli/crates/server/src/bridge/log.rs, cli/crates/server/src/bridge/mod.rs, cli/crates/server/src/bridge/search.rs, cli/crates/server/src/bridge/server.rs, cli/crates/server/src/bridge/types.rs, cli/crates/server/src/bridge/udf.rs, cli/crates/server/src/servers.rs, cli/crates/server/src/types.rs, cli/crates/server/src/udf_builder.rs
This introduces an initial logging of operation-related log events (operation start and completion) that get posted through the bridge.
This also adds a '--debug' argument to the 'dev' command that for now enables logging of introspection queries.
=> CLI: Print out the new operation-related events logged through the bridge to the stdout

.github/workflows/cli.yml, cli/Cargo.lock, cli/changelog/0.28.0.md, cli/crates/cli/tests/search.rs, cli/crates/server/Cargo.toml, cli/crates/server/src/bridge/api_counterfeit/search/mod.rs, cli/crates/server/src/bridge/api_counterfeit/search/paginated_searcher.rs, cli/crates/server/src/bridge/api_counterfeit/search/protocol.rs, cli/crates/server/src/bridge/api_counterfeit/search/query_builder.rs, cli/crates/server/src/bridge/search.rs
Adding regex filter, it's actually relatively limited by tantivy in terms of regex complexity, but better than nothing.
I'm also now handling user errors a bit better (invalid regex/cursor) a bit better instead of just saying "Search failed".
=> feat: Add regex filter in search query

cli/crates/cli/tests/custom_resolvers.rs, cli/crates/cli/tests/snapshots/custom_resolvers__query_mutation_resolver_4_1.snap, cli/crates/common/src/types.rs
We had a case mismatch on log levels between our JS and Rust.
Also added a test to make sure we don't regress.
Fixes GB-4406
=> fix: console.log not working

.github/workflows/cli.yml, cli/Cargo.lock, cli/crates/backend/src/types.rs, cli/crates/cli/src/dev.rs, cli/crates/cli/src/output/report.rs, cli/crates/server/src/bridge/log.rs, cli/crates/server/src/bridge/types.rs, cli/crates/server/src/bridge/udf.rs, cli/crates/server/src/types.rs
This adds more clarity to the log stream in the CLI.
=> feat(logs): GB-4411: Nest all request-scoped log events under the operation completion entry

cli/crates/cli/src/cli_input.rs, cli/crates/cli/src/output/report.rs
This is a slight tweak of the definition of the `--verbose` flag. We don't want it to enable logging of introspection queries. For that you'll need an explicit `--log-level-graphql-operations=debug` or the all-encompassing `--log-level=debug`.
=> Redefine the `--verbose` flag not to log introspection queries.

.github/workflows/cli.yml
Binaries for each commit built will get uploaded to an R2 bucket.
=> GB-4074: CLI: Expose build artifacts for Mac and Linux as downloadable artifacts

cli/Cargo.lock, cli/crates/backend/src/api/create.rs, cli/crates/backend/src/api/link.rs, cli/crates/backend/src/api/types.rs, cli/crates/cli/Cargo.toml, cli/crates/cli/src/cli_input.rs, cli/crates/cli/src/link.rs, cli/crates/cli/src/main.rs, cli/crates/cli/src/output/report.rs, cli/crates/cli/tests/link.rs, cli/crates/cli/tests/utils/environment.rs
- Adds the ability to pass a `project` argument to `link` which makes `link` run non-interactively (and without any external calls), validates that the passed argument is a valid ULID
- Does not store the account ID when linking as it's not needed
=> GB-4562 - Non-interactive link

cli/crates/cli/tests/auth.rs, cli/crates/cli/tests/graphql/auth/entrypoint-field-resolver.graphql, cli/crates/cli/tests/snapshots/auth__entrypoint_mutation_field_resolver_mixed___writer_with_entrypoint_field_mutation_should_succeed.snap, cli/crates/cli/tests/snapshots/auth__entrypoint_mutation_field_resolver_mixed__reader_entrypoint_field_mutation_should_fail.snap, cli/crates/cli/tests/snapshots/auth__entrypoint_query_field_resolver__reader_with_entrypoint_field_query_should_succeed.snap, cli/crates/cli/tests/snapshots/auth__entrypoint_query_field_resolver__writer_with_entrypoint_field_query_should_fail.snap
Add auth tests for top level query and mutation resolvers.
=> chore(test): Extend entrypoint resolver auth tests

packages/grafbase-sdk/src/query.ts, packages/grafbase-sdk/tests/unit/queries.test.ts
=> fix(sdk): GB-4552: Allow enum refs in mutation/query extends

.github/workflows/cli.yml, cli/crates/cli/tests/mongodb/main.rs, packages/grafbase-sdk/src/connector/mongodb.ts, packages/grafbase-sdk/tests/unit/mongodb.test.ts
Data API URL can be set directly in the connector.
API counterpart: https://github.com/grafbase/api/pull/2651
=> fix(sdk): Allow setting the Atlas Data API URL for MongoDB

packages/grafbase-sdk/src/grafbase-schema.ts, packages/grafbase-sdk/tests/unit/mongodb.test.ts
If calling `g.datasource` too early with a MongoDB connector, the models are lost. This won't do.
=> fix(sdk): GB-4630: Do not lose models if MongoDB datasource is added too early

.ignore
- Add .ignore hardlink for .gitignore
=> GB-4644 - Add .ignore hardlink for .gitignore

cli/crates/cli/src/cli_input.rs
Fix a mislabeled value name resulting from a copy paste gone wrong.
=> fix(args): Fix a mislabeled value name for the --log-level-fetch-requests argument

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.6.1.md, packages/grafbase-sdk/package.json, packages/grafbase-sdk/src/connector/graphql.ts, packages/grafbase-sdk/src/connector/mongodb.ts, packages/grafbase-sdk/src/connector/openapi.ts, packages/grafbase-sdk/tests/unit/graphql.test.ts, packages/grafbase-sdk/tests/unit/mongodb.test.ts, packages/grafbase-sdk/tests/unit/openapi.test.ts
Previously, `{ namespace: false }` rendered nothing, which is wrong.
=> fix(sdk): Always render namespace in SDK connectors

cli/Cargo.lock, cli/crates/server/Cargo.toml, cli/crates/server/src/consts.rs, cli/crates/server/src/errors.rs, cli/crates/server/src/udf_builder.rs
This PR adds a symlink to grafbase-wasm-sdk and updates the wrangler.toml used on resolvers to use a rule that makes this wasm available when uploading the worker.
The symlink is required because wrangler build rules use relative paths.
=> feat(resolvers): optionally create symlink to grafbase-wasm-sdk

engine/crates/grafbase-engine-integration-tests/tests/errors/mod.rs, engine/crates/grafbase-engine-integration-tests/tests/execution/mod.rs, engine/crates/grafbase-engine-integration-tests/tests/integration_tests.rs, engine/crates/grafbase-engine-integration-tests/tests/mongodb/find_many.rs, engine/crates/grafbase-engine/src/context.rs, engine/crates/grafbase-engine/src/registry/mod.rs, engine/crates/grafbase-engine/src/registry/type_names.rs, engine/crates/grafbase-engine/src/resolver_utils/field.rs, engine/crates/grafbase-engine/src/resolver_utils/list.rs, engine/crates/graph-entities/src/response/mod.rs
While testing `@defer` I've discovered a few bugs: 
1. We were propagating errors up to the top level of a response rather than the nearest nullable field.
2. We weren't reporting the path correctly on errors.
3. Nested lists would get flattened into a single level of list.
4. Nullability validation at the various levels of the list (and of items in lists) was also pretty sketchy.
This PR fixes those:
1. We were being a bit overzealous with the question mark operator.  I've replaced one or two points with proper error->null conversion to fix this.
2. Was because we called `set_error_path` all over the place which overwrote the path with a less specific path.  I've updated `set_error_path` to only set the path if there's not one already, which fixes that.
3. Our list resolver code just …
=> fix: error propagation & nested list resolution

engine/Cargo.lock, engine/crates/gateway-local/Cargo.toml, engine/crates/gateway-local/src/execution.rs, engine/crates/gateway-protocol/Cargo.toml, engine/crates/gateway-protocol/src/execution_engine.rs, engine/crates/gateway-protocol/src/lib.rs, engine/crates/gateway-types/Cargo.toml
I'm likely going to have to add another method or two to the ExecutionEngine trait soon, as well as updating a few places that it's used.  But it seemed quite difficult to work with, so I've tried to simplify it a bit first:
1. It had a ton of associated types that really only seem to exist because it doesn't have access to gateway-protocol types.  I've just moved it into `gateway-protocol` to fix this.  Not sure if it really needed to be in it's own crate.  Now that I'm typing this I'm wondering if I could have just added a dep between on `gateway-protocol` instead.  Not sure if that's any better though, let me know in the comments.
2. Updated it to take `self: Arc<Self>` so we don't need to pass a bunch of context to each function that could just live on self.
3. Tried to simplify the …
=> chore: simplify ExecutionEngine trait

engine/Cargo.lock, engine/crates/grafbase-engine-integration-tests/tests/defer/mod.rs, engine/crates/grafbase-engine/Cargo.toml, engine/crates/grafbase-engine/src/context.rs, engine/crates/grafbase-engine/src/context/resolver_chain.rs, engine/crates/grafbase-engine/src/deferred.rs, engine/crates/grafbase-engine/src/error.rs, engine/crates/grafbase-engine/src/extensions/mod.rs, engine/crates/grafbase-engine/src/lib.rs, engine/crates/grafbase-engine/src/query_path.rs, engine/crates/grafbase-engine/src/registry/resolvers/resolved_value.rs, engine/crates/grafbase-engine/src/resolver_utils/container.rs, engine/crates/grafbase-engine/src/resolver_utils/field.rs, engine/crates/grafbase-engine/src/resolver_utils/list.rs, engine/crates/grafbase-engine/src/response/streaming.rs, engine/crates/grafbase-engine/src/schema.rs, engine/crates/grafbase-engine/src/subscription.rs, engine/crates/grafbase-engine/src/validation/rules/arguments_of_correct_type.rs, engine/crates/grafbase-engine/src/validation/rules/default_values_of_correct_type.rs, engine/crates/grafbase-engine/src/validation/utils.rs, engine/crates/sdl-parser/src/rules/default_directive_types.rs
I introduced basic `@defer` support to grafbase-engine in #2696.  One of the things I skipped was error handling.  
This was trickier than you might expect because error handling requires the path to be set correctly in the `Context`, but `Context.path_node` made heavy use of references in a way that made it really hard to defer.  I've ended up re-working it to a `Vector` of `ArcIntern<String>` instead of a reverse linked list.  It's much easier to make use of.  I'm using `im::Vector` instead of just a `Vec` to theoretically make cloning slightly cheaper, though I've been careful to hide that detail so we can swap it out if it proves to be a waste of time.
=> feat: error handling for @defer

engine/crates/grafbase-engine-integration-tests/tests/defer/mod.rs, engine/crates/grafbase-engine-integration-tests/tests/defer/type_conditions.rs, engine/crates/grafbase-engine/src/schema.rs
Incremental payloads as used by `@defer` have a `hasNext` property that tells you whether to expect any more payloads after the current one.  I skipped over setting this correctly when I first implemented defer - just setting it to true all the time.  This PR fixes that.
=> feat: set hasNext correctly in `@defer`

engine/Cargo.lock, engine/crates/engine/Cargo.toml, engine/crates/engine/src/deferred.rs, engine/crates/engine/src/response/streaming.rs, engine/crates/engine/src/schema.rs, engine/crates/engine/src/validation/rules/overlapping_fields_can_be_merged.rs, engine/crates/gateway-local/Cargo.toml, engine/crates/gateway-local/src/execution.rs, engine/crates/integration-tests/Cargo.toml, engine/crates/integration-tests/tests/defer/mod.rs, engine/crates/runtime-protocol/Cargo.toml, engine/crates/runtime-protocol/src/execution_engine.rs, engine/crates/runtime-protocol/src/lib.rs
The engine currently has support for `@defer` but it's useless without some sort of streaming transport.  This adds support for the [GraphQLOverSSE][1] & [Incremental Delivery][2] transports into the `gateway-local` crate.  Though I'll still need to make another PR in `api` followed by a PR here before this is functional.
While testing this I found that doing a `@defer` at the top level of the query was causing a panic because of some mismatched exepctations around `resolver_chain_node`.  So I've also fixed that in this PR
[1]: https://github.com/graphql/graphql-over-http/blob/main/rfcs/GraphQLOverSSE.md
[2]: https://github.com/graphql/graphql-over-http/blob/main/rfcs/IncrementalDelivery.md
=> feat: add SSE & incremental delivery to local gateway

engine/crates/gateway-adapter-local/src/execution.rs
I noticed when writing tests of SSE that a naive client implementation might assume `body` is always JSON, but I was sending the word `complete` in the body of the complete event.  I don't think it's wrong, but might as well make it valid JSON.
=> fix: send valid json in the complete body

cli/crates/server/src/udf_builder.rs
This PR introduces a check ensuring that we don't reinstall wrangler excessively. If we find a valid wrangler already installed in ~/.grafbase/wrangler – by trying to invoke it through `npm exec` – and it's of the right version, no attempt to install it again will be carried out. Even if `npm install` itself for the existing package would already have been fairly quick.
=> fix(udf): GB-4829: Avoid installing wrangler when it's already installed with the right version

engine/crates/engine/src/registry/mod.rs, engine/crates/engine/src/registry/resolvers/mod.rs, engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/rules/experimental.rs, engine/crates/parser-sdl/src/rules/mod.rs, engine/crates/parser-sdl/src/rules/mongodb_directive/model_directive/types/input.rs, engine/crates/parser-sdl/src/rules/neon_directive.rs
Adds a new directive `@experimental` parsed only at the global level (or at schema level).
```graphql
schema @experimental(kv: true)
```
=> feat: @experimental

engine/crates/gateway-adapter/src/customer_deployment_config/mod.rs
These aren't necessary any more after upstream changes in the platform.
=> Drop the `#[serde(default)]` annotations from the fields in `CommonCustomerDeploymentConfig`

engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/tests.rs
Add missing `@experimental` directive in the schema parsing function. Additionally add some tests to validate its actually recognised.
=> fix: @experimental

engine/crates/engine/src/deferred.rs, engine/crates/engine/src/directive.rs, engine/crates/engine/src/lib.rs, engine/crates/engine/src/resolver_utils/container.rs, engine/crates/engine/src/resolver_utils/fragment.rs, engine/crates/integration-tests/tests/defer/mod.rs
I added `@defer` in some other PR, but one of the bits I skipped over was its arguments: `label` & `if`.  This PR adds those in, using serde to do most of the heavy lifting.
=> feat: `@defer` arguments

engine/Cargo.lock, engine/crates/gateway-adapter/Cargo.toml, engine/crates/gateway-adapter/src/execution_engine.rs, engine/crates/gateway-adapter/src/lib.rs, engine/crates/gateway-adapter/src/streaming_format.rs
We're using the HTTP Accept header to determine which transport we use to reply to incoming requests.  I couldn't find an obvious way to parse the `Accept` header properly at the time I was writing the code, so I temporarily did the dumbest thing I could to not get blocked.
Came back to it today and this time I managed to find a crate that does the trick.  So this PR pulls that in and fixes that issue.
=> fix: parse accept header properly

cli/crates/cli/tests/defer/main.rs
I sloppily copied & pasted some non-async test code into an async test.  This worked fine in this repo but when running the dynamodb version of these tests in our `api` repo this will cause a panic because we try to start a tokio runtime inside the existing tokio runtime.
=> fix: dont call Environment::init from async context

engine/crates/engine/src/registry/resolvers/transformer.rs, engine/crates/engine/src/registry/scalars/timestamp.rs, engine/crates/parser-sdl/src/rules/mongodb_directive/model_directive/model_type/resolver_data.rs
This is much better than doing stupid conversions for all connectors.
=> fix(connector): Convert MongoDB timestamps to standard format in a transformer

engine/crates/engine/Cargo.toml, engine/crates/engine/src/lib.rs, engine/crates/engine/src/registry/resolvers/atlas_data_api.rs, engine/crates/engine/src/registry/resolvers/custom.rs, engine/crates/engine/src/registry/resolvers/graphql.rs, engine/crates/engine/src/registry/resolvers/http/mod.rs, engine/crates/engine/src/registry/resolvers/postgresql.rs, engine/crates/engine/src/send_wrapper.rs, engine/crates/integration-tests/src/udfs.rs, engine/crates/runtime-local/src/ufd_invoker.rs, engine/crates/runtime/src/udf.rs
I've was adding some GraphQL connector tests into the integration-tests today, when I ran into some panics from our use of `SendWrapper`.  It was safe to use `SendWrapper` in wasm because it's inherently single threaded - less so in native code.
Thankfully we generally only need SendWrapper when we're building for wasm.  So I've updated all the places we use it to only do so on WASM.
=> fix: use SendWrapper in less places

engine/Cargo.lock, engine/crates/integration-tests/Cargo.toml, engine/crates/integration-tests/src/engine/builder.rs, engine/crates/integration-tests/src/engine/mod.rs, engine/crates/integration-tests/src/lib.rs, engine/crates/integration-tests/src/mocks.rs, engine/crates/integration-tests/src/mocks/graphql.rs, engine/crates/integration-tests/tests/graphql_connector/basic.rs, engine/crates/integration-tests/tests/graphql_connector/headers.rs, engine/crates/integration-tests/tests/graphql_connector/mod.rs, engine/crates/integration-tests/tests/graphql_connector/snapshots/integration_tests__graphql_connector__basic__namespaced-issue.snap, engine/crates/integration-tests/tests/graphql_connector/snapshots/integration_tests__graphql_connector__basic__namespaced-null.snap, engine/crates/integration-tests/tests/graphql_connector/snapshots/integration_tests__graphql_connector__basic__namespaced-pull-request-with-bot.snap, engine/crates/integration-tests/tests/graphql_connector/snapshots/integration_tests__graphql_connector__basic__namespaced-pull-request-with-user.snap, engine/crates/integration-tests/tests/graphql_connector/snapshots/integration_tests__graphql_connector__basic__unnamespaced-issue.snap, engine/crates/integration-tests/tests/graphql_connector/snapshots/integration_tests__graphql_connector__basic__unnamespaced-null.snap, engine/crates/integration-tests/tests/graphql_connector/snapshots/integration_tests__graphql_connector__basic__unnamespaced-pull-request-with-bot.snap, engine/crates/integration-tests/tests/graphql_connector/snapshots/integration_tests__graphql_connector__basic__unnamespaced-pull-request-with-user.snap, engine/crates/integration-tests/tests/graphql_connector/transforms.rs, engine/crates/integration-tests/tests/integration_tests.rs
I'm adding some functionality that affects the GraphQL connector so figured this was as good a time as any to port the tests from the CLI over to the integration tests.
=> chore: port GraphQL connector tests into integration tests

engine/crates/engine/src/registry/resolvers/graphql/serializer.rs, engine/crates/engine/src/registry/resolvers/graphql/snapshots/engine__registry__resolvers__graphql__serializer__tests__field_directives@query { foo @include @skip }.snap, engine/crates/engine/src/registry/resolvers/graphql/snapshots/engine__registry__resolvers__graphql__serializer__tests__field_directives@query { foo @include(if true) @skip @skip(if 42) }.snap, engine/crates/engine/src/registry/resolvers/graphql/snapshots/engine__registry__resolvers__graphql__serializer__tests__field_directives@query { foo @include(if true) @skip(if 42) }.snap, engine/crates/engine/src/registry/resolvers/graphql/snapshots/engine__registry__resolvers__graphql__serializer__tests__fragment_spread@query { ... fooBar @skip }.snap, engine/crates/engine/src/registry/resolvers/graphql/snapshots/engine__registry__resolvers__graphql__serializer__tests__inline_fragment@query { ... on Foo @skip { baz } }.snap, engine/crates/integration-tests/src/helpers.rs, engine/crates/integration-tests/tests/graphql_connector/defer.rs, engine/crates/integration-tests/tests/graphql_connector/mod.rs
Now that we support `@defer` we need to be careful to not send it to connected GraphQL APIs.  They might well not support the directive, and even if they do we don't have any support for streaming responses from connected APIs.
This filters out the directive to handle this.  We can maybe do something better in the future/
=> fix: dont forward `@defer` to connected gql apis

engine/Cargo.lock, engine/crates/engine/Cargo.toml, engine/crates/engine/src/registry/resolvers/postgresql.rs, engine/crates/engine/src/registry/resolvers/postgresql/context.rs, engine/crates/engine/src/registry/resolvers/postgresql/context/filter.rs, engine/crates/engine/src/registry/resolvers/postgresql/context/filter/complex.rs, engine/crates/engine/src/registry/resolvers/postgresql/context/filter/simple.rs, engine/crates/engine/src/registry/resolvers/postgresql/context/selection/collection_args.rs, engine/crates/engine/src/registry/resolvers/postgresql/request.rs, engine/crates/engine/src/registry/resolvers/postgresql/request/find_many.rs, engine/crates/engine/src/registry/resolvers/postgresql/request/query.rs, engine/crates/engine/src/registry/resolvers/postgresql/request/query/builder.rs, engine/crates/integration-tests/src/postgresql.rs, engine/crates/integration-tests/tests/postgresql/find_many.rs, engine/crates/integration-tests/tests/postgresql/introspection.rs, engine/crates/integration-tests/tests/postgresql/mod.rs, engine/crates/parser-postgresql/src/registry/context/input.rs, engine/crates/parser-postgresql/src/registry/context/output.rs, engine/crates/parser-postgresql/src/registry/context/output/builders.rs, engine/crates/parser-postgresql/src/registry/queries.rs, engine/crates/parser-postgresql/src/registry/queries/find_many.rs, engine/crates/parser-postgresql/src/registry/queries/input.rs, engine/crates/parser-postgresql/src/registry/queries/input/filter.rs, engine/crates/parser-postgresql/src/registry/queries/input/oneof.rs, engine/crates/parser-postgresql/src/registry/types.rs, engine/crates/parser-postgresql/src/registry/types/scalar.rs, engine/crates/postgresql-types/src/database_definition/walkers/table_column.rs
Tests are over 2k lines, so this one is finally under 1k for the feature :)
```graphql
query {
userCollection(filter: { id: { eq: 1 } }) {
edges { node { id name } }  
}
}
```
Nested filters from n:1 side:
```graphql
query {
userCollection(filter: { profile: { id: { eq: 1 } } }) {
edges {
node {
id
name
profile { description }
}
}
}
}
```
And from 1:n side:
```graphql
query {
userCollection(filter: { blogs: { contains: { id: { eq: 1 } } } }) {
edges {
node {
id
name
blogs { edges { node { id title } } }
}
}
}
}
```
Arrays have few postgres-specific operations:
- `contains`: if the column array contains all the elements from the given array
- `contained`: if the given array contains all the elements from the column
- `overlaps`: if the given array overlaps with any of the elements from the …
=> feat(connector): Neon findMany

engine/crates/engine/src/registry/resolvers/graphql/serializer.rs, engine/crates/engine/value/src/lib.rs, engine/crates/integration-tests/src/mocks/graphql.rs, engine/crates/integration-tests/tests/graphql_connector/basic.rs, engine/crates/integration-tests/tests/graphql_connector/transforms.rs
The GraphQL connector needs to track which variables are used inside a query in order to know which variables to send to the downstream API.  It was doing this, but it was only pulling top-level variables rather than any nested inside a `Value`.  This PR fixes that and adds a test that catches the failure.
=> fix: handle variables inside inputs in graphql connector

engine/crates/engine/src/registry/resolvers/postgresql/context.rs, engine/crates/integration-tests/src/engine/builder.rs, engine/crates/integration-tests/src/postgresql.rs, engine/crates/postgresql-types/src/transport/neon.rs
A small tweak ensuring requests to Neon will get logged.
=> fix(neon): Add `x-grafbase-fetch-trace-id` header to the Neon requests to ensure they get logged properly

engine/crates/gateway-adapter/src/streaming_format.rs
graphql-codegen sends an accept header with `multipart/mixed` in it, so we're responding with `multipart/mixed`. However it doesn't like our multipart mixed responses and crashes.
I'm investigating the problem but in the meantime I'm putting this in so we just do a normal JSON reply to graphql-codegen
=> fix: stop breaking graphql-codegen

engine/Cargo.lock, engine/crates/engine/Cargo.toml, engine/crates/engine/src/registry/resolvers/postgresql.rs, engine/crates/engine/src/registry/resolvers/postgresql/context.rs, engine/crates/engine/src/registry/resolvers/postgresql/context/selection.rs, engine/crates/engine/src/registry/resolvers/postgresql/context/selection/collection_args.rs, engine/crates/engine/src/registry/resolvers/postgresql/request/find_many.rs, engine/crates/engine/src/registry/resolvers/postgresql/request/find_one.rs, engine/crates/engine/src/registry/resolvers/postgresql/request/query.rs, engine/crates/engine/src/registry/resolvers/resolved_value.rs, engine/crates/engine/src/registry/resolvers/transformer.rs, engine/crates/integration-tests/src/postgresql.rs, engine/crates/integration-tests/tests/postgresql/find_many.rs, engine/crates/integration-tests/tests/postgresql/find_many/pagination.rs, engine/crates/integration-tests/tests/postgresql/find_many/pagination/cursors.rs, engine/crates/integration-tests/tests/postgresql/find_many/pagination/filters.rs, engine/crates/integration-tests/tests/postgresql/find_many/pagination/filters/nested.rs, engine/crates/integration-tests/tests/postgresql/find_one/joins.rs, engine/crates/integration-tests/tests/postgresql/introspection.rs, engine/crates/parser-postgresql/src/registry/queries/find_many.rs, engine/crates/parser-postgresql/src/registry/types.rs, engine/crates/parser-postgresql/src/registry/types/order_direction.rs, engine/crates/parser-postgresql/src/registry/types/page_info.rs, engine/crates/parser-postgresql/src/registry/types/table.rs, engine/crates/postgresql-types/Cargo.toml, engine/crates/postgresql-types/src/cursor.rs, engine/crates/postgresql-types/src/database_definition/names.rs, engine/crates/postgresql-types/src/database_definition/walkers/table.rs, engine/crates/postgresql-types/src/lib.rs
Implements cursors, page infos and before/after filters for Neon/PostgreSQL. Again, about 2k lines of this PR are tests, so the actual feature should be about 1k lines to read.
Some weird things: we load all the data, even nested data, in one query. This kind of puts us implementing page infos in resolvers, and additionally the cursors are resolved values, so they are also handled in special resolvers. This required me to add some query-specific data to the resolved value, which allows cursor calculation if needed. This whole thing has a bit too much copying we should maybe address later.
Another one that will bring questions is our ordering preference. MongoDB has nulls first _always_, but PostgreSQL has this as a server setting, or nulls last when ascending. For the first iteration, we …
=> feat(connector): Neon pagination

engine/.cargo/config.toml, engine/crates/engine/src/registry/resolvers/postgresql/context/filter/complex.rs, engine/crates/engine/src/registry/resolvers/postgresql/context/selection/collection_args.rs, engine/crates/integration-tests/src/helpers.rs, engine/crates/integration-tests/src/postgresql.rs, engine/crates/integration-tests/tests/graphql_connector/basic.rs, engine/crates/integration-tests/tests/postgresql/find_many/pagination/filters.rs, engine/crates/parser-postgresql/src/registry/queries/input.rs, engine/crates/parser-postgresql/src/registry/queries/input/filter.rs, engine/crates/parser-postgresql/src/registry/types.rs, engine/crates/parser-postgresql/src/registry/types/table.rs, engine/crates/parser-sdl/src/rules/mongodb_directive/model_directive/model_type/resolver_data.rs, engine/crates/parser-sdl/src/tests.rs, engine/crates/postgresql-types/src/database_definition/postgres_type.rs
When using those crates with inside api I had clippy complaining about unused dependencies... So could have just added that check, but thought might as well have the same clippy configuration.
=> chore: Use same clippy as api

cli/Cargo.lock, cli/crates/cli/Cargo.toml, engine/Cargo.lock, engine/crates/engine/Cargo.toml, engine/crates/gateway-adapter-local/Cargo.toml, engine/crates/gateway-adapter-local/src/execution.rs, engine/crates/gateway-core/src/streaming_format.rs
GraphQL codegen supports using the incremental delivery transport, and uncovered a few problems in our implementation.  Tricky to find these, but easy enough to fix.
1. Each part has to contain a content-type header.
2. The multipart-stream library we're using wasn't sending a trailing boundary, so I've forked to fix that.
3. The multipart-stream library we're using wasn't putting boundaries on their own line, so I've also fixed that in our fork.
=> chore: fix incremental delivery implementation

cli/crates/cli/tests/defer/main.rs, engine/crates/engine/src/lib.rs, engine/crates/engine/src/response/streaming.rs, engine/crates/engine/src/schema.rs, engine/crates/integration-tests/src/helpers.rs, engine/crates/integration-tests/tests/defer/mod.rs, engine/crates/integration-tests/tests/defer/type_conditions.rs
The [defer & stream RFC][1] says "The first payload is the same shape as a standard GraphQL response.".  Which is what I implemented. 
But, if you look at it's examples they all have `hasNext` in the first payload.  This PR updates the initial response to contain `hasNext`.
[1]: https://github.com/graphql/graphql-wg/blob/main/rfcs/DeferStream.md#payload-format
=> fix: add hasNext into the initial response when streaming

engine/crates/engine/src/registry/resolvers/mod.rs, engine/crates/engine/src/registry/resolvers/transformer.rs, engine/crates/engine/src/resolver_utils/field.rs
Instead of calling `data_resolved()` and then cloning the `&Value`, we get the resolved value by-value, then `take()` the data out. Calling `take()` will only allocate if we have no other references to the data.
Tested this with some scenarios, and it will skip allocations in most cases. Nested page infos are still cloning the underlying data sadly, and we should consider finding a better solution for that in the future.
But. This PR will still reduce allocations, and that's a net-positive anyhow so let's go with this?
Closes: GB-5032
=> fix(connector): Reduce allocations for PostgreSQL pagination

engine/crates/engine/src/registry/resolvers/postgresql/context/filter/simple.rs, engine/crates/integration-tests/tests/postgresql/find_one.rs, engine/crates/parser-postgresql/src/registry/context/output.rs, engine/crates/parser-postgresql/src/registry/context/output/builders.rs, engine/crates/parser-postgresql/src/registry/queries/input/filter.rs, engine/crates/parser-postgresql/src/registry/queries/input/oneof.rs, engine/crates/postgresql-types/src/database_definition.rs, engine/crates/postgresql-types/src/database_definition/names.rs
This fixes an edge case that might seem small, but would lead to catastrophic results in the worst case. Let's imagine a table:
```sql
CREATE TABLE "user" (
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NULL,
CONSTRAINT foo_key UNIQUE (name, email)
);
```
The input type would be something like this:
```graphql
query {
user(by: { nameEmail: { name: "Naukio", email: null } }) {
name
email
}
}
```
This would trigger a query with `WHERE name = 'Naukio' AND email IS NULL`. Now, the column being nullable, the generated graphql type allows one to emit the value completely, so this is also allowed:
```graphql
query {
user(by: { nameEmail: { name: "Naukio" } }) {
name
email
}
}
```
Before the fix, it renders a query `WHERE name = 'Naukio'`, which then could return more than one rows, leading to …
=> fix(connector): Allow emitting input field for nullable composite key

cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.37.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json, packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.6.4.md, packages/grafbase-sdk/package.json
Releasing the Postgres renames.
=> chore: Bump CLI to 0.37.1 and bump SDK to 0.6.4

engine/crates/engine/src/registry/resolvers/custom.rs
We've got it covered with runtime logs now.
=> fix(gateway): Drop the `log::error!()` from the branch when a UDF invocation fails

.github/workflows/cli.yml
Using the bigger macos runner.
=> chore(ci): Use xlarge instance for macos builds

cli/crates/cli/src/output/report.rs
Now it'll be:
```
2023-10-09T16:00:59.459+02:00 POST /graphql 200 | query IntrospectionQuery
2023-10-09T16:01:10.472+02:00 POST /graphql 200 | query IntrospectionQuery
2023-10-09T16:01:19.264+02:00 POST /graphql 200 | query Test34124
2023-10-09T16:01:19.281+02:00 [ERROR] resolver return-string | HELLO WORLD!
```
=> fix(logs): Runtime logs: Change the timezone of the timestamp printed to local.

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.6.5.md, packages/grafbase-sdk/package.json
Following https://github.com/grafbase/grafbase/pull/785
=> chore(sdk): bump to 0.6.5

cli/Cargo.lock, engine/Cargo.lock, engine/crates/engine/Cargo.toml, engine/crates/engine/src/registry/resolvers/postgres.rs, engine/crates/engine/src/registry/resolvers/postgres/context.rs, engine/crates/engine/src/registry/resolvers/postgres/context/create_input.rs, engine/crates/engine/src/registry/resolvers/postgres/context/update_input.rs, engine/crates/engine/src/registry/resolvers/postgres/request.rs, engine/crates/engine/src/registry/resolvers/postgres/request/create_one.rs, engine/crates/engine/src/registry/resolvers/postgres/request/query.rs, engine/crates/engine/src/registry/resolvers/postgres/request/query/insert.rs, engine/crates/engine/src/registry/resolvers/postgres/request/query/update.rs, engine/crates/engine/src/registry/resolvers/postgres/request/update_many.rs, engine/crates/engine/src/registry/resolvers/postgres/request/update_one.rs, engine/crates/integration-tests/tests/postgres/introspection.rs, engine/crates/integration-tests/tests/postgres/mod.rs, engine/crates/integration-tests/tests/postgres/update_many.rs, engine/crates/integration-tests/tests/postgres/update_one.rs, engine/crates/parser-postgres/src/registry/context/input.rs, engine/crates/parser-postgres/src/registry/queries.rs, engine/crates/parser-postgres/src/registry/queries/input.rs, engine/crates/parser-postgres/src/registry/queries/input/update.rs, engine/crates/parser-postgres/src/registry/queries/update_many.rs, engine/crates/parser-postgres/src/registry/queries/update_one.rs, engine/crates/parser-postgres/src/registry/types/scalar.rs, engine/crates/postgres-types/src/database_definition/postgres_type.rs
Adds the update and updateMany mutations for PostgreSQL.
Tests: 2425 lines
Implementation: 469 lines
Updates one row in the database.
```graphql
query {
userUpdate(by: { id: 1 }, input: { name: "Musti" }) {
id
name
}
}
```
The return value is a user:
```json
{
"data": {
"userUpdate": {
"id": 1,
"name": "Musti"
}
}
}
```
So far only scalar fields can be used in the updates. We'll be coming back to the nested updates in the following issue: https://linear.app/grafbase/issue/GB-5089/nested-updates
Updates multiple rows in the database
```graphql
query {
userUpdateMany(filter: { id: { eq: 1 } }, input: { name: "Musti" }) {
id
name
}
}
```
The return value is a list of users:
```json
{
"data": {
"userUpdateMany": [
{
"id": 1,
"name": "Musti"
}
]
}
}
```
The query is not just a simple update, …
=> feat(connector): Postgres update mutations

engine/crates/engine/src/registry/federation.rs, engine/crates/engine/src/registry/resolvers/federation.rs, engine/crates/engine/src/registry/type_names.rs, engine/crates/integration-tests/tests/federation/mod.rs, engine/crates/parser-sdl/src/rules/basic_type.rs, engine/crates/parser-sdl/src/rules/federation/directive.rs, engine/crates/parser-sdl/src/rules/federation/key.rs, engine/crates/parser-sdl/src/rules/graphql_directive.rs, engine/crates/parser-sdl/src/rules/openapi_directive.rs, engine/crates/parser-sdl/src/rules/postgres_directive.rs, engine/crates/parser-sdl/src/rules/unique_directive.rs, engine/crates/parser-sdl/src/tests.rs
Sometimes one subgraph will want to add fields to a type that is owned by another subgraph.  This partially enables suppport for that in Grafbase.  e.g. to add a name to a `TodoList` owned by another subgraph you could use this schema:
```graphql
extend schema @federation(version: "2.3")
type TodoList @key(fields: "id") {
id: ID!
name: String! @resolver(name: "todoListName")
}
```
=> feat: federation resolver for resolvable basic types

packages/grafbase-sdk/src/index.ts, packages/grafbase-sdk/src/resolver/context.ts, packages/grafbase-sdk/src/resolver/context/ai.ts, packages/grafbase-sdk/src/resolver/context/kv.ts, packages/grafbase-sdk/src/resolver/info.ts
This commit adds two exports to `@grafbase/sdk':
- `Context`: the type of the `context` arg in resolvers.
- `Info`: the type of the `info` arg in resolvers.
The source is, at much as possible, annotated with the source of truth
for each part of the types in the comments.
This commit implements that section of the RFC: https://www.notion.so/grafbase/Typed-Resolvers-b4a0b47f4b5b4d2b9815e0aa82c6a8a8?pvs=4#7e9386db2ac648a28d5fd8db11f9b4b1
Questions:
- In several places, I used `any`, but we may want to use `unknown`
instead (different DX for sure). Are there opinions? Graphql.JS for
example uses `Record<string, unknown>` for variables.
- My current plan for testing that these types match reality is to
release `@grafbase/sdk` once this is merged, then manually check in
a deployment. Is there a …
=> feat(sdk): add types for resolver  `context` and `info` args

packages/grafbase-sdk/src/resolver/context/kv.ts
- `metadata` is optional in KVSetOptions
- `type` is optional in KVGetOptions
- KVListKey will not return metadata if there is none for the key
We should cut a patch release when this is merged.
Part of https://linear.app/grafbase/issue/GB-5097/implement-types-for-context-and-info-args-in-grafbasesdk
=> sdk: fix errors in ResolverContext KV type definitions

cli/crates/cli/src/output/report.rs, cli/crates/server/src/bridge/log.rs, cli/crates/server/src/bridge/types.rs, cli/crates/server/src/types.rs, engine/crates/common-types/src/lib.rs, engine/crates/engine/src/registry/resolvers/postgres/context.rs, engine/crates/engine/src/registry/resolvers/postgres/request.rs, engine/crates/engine/src/registry/resolvers/postgres/request/create_many.rs, engine/crates/engine/src/registry/resolvers/postgres/request/create_one.rs, engine/crates/engine/src/registry/resolvers/postgres/request/delete_many.rs, engine/crates/engine/src/registry/resolvers/postgres/request/delete_one.rs, engine/crates/engine/src/registry/resolvers/postgres/request/find_many.rs, engine/crates/engine/src/registry/resolvers/postgres/request/find_one.rs, engine/crates/engine/src/registry/resolvers/postgres/request/log.rs, engine/crates/postgres-types/src/transport.rs
Debug logs for Postgres queries and mutations. Only available for the CLI when running logs in debug mode, not a great idea to have these on production due to the queries having data we don't want in public logs.
Example shows two mutation queries: the first one errors, and the second one is successful and returns data.
Closes: GB-5065
=> feat(connector): Log Postgres queries

engine/crates/engine/src/registry/resolvers/postgres/request/log.rs
Fixes problems in here https://github.com/grafbase/api/actions/runs/6506409579/job/17671891694?pr=2858
In wasm futures are not `Send`, so we cannot require that in the logger.
=> Remove Send requirement from the Postgres query logger

packages/grafbase-sdk/src/authorizer/context.ts, packages/grafbase-sdk/src/authorizer/verifiedIdentity.ts, packages/grafbase-sdk/src/index.ts
It looks like this:
```typescript
// grafbase/authorizers/myJwt.ts
import { AuthorizerContext, VerifiedIdentity } from '@grafbase/sdk'
export default async ({ request }: AuthorizerContext): VerifiedIdentity? {
// ...
}
```
Implements the [relevant section of the RFC](https://www.notion.so/grafbase/Typed-Resolvers-b4a0b47f4b5b4d2b9815e0aa82c6a8a8?pvs=4#51dd1771bc334f3094f9ce915c6a83d3).
Closes GB-5113
=> sdk: export type definition for authorizer arguments and return type

examples/resolvers-kv/README.md, examples/resolvers-kv/grafbase/auth/allowAll.ts, examples/resolvers-kv/grafbase/grafbase.config.ts, examples/resolvers-kv/grafbase/resolvers/getAnswer.ts, examples/resolvers-kv/package-lock.json, examples/resolvers-kv/package.json, packages/grafbase-sdk/src/authorizer/context.ts, packages/grafbase-sdk/src/authorizer/verifiedIdentity.ts
I haven't found existing examples (in `/examples`) using KV, so this seemed like an opportunity. The original purpose of this PR is to have a working example of typed resolvers and authorizers with the recently added types from SDK, so we can link to it in the changelog.
It is very very basic and not much of a functioning app, feedback welcome.
=> examples: add a KV + typed resolver and authorizer example

packages/grafbase-sdk/src/federation.ts, packages/grafbase-sdk/src/type.ts, packages/grafbase-sdk/tests/unit/types.test.ts
I added support for the `@key` directive to SDL in #790 - this adds the equivalent functionality into the SDK:
```typescript
g.type('User', {
id: g.id()
}).key('id')
```
=> feat: add federation key support to sdk

cli/Cargo.toml, cli/crates/cli/tests/init_ts.rs, cli/crates/common/Cargo.toml, cli/crates/common/build.rs, cli/crates/common/src/consts.rs
I released 0.7.0 of the SDK earlier, but forgot to update the `GRAFBASE_SDK_PACKAGE_VERSION` constant that the CLI uses to create package.json files.
This PR automates that process - instead of having a hardcoded constant we now read the package.json and populate the constant with whatever is in there.
=> feat: pull the current SDK version from its package.json

engine/crates/engine/src/registry/resolvers/postgres/context.rs, engine/crates/engine/src/registry/resolvers/postgres/request/create_many.rs, engine/crates/engine/src/registry/resolvers/postgres/request/create_one.rs, engine/crates/engine/src/registry/resolvers/postgres/request/delete_many.rs, engine/crates/engine/src/registry/resolvers/postgres/request/delete_one.rs, engine/crates/engine/src/registry/resolvers/postgres/request/log.rs, engine/crates/engine/src/registry/resolvers/postgres/request/query/delete.rs, engine/crates/engine/src/registry/resolvers/postgres/request/query/insert.rs, engine/crates/engine/src/registry/resolvers/postgres/request/query/update.rs, engine/crates/engine/src/registry/resolvers/postgres/request/update_many.rs, engine/crates/engine/src/registry/resolvers/postgres/request/update_one.rs, engine/crates/integration-tests/tests/postgres/create_many.rs, engine/crates/integration-tests/tests/postgres/create_one.rs, engine/crates/integration-tests/tests/postgres/create_one/types.rs, engine/crates/integration-tests/tests/postgres/delete_many.rs, engine/crates/integration-tests/tests/postgres/delete_one.rs, engine/crates/integration-tests/tests/postgres/introspection.rs, engine/crates/integration-tests/tests/postgres/update_many.rs, engine/crates/integration-tests/tests/postgres/update_one.rs, engine/crates/parser-postgres/src/registry/context/input.rs, engine/crates/parser-postgres/src/registry/queries/create_many.rs, engine/crates/parser-postgres/src/registry/queries/create_one.rs, engine/crates/parser-postgres/src/registry/queries/delete_many.rs, engine/crates/parser-postgres/src/registry/queries/delete_one.rs, engine/crates/parser-postgres/src/registry/queries/input/filter.rs, engine/crates/parser-postgres/src/registry/queries/update_many.rs, engine/crates/parser-postgres/src/registry/queries/update_one.rs, engine/crates/parser-postgres/src/registry/types/table.rs, engine/crates/postgres-types/src/transport/tcp.rs
This patch changes all Postgres mutations in a way which allows setting the `returning` selection explicitly, or leave it out from the query. So a query that used to work like this:
```graphql
userDeleteMany(filter: { age: { gt: 18 } }) {
id
name
}
```
is now:
```graphql
userDeleteMany(filter: { age: { gt: 18 } }) {
returning {
id
name
}
rowCount
}
```
If the user is not passing the `returning` value in the selection, we do not load any data from the database. This makes sense, if deleting large amounts of data, and the result set is too big to fit to the memory. Additional value `rowCount` is added to mark how many rows the mutation affected.
Now, one can write the delete like so:
```graphql
userDeleteMany(filter: { age: { gt: 18 } }) {
rowCount
}
```
The operation is going to be much …
=> fix(connector): Make Postgres mutations use explicit returning value

.github/actions/cdn_assets/action.yml, .github/actions/cli_assets/action.yml, .github/workflows/cli-partial-release.yml, .github/workflows/cli.yml, .github/workflows/sanitize-alert-schedule.yml, cli/Cargo.lock, cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/crates/server/README.md, cli/crates/server/build.rs, cli/crates/server/src/types.rs, cli/crates/server/templates/pathfinder.hbs, cli/scripts/load-assets.sh
The CLI includes [Pathfinder](https://github.com/grafbase/pathfinder) as part of the `grafbase dev` workflow. A bundled build of Pathfinder is included in the assets file (`assets.tar.gz`) that is built locally when we iterate in this repo, and downloaded from a canonical source for CLI releases. The assets are included in the compiled CLI binaries, then decompressed to `~/.grafbase` when we start a server.
Before this commit, a bundled build of Pathfinder is included in the assets archive that is built and downloaded separately from this repo.
What this commit changes:
- the Pathfinder wrapper app (the `cli-app` package) moves from the website repo to this repo, under `packages/`.
- the Pathfinder build included in the CLI binary is built from source in this repo. **This makes updating …
=> feat(cli): include Pathfinder here instead of through CDN assets

engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/rules/graphql_directive.rs, engine/crates/parser-sdl/src/rules/mongodb_directive.rs, engine/crates/parser-sdl/src/rules/openapi_directive.rs, engine/crates/parser-sdl/src/rules/postgres_directive.rs, engine/crates/parser-sdl/src/validations.rs
Until now we've done no validation of connector names, so silly things like `""` are allowed.  This adds some simple validation using the GraphQL name validation rules.
Fixes GB-5134
=> fix: empty connector names shouldn't be allowed

cli/crates/cli/src/logs.rs, cli/crates/cli/src/output/report.rs
CLI: Adjust runtime logs based on the new federation orientation.
=> fix(logs): CLI: Adjust runtime logs based on the new federation orientation

cli/Cargo.lock, cli/crates/typed-resolvers/Cargo.toml, cli/crates/typed-resolvers/README.md, cli/crates/typed-resolvers/src/analyze.rs, cli/crates/typed-resolvers/src/codegen.rs, cli/crates/typed-resolvers/src/error.rs, cli/crates/typed-resolvers/src/lib.rs, cli/crates/typed-resolvers/tests/schema_types.rs, cli/crates/typed-resolvers/tests/schema_types/basic.expected.ts, cli/crates/typed-resolvers/tests/schema_types/basic.graphql, cli/crates/typed-resolvers/tests/schema_types/basic_enum.expected.ts, cli/crates/typed-resolvers/tests/schema_types/basic_enum.graphql, cli/crates/typed-resolvers/tests/schema_types/custom_scalars.expected.ts, cli/crates/typed-resolvers/tests/schema_types/custom_scalars.graphql, cli/crates/typed-resolvers/tests/schema_types/interfaces.expected.ts, cli/crates/typed-resolvers/tests/schema_types/interfaces.graphql, cli/crates/typed-resolvers/tests/schema_types/keyword_names.expected.ts, cli/crates/typed-resolvers/tests/schema_types/keyword_names.graphql, cli/crates/typed-resolvers/tests/schema_types/recursive_types.expected.ts, cli/crates/typed-resolvers/tests/schema_types/recursive_types.graphql, cli/crates/typed-resolvers/tests/schema_types/type_extensions.expected.ts, cli/crates/typed-resolvers/tests/schema_types/type_extensions.graphql, cli/crates/typed-resolvers/tests/schema_types/union.expected.ts, cli/crates/typed-resolvers/tests/schema_types/union.graphql, cli/crates/typed-resolvers/tests/schema_types/wrapper_types.expected.ts, cli/crates/typed-resolvers/tests/schema_types/wrapper_types.graphql
This PR is large, but mostly because of tests.
First iteration of the implementation of the GraphQL SDL -> TypeScript
resolver types part of Typed Resolvers.
This is a new standalone crate in `cli`. It does not reuse existing
infrastructure because the amount of analysis required on the schema is
very limited: we do not want to do extra validation because we want to
tolerate fairly broken schemas and still generate code,and code
generation has to be fast for integration in the `gb dev` loop.
Unlike graphql-code-generator, we do not generate types for the resolver
functions. By design, the generated module has one TypeScript type per
GraphQL type. They have the same name (except TS reserved keywords), and
they are in the same order in the generated file as in the source file.
We do not …
=> feat(cli): implement typescript code generation for resolvers

cli/Cargo.lock, cli/crates/cli/Cargo.toml, cli/crates/cli/src/build.rs, cli/crates/cli/src/cli_input.rs, cli/crates/cli/src/dev.rs, cli/crates/cli/src/main.rs, cli/crates/cli/src/output/report.rs, cli/crates/cli/src/start.rs, cli/crates/common/src/environment.rs, cli/crates/server/Cargo.toml, cli/crates/server/src/bridge/server.rs, cli/crates/server/src/bridge/udf.rs, cli/crates/server/src/lib.rs, cli/crates/server/src/servers.rs, cli/crates/server/src/types.rs, cli/crates/server/src/udf_builder.rs
- Only a single instance of miniflare is used, shared across workers.
- UDFs are built in parallel
- Adding a very simple cache mechanism, avoiding recompiling UDFs
if nothing changed.
I'm also adding a `build` command which does all the UDF compilation in a separate step. It's only helpful for the `start` command currently, allowing one to `grafbase build` during a docker image build.
Resolves: GB-5109,GB-5110
=> feat: A bunch of improvements for grafbase start and build command

cli/Cargo.lock, engine/Cargo.lock, engine/crates/parser-sdl/Cargo.toml, engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/rules/model_directive.rs, engine/crates/parser-sdl/src/rules/mongodb_directive/model_directive.rs, engine/crates/parser-sdl/src/rules/visitor.rs, engine/crates/parser-sdl/src/rules/visitor/cons.rs, engine/crates/parser-sdl/src/rules/visitor/context.rs, engine/crates/parser-sdl/src/rules/visitor/error.rs, engine/crates/parser-sdl/src/rules/visitor/nil.rs, engine/crates/parser-sdl/src/rules/visitor/trait.rs, engine/crates/parser-sdl/src/rules/visitor/warnings.rs, packages/grafbase-sdk/src/grafbase-schema.ts
Does two things: adds a `Warnings` struct, which prints a warnings if needed:
And, splits the `visitor.rs` into separate modules so it's a bit easier to read.
Closes: GB-5137
=> chore: Deprecate Grafbase database

engine/crates/engine/src/registry/export_sdl.rs, engine/crates/engine/src/registry/federation.rs, engine/crates/engine/src/registry/field_set.rs, engine/crates/engine/src/registry/mod.rs, engine/crates/engine/src/registry/requires.rs, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__flat_output-2.snap, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__petstore_output-2.snap, engine/crates/parser-sdl/src/rules/basic_type.rs, engine/crates/parser-sdl/src/rules/federation/field_set.rs, engine/crates/parser-sdl/src/rules/federation/key.rs, engine/crates/parser-sdl/src/rules/federation/mod.rs
Federation makes quite a lot of use of `FieldSet`s - a simplified GraphQL string without arguments, fragments, spreads etc.
For the sake of speed I added a naive parser of these in a previous PR.  But I'm in the middle of implementing `@requires` which will likely run into the limitations of my previous approach.
So, this PR adds some more thorough parsing.
=> fix: proper FieldSet parsing

engine/crates/parser-openapi/src/graph/debug.rs, engine/crates/parser-openapi/src/graph/input_value.rs, engine/crates/parser-openapi/src/graph/mod.rs, engine/crates/parser-openapi/src/graph/operations.rs, engine/crates/parser-openapi/src/graph/parameters.rs, engine/crates/parser-openapi/src/graph/resource.rs, engine/crates/parser-openapi/src/output/federation.rs, engine/crates/parser-openapi/src/tests/federation.rs, engine/crates/parser-openapi/src/tests/mod.rs
The types `parser-openapi` works with are often just wrappers around a `NodeIndex`.  When working with these it can be quite awkward to debug - if you try to log details of the types you're working with you just get `OutputType(123)` or whatever.
This PR adds a `DebugNode` trait and implements it for some of these wrapper types - basically a clone of `Debug` that takes an `OpenApiGraph` (which is where the actual data these IDs refer to lives).
Also added some better tracing setup for the `parser-openapi` tests.
I've had this sitting on my local machine for a week or two, figured i should get it pushed up before I forget
=> chore: better debug logging in parser-openapi

cli/crates/cli/src/cli_input.rs
Ensure the project context is only required if no reference is passed to the `logs` command.
=> fix(logs): running the `logs` command should be possible without being in a project context

packages/grafbase-sdk/src/index.ts, packages/grafbase-sdk/src/resolver/resolverFn.ts
This is a convenience type for resolver functions. It is generic because resolvers have different parent, argument and return types. It works for both sync and async resolvers. This will be used by generated code as part of the typed resolvers work, so it is not meant primarily for direct end-user consumption.
Related to https://github.com/grafbase/grafbase/pull/843 but not blocking.
first part of GB-5163
=> feat(sdk): add new ResolverFn export

cli/Cargo.lock, cli/crates/cli/Cargo.toml, cli/crates/cli/src/cli_input.rs, cli/crates/cli/src/errors.rs, cli/crates/cli/src/main.rs, cli/crates/cli/src/subgraph.rs, cli/crates/cli/tests/introspection.rs, cli/crates/cli/tests/utils/environment.rs, cli/crates/graphql-introspection/Cargo.toml, cli/crates/graphql-introspection/src/lib.rs, cli/crates/graphql-introspection/src/standard.rs, cli/crates/graphql-introspection/src/subgraph.rs
Introduces a new subcommand `subgraph` and one subcommad to that called `introspect`. This command first runs a query to the given endpoint:
```graphql
query {
_service {
sdl
}
}
```
If this query succeeds, that's the given output. If not, we run the standard GraphQL introspection and output _that_ schema.
Closes: GB-5141
=> cli: Subgraph introspection

cli/crates/typed-resolvers/src/codegen.rs, cli/crates/typed-resolvers/tests/schema_types/basic.expected.ts, cli/crates/typed-resolvers/tests/schema_types/basic_enum.expected.ts, cli/crates/typed-resolvers/tests/schema_types/custom_scalars.expected.ts, cli/crates/typed-resolvers/tests/schema_types/interfaces.expected.ts, cli/crates/typed-resolvers/tests/schema_types/keyword_names.expected.ts, cli/crates/typed-resolvers/tests/schema_types/recursive_types.expected.ts, cli/crates/typed-resolvers/tests/schema_types/type_extensions.expected.ts, cli/crates/typed-resolvers/tests/schema_types/union.expected.ts, cli/crates/typed-resolvers/tests/schema_types/with_resolvers.expected.ts, cli/crates/typed-resolvers/tests/schema_types/wrapper_types.expected.ts
This commit is prompted by a fear that has been visiting me at night since 9aba0fc513e67afb2a877c187f71f782f10c299e. The name of that fear is name collisions in generated code.
Before this commit, we have `safe_ts_type_name()`, a function that takes care of making a GraphQL type name TypeScript-safe, turning `undefined` into `_undefined` for example. We then generate one `export type` or moral equivalent for each GraphQL definition in the GraphQL schema.
There are several problems with that approach:
- Name collisions with other types we generate (`Resolver`) or types from the SDK. Of course we could add extra exceptions and rename `Resolver` to `_Resolver` for example, but that doesn't seem fool proof.
- Discoverability. If we rename types, they are not as discoverable.
The solution …
=> cli: future proof generated TS type names, improve DX

engine/crates/parser-openapi/src/graph/mod.rs, engine/crates/parser-openapi/src/tests/mod.rs, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__petstore_without_prefix.snap
I updated OpenAPI to not prefix types if namespacing was disabled in #828 - but apparently I did not test it well enough because they were still mostly being prefixed.  This fixes that.
=> fix: un-namespaced OpenAPI types were still being prefixed

flake.nix
The `full` and `nightly` dev shells don't evaluate cleanly.
Now `nix flake check` passes.
=> nix: delete dead code

cli/crates/typed-resolvers/src/analyze.rs, cli/crates/typed-resolvers/src/codegen.rs, cli/crates/typed-resolvers/tests/schema_types/extend_root_type.expected.ts, cli/crates/typed-resolvers/tests/schema_types/extend_root_type.graphql
The source of the bug is that the SDL schemas produced by the CLI extend `Query`, `Mutation` and `Subscription` but do not define them. The fix involves defining them ourselves in analysis if they are not already defined.
closes GB-5175
=> fix(cli): fix generated TS code for resolvers on root types

cli/crates/typed-resolvers/src/analyze.rs, cli/crates/typed-resolvers/src/codegen.rs, cli/crates/typed-resolvers/tests/schema_types/extend_root_type.expected.ts, cli/crates/typed-resolvers/tests/schema_types/with_resolvers.expected.ts, cli/crates/typed-resolvers/tests/schema_types/with_resolvers.graphql
For object and interface types, in the generated TypeScript code. This is a correctness problem:
- In the `parent` argument, because that data may not be present (e.g. sibling resolver's responses)
- In the return types, because the resolver is not necessarily responsible for returning that data.
Thanks @obmarg  for noticing the problems.
closes GB-5177
=> typed-resolvers: make all fields that could have resolvers attached optional

crates/composition/.gitignore, crates/composition/Cargo.toml, crates/composition/src/compose_supergraph.rs, crates/composition/src/context.rs, crates/composition/src/diagnostics.rs, crates/composition/src/ingest_subgraph.rs, crates/composition/src/lib.rs, crates/composition/src/result.rs, crates/composition/src/strings.rs, crates/composition/src/subgraphs.rs, crates/composition/src/subgraphs/walkers.rs, crates/composition/src/supergraph.rs, crates/composition/src/supergraph/render.rs, crates/composition/tests/composition/object_fields_clash/subgraphs/critics.graphql, crates/composition/tests/composition/object_fields_clash/subgraphs/label.graphql, crates/composition/tests/composition/object_fields_clash/supergraph.graphql, crates/composition/tests/composition/object_interface_clash/subgraphs/accounting.graphql, crates/composition/tests/composition/object_interface_clash/subgraphs/inventory.graphql, crates/composition/tests/composition/object_interface_clash/supergraph.graphql, crates/composition/tests/composition/objects_basic/subgraphs/a.graphql, crates/composition/tests/composition/objects_basic/subgraphs/b.graphql, crates/composition/tests/composition/objects_basic/supergraph.graphql, crates/composition/tests/composition_tests.rs
This commit is a proposal for a general crate structure for supergraph
composition. Everything is a suggestion and up for discussion. It is
definitely very far from complete, and some areas (error reporting) are
just sketched.
What this commit _does_ contains: a proposed public API with a compose
function:
```rust
pub fn compose(subgraphs: &Subgraphs) -> CompositionResult
```
Where `CompositionResult` is SDL for a supergraph and diagnostics.
As well as the general flow, a test suite and the two following
composition rules as a proofs of concept:
- Declaration of different kinds cannot be merged. For example if you
have `type User { ... }` and `interface User { ... }` in two different
subgraphs, this is a composition error.
- Objects can be merged as long as their fields do not overlap (no …
=> composition: first bits

.github/workflows/composition.yml, crates/composition/Cargo.toml, crates/composition/src/compose_supergraph.rs, crates/composition/src/ingest_subgraph.rs, crates/composition/src/ingest_subgraph/schema_definitions.rs, crates/composition/src/subgraphs.rs, crates/composition/src/subgraphs/walkers.rs, crates/composition/tests/composition/shareable_basic/subgraphs/accounts.graphql, crates/composition/tests/composition/shareable_basic/subgraphs/marketing.graphql, crates/composition/tests/composition/shareable_basic/subgraphs/subscriptions.graphql, crates/composition/tests/composition/shareable_basic/supergraph.graphql
Implemented in this PR:
- `@link` directive imports and aliasing (see docs in diff)
- Fields with `@shareable` are allowed to be defined in multiple
subgraphs
Also sets up very basic CI for crates/composition.
Part of GB-5176
=> composition: implement @shareable and @link basics

cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.41.2.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Fixes
- Fields of generated TypeScript types for sibling and downstream resolvers are now optional (#861)
- Generated TS resolver types now work even if you extend root types (e.g. Query) without defining them (#859)
=> cli: release 0.41.2

engine/crates/engine/src/response/mod.rs
If you're running rover in development it'll poll your subgraph every 2 seconds.  If that subgraph is `grafbase dev` then it's quite noisy: a constant stream of `query SubgraphIntrospectQuery 0ns` messages in your console.
This PR updates the `is_operation_introspection` query to consider the `_service` field as part of introspection, which should silence those queries like we do with normal introspection.
=> fix: silence federation introspection queries in dev command

engine/crates/engine/parser/src/lib.rs, engine/crates/engine/parser/src/parse/executable.rs, engine/crates/engine/parser/src/parse/mod.rs, engine/crates/engine/src/context/field.rs, engine/crates/engine/src/registry/resolvers/graphql/serializer.rs, engine/crates/engine/src/registry/resolvers/join.rs, engine/crates/engine/src/registry/resolvers/mod.rs, engine/crates/engine/value/src/argument_set.rs, engine/crates/engine/value/src/lib.rs, engine/crates/integration-tests/tests/execution/joins.rs, engine/crates/integration-tests/tests/execution/mod.rs, engine/crates/integration-tests/tests/graphql_connector/basic.rs, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__petstore_without_namespace.snap, engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/rules/basic_type.rs, engine/crates/parser-sdl/src/rules/extend_connector_types.rs, engine/crates/parser-sdl/src/rules/join_directive.rs, engine/crates/parser-sdl/src/rules/mod.rs
I've been working on a test case for the OpenAPI<->Subgraph integration where I've got a Locations API & a Reviews API.  With the integration as it currently stands I've managed to add a `location` field into the `Review` entity quite easily.  What's currently quite difficult is extending the `Location` type with endpoints from the Reviews API.
My reviews API has an endpoint `location_reviews/:id` which I'd like to add to the `Location` type as `reviewsForLocation: [Review]`.  The OpenAPI connector exposes this endpoint as a field on the `Query` type: `locationReviews(locationId: String)`.  But there's no way to add that `Query` field onto the `Location` type.
I've solved that by adding the `@join` directive that we've spoke about in the past, as it does basically what we want.  So for my …
=> feat: @join directive

engine/crates/engine/src/registry/federation.rs, engine/crates/engine/src/registry/resolvers/federation.rs, engine/crates/integration-tests/tests/federation/mod.rs, engine/crates/integration-tests/tests/federation/openapi.rs, engine/crates/parser-sdl/src/rules/basic_type.rs, engine/crates/parser-sdl/src/rules/extend_connector_types.rs, engine/crates/parser-sdl/src/rules/federation/key.rs, engine/crates/parser-sdl/src/rules/join_directive.rs, engine/crates/parser-sdl/src/rules/requires_directive.rs, engine/crates/parser-sdl/src/rules/snapshots/parser_sdl__rules__join_directive__tests__acceptable_return_type_nullability_mismatch.snap, engine/crates/parser-sdl/src/rules/snapshots/parser_sdl__rules__join_directive__tests__return_type_lists_success.snap, engine/crates/parser-sdl/src/validations.rs
The OpenAPI connector attempts to infer federation keys from the shape of the underlying API.  If an endpoint returns a named type from the schema, and has a URL parameter that clearly maps to some field on that type, then we can easily generate a resolver.  This works OK for some schemas but there are a lot of edge cases where it just doesn't.
For those cases, we want users to be able to specify how a key should be resolved when the `_entities` field is called with that key.  This PR does that by adding a `select` field to the `@key` directive - which takes the same input as the `@join` directive and is hooked up to the same resolution mechanism.
=> feat: extend openapi types with federation keys

engine/crates/postgres-types/src/transport/tcp.rs, engine/crates/postgres-types/src/transport/tcp/executor.rs, engine/crates/postgres-types/src/transport/tcp/transaction.rs
This allows us to use transactions with the transport, and run the same query/execute methods as we do with the normal functions.
=> feat(connector): Transaction support for Postgres

engine/crates/postgres-types/src/transport/tcp.rs
This makes it much easier to use the transaction in the api: the postgres-types is the crate dictating the version and the feature flags, and we can just
```rust
use postgres_types::transport::tcp::Transaction;
```
in the api.
=> chore: pub use postgres transport

Dockerfile
We've made a few changes to the build process since this was added, so needed some updates:
1. The CLI now reads the SDKs `package.json`.  Easy to fix.
2. We also need the cli-app assets.  I've opted to build these in the dockerfile.
=> fix: update the Dockerfile

cli/Cargo.lock, engine/Cargo.lock, engine/crates/postgres-connector-types/Cargo.toml, engine/crates/postgres-connector-types/src/transport/tcp.rs
Tokio-postgres loves to cache everything internally and in secrecy. This will not play well with transactional connection pools. Let's disable that.
=> fix(connector): Prevent type statement caching for Postgres

.github/workflows/engine.yml, crates/composition/src/lib.rs
This is an omission from https://github.com/grafbase/grafbase/pull/889. When we update this crate in api, we will have to call render_sdl on the federated graph to get the SDL string.
=> composition: re-export grafbase_federated_graph::render_sdl

crates/composition/src/compose.rs, crates/composition/src/compose/context.rs, crates/composition/src/compose/input_object.rs, crates/composition/src/composition_ir.rs, crates/composition/src/emit_federated_graph.rs, crates/composition/src/emit_federated_graph/context.rs, crates/composition/src/emit_federated_graph/field_types_map.rs, crates/composition/src/subgraphs.rs, crates/composition/src/subgraphs/definitions.rs, crates/composition/src/subgraphs/fields.rs, crates/composition/src/subgraphs/keys.rs, crates/composition/src/subgraphs/walkers.rs, crates/composition/tests/composition/enum_only_outputs/federated.graphql, crates/federated-graph/src/federated_graph.rs, crates/federated-graph/src/render_sdl.rs
Populate the grafbase_federated_graph::Object::resolvable_keys list for each object.
closes GB-5266
=> composition: populate entity provenance

cli/crates/server/src/bridge/server.rs, cli/crates/server/src/errors.rs
It was wrong, leading to a very confusing "node isn't installed" error if a resolver failed to build.
=> fix: correct the error on UDF build errors

crates/composition/src/compose.rs, crates/composition/src/compose/context.rs, crates/composition/src/composition_ir.rs, crates/composition/src/emit_federated_graph.rs, crates/composition/tests/composition/input_objects_nonshared_required_field/subgraphs/cyclist.graphql, crates/composition/tests/composition/missing_query_type/federated.graphql, crates/composition/tests/composition/missing_query_type/subgraphs/one.graphql, crates/composition/tests/composition/missing_query_type/subgraphs/two.graphql, crates/composition/tests/composition/object_fields_clash/subgraphs/label.graphql, crates/composition/tests/composition/object_interface_clash/subgraphs/accounting.graphql
By moving finding the root types from emit_federated_graph to composition, where we can produce diagnostics.
=> composition: handle missing `Query` without panicking

cli/Cargo.lock, cli/crates/backend/src/project.rs, cli/crates/cli/src/init.rs, cli/crates/cli/src/output/report.rs
`grafbase init` can set up a project from a template.  The output assumed that all the templates were written using SDL though, and always pointed the user at a `schema.graphql` file.  This makes it a little smarter: it'll now do the right thing depending on the template.
Unfortunately had to get rid of a `tokio::main` attr because it didn't like  return values, but 🤷‍♂️.
=> fix: don't assume templates are SDL based in init

engine/crates/integration-tests/tests/federation/keys.rs, engine/crates/integration-tests/tests/federation/mod.rs
Seeing a few failures around these scenarios in the apollo subgraph tests, even though I thought we had support for them.
Decided to write a few tests of our own just to make sure.
Part of GB-4983
=> test: testing repeated, composite & multi-field keys

engine/crates/engine/src/registry/export_sdl.rs, engine/crates/engine/src/registry/mod.rs, engine/crates/engine/src/registry/tests.rs, engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__array_input_value.snap, engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__conversion.snap, engine/crates/parser-graphql/src/snapshots/parser_graphql__tests__counries_output.snap, engine/crates/parser-graphql/src/snapshots/parser_graphql__tests__unnamed_connector.snap, engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/rules/basic_type.rs, engine/crates/parser-sdl/src/rules/deprecated_directive.rs, engine/crates/parser-sdl/src/rules/enum_type.rs, engine/crates/parser-sdl/src/rules/extend_connector_types.rs, engine/crates/parser-sdl/src/rules/extend_query_and_mutation_types.rs, engine/crates/parser-sdl/src/rules/mod.rs, engine/crates/parser-sdl/src/snapshots/parser_sdl__tests__schema.snap, engine/crates/parser-sdl/src/snapshots/parser_sdl__tests__test_model_reserved_fields-req-a.snap, engine/crates/parser-sdl/src/snapshots/parser_sdl__tests__test_model_reserved_fields-req-b.snap
While testing the federation subgraph stuff, I noticed we don't support the `@deprecated` directive properly.  This is core GraphQL stuff so figured I should probably fix.
Part of GB-5001
=> fix: `@deprecated` directive

examples/nuxt/src/plugins/urql.ts
This is a DX improvement when developing - we can avoid loading the entire barrel file at `#app` by using the new granular imports merged in https://github.com/nuxt/nuxt/pull/23951.
=> fix: import nuxt composables from #imports

engine/crates/engine/src/registry/export_sdl.rs, engine/crates/engine/src/registry/mod.rs, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__flat_output-2.snap, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__petstore_output-2.snap, engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/registry/pagination.rs, engine/crates/parser-sdl/src/registry/search.rs, engine/crates/parser-sdl/src/rules/basic_type.rs, engine/crates/parser-sdl/src/rules/extend_connector_types.rs, engine/crates/parser-sdl/src/rules/extend_query_and_mutation_types.rs, engine/crates/parser-sdl/src/rules/federation/inaccessible.rs, engine/crates/parser-sdl/src/rules/federation/mod.rs, engine/crates/parser-sdl/src/rules/federation/tag.rs
I think these are the last two simple federation directives.
They can apply to a lot more than just fields but for now I'm only supporting them on fields.  Not super hard to fix that later, but would like to save the time for now.
=> feat: `@inaccessible` & `@tag` directives

.github/workflows/sdk.yml
#921 added a default working directory of `./packages`, but this step was trying to `cd packages`.
=> fix: the publish step in the SDK CLI

cli/crates/cli/tests/dev_watch.rs, cli/crates/typed-resolvers/src/error.rs, cli/crates/typed-resolvers/src/lib.rs, cli/crates/typed-resolvers/tests/schema_types.rs, engine/crates/parser-sdl/src/rules/experimental.rs
Unfortunately we can't use the same mechanism as the other experimental features, because the typed resolvers logic is outside of the engine and doesn't have access to the registry.
Confirmed that this works locally, ideally there would be automated tests, but this should go in today's release.
closes GB-5332
=> cli: make codegen opt-in with an experimental feature

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.9.1.md, packages/grafbase-sdk/package.json, packages/grafbase-sdk/src/experimental.ts
- The typed resolvers code generation is now an experimental feature, you have to enable it in the `experimental.codegen` field in your config.
---
Also adds a line that was missing in https://github.com/grafbase/grafbase/pull/930. Can do a separate PR if that is problematic.
=>  sdk: release 0.9.1

cli/crates/backend/src/api/create.rs, cli/crates/backend/src/api/deploy.rs, cli/crates/backend/src/api/graphql/api.graphql, cli/crates/backend/src/api/graphql/types/mutations.rs, cli/crates/backend/src/errors.rs, cli/crates/backend/src/project.rs, cli/crates/cli/src/output/report.rs, cli/crates/cli/tests/custom_resolvers.rs, cli/crates/cli/tests/dev_watch.rs, cli/crates/cli/tests/init.rs, cli/crates/cli/tests/init_ts.rs, cli/crates/cli/tests/link.rs, cli/crates/cli/tests/utils/environment.rs, cli/crates/common/src/environment.rs, cli/crates/server/src/codegen_server.rs, cli/crates/server/src/environment.rs, cli/crates/server/src/servers.rs
Introduce a fallback mechanism in searching the paths such as the current `grafbase` subdirectory remains supported. It will be phased out in the future. At the same time, the main search path for 'schema.graphql' and 'grafbase.config.ts' will now be the current directory.
=> fix(cli): Change the project root semantics such as `grafbase/` becomes only a fallback for the project root

cli/crates/cli/tests/link.rs, cli/crates/common/src/consts.rs, cli/crates/common/src/environment.rs, cli/crates/server/src/file_watcher.rs
With the new projecct root scheme, .grafbase is located inside the project root
Therefore, it must be excluded from watching.
=> fix(watcher): Ensure the watcher doesn't pick up on changes from .grafbase

.github/CODEOWNERS
That directory doesn't exist anymore, the crates that were there were moved to engine/crates/
=> fix(CODEOWNERS): remove entry about crates/

engine/crates/integration-tests/tests/postgres/find_one.rs, engine/crates/integration-tests/tests/postgres/introspection.rs, engine/crates/parser-postgres/src/introspection/queries/enums.sql, engine/crates/parser-postgres/src/registry/context/input.rs, engine/crates/parser-postgres/src/registry/queries/input.rs, engine/crates/parser-postgres/src/registry/queries/input/create.rs, engine/crates/parser-postgres/src/registry/queries/input/filter.rs, engine/crates/parser-postgres/src/registry/queries/input/update.rs, engine/crates/parser-postgres/src/registry/types.rs, engine/crates/parser-postgres/src/registry/types/scalar.rs, engine/crates/parser-postgres/src/registry/types/table.rs, engine/crates/postgres-connector-types/src/database_definition/walkers/table_column.rs
This case was missing from our tests:
- Using a namespaced connector
- A table with an enum column
- A relation to that table so that the side with an enum column being to-many
Now the update and filter types were missing, and the user gets an error `Type 'EnumTypeName' not found!`
=> fix(postgres): Add enum filter and update types for nested collections

cli/crates/cli/tests/owner.rs
These were hardcoded with an expiration date of 1700000000 which was yesterday, causing all the tests to suddenly fail. I've updated the tests to just generate their own JWTs, which should prevent this becoming an issue again.
Hardcoded JWTs in tests is kind of a bad idea anyway - harder to debug, harder to write, requires more documentation and you run into silly things like this.
=> fix: remove hardcoded JWTs from owner tests

engine/Cargo.lock, engine/crates/integration-tests/Cargo.toml, engine/crates/integration-tests/src/federation/builder.rs, engine/crates/integration-tests/tests/federation/basic/fragments.rs, engine/crates/integration-tests/tests/federation/basic/mod.rs, engine/crates/integration-tests/tests/federation/basic/variables.rs
Updates the federation tests to start their mock servers & introspect them over HTTP.
This commit also temporarily passes the downstream URL in as a the name of the subgraph.  I'll change this back when the composition library lets you pass in a URL and a name.
Part of GB-5337
=> test: introsect subgraphs in federation integration tests

cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.44.3.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json, engine/Cargo.lock, engine/Cargo.toml
Features
- `grafbase subgraphs introspect` has been renamed to `grafbase introspect`.
- New hidden subcommands in CLI: `schema`, `publish` and `subgraphs`.
=> cli: release 0.44.3

engine/crates/composition/src/ingest_subgraph.rs, engine/crates/composition/src/subgraphs.rs, engine/crates/composition/src/subgraphs/walkers.rs, engine/crates/composition/tests/composition/custom_scalars_basic/federated.graphql, engine/crates/composition/tests/composition/enum_only_inputs/federated.graphql, engine/crates/composition/tests/composition/enum_only_outputs/federated.graphql, engine/crates/composition/tests/composition/enum_unused/federated.graphql, engine/crates/composition/tests/composition/input_object_basic/federated.graphql, engine/crates/composition/tests/composition/interfaces_basic/federated.graphql, engine/crates/composition/tests/composition/object_field_arguments_basic/federated.graphql, engine/crates/composition/tests/composition/objects_basic/federated.graphql, engine/crates/composition/tests/composition/shareable_basic/federated.graphql, engine/crates/composition/tests/composition/unions_basic/federated.graphql, engine/crates/composition/tests/composition_tests.rs, engine/crates/integration-tests/src/federation/builder.rs
The output from `graphql-composition` has a `url` field in it, which was being populated from the `name`.  This adds another parameter for the `url` and populates from that instead.
Tried not to overthink this: it's just a plain &str argument rather than a `Url` or anything more strongly typed.  Though happy to change if anyone has preferences.
=> feat: graphql-composiiton now accepts a url

cli/crates/backend/src/api/create.rs, cli/crates/backend/src/api/deploy.rs, cli/crates/common/src/environment.rs
The traversal when constructing the archive should use a minimum depth of 1.
This also changes how the relative project root is determined (it isn't hardcoced to '.'). This coincidentally allows people to keep using UDFs outside the relative project root path, which should be a common use case.
=> fix(deploy): Fix the root path handling for newly created projects.

engine/crates/engine-v2/schema/src/conversion.rs, engine/crates/engine-v2/schema/src/lib.rs, engine/crates/engine-v2/src/plan/planner.rs, engine/crates/integration-tests/tests/federation/basic/mod.rs
=> fix: Only set resolvers at root fields in the v2 schema for federation

cli/crates/cli/tests/custom_resolvers.rs, cli/crates/cli/tests/utils/environment.rs, cli/crates/common/src/environment.rs
We have failed to account for the new default project root path in how we're resolving the paths to UDFs.
Ensure the tests are parametrised by both back-compat and present scheme.
=> fix(udf): Fix an issue with path resolution for resolvers/authorizers with the new root scheme

cli/crates/federated-dev/src/dev/composer.rs, cli/crates/federated-dev/src/dev/router.rs
Some of the handler functions in federation dev return `Result`, which makes it really easy to use `?`.  Normally this would be good, but in this case `?` is going to break the loop inside these actors, causing them to shutdown their channels, and the system to subtly stop working properly.
This updates two of the more critical actors to handle errors a bit more explicitly.  I've left Refresher & Ticket alone for now because their only instances of `?` are probably fine to early return.  Though maybe we should just be consistent, any thoughts?
=> chore: don't return result from some actor handler functions

engine/crates/engine-v2/schema/src/conversion.rs, engine/crates/engine-v2/schema/src/ids.rs, engine/crates/engine-v2/schema/src/introspection.rs, engine/crates/engine-v2/schema/src/lib.rs, engine/crates/engine-v2/src/request/binder.rs
Adding the introspection fields into the schema for engine-v2. They're not used currently and they're missing a resolver, but they're there. :)
=> Adding introspetion fields to engine v2 schema

cli/crates/cli/tests/custom_resolvers.rs, cli/crates/server/src/environment.rs
Environment variables from grafbase/.env weren't being picked up after a recent regression. This PR fixes that.
=> fix(udf): Fix the handling of the .env file in grafbase/ for UDFs.

engine/crates/composition/src/compose/object.rs, engine/crates/composition/src/ingest_subgraph.rs, engine/crates/composition/src/ingest_subgraph/nested_key_fields.rs, engine/crates/composition/src/ingest_subgraph/object.rs, engine/crates/composition/src/subgraphs/definitions.rs, engine/crates/composition/src/subgraphs/field_types.rs, engine/crates/composition/src/subgraphs/fields.rs, engine/crates/composition/src/subgraphs/keys.rs, engine/crates/composition/tests/composition/entity_composite_key_basic/federated.graphql, engine/crates/composition/tests/composition/entity_composite_key_basic/subgraphs/courses.graphql, engine/crates/composition/tests/composition/entity_composite_key_basic/subgraphs/ratings.graphql, engine/crates/composition/tests/composition/entity_composite_key_basic/subgraphs/students.graphql, engine/crates/composition/tests/composition/entity_composite_key_nested/federated.graphql, engine/crates/composition/tests/composition/entity_composite_key_nested/subgraphs/patient_info.graphql, engine/crates/composition/tests/composition/entity_composite_key_nested/subgraphs/patient_record.graphql, engine/crates/composition/tests/composition/entity_staggered_composite_key/federated.graphql, engine/crates/composition/tests/composition/entity_staggered_composite_key/subgraphs/first.graphql, engine/crates/composition/tests/composition/entity_staggered_composite_key/subgraphs/second.graphql, engine/crates/federated-graph/src/from_sdl.rs
Concretely, entities defining keys like `@key(fields: "id name")` and
even nested selections like `@key(fields: "patient { id } recordId")`.
A lot of the complexity in this PR comes from the machinery to detect
that:
1. An object is part of an entity in a subgraph because one of its field
is part of a nested key on another entity.
2. A field is part of a key, not on its parent object but another object
that includes it in its key through a nested selection.
closes GB-5264
=> composition: implement composite key support

cli/crates/backend/src/api/graphql/types/queries/fetch_subgraph_schema.rs, cli/crates/backend/src/api/publish.rs, cli/crates/backend/src/api/schema.rs, cli/crates/backend/src/api/subgraphs.rs, cli/crates/cli/src/cli_input/project_ref.rs
As you will see in the diff, this works everywhere except in `grafbase schema` and `grafbase subgraphs`, because the branch is required by the API schema in these cases.
=> cli: make branch optional in ProjectRef

engine/crates/postgres-connector-types/src/transport.rs, engine/crates/postgres-connector-types/src/transport/tcp.rs, engine/crates/postgres-connector-types/src/transport/tcp/transaction.rs
The close function will take care the client and connection are cleanly closed. This is going to solve the issue in the API with connection leaks and all kinds of annoying race conditions.
=> fix: Introduce closing functionality to Postgres transport

engine/crates/composition/src/ingest_subgraph/schema_definitions.rs, engine/crates/composition/tests/composition/entity_multiple_keys_basic/federated.graphql, engine/crates/composition/tests/composition/entity_multiple_keys_basic/subgraphs/multi_key.graphql, engine/crates/composition/tests/composition/entity_multiple_keys_basic/subgraphs/single_key.graphql, engine/crates/composition/tests/composition/enum_only_outputs/subgraphs/activities.graphql, engine/crates/composition/tests/composition/enum_only_outputs/subgraphs/episodes.graphql, engine/crates/composition/tests/composition/enum_only_outputs/subgraphs/teletubbyRepository.graphql, engine/crates/composition/tests/composition/enum_strict_matching_error/subgraphs/activities.graphql, engine/crates/composition/tests/composition/enum_strict_matching_error/subgraphs/episodes.graphql, engine/crates/composition/tests/composition/enum_strict_matching_error/subgraphs/teletubbyRepository.graphql, engine/crates/composition/tests/composition/inconsistent_entitiness/subgraphs/natural-reserve.graphql, engine/crates/composition/tests/composition/inconsistent_entitiness/subgraphs/zoo.graphql, engine/crates/composition/tests/composition/inconsistent_keys/subgraphs/academia.graphql, engine/crates/composition/tests/composition/inconsistent_keys/subgraphs/novelists.graphql, engine/crates/composition/tests/composition/input_object_basic/subgraphs/emailbook.graphql, engine/crates/composition/tests/composition/input_object_basic/subgraphs/phonebook.graphql, engine/crates/composition/tests/composition/provides_basic/subgraphs/products.graphql, engine/crates/composition/tests/composition/provides_basic/subgraphs/users.graphql, engine/crates/composition/tests/composition/requires_basic/subgraphs/chilies.graphql
Change federation directive visibility rules: to align with the ecosystem, do not require an `@link` directive to be present to put the federation directives (`@key`, `@shareable`, `@provides`, etc.) in scope, unprefixed.
Test multikeys: add a test case with an entity with multiple keys to confirm that it works.
closes GB-5265
closes GB-5367
=> composition: change federation directive visibility rules, test multikeys

engine/crates/composition/src/composition_ir.rs, engine/crates/composition/src/emit_federated_graph.rs, engine/crates/composition/src/ingest_subgraph.rs, engine/crates/composition/src/subgraphs/definitions.rs, engine/crates/composition/tests/composition/interface_implementing_interface_basic/federated.graphql, engine/crates/composition/tests/composition/interface_implementing_interface_basic/subgraphs/product.graphql, engine/crates/composition/tests/composition/interface_implementing_interface_basic/subgraphs/user.graphql, engine/crates/composition/tests/composition/interfaces_basic/federated.graphql, engine/crates/composition/tests/composition_tests.rs, engine/crates/federated-graph/src/federated_graph.rs, engine/crates/federated-graph/src/from_sdl.rs, engine/crates/federated-graph/src/render_sdl.rs, engine/crates/integration-tests/tests/federation/introspection.rs
Previously, we were not adding `implements x & y & z` to any model or interface in the federated schemas. This commit implements the composition of these implementations.
closes GB-5393
=> composition: compose interface implementations 

engine/crates/composition/src/compose/context.rs, engine/crates/composition/src/compose/enums.rs, engine/crates/composition/src/compose/input_object.rs, engine/crates/composition/src/compose/interface.rs, engine/crates/composition/src/compose/object.rs, engine/crates/composition/src/composition_ir.rs, engine/crates/composition/src/emit_federated_graph.rs, engine/crates/composition/src/ingest_subgraph.rs, engine/crates/composition/src/ingest_subgraph/enums.rs, engine/crates/composition/src/ingest_subgraph/object.rs, engine/crates/composition/src/lib.rs, engine/crates/composition/src/subgraphs.rs, engine/crates/composition/src/subgraphs/enums.rs, engine/crates/composition/src/subgraphs/fields.rs, engine/crates/composition/tests/composition/composed_directives_basic/federated.graphql, engine/crates/composition/tests/composition/composed_directives_basic/subgraphs/birdwatch_basic.graphql, engine/crates/composition/tests/composition/composed_directives_basic/subgraphs/observations.graphql, engine/crates/composition/tests/composition/composed_directives_basic/subgraphs/sightings.graphql, engine/crates/federated-graph/src/from_sdl.rs, engine/crates/federated-graph/src/render_sdl.rs
This is the first PR that composes directives, so some of the work here is starting to lay down foundations for this.
What is implemented:
- `@deprecated` everywhere it is valid in the GraphQL 2021 spec (i.e. object fields and enum values)
- `@tag` on object fields. It can be in many other places, but I did not want to make this PR much larger than it already is.
Closes GB-5395
Part of GB-5396
=> composition: implement @deprecated, @tag on fields

.github/actions/sanitize/action.yml, cli/crates/cli/tests/custom_resolvers.rs
Fixing:
```
--- TRY 3 STDERR:        grafbase::custom_resolvers test_field_resolver::case_10::variant_2______grafbase___________ ---
error This project's package.json defines "packageManager": "yarn@^yarn@1.22.0". However the current global version of Yarn is 1.22.21.
Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
thread 'test_field_resolver::case_10::variant_2______grafbase___________' panicked at crates\cli\tests\custom_resolvers.rs:298:48:
should have succeeded: Custom { kind: Other, error: …
```
=> fix custom resolver CI issue

Cargo.lock, cli/crates/gateway/Cargo.toml, cli/crates/gateway/src/executor.rs, cli/crates/gateway/src/lib.rs, cli/crates/server/src/errors.rs, cli/crates/server/src/servers.rs, engine/crates/engine/src/registry/resolvers/postgres.rs, engine/crates/engine/src/registry/resolvers/postgres/context.rs, engine/crates/integration-tests/src/engine/builder.rs, engine/crates/runtime-local/src/pg.rs, engine/crates/runtime/src/pg.rs
This caches connections for postgres for local dev, storing them to a dumb hashmap. No pooling yet, but for quick and dirty dev runs this cuts hundreds of milliseconds from every query.
I seriously hope the factory changes don't hurt us in the API. We might want to have an extra command for a cached connections, if that is the case.
=> fix(postgres): On a local context, we want to cache connections

engine/crates/engine-v2/src/executor/graphql/query.rs, engine/crates/engine-v2/src/request/bind.rs, engine/crates/integration-tests/src/mocks/graphql.rs, engine/crates/integration-tests/src/mocks/graphql/federation/accounts.rs, engine/crates/integration-tests/src/mocks/graphql/federation/mod.rs, engine/crates/integration-tests/src/mocks/graphql/federation/products.rs, engine/crates/integration-tests/src/mocks/graphql/federation/reviews.rs, engine/crates/integration-tests/tests/federation/introspection.rs, engine/crates/integration-tests/tests/federation/mod.rs, engine/crates/integration-tests/tests/federation/subgraphs/mod.rs
Adding fake federation subgraphs and execute two tests on those with a few bug fixes.
=> chore: Add simple engine-v2 test with a query having fields from two different subgraphs

cli/Makefile.toml
It broke with yesterday's PR merging the two cargo workspaces. The solution is to upgrade only `grafbase` (the crate in `cli/crates/cli`). That cascades to bumping all crates that inherit the workspace version, which is the expected behaviour.
=> cli: fix cargo make `bump` script

.github/workflows/cli-partial-release.yml
The script expects to find a `Cargo.toml` in cli/, but it moved to the repo root.
=> cli: remove cd in cli release workflow

Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/backend/src/api/deploy.rs, cli/crates/backend/src/project.rs
Use [tar](https://crates.io/crates/tar) rather than [async-tar](https://crates.io/crates/async-tar) to create the archive that gets pushed as part of the `grafbase deploy` flow.
=> fix(deploy): Attempt at fixing GB-5429

.github/actions/init_rust_job/action.yml
We suspect there might be problems with the buildjet cache and macos builders
=> ci: try reverting to actions/cache@v3

engine/crates/integration-tests/tests/postgres/introspection.rs, engine/crates/postgres-connector-types/src/database_definition/walkers/relation.rs, engine/crates/postgres-connector-types/src/database_definition/walkers/table.rs
User had breakage due to this issue. They have a table without any unique constraints, which we filter out from rendering (e.g. in graphql, it doesn't make much sense to use these tables due to most of the operations breaking or not being available). This fix prevents _relations_ to these tables from getting rendered, which lead to interesting "type does not exist" problems.
=> fix(postgres): Do not display relations to tables we cannot show

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.45.7.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Fixes
- OpenAPI connector: infer entities for resources with multiple schemas. (#1034)
The connector will now infer response types in more cases where it previously was more strict.
=> cli: bump to 0.45.7

cli/crates/cli/src/main.rs, cli/crates/cli/src/output/report.rs, cli/crates/federated-dev/src/dev/bus/message.rs, cli/crates/federated-dev/src/dev/composer.rs, cli/crates/federated-dev/src/dev/router.rs
The output messages fall in two categories:
- In the federated dev process output
+ We now log the outcome of composition (success/failure) whenever a subgraph is added or removed from the federated graph.
- The `publish` output
+ Improved rendering of composition errors on publish
+ New message when publish succeeds
closes GB-5513
closes GB-5514
closes GB-5515
closes GB-5516
=> cli: improve logged output of federated dev

engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/rules/extend_field.rs, engine/crates/parser-sdl/src/rules/mod.rs, engine/crates/parser-sdl/src/tests.rs
Users might want to add federation directives to connector generated types. Doing this with the existing extend keyword is awkward because either:
1. We'd have to force users to write out the full field definition or
2. We'd have to just ignore the arguments & return type inside extensions - which is a bit ambigous, is the user adding a clashing field or adding a field just to extend its directives?
So I've added a `extendField` directive to objects to allow users to do this:
```graphql
extend type Blah
@extendField(
name: "foo"
external: true
override: {from: "Blah"}
provides: {fields: "id"}
)
```
Part of GB-5518
=> feat: `@extendField` directive

packages/grafbase-sdk/src/grafbase-schema.ts, packages/grafbase-sdk/src/type.ts, packages/grafbase-sdk/tests/unit/types.test.ts
Missed this when adding federation to the SDK.  Will do a follow up PR with the ability to extend fields with attributes as well.
Part of GB-5518
=> feat: connector types can be extended with federation keys

engine/crates/composition/src/compose.rs, engine/crates/composition/src/compose/context.rs, engine/crates/composition/src/compose/entity_interface.rs, engine/crates/composition/src/compose/enums.rs, engine/crates/composition/src/compose/input_object.rs, engine/crates/composition/src/compose/interface.rs, engine/crates/composition/src/compose/object.rs, engine/crates/composition/src/compose/scalar.rs, engine/crates/composition/src/composition_ir.rs, engine/crates/composition/src/emit_federated_graph.rs, engine/crates/composition/src/ingest_subgraph.rs, engine/crates/composition/src/ingest_subgraph/object.rs, engine/crates/composition/src/subgraphs/definitions.rs, engine/crates/composition/src/subgraphs/fields.rs, engine/crates/composition/tests/composition/descriptions_basic/federated.graphql, engine/crates/composition/tests/composition/descriptions_basic/subgraphs/selfExplanatoryTofu.graphql, engine/crates/composition/tests/composition/descriptions_basic/subgraphs/tofu.graphql, engine/crates/federated-graph/src/federated_graph.rs, engine/crates/federated-graph/src/from_sdl.rs, engine/crates/federated-graph/src/render_sdl.rs
The strategy for composing descriptions seems to be picking the first one we find. There can be an optional lint to enforce that they are the same across subgraphs.
closes GB-5394
=> composition: implement description composition

Cargo.lock, engine/crates/engine-v2/Cargo.toml, engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/executor/graphql/mod.rs
=> fix(engine-v2): Add the ability to inject a self domain configuration with a custom `worker::Fetcher` to route requests through

engine/crates/composition/src/compose/context.rs, engine/crates/composition/src/compose/directives.rs, engine/crates/composition/src/compose/entity_interface.rs, engine/crates/composition/src/compose/enums.rs, engine/crates/composition/src/compose/input_object.rs, engine/crates/composition/src/compose/interface.rs, engine/crates/composition/src/compose/object.rs, engine/crates/composition/src/compose/scalar.rs, engine/crates/composition/src/subgraphs/fields.rs, engine/crates/composition/tests/composition/composed_directives_basic/federated.graphql, engine/crates/composition/tests/composition/inaccessible_basic/federated.graphql, engine/crates/composition/tests/composition/tag_directive_basic/federated.graphql, engine/crates/composition/tests/composition/tag_directive_basic/subgraphs/apple.graphql, engine/crates/composition/tests/composition/tag_directive_basic/subgraphs/orange.graphql, engine/crates/federated-graph/src/federated_graph.rs, engine/crates/federated-graph/src/render_sdl.rs
As you will see in the diff, there were places left where we weren't
properly composing and rendering all or some directives, notably
directives on field arguments. The refactorings in the past few PRs
made filling these holes doable cleanly.
The @tag directive is now implemented everywhere it is valid.
closes GB-5396
=> composition: finish @tag implementation

engine/crates/composition/src/compose/directives.rs, engine/crates/composition/src/compose/enums.rs, engine/crates/composition/src/compose/interface.rs, engine/crates/composition/src/ingest_subgraph.rs, engine/crates/composition/src/ingest_subgraph/directives.rs, engine/crates/composition/src/ingest_subgraph/enums.rs, engine/crates/composition/src/ingest_subgraph/fields.rs, engine/crates/composition/src/subgraphs.rs, engine/crates/composition/src/subgraphs/definitions.rs, engine/crates/composition/src/subgraphs/directives.rs, engine/crates/composition/src/subgraphs/enums.rs, engine/crates/composition/src/subgraphs/fields.rs, engine/crates/composition/tests/composition/interfaces_basic/federated.graphql, engine/crates/composition/tests/composition/interfaces_basic/subgraphs/social.graphql, engine/crates/composition/tests/composition/object_implementing_composed_interface/federated.graphql, engine/crates/composition/tests/composition/object_implementing_composed_interface/subgraphs/nutrition.graphql, engine/crates/composition/tests/composition/object_implementing_composed_interface/subgraphs/product.graphql
The rule is that a composed interface is the union of all the interfaces
in all the schemas, and objects implementing that interface in the
composed schema must implement all fields of the interfface. In this PR,
we validate that.
closes GB-5507
=>   composition: check implementers of composed interfaces 

packages/grafbase-sdk/src/config.ts, packages/grafbase-sdk/src/graph.ts
- Removes do not use warnings from the new graph API in the SDK
=> Remove do not use warnings

engine/crates/composition/src/compose.rs, engine/crates/composition/src/compose/object.rs, engine/crates/composition/src/subgraphs/fields.rs, engine/crates/composition/tests/composition/inaccessible_basic/federated.graphql, engine/crates/composition/tests/composition/inaccessible_basic/subgraphs/one.graphql, engine/crates/composition/tests/composition/inaccessible_in_one_subgraph_is_enough/federated.graphql, engine/crates/composition/tests/composition/inaccessible_in_one_subgraph_is_enough/subgraphs/one.graphql, engine/crates/composition/tests/composition/inaccessible_in_one_subgraph_is_enough/subgraphs/three.graphql, engine/crates/composition/tests/composition/inaccessible_in_one_subgraph_is_enough/subgraphs/two.graphql, engine/crates/composition/tests/composition/input_object_basic/federated.graphql, engine/crates/composition/tests/composition/input_object_basic/subgraphs/emailbook.graphql, engine/crates/composition/tests/composition/input_object_basic/subgraphs/phonebook.graphql, engine/crates/composition/tests/composition/object_field_arguments_basic/federated.graphql, engine/crates/composition/tests/composition/object_field_arguments_basic/subgraphs/history.graphql, engine/crates/composition/tests/composition/object_field_arguments_basic/subgraphs/inventory.graphql, engine/crates/composition/tests/composition/object_field_arguments_basic/subgraphs/performance.graphql, engine/crates/composition/tests/composition/shareable_basic/federated.graphql, engine/crates/composition/tests/composition/shareable_basic/subgraphs/accounts.graphql, engine/crates/composition/tests/composition/shareable_basic/subgraphs/marketing.graphql, engine/crates/composition/tests/composition/shareable_basic/subgraphs/subscriptions.graphql, engine/crates/composition/tests/composition/shareable_non_matching_fields/federated.graphql, engine/crates/composition/tests/composition/shareable_non_matching_fields/subgraphs/algae_one.graphql, engine/crates/composition/tests/composition/shareable_non_matching_fields/subgraphs/algae_two.graphql
The fields must match between subgraphs, except those marked with `@inaccessible`.
closes GB-5508
=> composition: implement strict matching rules for shareable objects

Cargo.lock, cli/crates/federated-dev/Cargo.toml, cli/crates/federated-dev/src/dev/router.rs, engine/crates/engine-v2/Cargo.toml, engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/executor/graphql/mod.rs, engine/crates/engine-v2/src/executor/mod.rs, engine/crates/engine-v2/src/lib.rs, engine/crates/integration-tests/src/federation/builder.rs, engine/crates/runtime-local/src/fetch.rs, engine/crates/runtime-local/src/lib.rs, engine/crates/runtime/Cargo.toml, engine/crates/runtime/src/fetch.rs, engine/crates/runtime/src/lib.rs
feature flags are a pain to deal with we've seen that with the previous
sqlite vs dynamodb for example. So environment specific logic should be
abstracted away in `runtime` crate. This also solves the problem of
sharing CF worker specific http request logic across the whole engine.
=> chore(engine-v2): Remove cf-workers feature flag and move it behind a trait

cli/crates/cli/src/check.rs, cli/crates/cli/src/output/report.rs
The fix: we were passing on the `--schema` argument as schema to the API, but it is the filesystem path to the schema. The fix is to read the file at that path.
The tweak: schema check failures are spelled out, we don't jump straight into displaying the errors anymore.
=> cli: a fix and a tweak for the check command

cli/crates/cli/src/check.rs, cli/crates/cli/src/cli_input/check.rs
All in the check command. The renaming is in order to align with `grafbase publish`.
=> cli: rename --subgraph to --name, document reading schema from stdin

Cargo.lock, engine/crates/engine-v2/Cargo.toml, engine/crates/engine-v2/schema/src/lib.rs, engine/crates/engine-v2/schema/src/walkers/input_object.rs, engine/crates/engine-v2/schema/src/walkers/input_value.rs, engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/execution/variables.rs, engine/crates/engine-v2/src/plan/planner.rs, engine/crates/engine-v2/src/request/walkers/field_argument.rs, engine/crates/engine-v2/src/request/walkers/variables.rs, engine/crates/engine-v2/src/response/mod.rs, engine/crates/engine-v2/src/sources/graphql/query.rs, engine/crates/engine/value/src/lib.rs, engine/crates/integration-tests/src/federation/mod.rs, engine/crates/integration-tests/src/mocks/graphql/echo.rs, engine/crates/integration-tests/tests/federation/basic/variables.rs, engine/crates/integration-tests/tests/federation/introspection.rs
This implements variable coercion in engine-v2 along with a bunch of tests.  It also includes some validation of the actual values of variables - though it doesn't implement most of the other variable validations from the spec.
Part of GB-5406
=> feat: variable coercion in engine-v2

engine/crates/engine-v2/schema/src/walkers/field.rs, engine/crates/engine-v2/schema/src/walkers/input_object.rs, engine/crates/engine-v2/schema/src/walkers/type.rs, engine/crates/engine-v2/src/execution/variables.rs, engine/crates/engine-v2/src/request/bind.rs, engine/crates/integration-tests/tests/federation/basic/variables.rs
I added variable coercion in #1084, but after PRing decided I could improve the error messages somewhat.  This does that: mostly referring to actual types instead of the hand-wavey stuff I was doing before.
Also changed a `TypeWalker::name` to a `Display` impl, because `name` seemed like a bad name, since I'd argue `[String!]!` is not really a name.
Part of GB-5406
=> fix: improve error messages on coercion failure

.github/workflows/cli.yml
We currently don't have cancel-in-progress turned on for our CLI CI builds, which means if you push a new commit you have to wait for any existing CI runs to finish before your latest commit will get built.
Not sure if there's a good reason for this, but I can't think of one, so maybe lets try enabling `cancel-in-progress`?  Shout if you know of a reason why this will be terrible.
=> fix: cancel in progress CLI builds

cli/crates/cli/src/check.rs
We forgot to do this. This is important for CI / script use cases.
=> cli: exit with status code 1 on failed checks

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.48.0.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Features
- A new `grafbase check` command to run schema checks in federated and single graph projects.
- `grafbase publish` can now take the schema SDL to publish from stdin as an alternative to a file with the `--schema` parameter. This enables piping the output of introspect into publish. (#1083)
- In all commands that take a `PROJECT_REF` argument (account/project@branch), the branch is now optional. It will default to the main branch of the project. (#1081)
- `grafbase init` now generates an initial configuration that takes the latest changes in @@grafbase/sdk into account.
Fixes
- File watcher fixes (#1064). `grafbase dev`, was watching too many files, leading to unnecessary reloads.
=> cli: release 0.48.0

cli/crates/cli/src/cli_input/introspect.rs, cli/crates/cli/src/cli_input/sub_command.rs, cli/crates/cli/src/introspect.rs, cli/crates/cli/src/output/report.rs, cli/crates/server/src/introspect_local.rs, cli/crates/server/src/lib.rs
The use case is schema checks. You want the SDL schema of the current
project as it is locally, not the deployed version. The current best
solution is to start a dev server and introspect it. This commit
introduces a much easier solution: `grafbase introspect --dev`.
=> cli: add introspect --dev command to dump project schema 

engine/crates/composition/src/subgraphs.rs, engine/crates/integration-tests/src/mocks/graphql.rs, engine/crates/integration-tests/src/mocks/graphql/almost_empty.rs, engine/crates/integration-tests/tests/federation/basic/scalars.rs
Composition was filtering out built in scalars that weren't present in any subgraph. This meant that engine-v2 wasn't aware of them, so you'd get `Unknown type: "ID"` errors if you tried to use them.  Shouldn't really matter for valid queries, but still worth fixing.
Fixes GB-5576
=> fix: don't remove built in scalars in composition

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.48.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Features
- The `grafbase introspect` command can now take a `--dev` flag to introspect the local project's schema. It is mutually exclusive with the `--url` flag. (#1095)
Fixes
- Due to the recent added support for configuration at the repository root, the generated TS code for typed resolvers was generated at the repository root, even when the configuration lived in the ./grafbase directory. This releases fixes that behaviour: the `generated` directory will be at the same level as the configuration. (#1093)
=> cli: release 0.48.1

engine/crates/engine-config-builder/src/lib.rs, engine/crates/engine-v2/config/src/lib.rs, engine/crates/engine-v2/config/src/v2.rs, engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/rules/all_subgraphs_directive.rs, engine/crates/parser-sdl/src/rules/mod.rs
PR #1105 added a `@subgraph` attribute for adding headers to a particular subgraph.  This adds `@allSubgraphs` - the equivalent directive for adding headers to all of the subgraphs.
Fixes GB-5604
=> feat: add `@allSubgraphs` to parser-sdl, pass to engine-v2

cli/crates/backend/src/api/graphql/types/queries/list_subgraphs.rs, cli/crates/backend/src/api/subgraphs.rs, cli/crates/cli/src/output/report.rs, cli/crates/cli/src/subgraphs.rs
The problem we faced is that the subgraphs field is on `Branch`. The fix is a different GraphQL query in the absence of a branch name. This commit uses `Project.productionBranch` instead.
closes GB-5600
=> cli: make branch optional in `grafbase subgraphs`

engine/crates/composition/src/lib.rs, engine/crates/composition/src/subgraphs.rs, engine/crates/composition/tests/composition/composition_of_zero_subgraphs/federated.graphql, engine/crates/composition/tests/composition/composition_of_zero_subgraphs/subgraphs/.gitignore, engine/crates/composition/tests/composition_tests.rs
This gives a much better error compared to whatever it is with missing query.
Part of: GB-5588
=> fix: composition should short circuit error if composing with no graphs

cli/crates/backend/src/api/graphql/types/mutations.rs, cli/crates/backend/src/api/publish.rs, cli/crates/cli/src/output/report.rs, cli/crates/cli/src/publish.rs
Instead of just "FederatedGraphCompositionError".
closes GB-5585
=> cli: return specific composition errors when publish fails at composition

Cargo.lock, cli/crates/federated-dev/src/dev.rs, cli/crates/federated-dev/src/dev/bus.rs, cli/crates/federated-dev/src/dev/router.rs, engine/crates/engine-v2/schema/src/conversion.rs, engine/crates/engine-v2/schema/src/ids.rs, engine/crates/engine-v2/schema/src/lib.rs, engine/crates/engine-v2/schema/src/sources/federation.rs, engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/execution/context.rs, engine/crates/engine-v2/src/execution/coordinator.rs, engine/crates/engine-v2/src/sources/graphql/federation.rs, engine/crates/engine-v2/src/sources/graphql/mod.rs, engine/crates/engine/src/headers.rs, engine/crates/integration-tests/Cargo.toml, engine/crates/integration-tests/src/federation/builder.rs, engine/crates/integration-tests/src/federation/mod.rs, engine/crates/integration-tests/src/mocks/graphql/fake_github.rs, engine/crates/integration-tests/tests/federation/basic/fragments.rs, engine/crates/integration-tests/tests/federation/basic/headers.rs, engine/crates/integration-tests/tests/federation/basic/mod.rs, engine/crates/integration-tests/tests/federation/basic/scalars.rs, engine/crates/integration-tests/tests/federation/basic/variables.rs, engine/crates/integration-tests/tests/federation/introspection.rs, engine/crates/integration-tests/tests/federation/subgraphs/mod.rs, engine/crates/integration-tests/tests/federation/subgraphs/simple_key.rs, engine/crates/integration-tests/tests/graphql_connector/headers.rs, engine/crates/runtime-local/src/fetch.rs, engine/crates/runtime/src/fetch.rs
This updates engine-v2 to send the headers configured for each subgraph to that subgraph.
Fixes GB-5606
=> feat: send configured headers to subgraph

packages/grafbase-sdk/src/config.ts, packages/grafbase-sdk/src/federated/headers.ts, packages/grafbase-sdk/src/grafbase-schema.ts, packages/grafbase-sdk/src/graph.ts, packages/grafbase-sdk/tests/unit/federation-graph.test.ts
As outlined in the [RFC][1]
Fixes GB-5605
[1]: https://www.notion.so/Configurable-subgraph-headers-44c5e3fd62d4489db1bc4e5419119f8d
=> feat: add federation header config to SDK

engine/crates/integration-tests/src/engine/mod.rs, engine/crates/integration-tests/tests/federation/introspection.rs, engine/crates/integration-tests/tests/federation/snapshots/integration_tests__federation__introspection__introspecting_with_grafbase_openapi_subgraph.snap
I wanted to test some engine<->engine-v2 interactions, so figured I might as well add the code to integration-tests that allows us to do this there.
Currently only tests introspection, because that's what I needed to test - if you try making calls you _might_ need to fix some more stuff.
=> test: allow engine-v2 tests to use engine-v1 as subgraph

engine/crates/engine/parser/src/types/mod.rs
We can skip one allocation in the router.
=> chore: add as_ref for operation type

engine/crates/engine-v2/src/execution/coordinator.rs, engine/crates/engine-v2/src/plan/mod.rs, engine/crates/engine-v2/src/plan/planner.rs, engine/crates/engine-v2/src/request/walkers/flat.rs, engine/crates/engine-v2/src/response/error.rs, engine/crates/engine-v2/src/response/write/deserialize/field.rs, engine/crates/engine-v2/src/response/write/deserialize/list.rs, engine/crates/engine-v2/src/response/write/deserialize/mod.rs, engine/crates/engine-v2/src/response/write/deserialize/nullable.rs, engine/crates/engine-v2/src/response/write/manual.rs, engine/crates/engine-v2/src/response/write/mod.rs, engine/crates/engine-v2/src/response/write/writer.rs, engine/crates/engine-v2/src/sources/graphql/deserialize/errors.rs, engine/crates/engine-v2/src/sources/mod.rs, engine/crates/integration-tests/src/mocks/graphql.rs, engine/crates/integration-tests/src/mocks/graphql/state_mutation.rs, engine/crates/integration-tests/tests/federation/basic/mod.rs, engine/crates/integration-tests/tests/federation/basic/mutation.rs
For mutations, I'm now executing executors one at a time. The executor future returns then:
```
struct ExecutorFutResult<'ctx> {
result: ExecutorResult<ExecutorOutput>,
next_executors: VecDeque<Executor<'ctx>>,
}
```
So the actual result to update the response and plan the children. And the next executors, which are only used for mutation root fields. Ensuring they're executed one after another. Error management is more hacky than I thought during planning, but well good enough for now.
=> feat(engine-v2): Execute mutations sequentially

.github/workflows/cli.yml, cli/crates/cli/tests/dev.rs, cli/crates/server/src/consts.rs, cli/crates/server/src/servers.rs
A potential customer is running into issues running `grafbase dump-config` because they've got `"module": true` in their package.json.  They're getting the following error:
```
Error: could not load grafbase/grafbase.config.ts
Caused by: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /snip/sdk/examples/connector-example/grafbase/grafbase.config.ts
require() of ES modules is not supported.
require() of /snip/connector-example/grafbase/grafbase.config.ts from /snip/.grafbase/parser/parse-config.ts is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from …
```
=> fix: adjust parser code to support esm modules

cli/crates/cli/src/cli_input/publish.rs
The arg groups still made --schema-path required in the absence of --dev. This change makes piping a schema to publish as in `grafbase introspect | grafbase publish account/project --url https://example.com` work.
=> cli: fix piping schema to publish

engine/crates/composition/tests/composition/kebab_case_subgraph_names/federated.graphql, engine/crates/composition/tests/composition/kebab_case_subgraph_names/subgraphs/brochette-repository.graphql, engine/crates/composition/tests/composition/kebab_case_subgraph_names/subgraphs/kushi-store.graphql, engine/crates/composition/tests/composition/kebab_case_subgraph_names/subgraphs/schaschlik-service.graphql, engine/crates/federated-graph/src/render_sdl.rs
In cases where the subgraph name contains hyphen ('-') characters, we were rendering them as-is in the join__Graph enum variant names, but this is not valid in GraphQL identifiers. We now replace them with underscores.
closes GB-5647
=> federated-graph: fix rendering of join__Graph variants

Cargo.lock, engine/crates/composition/CHANGELOG.md, engine/crates/composition/Cargo.toml
Composition has been finished recently and is going into production this week. This warrants a crates.io release, since the library is in a much more useful state now.
=> composition: release 0.2.0

engine/crates/engine-v2/src/execution/context.rs, engine/crates/engine-v2/src/request/walkers/field.rs, engine/crates/engine-v2/src/request/walkers/fragment.rs, engine/crates/engine-v2/src/request/walkers/inline_fragment.rs, engine/crates/engine-v2/src/request/walkers/mod.rs, engine/crates/engine-v2/src/request/walkers/plan_selection_set.rs, engine/crates/engine-v2/src/request/walkers/selection_set.rs
This adds an `IntoIterator` implementation for the selection set walker of the operation, to iterate over fields and fragments. There is an existing for executors filtered for their plan, but caching will need that to traverse the whole operation.
=> chore: Engine v2: add selection set walkers (without plan), needed for caching

.github/actions/sanitize/action.yml, Cargo.toml
I've been running a lot of CLI release builds on my machine recently and it is incredibly slow to compile - about 4 minutes, even if I've only changed a couple of the CLI crates and all the dependencies are already built.  CI is also pretty slow - 30ish minutes for a full run, much of which is spent compiling for the various platforms.
This PR speeds both those things.  CI runs are down to ~18 minutes, release builds on my machine now take less than 2 minutes.
This does increase the size of the built CLI a bit - up from 38MB to 60-70MB. I kinda think that's fine, but comment if you don't?
=> chore: optimize build time

cli/crates/server/src/codegen_server.rs, cli/crates/server/src/file_watcher.rs
It broke as a result of e867890. We started sending the path to the schema as a string instead of the schema to the codegen function.
The solution requires merging the two tasks, because they share `last_seen_sdl`.
closes GB 5676
=> cli: fix ts code generation

engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/rules/basic_type.rs, engine/crates/parser-sdl/src/rules/check_type_collision.rs, engine/crates/parser-sdl/src/rules/extend_connector_types.rs
Roughly, there are three scenarios for extend type:
- extend type Query / extend type Mutation -> these are special cases, there are tests
- extend types for types from connectors -> also tested
- extend type for types defined in the config / sdl -> that's where the issue applies
In that last point, two subcases: extending a model and extending a type that is returned by a resolver extending a connector type. The first use case is being sunset. The second use case is tested and fixed in this PR.
closes GB-5067
=> parser-sdl: fix extending type causing duplicate type definition error

engine/crates/composition/src/compose/context.rs, engine/crates/composition/src/compose/entity_interface.rs, engine/crates/composition/src/compose/enums.rs, engine/crates/composition/src/compose/input_object.rs, engine/crates/composition/src/compose/interface.rs, engine/crates/composition/src/compose/scalar.rs, engine/crates/composition/src/composition_ir.rs, engine/crates/composition/src/emit_federated_graph.rs, engine/crates/composition/src/emit_federated_graph/context.rs
A while ago, we introduced a separate string interning map for static strings that may not show up in the subgraphs but are part of the federated graph and as such, need to be in `FederatedGraph.strings`.
The problem is that the same string can end up in both the map for strings from the subgraphs, and, if the static version was inserted before, in the second map for static strings.
The important consequence of this is that you could end up with two `StringId`s that are not equal representing the same string, which defeats the point of one big reason for interning in the first place: cheap and reliable comparisons.
This commit fixes that by not trying to be smart about converting `subgraphs::StringId`s into `federated::StringId`s and rehashing the string themselves instead.
=> composition: restore broken assumption about interned strings

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.52.0.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Features
- Caching support for federated graphs (#1144)
Fixes
- 0.51.0 contained a regression where the TypeScript types for resolvers were not generated even when opting in to the codegen experimental feature. (#1156)
- Handle the "branch does not exist" error in the `grafbase publish` command (#1141)
- Fixed extending types for resolvers in many scenarios (#1143)
=> cli: release 0.52.0

Cargo.lock, cli/crates/server/Cargo.toml, cli/crates/server/src/errors.rs, cli/crates/server/src/proxy.rs
I've been (lightly) obsessing over CI build times the past few days - and noticed we were still building sqlite/sqlx etc. in the CLI even though the database feature has been removed.
This is probably because `proxy.rs` had a `#[allow(unused)]` that was hiding quite a few unused warnings.  This removes that, fixes the warnings, removes sqlite.
=> chore: remove sqlx dependency

engine/crates/federated-graph/src/render_sdl.rs
As doing: `interface Blah """` is not valid syntax.
~Seems like this SDL rendering code has made its way into the critical path for every deployment - we should probably have more tests of it, though I'm not doing that tonight.~ Actually it's probably what powers all the composition tests isn't it, never mind - just couldn't find them.
=> fix: print interface description _before_ `interface`

cli/crates/backend/src/api/create.rs, cli/crates/backend/src/api/graphql/types/mutations.rs
In preparation for the final phase out of the database feature.
=> fix(create): GB-5652: Stop sending database regions to the project creation mutations

Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/backend/src/errors.rs, cli/crates/backend/src/lib.rs, cli/crates/backend/src/project.rs
Somehow this dependency override has been carried over despite not being applied any more (`http-cache-reqwest` uses v12).
=> chore(deps): Get rid of the unused cacache 11.0 dependency

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.52.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Fixes
- Make MongoDB connector produce valid schemas when introspected (#1162)
- Fix a bug in the rendering of GraphQL schemas where the interface description would be printed after its name (#1166)
=> cli: release 0.52.1

Cargo.lock, Cargo.toml, cli/crates/backend/src/api/client.rs, cli/crates/backend/src/api/login.rs, cli/crates/cli/Cargo.toml, cli/crates/cli/tests/graphql-directive/server.rs, cli/crates/federated-dev/Cargo.toml, cli/crates/federated-dev/src/dev.rs, cli/crates/gateway/Cargo.toml, cli/crates/gateway/src/executor.rs, cli/crates/gateway/src/response.rs, cli/crates/server/Cargo.toml, cli/crates/server/src/bridge/server.rs, cli/crates/server/src/error_server/server.rs, cli/crates/server/src/errors.rs, cli/crates/server/src/proxy.rs, cli/crates/server/src/servers.rs, engine/crates/dataloader/Cargo.toml, engine/crates/federated-graph/Cargo.toml, engine/crates/gateway-core/Cargo.toml, engine/crates/integration-tests/Cargo.toml, engine/crates/integration-tests/src/mocks/graphql.rs, engine/crates/runtime/Cargo.toml
Upgrade axum, hyper, http and other HTTP-related dependencies.
=> chore(deps): GB-5699: Upgrade axum, hyper, http and friends in the CLI

Cargo.lock, Cargo.toml, cli/changelog/0.52.2.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Has this fix: https://github.com/grafbase/api/pull/3071
=> chore: bump to version 0.52.2

.github/workflows/cli.yml
Having upload in v3 and download in v4 broke our release pipeline.
=> chore: bump upload-artifact to v4 in GH workflow

cli/crates/typed-resolvers/src/analyze.rs, cli/crates/typed-resolvers/src/codegen.rs, cli/crates/typed-resolvers/tests/schema_types/datetime.expected.ts, cli/crates/typed-resolvers/tests/schema_types/datetime.graphql
The SDL generated from user configuration does not contain custom scalar definitions for builtin types like DateTime and IPAddress, so the code generation logic could not resolve the types of these fields and left them out of the generated code.
The short term fix in this PR is to integrate those in the codegen worker's understanding of builtin scalars.
The long term fix will come with basing TS code generation on the whole registry, which we want to do anyway for a host of other reasons.
closes GB-5694
=> fix(cli): generate TS for fields w/ grafbase scalar type

.github/workflows/cli.yml, cli/crates/server/src/config/mod.rs, cli/crates/server/src/consts.rs
A user found another problem with ts-nodes ability to work with CJS & ESM files, which appears to be [this
issue](https://github.com/TypeStrong/ts-node/issues/1997).  Swaping to tsx instead seems to fix this and removes the need for having two different copies of the parse-config script.
Depends on https://github.com/grafbase/api/pull/3073 being pulled in.
I've tested this with a project with CJS & ESM, on node 18 & 20.
=> fix: swap ts-node for tsx.

Cargo.lock, engine/crates/operation-checks/Cargo.toml, engine/crates/operation-checks/src/aggregate_field_usage.rs, engine/crates/operation-checks/src/aggregate_field_usage/async_graphql.rs, engine/crates/operation-checks/src/lib.rs
This PR adds a crate in engine/crates. The crate is called `operation-checks` and is meant to hold the business logic for operation checks.
At a high level, within a schema check, the operation check step does the following work:
1. Gathers the fields that are actively used by API consumers, with thresholds based on user settings. This can be done in two ways:
a. Taking already aggregated field data directly from an analytics database.
b. Taking aggregated operation-level data, and splitting it into field-level data.
2. Diff the old and the new API schema. The diffing part is already implemented in the graphql-schema-diff crate.
3. Determine if any of the breaking changes in the diff would apply to fields actively used by clients (determined in (1.)).
This PR implements bullet point 1.b. …
=>  operation-checks: initial crate with breaking up of operations into fields

Cargo.lock, engine/crates/engine-v2/Cargo.toml, engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/execution/context.rs, engine/crates/engine-v2/src/execution/coordinator.rs, engine/crates/engine-v2/src/execution/mod.rs, engine/crates/engine-v2/src/execution/variables.rs, engine/crates/engine-v2/src/plan/mod.rs, engine/crates/engine-v2/src/plan/planner.rs, engine/crates/engine-v2/src/request/ids.rs, engine/crates/engine-v2/src/request/mod.rs, engine/crates/engine-v2/src/request/walkers/plan.rs, engine/crates/engine-v2/src/request/walkers/variables.rs, engine/crates/engine-v2/src/response/write/ids.rs, engine/crates/engine-v2/src/response/write/mod.rs, engine/crates/engine-v2/src/sources/graphql/mod.rs, engine/crates/engine-v2/src/sources/graphql/subscription.rs, engine/crates/engine-v2/src/sources/mod.rs
I'm working on adding subscriptions to our federation offering.  The flow of subscriptions is fairly similar to a normal federation execution but with a few of important differences:
1. There can only be a single subscription field at the root.
2. That subscription field will translate into a subscription call to a subgraph.
3. We build up a fresh GraphQL response from each response we get back from that initial subscription.
This PR updates the ExecutorCoordinator to support the subscription flow as well as the normal flow.  I want to return a stream for subscriptions, ideally without spawning an async task, which needed a lot of refactoring.  Mostly removing references where I could, as they 
I needed to do a surprising amount of refactoring to get this working.  Mostly turning …
=> feat: update ExecutorCoordinator with subscription flow

engine/crates/engine-v2/Cargo.toml, engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/execution/coordinator.rs, engine/crates/engine-v2/src/execution/mod.rs, engine/crates/engine-v2/src/request/selection_set.rs, engine/crates/engine-v2/src/response/error.rs, engine/crates/engine-v2/src/response/mod.rs, engine/crates/engine-v2/src/sources/mod.rs, engine/crates/integration-tests/src/federation/mod.rs, engine/crates/integration-tests/tests/federation/basic/mod.rs, engine/crates/integration-tests/tests/federation/basic/streaming.rs
A follow up to #1198 - exposing the changes I made there to consumers of `engine-v2`.  I've not hooked this up in the CLI yet because I want to get subscriptions working first.   This does allow the code to be called in tests though.
I've added a passing test of queries & mutations via this function just to confirm.
Part of GB-5708
=> feat: expose `execute_stream` from engine-v2

engine/crates/graphql-schema-diff/src/state.rs, engine/crates/graphql-schema-diff/tests/diff/interface_implements_interface.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/object_interface.snapshot.json
In graphql-schema-diff, the changes about adding and removing implementers to an interface had paths of the shape "implementer.interface", which is obviously the wrong way round. This commit changes the order to "interface.implementer".
=> fix(graphql-schema-diff): make interface change path "interface.implementer"

Cargo.lock, engine/crates/engine/parser/src/lib.rs, engine/crates/engine/parser/src/parse/mod.rs, engine/crates/parser-graphql/Cargo.toml, engine/crates/parser-graphql/src/conversion.rs, engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__array_input_value.snap, engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__conversion.snap, engine/crates/parser-graphql/src/snapshots/parser_graphql__tests__counries_output.snap, engine/crates/parser-graphql/src/snapshots/parser_graphql__tests__preservation_of_type_casing.snap, engine/crates/parser-graphql/src/snapshots/parser_graphql__tests__unnamed_connector.snap
The GraphQL connector introspects the remote server and uses that to build up a Registry.  This commit fixes it's handling of default values.
Default values in introspection are returned as a string where the contents are the default value, encoded as it would be in a GraphQL document.  The GraphQL connector was taking this and converting it into a `ConstValue::String` of that string, which is not quite right.
This updates the conversion to use `engine-parser` to interpret the string first, so we end up with the correct `ConstValue` in the registry.
Looks like this fixes quite a few potential issues from the various snapshots this has updated.
Fixes GB-5752
=> fix: default values in graphql connector

engine/crates/integration-tests/src/engine/mod.rs, engine/crates/integration-tests/src/mocks/graphql.rs, engine/crates/integration-tests/src/mocks/graphql/fake_github.rs, engine/crates/integration-tests/src/mocks/graphql/federation/accounts.rs, engine/crates/integration-tests/src/mocks/graphql/federation/products.rs, engine/crates/integration-tests/src/mocks/graphql/federation/reviews.rs, engine/crates/integration-tests/src/mocks/graphql/state_mutation.rs
I'm about to start writing integration tests of my subscriptions work - and it'll be a lot easier to write those if I have subgraphs that support subscriptions.
This updates the GraphQL mock infrastructure in integration-tests to support subscriptions, and adds a subscription field to the `products` subgraph mock.
=> test: update graphql mocks to expose subscriptions

cli/crates/server/build.rs, cli/nix/cli.nix, flake.lock, flake.nix, packages/nix/cli-app.nix
This lets anybody with nix installed build the CLI from source with `nix build github:grafbase/grafbase#cli`, or run it with `nix run github:grafbase/grafbase#cli`, or build it locally with `nix build .#cli`, etc. This is also useful documentation on all the inputs required to build the Grafbase CLI.
This commit also introduces flake-parts to the repo. It is just a convenient way to organize the derivations that reuses the same module system any nixos or home-manager user will be familiar with.
One caveat though: the version and URL of the assets.tar.gz file are hardcoded. Ideally, we would also build these from source, but that can be done in a separate PR.
=> nix: derivation for the cli

Cargo.lock, cli/crates/gateway/src/lib.rs, engine/crates/engine-v2/Cargo.toml, engine/crates/engine-v2/src/lib.rs, engine/crates/engine-v2/src/response/cacheable.rs, engine/crates/engine-v2/src/response/mod.rs, engine/crates/gateway-core/src/cache/build_key.rs, engine/crates/gateway-core/src/cache/mod.rs, engine/crates/gateway-core/src/lib.rs, engine/crates/runtime/src/cache/mod.rs
This PR implements `Cacheable` for `v2::Response`. With this we can re-use `runtime::cache` for v2.
=> feat: implements `Cacheable` for `v2::Response`

packages/grafbase-sdk/src/query.ts, packages/grafbase-sdk/src/type.ts, packages/grafbase-sdk/tests/unit/types.test.ts
I added the ability to extend connector generated types with federation directives to the SDK in 81fd711.  One thing that still wasn't added then was the ability to add fields onto connector generated types - oops.
This does that.
=> feat: allow SDK users to add fields to connector types

Cargo.lock, engine/crates/integration-tests/src/mocks/graphql/federation/products.rs, engine/crates/integration-tests/tests/federation/introspection.rs, engine/crates/integration-tests/tests/federation/mod.rs, engine/crates/integration-tests/tests/federation/subscriptions.rs, engine/crates/runtime-local/Cargo.toml, engine/crates/runtime-local/src/fetch.rs, engine/crates/runtime-local/src/fetch/websockets.rs
PR #1222 finished the rest of the engine-v2 subscription implementation, but the actual subgraph subscription calls are delegated to the `Fetcher` trait.
This implements the websocket transport for subscription calls in `runtime-local` (as used in the CLI).  I used graphql-ws-client for the heavy lifting here (glad I _finally_ get to use this, ~3 years after I wrote the thing).
Also added some tests.
Fixes GB-5706
=> feat: hook runtime-local up to graphql-ws-client

engine/crates/engine/src/registry/resolvers/graphql.rs, engine/crates/engine/src/registry/resolvers/join.rs, engine/crates/integration-tests/src/mocks/graphql/fake_github.rs, engine/crates/integration-tests/tests/execution/joins.rs, engine/crates/integration-tests/tests/federation/introspection.rs, engine/crates/integration-tests/tests/graphql_connector/basic.rs, engine/crates/integration-tests/tests/graphql_connector/transforms.rs
A user on discord is trying to join two GraphQL connectors together.  The type containing the join appears inside a list.  When that list has > 1 item, we need to fetch > 1 field from the downstream API.  These fetches get deduplicated into a single query (cool - glad that works) but the fields in the query don't get aliased correctly.
So you end up with something like:
```
query {
foo(id: "1") { .. }
foo(id: "2") { .. }
} 
```
Which is not valid.  I fixed this by always aliasing fields in joins which should solve this problem.
But this uncovered another issue: the graphql connectors deserialisation wasn't taking aliases into account at all.  So even leaving aside joins any fetches of unnamespaced fields that use aliases would return null.  So I fixed that as well and added a test case.
=> fix: concurrent joins in the graphql connector

.github/workflows/cli.yml, cli/crates/server/src/config/mod.rs, cli/crates/server/src/consts.rs
We've been trying to use tsx lately to fix some issues around ESM modules and ts-node.  tsx claimed to just work, but in practice it is _so fragile_ - seems to work whenever we test it locally and then horribly breaks the minute it reaches someone else's machine.
=> Switch back to ts-node

engine/crates/operation-checks/src/check.rs, engine/crates/operation-checks/src/check/rules.rs, engine/crates/operation-checks/src/lib.rs, engine/crates/operation-checks/src/schema.rs, engine/crates/operation-checks/src/schema/async_graphql.rs, engine/crates/operation-checks/src/schema/wrapper_types.rs, engine/crates/operation-checks/src/schema/wrapping_types.rs, engine/crates/operation-checks/tests/cases/change_field_argument_type.snapshot, engine/crates/operation-checks/tests/cases/change_field_type_basic.snapshot, engine/crates/operation-checks/tests/cases/change_list_type_nesting.graphql, engine/crates/operation-checks/tests/cases/change_list_type_nesting.snapshot, engine/crates/operation-checks/tests/cases/change_requiredness_of_nested_list_type.graphql, engine/crates/operation-checks/tests/cases/change_requiredness_of_nested_list_type.snapshot
We were only looking at the outermost wrapper type previously and not really handling lists, not to speak of nested lists. This commit takes the wrapper types (! and []) into account on field type changes in operation checks.
In addition, expose CheckDiagnostic and Severity in public API. It was
an omission.
closes GB-5749
=> operation-checks: make sure we handle wrapper types correctly

Cargo.lock, cli/crates/server/Cargo.toml, cli/crates/server/src/proxy.rs
I spent a good chunk of this morning saying "why the fuck am I getting 404s" when I was trying to test subscriptions.  I had forgotten that we've got a proxy sitting between the user and the actual federated dev server 🤦.
This updates that to support proxying websocket connections through to the underlying dev server (which will come in my next PR - just cleaing it up now).
Part of GB-5715
=> feat: add websocket support to cli proxy

engine/crates/engine/src/request.rs, engine/crates/engine/src/schema.rs
Disable validating the operation limits for the internal _grafbase/graphql introspection.
=> chore(engine): Disable validating the operation limits for the internal _grafbase/graphql introspection

engine/crates/operation-checks/src/check.rs, engine/crates/operation-checks/src/check/rules.rs, engine/crates/operation-checks/tests/cases/remove_mutation_root.graphql, engine/crates/operation-checks/tests/cases/remove_mutation_root.snapshot
If you remove a regular object type, it registers as a field type change for the fields that return it. But that isn't the case for the root query, mutation and subscription types, so we need to check for that case separately.
closes GB-5769
=> operation-checks: implement breaking root type removal detection

Cargo.lock, cli/crates/federated-dev/src/dev/websockets.rs, cli/crates/gateway/src/executor.rs, engine/crates/gateway-core/Cargo.toml, engine/crates/gateway-core/src/streaming/mod.rs, engine/crates/gateway-v2/src/lib.rs, engine/crates/integration-tests/src/federation/mod.rs
The existing streaming transport code made use of `wait_until` to pump messages from one place to the other.  This was causing me lifetime problems when integrating into engine-v2, so I've reworked everything to happen inside the returned `Stream`.
I'm hoping this will work on production as well - we had to be careful about where the work was done previously so it was definitely inside the request context.  But I think doing the work inside the returned stream _should_ count as inside the context.  I'll test once this is merged though.
=> chore: reworked streaming transport code

engine/crates/operation-checks/src/aggregate_field_usage.rs, engine/crates/operation-checks/src/check.rs, engine/crates/operation-checks/src/check/rules.rs, engine/crates/operation-checks/src/operation.rs, engine/crates/operation-checks/src/operation/async_graphql.rs, engine/crates/operation-checks/src/schema.rs, engine/crates/operation-checks/src/schema/async_graphql.rs, engine/crates/operation-checks/tests/cases/remove_enum_value_used_in_argument.graphql, engine/crates/operation-checks/tests/cases/remove_enum_value_used_in_argument.snapshot, engine/crates/operation-checks/tests/cases/remove_used_enum_value_in_variable_default.graphql, engine/crates/operation-checks/tests/cases/remove_used_enum_value_in_variable_default.snapshot
We can only check the usage of the values in literals in queries (=> not their usage in variables), but we do catch when these would break.
closes GB-5747
=> operation-checks: implement rule about enum value removal

engine/crates/operation-checks/src/aggregate_field_usage.rs, engine/crates/operation-checks/src/check.rs, engine/crates/operation-checks/src/check/rules.rs, engine/crates/operation-checks/src/schema.rs, engine/crates/operation-checks/tests/cases/make_argument_with_default_nonnull_without_default.graphql, engine/crates/operation-checks/tests/cases/make_argument_with_default_nonnull_without_default.snapshot, engine/crates/operation-checks/tests/cases/remove_nonnull_argument_default.graphql, engine/crates/operation-checks/tests/cases/remove_nonnull_argument_default.snapshot, engine/crates/operation-checks/tests/cases/remove_nullable_argument_default.graphql, engine/crates/operation-checks/tests/cases/remove_nullable_argument_default.snapshot
In operation checks, we not only care about the arguments queries are using, but also the arguments they are not using, because they could become mandatory, either because they go from nullable to nonnull, or because their default is removed.
This commit makes operation-checks aware of when arguments are left out so we can detect when a diff on argument default or type could cause issues. The test cases in the commit should cover all relevant scenarios.
closes GB-5748
=> operation-checks: implement unused argument awareness

Cargo.lock, Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/cli/tests/federation.rs, cli/crates/cli/tests/utils/environment.rs, cli/crates/federated-dev/src/dev.rs, engine/crates/async-runtime/Cargo.toml, engine/crates/async-runtime/src/lib.rs, engine/crates/async-runtime/src/stream.rs, engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/execution/coordinator.rs, engine/crates/engine-v2/src/execution/mod.rs, engine/crates/gateway-core/src/streaming/mod.rs, engine/crates/gateway-v2/src/lib.rs, engine/crates/gateway-v2/src/streaming.rs, engine/crates/graphql-mocks/src/lib.rs, engine/crates/integration-tests/Cargo.toml
Adds [Incremental Delivery][1] & [GraphQL Over SSE][2] support to federated dev.
We already had code for these in the CLI, so I'm mostly just hooking things up.
Fixes GB-5797
[1]: https://github.com/graphql/graphql-over-http/blob/main/rfcs/IncrementalDelivery.md
[2]: https://github.com/graphql/graphql-over-http/blob/main/rfcs/GraphQLOverSSE.md
=> feat: add sse & multipart transports to federated dev

cli/crates/cli/tests/defer/main.rs, cli/crates/cli/tests/federation.rs, cli/crates/cli/tests/utils/async_client.rs
Currently using SSE or multipart in the cli tests is quite laborious.  I'm about to add a few more of these tests, so I've extracted out some utilities to make doing this less laborious.
=> chore: streaming transport utilities in cli tests

cli/crates/federated-dev/src/dev.rs, cli/crates/federated-dev/src/dev/websockets.rs, engine/crates/gateway-v2/src/lib.rs, engine/crates/integration-tests/src/federation/mod.rs
I added `Gateway::authorize` recently, and made it return an `engine_v2::Response` on error, as it was the easiest thing to integrate with all the transports.
However, in the `api` repo the code _really_ wants to take a `gateway_v2::Response` - which I'd avoided using in `grafbase` because it doesn't work well with the streaming transports.
This updates the code to just return an `Option`, along with adding some easy functions for constructing the various error responses.
=> chore: make `Gateway::authorize` easier to work with

engine/crates/graphql-mocks/Cargo.toml
```
prisma-desktop.tom.src/gh/grafbase/grafbase λ cargo check
warning: /home/tom/src/gh/grafbase/grafbase/engine/crates/graphql-mocks/Cargo.toml: unused manifest key: package.private
```
The option that was meant is likely "publish"
(https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish-field). This commit replaces private = true with publish = false.
=> Fix cargo warning on main

packages/grafbase-sdk/src/config.ts, packages/grafbase-sdk/src/operation-limits.ts, packages/grafbase-sdk/tests/unit/operation-limits.test.ts
Adds support for operation limits to the TypeScript config translation.
=> feat(sdk): GB-5680: Add support for operation limits to the TypeScript config translation

engine/crates/composition/src/compose/entity_interface.rs, engine/crates/composition/src/compose/input_object.rs, engine/crates/composition/src/compose/interface.rs, engine/crates/composition/src/compose/object.rs, engine/crates/composition/src/composition_ir.rs, engine/crates/composition/tests/composition/entity_composite_key_basic/federated.graphql, engine/crates/composition/tests/composition/entity_interface_basic/federated.graphql, engine/crates/composition/tests/composition/entity_multiple_keys_basic/federated.graphql, engine/crates/composition/tests/composition/entity_staggered_composite_key/federated.graphql, engine/crates/composition/tests/composition/enum_only_outputs/federated.graphql, engine/crates/composition/tests/composition/field_type_composition/federated.graphql, engine/crates/composition/tests/composition/inaccessible_basic/federated.graphql, engine/crates/composition/tests/composition/input_object_basic/federated.graphql, engine/crates/composition/tests/composition/kebab_case_subgraph_names/federated.graphql, engine/crates/composition/tests/composition/object_field_arguments_basic/federated.graphql, engine/crates/composition/tests/composition/provides_basic/federated.graphql, engine/crates/composition/tests/composition/requires_basic/federated.graphql, engine/crates/composition/tests/composition/shareable_basic/federated.graphql, engine/crates/composition/tests/composition/tag_directive_basic/federated.graphql, engine/crates/engine-v2/schema/src/conversion.rs, engine/crates/federated-graph/src/federated_graph.rs, engine/crates/federated-graph/src/from_sdl.rs, engine/crates/federated-graph/src/render_sdl.rs
This is necessary for the router to know which subgraphs can resolve the shared fields. Unlike fields of value types, shareable fields of entities do not have to be defined on every subgraph that exposes the entity.
Also omitted @field on:
- inaccessible fields
- entity key fields (the information is already on `@type`)
=> composition: emit multiple `@field`s for shareable fields of entities

engine/crates/engine-v2/src/execution/context.rs, engine/crates/engine-v2/src/response/write/deserialize/field.rs, engine/crates/engine-v2/src/response/write/deserialize/list.rs, engine/crates/engine-v2/src/response/write/deserialize/mod.rs, engine/crates/engine-v2/src/response/write/deserialize/nullable.rs, engine/crates/engine-v2/src/response/write/deserialize/selection_set/collected.rs, engine/crates/engine-v2/src/response/write/deserialize/selection_set/mod.rs, engine/crates/engine-v2/src/response/write/deserialize/selection_set/undetermined.rs, engine/crates/engine-v2/src/response/write/mod.rs, engine/crates/engine-v2/src/response/write/writer.rs, engine/crates/engine-v2/src/sources/graphql/deserialize/entities.rs, engine/crates/engine-v2/src/sources/graphql/deserialize/errors.rs, engine/crates/engine-v2/src/sources/graphql/deserialize/mod.rs, engine/crates/engine-v2/src/sources/graphql/deserialize/response.rs, engine/crates/engine-v2/src/sources/graphql/federation.rs, engine/crates/engine-v2/src/sources/graphql/mod.rs, engine/crates/engine-v2/src/sources/graphql/query.rs, engine/crates/engine-v2/src/sources/graphql/subscription.rs, engine/crates/integration-tests/tests/federation/basic/mutation.rs
With this PR, when `data` is null in the GraphQL response, we now only show the upstream error if there is any.
I simplified the use of `GraphqlResponseSeed` by re-using the `SeedContext`, which holds a `RefCell` of the mutable output, used for deserializing data into the response graph. I also created an inner struct wrapped in a `Rc` to make it simpler to share.
I separated it from the `ResponseObjectWriter` which is a broken abstraction only used for introspection as of today and intend to remove at some point.
=> fix(engine-v2): better errors when upstream returns null data

Cargo.lock, engine/crates/parser-graphql/src/lib.rs
The error that a user was presented with when introspection was disabled was not great:
> Error: api data source: Could not complete request to GraphQL server: Error
> making HTTP request: error decoding response body: invalid type: null,
> expected struct IntrospectedSchema at line 1 column 92
This PR pulls in a fix from `cynic-introspection` and tweaks our error message a little. The error is now:
> Error: api data source: Error returned when running introspection:
> introspection disabled
=> fix: handle disabled introspection in graphql connector

Cargo.lock, Cargo.toml, cli/crates/cli/tests/defer/main.rs, cli/crates/cli/tests/federation.rs, cli/crates/cli/tests/openapi/main.rs, engine/crates/graphql-schema-diff/tests/diff/add_fields.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/add_one_object.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/directive_basic.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/enum_basic.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/field_argument_default.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/field_argument_default_value.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/field_arguments_basic.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/field_type_change.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/interface_implements_interface.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/mutation_type_changed.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/object_becomes_enum.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/object_interface.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/query_type_changed.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/schema_definition_basic.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/subscription_type_changed.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/union_basic.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/union_members.snapshot.json, engine/crates/integration-tests/Cargo.toml, engine/crates/parser-openapi/Cargo.toml, engine/crates/parser-openapi/src/graph/construction.rs, engine/crates/parser-openapi/src/graph/input_value.rs, engine/crates/parser-openapi/src/graph/mod.rs, engine/crates/parser-openapi/src/graph/output_type.rs
This will help avoid map ordering issues relative to what directory the tests are ran from.
=> chore(tests): Enable the 'preserve_order' feature flag for serde_json globally

cli/crates/server/src/codegen_server.rs, cli/crates/server/src/servers.rs, cli/crates/typed-resolvers/src/analyze.rs, cli/crates/typed-resolvers/src/check_resolver.rs, cli/crates/typed-resolvers/src/error.rs, cli/crates/typed-resolvers/src/lib.rs, cli/crates/typed-resolvers/tests/schema_types.rs, engine/crates/engine/src/registry/mod.rs, engine/crates/engine/src/registry/tests.rs, engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__array_input_value.snap, engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__conversion.snap, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__flat_output-2.snap, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__petstore_output-2.snap, engine/crates/parser-sdl/src/rules/experimental.rs
The decisive change to get the GraphQL schema from the registry instead of the config. (Internal) RFC:
https://www.notion.so/grafbase/Grafbase-GraphQL-clients-integration-68b7a475f5d94222aba4c9e6a405b2d7
closes GB-5256
=> cli: handle types from connectors in resolver codegen

engine/crates/engine-v2/schema/src/conversion.rs, engine/crates/federated-graph/src/from_sdl.rs
- Ignoring empty entity keys in engine schema
- Ignoring schema directives in federated-graph for now. The one used in gateway-benchmarks has:
```graphql
schema
https://github.com/link(url: "https://specs.apollo.dev/link/v1.0")
https://github.com/link(url: "https://specs.apollo.dev/join/v0.3", for: EXECUTION)
{
query: Query
}
```
- Ignoring `@join_field` when `external: true`. Not sure to see any point in them.
=> chore: Various engine-v2-schema and federated-graph fixes

cli/crates/cli/src/publish.rs
When no schema is piped, instead of still waiting for a schema on stdin, use `atty` to detect if stdin is an interactive terminal, and if yes fail fast.
closes GB-5851
=> cli: detect when there is no pipe in `publish`

Cargo.lock, engine/crates/engine-v2/Cargo.toml, engine/crates/engine-v2/src/execution/coordinator.rs, engine/crates/engine-v2/src/plan/attribution.rs, engine/crates/engine-v2/src/plan/expectation.rs, engine/crates/engine-v2/src/plan/ids.rs, engine/crates/engine-v2/src/plan/mod.rs, engine/crates/engine-v2/src/plan/planner.rs, engine/crates/engine-v2/src/plan/planner/boundary_planner.rs, engine/crates/engine-v2/src/plan/planner/boundary_selection_set.rs, engine/crates/engine-v2/src/request/flat.rs, engine/crates/engine-v2/src/request/path.rs, engine/crates/engine-v2/src/request/walkers/flat.rs, engine/crates/engine-v2/src/request/walkers/mod.rs, engine/crates/engine-v2/src/request/walkers/plan_selection_set.rs, engine/crates/engine-v2/src/request/walkers/selection_set.rs, engine/crates/engine-v2/src/sources/graphql/federation.rs, engine/crates/engine-v2/src/sources/graphql/mod.rs, engine/crates/engine-v2/src/sources/graphql/query.rs, engine/crates/engine-v2/src/sources/introspection/mod.rs, engine/crates/engine-v2/src/sources/mod.rs, engine/crates/engine-v2/src/utils.rs, engine/crates/graphql-mocks/src/federation/accounts.rs, engine/crates/graphql-mocks/src/federation/products.rs, engine/crates/integration-tests/Cargo.toml, engine/crates/integration-tests/src/federation/builder.rs, engine/crates/integration-tests/tests/federation/introspection.rs, engine/crates/integration-tests/tests/federation/subgraphs/mod.rs, engine/crates/integration-tests/tests/federation/subgraphs/sibling_dependencies.rs, engine/crates/integration-tests/tests/federation/subgraphs/simple_key.rs
This PR adapts the planner to take into account sibling plan dependencies. Supposing a subgraph A returns a `Product`, we might retrieve fields from a subgraph B which depends on fields coming from a different subgraph C. This typically happens when the `key` used between `A` and `B` aren't the same.
I've hanged mutations root field logic to also rely on this, making the plan for a root field a dependency of the next one.
All of this code is more complex than needed and I understood why doing this. The tricky parts of GraphQL planning are type conditions and the `skip`/`include` as this generates a lot of conditions for the shape of the queried data. However this only really impacts us when generating the expectations (how to read/validate the upstream response) but not that much the …
=> feat: Handle sibling plan dependencies

Cargo.lock, cli/crates/federated-dev/src/dev/websockets.rs, cli/crates/federated-dev/src/dev/websockets/axum.rs, engine/crates/gateway-v2/Cargo.toml, engine/crates/gateway-v2/src/lib.rs, engine/crates/gateway-v2/src/websockets/messages.rs, engine/crates/gateway-v2/src/websockets/mod.rs
Apollo explorer whinges about this if you give it a null, so updated to omit if null.
Also moved the definition into `gateway-v2` so I can share this with the `api` repo.
=> fix: graphql-ws connection_ack payload shouldn't be null

cli/crates/cli/tests/federation.rs, engine/crates/engine-config-builder/src/lib.rs, engine/crates/engine-v2/config/src/v2/mod.rs, engine/crates/engine-v2/schema/src/conversion.rs, engine/crates/engine-v2/schema/src/sources/federation.rs, engine/crates/engine-v2/src/sources/graphql/subscription.rs, engine/crates/parser-sdl/src/federation.rs, engine/crates/parser-sdl/src/rules/all_subgraphs_directive.rs, engine/crates/parser-sdl/src/rules/subgraph_directive.rs, packages/grafbase-sdk/src/federated/subscriptions.ts, packages/grafbase-sdk/src/grafbase-schema.ts, packages/grafbase-sdk/src/index.ts, packages/grafbase-sdk/tests/unit/federation-graph.test.ts
I'd hard coded this in previous commits so I could do testing without messing about with configuration - this is a more "proper" implementation.  By default we use the normal subgraph URL, but users can override with a specific URL to use for websockets.
Part of GB-5711
=> feat: add websocket urls into the federation config

cli/nix/cli.nix
We can't ignore some md files because they are required to build the corresponding crate.
=> nix: fix cli build

Cargo.lock, cli/crates/federated-dev/Cargo.toml, cli/crates/federated-dev/src/dev.rs, engine/crates/runtime-local/Cargo.toml, engine/crates/runtime-local/src/fetch.rs
I've been tesitng things with hasura, which requires auth - but was getting a
lot of "forbidden" errors.  After far too much digging, turns out this is
because I forgot to pass headers in the `connection_init` payload.
Also enabled TLS in `async_tungstenite` since it turns out to not be 
enabled by default.
Fixes GB-5879
=> fix: send headers in subscription init payload

Cargo.lock, Dockerfile, cli/crates/cli/src/build.rs, cli/crates/cli/src/cli_input/start.rs, cli/crates/cli/src/main.rs, cli/crates/cli/src/start.rs, cli/crates/common/src/consts.rs, cli/crates/federated-dev/Cargo.toml, cli/crates/federated-dev/src/dev.rs, cli/crates/federated-dev/src/dev/bus.rs, cli/crates/federated-dev/src/dev/bus/admin.rs, cli/crates/federated-dev/src/dev/gateway_nanny.rs, cli/crates/federated-dev/src/lib.rs, cli/crates/server/Cargo.toml, cli/crates/server/src/config/actor.rs, cli/crates/server/src/errors.rs, cli/crates/server/src/servers.rs
Adding an option to read an Apollo `supergraphql.graphql` (`FederatedGraph`) and use that as the graph statically. I'm not support any subgraph changes when doing so.
=> chore: add federated-graph-schema arg for federated start

cli/crates/cli/tests/federation.rs
I'd set a bunch of tests to `#[ignore]` because they depended on an unreleased SDK feature.  That's now released, so i'm reinstating the tests.
Fixes GB-5867
=> chore: reinstate federation tests

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.55.0.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/cli/src/introspect/graphql_grammar.yml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Features
- The `grafbase introspect` command now highlights the introspected GraphQL when used in an interactive terminal. This can be disabled through the NO_COLOR env var or the new `--no-color` parameter. (#1303)
=> cli: release 0.55.0

cli/crates/federated-dev/src/dev/websockets.rs, engine/crates/gateway-v2/src/websockets/messages.rs
A few things I knowingly skipped from my initial implementation:
- Timeouts if the user doesn't init the connection
- Returning the `Error` message on fatal errors.
- Erroring out if the user tries to subscribe before init
Fixes GB-5792
=> fix: handle websocket error conditions better in cli

engine/crates/validation/README.md, engine/crates/validation/src/validate/schema_definition.rs, engine/crates/validation/tests/validation_errors/unknown_type_in_schema_def.errors.txt
There was a typo in one validation error message, this commit fixes it.
The README is made more complete by adding an `Example` section and a `Status` section.
=> graphql-schema-validation: expand README, fix typo in error

cli/crates/backend/src/api/consts.rs, cli/crates/backend/src/api/create.rs, cli/crates/backend/src/api/deploy.rs, cli/crates/backend/src/api/link.rs, cli/crates/backend/src/api/unlink.rs, cli/crates/backend/src/api/utils.rs, cli/crates/cli/src/create.rs, cli/crates/cli/src/deploy.rs, cli/crates/cli/src/errors.rs, cli/crates/cli/src/link.rs, cli/crates/cli/src/output/report.rs, cli/crates/common/src/consts.rs
- Implements the new `deploy` flow which asks users whether to link or create a project if it is not already linked
=> GB-3663 - New deploy flow

engine/crates/parser-sdl/src/rules/basic_type.rs
I added a bit of validation around arguments in #1333 which caused my tests to fail.  Turns out this is because we've been dropping arguments of the fields basic types rather than putting them into the Registry.
I'm surprised this didn't cause issues elsewhere tbh, expect we're not being very strict/have other bugs.
Easy to fix though, which this does.
=> fix: fields of basic types can have arguments.

Cargo.lock, cli/crates/cli/Cargo.toml, cli/crates/cli/tests/federation.rs, cli/crates/cli/tests/utils/async_client/websockets.rs, cli/crates/server/Cargo.toml, engine/crates/runtime-local/Cargo.toml, engine/crates/runtime-local/src/fetch.rs, engine/crates/runtime-local/src/fetch/websockets.rs
I wasn't especially happy with the API for graphql-ws-client when I was building subscriptions last month, so I've spent a couple of weekends improving things.
This PR pulls in the release candidate I just put out, so I can be sure it works for our use case.
=> chore: pull in graphql-ws-client 0.8.0-rc.1

cli/crates/gateway/src/executor.rs, cli/crates/gateway/src/response.rs, cli/crates/gateway/src/serving.rs, engine/crates/gateway-core/src/cache/mod.rs, engine/crates/gateway-core/src/executor.rs, engine/crates/gateway-core/src/lib.rs, engine/crates/gateway-core/src/response.rs
I'm trying to implement batching in the various gateway crates, but finding it very hard to follow some of the code.  Mostly because we have too many things named `Response` that are closely related but not quite the same (and in places we're working with 2-3 of them in a single line of code)
This attempts to clean that up a bit:
- Renamed `Executor::Response` to `Executor::StreamingResponse` since it's actually only used for `execute_stream`.
- Made the error handling for `gateway::Response` a bit clearer - we were doing a `.into()` that acted like some combination of `.unwrap()` and `map_err().unwrap_err()`.  I found this quite hard to follow (particularly since go to def doesn't work well for `From` impls) so switched it about a bit.
- Got rid of `with_additional_headers` from …
=> chore: attempt to make gateway_core a bit clearer.

engine/crates/engine-v2/schema/src/names.rs, engine/crates/engine-v2/schema/src/walkers/enum.rs, engine/crates/engine-v2/schema/src/walkers/mod.rs, engine/crates/engine-v2/src/execution/variables.rs, engine/crates/engine-v2/src/sources/introspection/writer.rs
Simple EnumValue walker which supports renaming
=> chore: Add EnumValueWalker in engine-v2

Cargo.lock, cli/crates/cli/tests/apq.rs, cli/crates/cli/tests/utils/async_client.rs, cli/crates/cli/tests/utils/async_client/websockets.rs, cli/crates/federated-dev/src/dev.rs, cli/crates/gateway/Cargo.toml, cli/crates/gateway/src/context.rs, cli/crates/gateway/src/serving.rs, engine/crates/engine/src/lib.rs, engine/crates/engine/src/request.rs, engine/crates/engine/src/request/query.rs, engine/crates/gateway-core/src/serving.rs
GET request have a specific format, values are encoded in JSON, but the root fields are url
encoded. To ensure that the HTTP framework doesn't mess with it, we're first trying to
deserialize all values as strings.
```sh
curl --get http://localhost:4000/graphql \
--header 'content-type: application/json' \
--data-urlencode 'query={__typename}' \
--data-urlencode 'extensions={"persistedQuery":{"version":1,"sha256Hash":"ecf4edb46db40b5132295c0291d62fb65d6759a9eedfa4d5d612dd5ec54a6b38"}}'
```
=> fix: Deserialize properly GET requests for the engine

cli/crates/cli/tests/batching.rs, cli/crates/cli/tests/utils/async_client.rs, cli/crates/cli/tests/utils/async_client/websockets.rs, cli/crates/cli/tests/utils/environment.rs, cli/crates/gateway/src/response.rs, cli/crates/gateway/src/serving.rs, engine/crates/gateway-core/src/cache/mod.rs, engine/crates/gateway-core/src/lib.rs, engine/crates/gateway-core/src/response.rs
Implements [this RFC](https://github.com/graphql/graphql-over-http/blob/main/rfcs/Batching.md) for standalone graphs in the CLI.
The RFC is pretty silent on whether requests should be run in parallel or in series.  Even the implementations linked to from the RFC can't agree: half of them do things in parallel, half in series.  I've settled on doing things serially for now as it's easy and definitely won't break anything.  Can revisit later if we need to.
Part of GB-5931
=> feat: graphql batching in cli standalone graphs

cli/crates/cli/src/introspect.rs, cli/nix/udf-wrapper.nix
This is the well known issue of `print!()` & co from the standard library panicking if stdout/stderr becomes unavailable. This commit fixes the issue in `grafbase introspect`.
Issue illustrated:
The panic message isn't shown anymore after this commit because introspect handles the error gracefully.
Also, update the npm deps hash in udf-wrapper.nix so `nix build .#cli` works again. 
closes GB-5788
=> cli: avoid crashing when stdout becomes unavailable in introspect

Cargo.lock, Cargo.toml, cli/crates/cli/Cargo.toml, engine/crates/engine-v2/config/Cargo.toml, engine/crates/engine-v2/schema/Cargo.toml, engine/crates/engine-v2/schema/src/builder/mod.rs, engine/crates/engine-v2/schema/src/ids.rs, engine/crates/engine-v2/schema/src/input_value/de.rs, engine/crates/engine-v2/schema/src/input_value/display.rs, engine/crates/engine-v2/schema/src/input_value/error.rs, engine/crates/engine-v2/schema/src/input_value/ids.rs, engine/crates/engine-v2/schema/src/input_value/mod.rs, engine/crates/engine-v2/schema/src/input_value/ser.rs, engine/crates/engine-v2/schema/src/lib.rs, engine/crates/engine-v2/schema/src/names.rs, engine/crates/engine-v2/schema/src/sources/introspection.rs, engine/crates/engine-v2/schema/src/walkers/enum.rs, engine/crates/engine-v2/schema/src/walkers/field.rs, engine/crates/engine-v2/schema/src/walkers/input_value.rs, engine/crates/engine-v2/schema/src/wrapping.rs, engine/crates/engine-v2/src/plan/walkers/argument.rs, engine/crates/engine-v2/src/request/selection_set.rs, engine/crates/engine-v2/src/request/walkers/field_argument.rs, engine/crates/engine-v2/src/response/read/ser.rs, engine/crates/engine-v2/src/sources/introspection/writer.rs, engine/crates/engine/Cargo.toml, engine/crates/integration-tests/tests/federation/introspection.rs, engine/crates/parser-graphql/Cargo.toml, engine/crates/parser-openapi/Cargo.toml, engine/crates/parser-sdl/Cargo.toml
Adding `InputValues` to store default input values & directive arguments in
the schema and later re-use the same type for input values for an operation.
As those are stored with the `InputValueDefinitionId` and `EnumValueId`
rather than strings this will allow an engine-v2 Resolver to be entirely
unaware of schema names, meaning we could rename any part of the schema.
And also adds the default values in the introspection now :D
=> chore: Add default values in introspection

cli/crates/cli/tests/introspection_configuration.rs, engine/crates/engine/src/validation/rules/fields_on_correct_type.rs, engine/crates/engine/src/validation/rules/known_argument_names.rs
- Disable 'did you mean' suggestions if introspection is disabled
=> Disable 'did you mean' suggestions if introspection is disabled

cli/crates/backend/src/api/graphql/api.graphql, cli/crates/backend/src/api/graphql/types/mutations.rs, cli/crates/backend/src/api/publish.rs
We spread on `...BranchDoesNotExistError` in the cli (publish), but the API broke by renaming the type. This commit takes in the new api.graphql and fixes the issue.
closes GB-6042
=> cli: update api schema, fix breaking change

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.58.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Fixes
- Fix bad GraphQL query in `grafbase publish` (#1577)
- Fix nested fragments in graphql connector, they did not work (#1371)
- Fix formatting for SDK extend directives (#1370)
=> cli: release 0.58.1

cli/nix/udf-wrapper.nix, engine/crates/engine-v2/schema/src/builder/ids.rs, engine/crates/engine-v2/schema/src/builder/mod.rs, engine/crates/engine-v2/schema/tests/conversion.rs, engine/crates/federated-graph/src/federated_graph/v1.rs, engine/crates/federated-graph/src/federated_graph/v2.rs, engine/crates/integration-tests/tests/federation/introspection.rs
Since they are not part of the API of the engine, they should be excluded as early as possible. They can fall through the cracks if they are included in the schema, so we remove them at conversion time.
The approach taken is to remove inaccessible output fields, input value definitions, union members and enum values. Since inaccessible types cause the fields returning them to also be inaccessible (composition rule), that automatically deals with inaccessible types.
closes GB-5949
=> engine-v2-schema: remove inaccessible items

Cargo.lock, cli/crates/backend/src/api/graphql/api.graphql, cli/crates/backend/src/api/graphql/types/mutations.rs, cli/crates/backend/src/api/graphql/types/mutations/submit_trusted_documents.rs, cli/crates/backend/src/api/mod.rs, cli/crates/backend/src/api/submit_trusted_documents.rs, cli/crates/cli/src/cli_input.rs, cli/crates/cli/src/cli_input/sub_command.rs, cli/crates/cli/src/cli_input/trust.rs, cli/crates/cli/src/errors.rs, cli/crates/cli/src/main.rs, cli/crates/cli/src/output/report.rs, cli/crates/cli/src/trust.rs, cli/crates/common/Cargo.toml, cli/crates/common/src/lib.rs, cli/crates/common/src/trusted_documents.rs, cli/crates/common/src/trusted_documents/apollo.rs
The command is called `trust` and lives at the top level, but we can
iterate if that turns out not to be self-explanatory enough.
The command is hidden for now, since the feature isn't complete in the
engine and infrastructure yet, and not documented.
It takes a branch reference, a client name and a manifest file that can
be either in Relay or Apollo Client format. We can easily add more
manifest formats as the appetite arises. We can even imagine using the
Grafbase CLI to generate manifests directly.
closes GB-6015
=> cli: new command for trusted document submission

Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/backend/src/api/deploy.rs, cli/crates/backend/src/api/errors.rs
A user was running into issues with `grafbase deploy` yesterday, where deployments failed with a bizzare error very similar to [this one][1].
We eventually tracked this down to files in the users `.direnv` or `.devenv` folders - based on the tar-rs issue _probably_ hard links of some description. While it would be good to not choke on hardlinks, I'd argue we shouldn't have been archiving these files in the first place: they're clearly meant to stay local to the users machine.
So this PR switches `walkdir` for `ignore`, which will respect `.gitignore` files etc, providing users with a sensible (and in most cases zero effort) way to exclude files from the archive we build on `grafbase deploy`.  I think this is a sensible default.
This _could_ have ramifications for anyone doing a `grafbase …
=> fix: respect `.gitignore` in `grafbase deploy`

cli/crates/backend/src/api/consts.rs
The CLI auth flow for the new dashboard is ready, so we can switch the CLI to start authenticating through that. The old URL already redirects to the new flow, so this won't change much from an end user perspective, and old version of the CLI won't break.
=> Change auth flow to use new dashboard [GB-6060]

engine/crates/engine-v2/src/response/write/deserialize/mod.rs, engine/crates/engine-v2/src/response/write/mod.rs, engine/crates/engine-v2/src/sources/graphql/deserialize/response.rs, engine/crates/integration-tests/tests/federation/basic/errors.rs
We wouldn't return upstream errors if data wasn't `null`, a stupid mistake.
We can do better with a custom Deserialize for federation
entities rather than re-using the generic GraphQL response one, but it
does require more work. So doing the MVP for now.
=> fix: Add missing upstream error for federation subgraph response.

engine/crates/graphql-schema-diff/README.md, engine/crates/graphql-schema-diff/src/state.rs, engine/crates/graphql-schema-diff/tests/diff/add_one_object.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/enum_basic.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/union_basic.snapshot.json
Same goes for variants of unions, values of enums, etc.
closes GB-6104
=> graphql-schema-diff: stop emitting addField for fields of new objects

engine/crates/federated-graph/src/render_sdl.rs
=> fix: Escape strings in federated graph SDL

cli/crates/cli/tests/assets/sdk-package-module.json, cli/crates/cli/tests/start.rs, cli/crates/cli/tests/utils/environment.rs
These tests got ignored ages ago.  I tried to resurrect them back in January but they were failing on certain platforms due to some `ts-node` issue.
Now that we're using bun they pass on all platforms, so yay to that.
Fixes GB-5912
=> test: re-instate the start test

engine/crates/engine/src/validation/visitors/cache_control.rs, engine/crates/integration-tests/src/engine/builder.rs, engine/crates/integration-tests/tests/caching/mod.rs, engine/crates/integration-tests/tests/integration_tests.rs, engine/crates/parser-sdl/src/rules/cache_directive/global.rs, engine/crates/tracing/src/filter.rs
Fixes a bug that happened when computing response cache tags that were not present when using mutation invalidation of type `entity` with a custom field.
=> fix: custom field entity mutation invalidation cache tag

cli/crates/production-server/src/server.rs, cli/crates/production-server/src/server/graph_updater.rs
This fixes a few things:
- When a connection fails to GDN, our subsequent connections were all failing. We prevent this by disabling the TCP keepalive.
- When a connection times out, the timeout can take a long time and when the connections are fast again we sent a burst of queries to the GDN for all the missed ticks. We should instead just skip all missed ticks and query again when the next time is due.
- Fixes a small typo in the server start log message.
- To keep http2 connection up and running nicely, we enable HTTP2 Ping, keepalive and idle pings.
Closes: GB-6214
=> fix: connection timeout failure modes, tick burst prevention and a typo

cli/crates/backend/src/api/check.rs, cli/crates/backend/src/api/consts.rs, cli/crates/backend/src/api/create.rs, cli/crates/backend/src/api/deploy.rs, cli/crates/backend/src/api/link.rs, cli/crates/backend/src/api/login.rs, cli/crates/backend/src/api/logs.rs, cli/crates/backend/src/api/publish.rs, cli/crates/backend/src/api/schema.rs, cli/crates/backend/src/api/subgraphs.rs, cli/crates/backend/src/api/submit_trusted_documents.rs, cli/crates/cli/tests/production_server.rs, cli/crates/production-server/src/server/graph_updater.rs
We need three different env vars:
- `GRAFBASE_API_URL` which is the API endpoint. Defaults to https://api.grafbase.com/graphql
- `GRAFBASE_GDN_URL` for starting the federated router, and getting the latest federated graph. Defaults to https://gdn.grafbase.com
Closes: GB-6209
=> feat: allow setting uplink, api and auth urls with env vars

cli/crates/cli/tests/introspection.rs, cli/crates/cli/tests/utils/environment.rs, cli/crates/server/src/introspect_local.rs
This is a bug that breaks the `grafbase introspect --dev | grafbase publish` workflow.
closes GB-6246
=> cli: include subgraph federation directives in grafbase introspect --dev

cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, engine/crates/engine-v2/Cargo.toml, engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/execution/coordinator.rs, engine/crates/engine-v2/src/execution/prepared.rs, engine/crates/engine-v2/src/sources/graphql/mod.rs, engine/crates/engine/Cargo.toml, engine/crates/engine/src/schema.rs, engine/crates/integration-tests/Cargo.toml, engine/crates/tracing/Cargo.toml, engine/crates/tracing/src/config.rs, engine/crates/tracing/src/otel/layer.rs
I'm dropping the `tracing` flags across the board and instead I'm adding a new feature in `grafbase_tracing`, "otlp" to gate any otlp capabilities. 
When creating `grafbase_tracing::otel::layers`, if one wants the otlp exporter to be configured in the `SpanProcessor` attached to the layer, one needs to explicitly set the `otlp` feature.
This is useful in two different ways:
- Avoid pulling in a bunch on dependencies when we just want the basic stuff (like typed spans)
- The above mitigates `http` crate version conflicts
- Keeps the crate `default` lean
=> feat: drop the tracing feature in the engines 

.github/actions/test/action.yml, .github/workflows/binaries.yml
This was missing from the action. Without it we can't release grafbase cli.
=> fix: enable cli releases

engine/crates/engine/src/registry/resolvers/graphql.rs, engine/crates/integration-tests/tests/execution/joins.rs
When the GraphQL connector needs to handle multiple concurrent requests to the same downstream, it tries to combine the operations from each request into a single operation.  When working with joins inside lists, this can lead to a situation where we need to get the same root field multiple times.
The naive approach to this leads to queries like this:
```graphql
query {
foo(id: 1) {
bar
}
foo(id: 2) {
bar
}
}
```
Which is not a valid query.  
I'd previously tried to fix this by putting aliases on the fields generated by joins, which worked alright when joins didn't support namespaced GraphQL connectors.  But now that we support namespaced queries this isn't good enough, the alias ends up put onto the root namespace field, like this:
```graphql
query {
field_1: myApi {
foo(id: 1) {
bar
}
} …
```
=> fix: alias grouped fields in namespaced graphql connector

Cargo.lock, engine/crates/tracing/Cargo.toml, engine/crates/tracing/src/config.rs, engine/crates/tracing/src/span.rs, engine/crates/tracing/src/span/request.rs
Adds a new feature `worker` to `grafbase-tracing` so we can record http requests spans deriving from `worker::Request`. Hopefully in the future this can go away as they are moving towards using the crate `http`.
=> feat: tracing worker integration

engine/crates/engine/src/context/field.rs, engine/crates/engine/src/registry/resolvers/graphql/serializer.rs, engine/crates/engine/src/registry/variables/mod.rs, engine/crates/engine/src/resolver_utils/dynamic.rs, engine/crates/engine/src/resolver_utils/joins.rs, engine/crates/graphql-mocks/src/fake_github.rs, engine/crates/graphql-mocks/src/lib.rs, engine/crates/integration-tests/tests/execution/joins.rs, engine/crates/integration-tests/tests/federation/introspection.rs, engine/crates/integration-tests/tests/federation/snapshots/integration_tests__federation__introspection__raw_introspetion_output.snap, engine/crates/integration-tests/tests/graphql_connector/transforms.rs
This is a fixed version of #1488 - I hadn't noticed a test failure and somehow it got merged anyway.  You can skip over the first commit if you want, it's only the second & third that are new.  Though it's not a big PR in the first place.
The issue with #1488 was that I was only processing joined variables on the current field before resolving, ignoring any sub-fields.  This doesn't work with any resolver that looks at the whole sub-query (e.g. the GraphQL connector).  I've updated it to do replacement across the whole query prior to running any resolvers.
Also added a more thorough test of this issue, since the one I'd written wasn't great.
=> fix: coerce enums when handling join variables (for real this time)

engine/crates/integration-tests/tests/execution/joins.rs
I'd fooled myself into thinking the order that joins were executed was determinstic - it is not.  This meant that the query snapshot could appear in one of two orders, making the test flaky.
Switched it so there's only a single fetch needed for the join, which solves the problem for now.
=> fix: a non-deterministic test

packages/grafbase-sdk/src/field.ts, packages/grafbase-sdk/src/query.ts, packages/grafbase-sdk/src/type.ts, packages/grafbase-sdk/src/typedefs/auth.ts, packages/grafbase-sdk/src/typedefs/cache.ts, packages/grafbase-sdk/src/typedefs/default.ts, packages/grafbase-sdk/src/typedefs/deprecated.ts, packages/grafbase-sdk/src/typedefs/enum.ts, packages/grafbase-sdk/src/typedefs/inaccessible.ts, packages/grafbase-sdk/src/typedefs/input.ts, packages/grafbase-sdk/src/typedefs/join.ts, packages/grafbase-sdk/src/typedefs/length-limited-string.ts, packages/grafbase-sdk/src/typedefs/list.ts, packages/grafbase-sdk/src/typedefs/map.ts, packages/grafbase-sdk/src/typedefs/override.ts, packages/grafbase-sdk/src/typedefs/provides.ts, packages/grafbase-sdk/src/typedefs/reference.ts, packages/grafbase-sdk/src/typedefs/resolver.ts, packages/grafbase-sdk/src/typedefs/scalar.ts, packages/grafbase-sdk/src/typedefs/shareable.ts, packages/grafbase-sdk/src/typedefs/tag.ts, packages/grafbase-sdk/src/typedefs/unique.ts, packages/grafbase-sdk/tests/unit/types.test.ts
I'm adding argument support to joins at the moment, and while planning how to do this I noticed the SDK has no way to add arguments to arbitrary fields.  It lets you add arguments to fields of the root query type but not anywhere else.
This PR fixes that by adding `arguments` functions to the `JoinDefinition` & `ResolverDefintion` types.  These are I _think_ the only places that arguments make sense at the moment, though I'm open to discussing if anyone thinks a different approach would be better.
I've also added an `allArguments` property to most of the types involved in specifying field types, even those that might not have their own arguments.  I needed to do this because e.g. `JoinDefinition` can be wrapped by `AuthDefinition` - so we need to make sure we ask every object in the …
=> feat: add argument support to the SDK

engine/crates/engine/src/registry/federation.rs, engine/crates/engine/src/resolver_utils/joins.rs, engine/crates/engine/src/validation/rules/provided_non_null_arguments.rs, engine/crates/integration-tests/tests/execution/joins.rs, engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/rules/basic_type.rs, engine/crates/parser-sdl/src/rules/extend_connector_types.rs, engine/crates/parser-sdl/src/rules/federation/key.rs, engine/crates/parser-sdl/src/rules/join_directive.rs, engine/crates/parser-sdl/src/rules/visitor.rs, engine/crates/parser-sdl/src/rules/visitor/warnings.rs, engine/crates/parser-sdl/src/schema_coord.rs, engine/crates/parser-sdl/src/validations.rs
A customer wants to forward an argument on a join field into the query that we use to perform the join.  This adds support for that, using the same variable syntax we already use.  
Any arguments on the join field are automatically available under `$argumentName`.  Currently arguments will always shadow fields of the parent object.  So if there's a `foo` argument then `$foo` will _always_ refer to that argument, and any field on the parent type named `foo` will be inaccessible.  The alternative to this would have been to use some special syntax to differentiate fields & arguments, but that seemed like a lot more work, and I'm not sure how likely it is for users to need that functionality.  We can always revisit later.
I'm not doing much validation on these arguments at parsing time …
=> feat: arguments on join fields

engine/crates/composition/src/compose/object.rs, engine/crates/composition/src/ingest_subgraph/directives.rs, engine/crates/composition/src/subgraphs/directives.rs, engine/crates/composition/src/validate.rs, engine/crates/composition/tests/composition/override_label/federated.graphql, engine/crates/composition/tests/composition/override_label/subgraphs/fst.graphql, engine/crates/composition/tests/composition/override_label_invalid/federated.graphql, engine/crates/composition/tests/composition/override_label_invalid/subgraphs/fst.graphql, engine/crates/federated-graph/src/federated_graph/v1.rs, engine/crates/federated-graph/src/federated_graph/v2.rs, engine/crates/federated-graph/src/federated_graph/v3.rs, engine/crates/federated-graph/src/from_sdl.rs, engine/crates/federated-graph/src/render_sdl.rs
This consists of a new `label` argument where you can specify a percentage
of traffic to direct to the overriding subgraph.
closes GB-6126
=> composition: implement progressive override

engine/crates/validation/CHANGELOG.md, engine/crates/validation/src/validate/schema_definition.rs, engine/crates/validation/tests/validation_errors/schema_definition_explicit_nonexistent_default_root.errors.txt, engine/crates/validation/tests/validation_errors/schema_definition_explicit_nonexistent_default_root.graphql, engine/crates/validation/tests/validation_errors/two_schema_definitions.graphql
When validating that the root types used in a schema definition exists, we were skipping the validation whenever the type is the default one for the root (Query, Mutation or Subscription). This commit makes the validation stricter. If Query does not exist, it is an error.
closes GB-6313
=> graphql-schema-validation: refuse references to nonexistent default roots

Cargo.lock, cli/crates/server/Cargo.toml, cli/crates/server/src/config/mod.rs, engine/crates/engine/src/registry/mod.rs, engine/crates/parser-sdl/src/connector_parsers.rs, engine/crates/parser-sdl/src/rules/visitor/context.rs
Since we use graphql_schema_validation on the generated schemas in the API, we should also validate in `grafbase dev` to tighten the feedback loop.
The engine tends to produce empty types, so we also have to start pruning these when finalizing the registry.
closes GB-6335
=> cli: validate the registry in grafbase dev

engine/crates/engine-v2/src/operation/input_value/query/mod.rs, engine/crates/engine-v2/src/operation/walkers/argument.rs, engine/crates/engine-v2/src/plan/walkers/field.rs, engine/crates/engine-v2/src/sources/graphql/query.rs
Splitting up code I did. Having variables for booleans and enum values when we include them in the normalized query felt a bit too much. And added a nice way to deserialize all arguments at once at some point.
=> chore(engine-v2): arguments walker and improve query string

engine/crates/engine-v2/src/operation/bind/mod.rs, engine/crates/engine-v2/src/operation/input_value/query/mod.rs, engine/crates/engine-v2/src/operation/selection_set.rs, engine/crates/engine-v2/src/operation/validation/introspection.rs, engine/crates/engine-v2/src/operation/walkers/argument.rs, engine/crates/engine-v2/src/operation/walkers/field.rs, engine/crates/engine-v2/src/plan/flat.rs, engine/crates/engine-v2/src/plan/planning/boundary.rs, engine/crates/engine-v2/src/plan/planning/planner.rs, engine/crates/engine-v2/src/plan/planning/walker_ext.rs, engine/crates/engine-v2/src/response/write/deserialize/field.rs, engine/crates/engine-v2/src/response/write/deserialize/list.rs, engine/crates/engine-v2/src/response/write/deserialize/nullable.rs, engine/crates/graphql-mocks/src/federation/inventory.rs, engine/crates/graphql-mocks/src/federation/mod.rs, engine/crates/graphql-mocks/src/federation/products.rs, engine/crates/graphql-mocks/src/federation/reviews.rs, engine/crates/graphql-mocks/src/lib.rs, engine/crates/integration-tests/tests/federation/introspection.rs, engine/crates/integration-tests/tests/federation/subgraphs/mod.rs, engine/crates/integration-tests/tests/federation/subgraphs/requires.rs
This PR adds argument handling to the planner. Before I only cared whether a field with the right `FieldDefinitionId` existed. I compare arguments from the `@requires` to one in the `Operation` fields, if I don't find a match I create a new field.
=> feat(engine-v2): add argument support for @requires part3

engine/crates/engine/src/registry/mod.rs, engine/crates/engine/src/registry/tests.rs, engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__array_input_value.snap, engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__conversion.snap, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__flat_output-2.snap, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__petstore_output-2.snap, engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/rules/mod.rs, engine/crates/parser-sdl/src/rules/trusted_documents_directive.rs, engine/crates/parser-sdl/src/rules/visitor/context.rs, packages/grafbase-sdk/src/config.ts, packages/grafbase-sdk/src/trusted-documents.ts, packages/grafbase-sdk/tests/unit/trusted-documents.test.ts
This is part of the work to enable trusted documents for managed standalone graphs.
The config looks like this:
```typescript
config({
graph: g,
trustedDocuments: {
enabled: true
}
})
```
closes GB-6346
=> Implement trusted documents configuration in SDK and registry

engine/crates/engine/src/registry/resolvers/mod.rs, engine/crates/integration-tests/tests/tracing/v1.rs, engine/crates/tracing/src/span.rs, engine/crates/tracing/src/span/resolver.rs
Adds resolver spans for v1 graphs.
=> feat: add resolver spans

Cargo.toml
=> fix: gb publish did not work without having http2 enabled for reqwest

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.64.3.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Fixes the http2 crash on API calls.
=> chore: bump cli to 0.64.3

engine/crates/engine/src/validation/utils.rs, engine/crates/engine/value/src/lib.rs, engine/crates/integration-tests/src/mongodb.rs, engine/crates/integration-tests/tests/mongodb/joins.rs, engine/crates/integration-tests/tests/mongodb/mod.rs, engine/crates/integration-tests/tests/mongodb/schema.rs, engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/parser_extensions.rs, engine/crates/parser-sdl/src/rules/basic_type.rs, engine/crates/parser-sdl/src/rules/check_type_validity.rs, engine/crates/parser-sdl/src/rules/extend_connector_types.rs, engine/crates/parser-sdl/src/rules/extend_query_and_mutation_types.rs, engine/crates/parser-sdl/src/rules/mongodb_directive/model_directive.rs, engine/crates/parser-sdl/src/rules/mongodb_directive/model_directive/create_type_context.rs, engine/crates/parser-sdl/src/rules/mongodb_directive/model_directive/model_type.rs, engine/crates/parser-sdl/src/rules/mongodb_directive/model_directive/model_type/resolver_data.rs, engine/crates/parser-sdl/src/rules/mongodb_directive/model_directive/types/create.rs, engine/crates/parser-sdl/src/rules/mongodb_directive/model_directive/types/filter.rs, engine/crates/parser-sdl/src/rules/mongodb_directive/model_directive/types/input.rs
A potential customer was trying to use our join directive to hook up two mongo db models up, like so:
```typescript
g.extend("Customer", (extend) => {
extend.addField(
"customerContacts",
g.ref("CustomerConnection").optional().join(
"mongoDB { contactCollection(first: 10, filter:{businessid:{eq: $customerid}})"
)
)
})
```
But this was giving them the following error:
> Field customerContacts got an undefined type: CustomerConnection
This particular error is because the mongo connector doesn't put its generated types into `ctx.types` which is where the code responsible for the above error looks for types.  I've fixed that by updating the undefined type code to also look in `registry.types` instead of just `ctx.types`.
After fixing that I noticed that the connector doesn't parse join …
=> feat: join support for mongo db connector

Cargo.lock, Cargo.toml, engine/crates/integration-tests/src/openid.rs, engine/crates/integration-tests/tests/openapi/headers.rs, gateway/crates/gateway-binary/tests/integration_tests.rs
Ensures we don't have reqwest 0.11 in our dependency tree any more.
=> chore(deps): Upgrade dependencies, most importantly reqwest to 0.12

engine/crates/engine/src/registry/mod.rs, engine/crates/integration-tests/tests/openapi/transforms.rs
- Remove fields that may return that type
- Remove query and mutation roots of that type
closes GB-6364
=> engine-v1: remove references to empty types when removing empty types

Cargo.lock, Cargo.toml, engine/crates/tracing/Cargo.toml
Align on 0.21.0, like in API. This is a problem when trying to upgrade the deps from this repo, because other deps using the workers crate aren’t caught up to 0.23.0 yet.
=> Fix (cloudflare) worker crate version

engine/crates/engine/src/schema.rs, engine/crates/integration-tests/tests/tracing/v1.rs
This PR removes the graphql document (query) from the tracing spans as they could potentially contain sensible data, be huge and potentially contributes to missing spans
=> feat: remove the query attribute from the gql span

engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/rules/federation/key.rs, engine/crates/parser-sdl/src/rules/join_directive.rs, engine/crates/parser-sdl/src/rules/mongodb_directive/model_directive.rs, engine/crates/parser-sdl/src/rules/mongodb_directive/type_directive.rs, engine/crates/parser-sdl/src/tests.rs, engine/crates/parser-sdl/src/validations.rs
- incorrect ordering or validation rules
- mongodb type rule didn't guard against extension types
- better error message for incompatible types
Pretty sure all of this would be simpler if we generated the schema by connector and then merged it with composition, but well, for another life
=> fix(parser-sdl): mongodb + extension types bugs

Cargo.lock, cli/crates/gateway/Cargo.toml, cli/crates/gateway/src/lib.rs, engine/crates/gateway-core/src/lib.rs, engine/crates/gateway-core/src/trusted_documents.rs
Implement trusted document handling in engine-v1. The implementation is nearly identical to the one in engine-v2. This will be tested with e2e tests.
closes GB-6252
=> Trusted documents for managed standalone graphs

packages/grafbase-sdk/src/define.ts, packages/grafbase-sdk/src/grafbase-schema.ts, packages/grafbase-sdk/src/typedefs/reference.ts, packages/grafbase-sdk/src/union.ts, packages/grafbase-sdk/tests/unit/types.test.ts
The following is currently a type error:
```
const user = g.type('User', {
name: g.string(),
age: g.int().optional()
})
const organization = g.type('Organization', {
domain: g.string(),
employeeCount: g.int()
})
const account = g.union('Account', { user, organization })
g.query('currentAccount', {
resolver: 'current-account',
returns: g.ref(account)
})
```
The solution in this commit is to make g.ref() accept union types. Alternatively, we could add g.unionRef() (similar to g.enumRef()), but that seems like unnecessary API sprawl.
closes GB-6390
=> sdk: make g.ref() accept unions

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.19.1.md, packages/grafbase-sdk/package.json
- `g.ref()` now accepts union types as input. [1545](https://github.com/grafbase/grafbase/pull/1545)
=> sdk: release 0.19.1

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.19.2.md, packages/grafbase-sdk/src/trusted-documents.ts, packages/grafbase-sdk/tests/unit/trusted-documents.test.ts
We would end up with something like `extend schema @trustedDocumentsextend schema...`.# Description
=> sdk: fix missing newline after trusted documents directive

engine/crates/gateway-core/src/trusted_documents.rs
All we see at the moment is `Internal server error`, which isn't helpful.
=> Improve logging for trusted document errors

Cargo.lock, engine/crates/tracing/src/otel/layer.rs, engine/crates/tracing/src/otel/provider.rs, gateway/crates/federated-server/src/config.rs, gateway/crates/federated-server/src/config/telemetry.rs, gateway/crates/federated-server/src/lib.rs, gateway/crates/federated-server/src/server.rs, gateway/crates/federated-server/src/server/graph_fetch_method.rs, gateway/crates/federated-server/src/server/graph_updater.rs, gateway/crates/federated-server/src/server/otel.rs, gateway/crates/gateway-binary/Cargo.toml, gateway/crates/gateway-binary/src/main.rs
Reload the otel layer when we receive a valid graph update. The reload will add updated resource attributes (account_id and branch_id) so these are present on exported spans.
=> feat: reload otel layer based on graph updated

.github/workflows/binaries.yml, Cargo.lock, Cargo.toml
We recently added `codegen-units=1` to the release build config.  This was aimed at reducing the size of the binaries that we ship for lambdas, and it was successful in that regard.  It slows release builds down quite significantly though, which has had an impact on CI times, as you can see on this graph.
That graph shows a day or two between the merge & a noticeable increase in CI times, but the merge was on friday and I assume it wasn't until the monday that every other piece of work had rebased onto `main` and pulled in the change.
This PR makes two changes:
- Creates a new cargo profile `lambda` that with `codegen-units=1` and updates CI to use this profile for building the lambda.  This shaved 5-6 minutes off.
- I then updated the lambda build to only use this profile when doing a …
=> chore: only use `codegen-units=1` for lambda releases

.github/actions/test/action.yml, .github/actions/test_upload_datadog/action.yml, .github/workflows/binaries.yml, .github/workflows/sanitize-alert-schedule.yml
We upload junit files to datadog in the API repo.  I fixed some of this in https://github.com/grafbase/api/pull/3459 but noticed that we weren't doing similar in this repo.  It can be useful to track failures, slow tests, flaky tests etc.
So, this PR adds the upload code to this repo as well.
=> chore: report test results to datadog

cli/crates/cli/src/errors.rs, cli/crates/cli/src/trust.rs
=> cli: improve manifest parsing errors in grafbase trust

engine/crates/composition/src/compose/object.rs, engine/crates/composition/src/ingest_subgraph/fields.rs, engine/crates/composition/src/subgraphs.rs, engine/crates/composition/src/subgraphs/fields.rs, engine/crates/composition/tests/composition/field_argument_default_mismatch/federated.graphql, engine/crates/composition/tests/composition/field_argument_default_mismatch/subgraphs/paris.graphql, engine/crates/composition/tests/composition/field_argument_default_mismatch/subgraphs/tokyo.graphql
The rule is that they have to match exactly between subgraphs, otherwise it's an error.
closes GB-6159
=> composition: implement composition of field argument defaults

engine/crates/composition/src/compose/entity_interface.rs, engine/crates/composition/tests/composition/entity_interface_different_key/federated.graphql, engine/crates/composition/tests/composition/entity_interfaces_multi_subgraph_missing_implementer/subgraphs/savana.graphql
Before this commit, we were only validating that the implementers of the interface — in the subgraph where the interface is defined — have the same key, but the error message mentioned @interfaceObject, which is not about implementers, but about types in other subgraphs.
This commit
- resolves the confusion: the error message now mentions the right problem
- implements validation of matching key for interface objects in other subgraphs
closes gb-5825
=> composition: validate that keys match in entity interfaces

engine/crates/runtime/src/cache/cached.rs, engine/crates/runtime/src/cache/mod.rs, engine/crates/tracing/src/tower.rs, gateway/crates/federated-server/src/server/engine.rs
Still thinking about how to propagate operation metadata. So adding those simple metrics for now to be able to move forward with the ClickHouse part.
=> Add basic request metrics

Cargo.lock, gateway/crates/federated-server/src/config.rs, gateway/crates/federated-server/src/config/telemetry.rs, gateway/crates/gateway-binary/Cargo.toml, gateway/crates/gateway-binary/src/main.rs, gateway/crates/gateway-binary/tests/telemetry/mod.rs
Main purpose is to allow me in api integration tests to set `grafbase.account_id` etc. as I don't rely on the otel-gateway
=> feat: allow defining custom resource attributes in otel

engine/crates/engine/derive/src/interface.rs, engine/crates/engine/src/registry/mod.rs, engine/crates/integration-tests/tests/custom_resolvers/mod.rs, engine/crates/parser-graphql/src/conversion.rs, engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/rules/basic_type.rs, engine/crates/parser-sdl/src/rules/interface.rs, engine/crates/parser-sdl/src/rules/mod.rs
Back in the days of `@model`, grafbase didn't support interfaces.  On adding the graphql connector, grafbase started having to support interfaces.
Hugo is currently trying to test some stuff around caching & interfaces, but he ran into difficulties testing, because `parser-sdl` still just ignores interfaces.  It's quite easy to fix this though, so that's what I've done.
At some point we'll probably need to do the same for union types as well, but that's for the future.  Also this doesn't techncially let users do interfaces because I've not updated the SDK, but we can do that if we want.
=> feat: allow tests to define interfaces

packages/grafbase-sdk/src/grafbase-schema.ts, packages/grafbase-sdk/tests/unit/federation-graph.test.ts
A follow up to #1578 - adds the subgraph url configuration into the SDK
Fixes GB-6127
=> feat: add subgraph url config to the SDK

.cargo/config.toml
As of Rust 1.70.0 the sparse protocol is now enabled by default.
Also remove git via CLI config
=> remove sparse cargo protocol as it is enabled by default

engine/crates/engine/src/error.rs, engine/crates/engine/src/registry/resolvers/custom.rs, engine/crates/engine/src/registry/resolvers/graphql.rs, engine/crates/engine/src/registry/resolvers/graphql/response.rs, engine/crates/engine/src/registry/resolvers/postgres.rs, engine/crates/graphql-mocks/src/lib.rs, engine/crates/integration-tests/tests/graphql_connector/errors.rs
=> fix: add response content for failing HTTP requests in the GraphQL connector

engine/crates/tracing/src/otel/metrics.rs, engine/crates/tracing/src/tower.rs, gateway/crates/gateway-binary/tests/telemetry/mod.rs
I'm again re-usingthe configuration from tracing for the `scheduled_delay`, this one
should probably be different between traces and metrics but likely shouldn't for the
exporters. Unless we want users to copy paste the configuration twice? So well.
=> chore: Fix latency metric and reduce test sleep duration

cli/crates/backend/src/errors.rs, cli/crates/backend/src/project.rs
Sometimes a move operation is impossible due to file system limitations.
=> GB-6482: Project template extraction: Change the move operation to be a copy operation

Cargo.lock, Cargo.toml, cli/crates/cli/tests/introspection.rs, gateway/crates/gateway-binary/tests/integration_tests.rs, graphql-introspection/Cargo.toml, graphql-introspection/src/lib.rs
An API we're working with contains the following directive:
```
@deprecated(reason: "Use \"urlSite\"")
```
When we run `grafbase introspect` we take whatever output we have and run it through `apollo_encoder` to prettify it.  Unfortunately `apollo_encoder` naively makes everything a block string, leading to this output:
```
@deprecated(reason: """Use "urlSite"""")
```
Note the 4 quotes on the end there.  I don't think this is valid GraphQL, I can't see any way this should parse based on the spec.
I tried to fix this by upgrading `apollo_encoder` but it turns out it's not even a thing anymore - the functionality has been rolled up into `apollo_compiler`.  I tried using this and it does fix the issue, but the output from `apollo_compiler` isn't particularly prettified:
``` …
```
=> fix: introspect when string literal ends in a double quote

Cargo.lock, cli/crates/cli/Cargo.toml, cli/crates/cli/src/check.rs, cli/crates/cli/src/introspect.rs, cli/crates/cli/src/main.rs, cli/crates/cli/src/publish.rs
If you run grafbase check without the --schema argument, the CLI will wait for a schema from stdin, giving the impression it is hanging. Similar to what we already did for `grafbase publish`, this commit makes the CLI exit early in this situation by detecting if stdin is a tty.
Also replaces the `atty` crate in the CLI with the new `IsTerminal` trait from the standard library (thanks @obmarg for the tip).
closes GH 6494
=> cli: return early with an error on missing schema in grafbase check

Cargo.lock, gateway/CHANGELOG.md, gateway/changelog/0.2.1.md, gateway/crates/federated-server/Cargo.toml, gateway/crates/gateway-binary/Cargo.toml, gateway/crates/gateway-binary/src/args.rs
=> fix: hide access token env value from gateway help page (if set)

Cargo.lock, Cargo.toml, engine/crates/graphql-schema-diff/Cargo.toml, engine/crates/graphql-schema-diff/src/lib.rs, engine/crates/graphql-schema-diff/src/state.rs, engine/crates/graphql-schema-diff/src/traverse_schemas.rs, engine/crates/graphql-schema-diff/tests/diff/field_wrapping_type_changes.graphql, engine/crates/graphql-schema-diff/tests/diff/field_wrapping_type_changes.snapshot.json, engine/crates/graphql-schema-diff/tests/diff/schema_definition_basic.graphql
The main reason is that we are dealing with large GraphQL schemas where async-graphql-parser blows up in size and memory usage in production. cynic-parser doesn't.
The other main reason is that cynic-parser has a much nicer API and sounder foundations to build on.
closes GB-6465
=> graphql-schema-diff: replace async-graphql-parser with cynic-parser

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.68.0.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
We need to do this separately from SDK due to one test not finding the SDK which is not yet released.
Enables the CORS parsing.
=> chore(cli): bump to 0.68.0

Cargo.lock, cli/crates/federated-dev/src/dev.rs, cli/crates/federated-dev/src/dev/gateway_nanny.rs, cli/crates/gateway/src/serving.rs, engine/crates/engine-v2/Cargo.toml, engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/http_response/mod.rs, engine/crates/engine/parser/src/types/mod.rs, engine/crates/integration-tests/src/federation/builder.rs, engine/crates/integration-tests/src/federation/builder/bench.rs, engine/crates/integration-tests/tests/tracing/tower.rs, engine/crates/tracing/src/lib.rs, engine/crates/tracing/src/metrics/mod.rs, engine/crates/tracing/src/metrics/operation.rs, engine/crates/tracing/src/metrics/request.rs, engine/crates/tracing/src/otel/layer.rs, engine/crates/tracing/src/tower.rs, gateway/crates/federated-server/src/server.rs, gateway/crates/federated-server/src/server/gateway.rs, gateway/crates/federated-server/src/server/otel.rs, gateway/crates/gateway-binary/src/main.rs, gateway/crates/gateway-binary/tests/telemetry/metrics.rs, gateway/crates/gateway-binary/tests/telemetry/mod.rs
I'm refactoring the metrics removing the `tracing` integration. Now I just pass around an opentelemetry `Meter` to create the metrics, it's simpler and avoids metrics to appear in the logs.
I've also added operation metrics exposed by the engine.
=> feat: engine-v2 operation metrics

Cargo.lock, cli/crates/server/Cargo.toml, cli/crates/server/benches/parse_sdl_benchmark.rs, cli/crates/server/src/config/mod.rs, cli/crates/server/src/config/parser.rs, cli/crates/server/src/lib.rs, engine/crates/parser-sdl/src/lib.rs
Introspection of data sources gets noticeably slow once you use enough connectors that require introspection when starting `grafbase dev` (openapi, postgres, graphql). We explicitly did not introspect concurrently until now because of memory usage concerns. So the solution here is a compromise:
- No multithreading. The CPU/memory bound work will all happen in the same thread, and it will run from start to end for each connector sequentially because that work does not yield. Only the IO is somewhat more concurrent.
- `FuturesOrdered` because although the order shouldn't matter, we should keep the same deterministic behaviour we had if we can.
If we wanted to parallelize more aggressively, potential candidates would be a thread per datasource or using tokio's spawn_blocking() for CPU work, …
=> engine-v1: introspect data sources concurrently

engine/crates/parser-openapi/src/graph/mod.rs
Bit weird to see these in a spec, but ok I suppose
=> fix: add missing http methods to parser-openapi

cli/crates/server/src/config/mod.rs
We're doing validation on SDL printed from the registry in `grafbase dev`, but this wasn't printing the federation subgraph fields & directives, even when subgraph support was enabled.
This is problematic because a subgraph that defines no query fields is valid, but its schema won't be valid if you don't add the federation plumbing to it.
=> fix: federation subgraph SDL should have federation plumbing

Cargo.lock, Cargo.toml, cli/crates/federated-dev/src/dev.rs, cli/crates/gateway/src/serving.rs, engine/crates/engine-v2/Cargo.toml, engine/crates/engine-v2/axum/src/lib.rs, engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/response/mod.rs, engine/crates/engine/src/schema.rs, engine/crates/integration-tests/tests/tracing/v1.rs, engine/crates/integration-tests/tests/tracing/v2.rs, engine/crates/tracing/Cargo.toml, engine/crates/tracing/src/metrics/mod.rs, engine/crates/tracing/src/metrics/operation.rs, engine/crates/tracing/src/metrics/request.rs, engine/crates/tracing/src/otel/layer.rs, engine/crates/tracing/src/span.rs, engine/crates/tracing/src/span/gql.rs, engine/crates/tracing/src/tower.rs, gateway/crates/federated-server/Cargo.toml, gateway/crates/federated-server/src/server.rs, gateway/crates/gateway-binary/Cargo.toml, gateway/crates/gateway-binary/docker-compose.yml, gateway/crates/gateway-binary/tests/telemetry/metrics.rs, gateway/crates/gateway-binary/tests/telemetry/metrics/operation.rs, gateway/crates/gateway-binary/tests/telemetry/metrics/request.rs, gateway/crates/gateway-binary/tests/telemetry/mod.rs
Adding missing metrics to rebuild analytics
- for overall analytics graphql errors, I'm propagating back through a header whether the operation had an error or not. The tracing layer detects the presence of this header and the one after removes it. Couldn't figure out how to merge those into a single layer without going insane with the types.
- renaming `gql.request.operation.*` attributes to `gql.operation.*` because it's just shorter and also in traces for consistency
- Using a versioned meter & tracer (`1.0`) and setting traces scope to `grafbase` instead of `batch-otel` like metrics.
- Adding `normalized_query` & `normalized_query_hash` in metrics the same way we do in workers today. We can be more efficient, but it is what is for now.
=> feat: Add missing metrics for analytics

cli/crates/gateway/src/executor.rs, engine/crates/engine/src/registry/mod.rs, engine/crates/engine/src/schema.rs, engine/crates/engine/src/validation/test_harness.rs, engine/crates/integration-tests/src/engine/builder.rs, engine/crates/integration-tests/tests/tracing/v1.rs, engine/crates/parser-sdl/src/rules/visitor/context.rs
I've hacked together an in memory cache in the executor to try and share registries between concurrent requests.  This means we need to use an `Arc<Engine>` most places we currently use an `Engine`.
=> chore: put registry into an arc

engine/crates/validation/CHANGELOG.md, engine/crates/validation/src/validate/input_object_cycles.rs, engine/crates/validation/tests/validation_errors/input_object_cycles_two.errors.txt, engine/crates/validation/tests/validation_errors/input_object_cycles_two.graphql
Whenever we had a graph of input objects with multiple cycles in graphql-schema-validation, we would go into an infinite loop and stack overflow. This commit changes the function at fault to do a proper BFS.
closes GB-6570
=> graphql-schema-validation: fix stack overflow on input type cycles

Cargo.lock, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/common/src/environment.rs, cli/crates/common/src/errors.rs, cli/crates/server/src/bridge/udf.rs, cli/crates/server/src/bun.rs, cli/crates/server/src/config/mod.rs, cli/crates/server/src/errors.rs
Currently, if you start `grafbase dev` or any command that reads the configuration with configuration in a grafbase.config.ts file, on NixOS, you will see this:
```
Grafbase CLI 0.69.1
Error: could not load grafbase/grafbase.config.ts
Caused by: Could not start dynamically linked executable: /home/tom/.grafbase/bun/bun
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```
This is because the CLI downloads a bun binary from GitHub releases. That will not work on NixOS.
This commit implements the minimum version of NixOS support: use the `bun` executable from `$PATH`, and if that is missing, fail with a helpful error.
Ideally, we would want to run the exact version of bun the …
=> cli: implement minimum support for NixOS
