grafbase/grafbase

- Cargo.lock
- Cargo.toml
- cli/changelog/0.70.0.md
- cli/crates/backend/Cargo.toml
- cli/crates/cli/Cargo.toml
- cli/crates/federated-dev/Cargo.toml
- cli/crates/server/Cargo.toml
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
**Features**
- New command: `grafbase lint` to apply style rules used in schema checks (#1622)
- `grafbase deploy` now allows defining the branch (#1623)
- Added NixOS support to the CLI (#1639)
**Fixes**
- Add timeouts for graphql and http data sources (#1624)
- graphql-shema-validation: fix stack overflow on input type cycles when there was more than one cycle in connected types in the schema (#1638)
- openapi connector: more correct inferrence of nullability of input fields, fixing input type cycle errorss (#1642)
> cli: release 0.70.0

- packages/grafbase-sdk/src/grafbase-schema.ts
- packages/grafbase-sdk/src/graph.ts
- packages/grafbase-sdk/tests/unit/typeDef.test.ts
This lets users mix GraphQL SDL and SDK to their preference when defining their configuration. The idea and implementation are both very basic.
The API takes the shape of a new argument to `graph.Standalone()`:
```typescript
const g = graph.Standalone({
typeDefs: /* GraphQL */ `
type Invoice {
id: ID!
invoiceNumber: String!
dueDate: Date!
totalAmount: Int!
}
extend type Query {
invoiceByNumber(invoiceNumber: String!): Invoice @resolver(name: "invoice/byNumber")
}
`
})
```
The implementation is equally straightforward: we append the GraphQL that was passed in at the end of the generated SDL configuration.
Potential issues:
- Ordering: we have a set ordering for schema items in the SDK. Appending the string as-is will not respect it.
- Error message: it will not be clear where the error …
> sdk: add ability to pass GraphQL SDL type definitions to standalone graphs

- packages/grafbase-sdk/CHANGELOG.md
- packages/grafbase-sdk/changelog/0.22.0.md
- packages/grafbase-sdk/package.json
Features
- graph.Standalone() now optionally takes GraphQL SDL definitions to include in the configuration. See [#1645](https://github.com/grafbase/grafbase/pull/1645) for details.
> sdk: release 0.22.0

- cli/crates/typed-resolvers/src/analyze.rs
- cli/crates/typed-resolvers/src/codegen.rs
- cli/crates/typed-resolvers/tests/schema_types/interfaces.expected.ts
- cli/crates/typed-resolvers/tests/schema_types/keyword_names.expected.ts
Before this commit, codegen would generate a TS interface with the fields of the GraphQL interface. But we are generating code for resolvers, and the resolver should not return only the interface fields, but a whole object that implements the interface, including `__typename`. This commit changes the generated code to a TypeScript union of all implementers of the interface.
closes GB-5171
> typed-resolvers: implement correct codegen for interfaces

- engine/crates/runtime-local/src/fetch.rs
- engine/crates/tracing/src/metrics/operation.rs
- gateway/crates/gateway-binary/tests/telemetry/metrics/operation.rs
> chore: Add missing gql.operation.type in operation metrics

- Cargo.lock
- cli/crates/backend/src/api/branch.rs
- cli/crates/backend/src/api/create.rs
- cli/crates/backend/src/api/deploy.rs
- cli/crates/backend/src/api/errors.rs
- cli/crates/backend/src/api/graphql/api.graphql
- cli/crates/backend/src/api/graphql/types/mutations.rs
- cli/crates/backend/src/api/graphql/types/queries/deployment_poll.rs
- cli/crates/backend/src/api/graphql/types/queries/list_branches.rs
- cli/crates/backend/src/api/graphql/types/queries/mod.rs
- cli/crates/backend/src/api/mod.rs
- cli/crates/cli/Cargo.toml
- cli/crates/cli/src/branch.rs
- cli/crates/cli/src/check.rs
- cli/crates/cli/src/cli_input.rs
- cli/crates/cli/src/cli_input/branch.rs
- cli/crates/cli/src/cli_input/branch_ref.rs
- cli/crates/cli/src/cli_input/create.rs
- cli/crates/cli/src/cli_input/deploy.rs
- cli/crates/cli/src/cli_input/project_ref.rs
- cli/crates/cli/src/cli_input/sub_command.rs
- cli/crates/cli/src/create.rs
- cli/crates/cli/src/deploy.rs
- cli/crates/cli/src/errors.rs
- cli/crates/cli/src/init.rs
- cli/crates/cli/src/main.rs
- cli/crates/cli/src/output/report.rs
- cli/crates/cli/src/publish.rs
- cli/crates/cli/src/schema.rs
- cli/crates/cli/src/subgraphs.rs
Videos tell more than words here:
Creating a new graph interactively, we can now add env vars from this dialog. The deployment errors, because we can't introspect the postgres with the given connection string:
[Screencast_20240425_185634.webm](https://github.com/grafbase/grafbase/assets/34967/63f4f0c8-39b8-42bc-848c-ae6404a0b95a)
Creating a new graph with env vars directly using CLI arguments. Now it works.
[Screencast_20240425_190139.webm](https://github.com/grafbase/grafbase/assets/34967/dd395759-e1ff-410d-91f9-978a5a6267e6)
Deploying from a linked project with branch, then listing branches, deleting the `.grafbase` directory and deploying with the graph ref that does not need a linked project.
[Screencast_20240425_190251.webm](https://github.com/grafbase/grafbase/assets/34967/1e6d6868-d …
> feat: allow deleting and listing branches, allow deploying without linking

- cli/crates/cli/tests/dev_watch.rs
- cli/crates/common/src/environment.rs
- cli/crates/server/src/codegen_server.rs
- cli/crates/typed-resolvers/src/lib.rs
- engine/crates/engine/src/registry/mod.rs
- engine/crates/engine/src/registry/tests.rs
- engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__array_input_value.snap
- engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__conversion.snap
- engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__flat_output-2.snap
- engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__petstore_output-2.snap
- engine/crates/parser-sdl/src/lib.rs
- engine/crates/parser-sdl/src/rules/codegen_directive.rs
- engine/crates/parser-sdl/src/rules/experimental.rs
- engine/crates/parser-sdl/src/rules/mod.rs
- engine/crates/parser-sdl/src/rules/visitor/context.rs
- packages/grafbase-sdk/src/codegen.ts
- packages/grafbase-sdk/src/config.ts
- packages/grafbase-sdk/src/experimental.ts
- packages/grafbase-sdk/tests/unit/codegen.test.ts
This stabilization PR does two things:
- Introduce the internal `@codegen` directive to configure codegen, replacing `@experimental(codegen: true)`. The experimental flag continues working for now but it is marked as deprecated in the SDK, so it will be a visible warning in users' IDE.
- Make the path where the generated code is written configurable.
We will need a SDK release after this is merged to expose the new configuration. In practice, it looks like this:
```ts
export default config({
graph: g,
codegen: {
enabled: true,
path: 'cat/meow'
}
});
```
closes GB-6468
closes GB-5246
closes GB-5245
closes GB-5244
> Stabilize resolver type code generation (codegen experimental feature)

- packages/grafbase-sdk/CHANGELOG.md
- packages/grafbase-sdk/changelog/0.23.0.md
- packages/grafbase-sdk/package.json
Features
- The `codegen` experimental feature is stabilized. The `codegen` option can be used in this way now:
```ts
export default config({
graph: g,
codegen: {
enabled: true,
// Optional: define the directory path where you want the generated code to be written, relative to your grafbase configuration. Default: "generated".
path: 'generated',
},
})
```
Deprecations
- The `kv`, `ai` and `codegen` experimental feature options are deprecated. Codegen is stabilized, but `kv` and `ai` are being removed.
> sdk: release 0.23.0

- Cargo.lock
- Cargo.toml
- engine/crates/engine/registry-v2-generator/Cargo.toml
- engine/crates/engine/registry-v2-generator/README.md
- engine/crates/engine/registry-v2-generator/domain/registry.graphql
- engine/crates/engine/registry-v2-generator/src/exts.rs
- engine/crates/engine/registry-v2-generator/src/file.rs
- engine/crates/engine/registry-v2-generator/src/idents.rs
- engine/crates/engine/registry-v2-generator/src/main.rs
- engine/crates/engine/registry-v2-generator/src/object.rs
- engine/crates/engine/registry-v2-generator/src/object/debug.rs
- engine/crates/engine/registry-v2-generator/src/object/equal.rs
- engine/crates/engine/registry-v2-generator/src/union.rs
As outlined in [the PR that adds registy-v2][1] a lot of that crate is generated. This PR contains the generator.  It:
- Reads the data structure from a GraphQL file (SDL for life).
- Generates the records, readers and neccesary plumbing for everything to work.
- Manually implements some things that would usually be derived (i.e. `Debug` & `PartialEq`), but can't because of the patterns being used.
- Adds some serde annotations on things to make our JSON smaller.  We've used serde_as for this in the past, but why have a macro do work on every compile when you can have a generator do it once (with the bonus that it's more obvious what transforms are taking place)
This crate started as a c&p from cynic-parser and is very quick & dirty. it does what it needs to do and nothing more, it …
> feat: code generator for registry-v2

- Cargo.lock
- Cargo.toml
- engine/crates/engine/registry-upgrade/Cargo.toml
- engine/crates/engine/registry-upgrade/README.md
- engine/crates/engine/registry-upgrade/src/lib.rs
- engine/crates/engine/registry-v2/src/common/types.rs
This is a crate that takes a `registry-v1::Registry` and spits out an equivalent `registry-v2::Registry`.  This allows us to hold off updating the parsers, that all use `registry-v1` while allowing the engine to work with `registry-v2`.  It's pretty straightforward other than that.
> feat: add registry-upgrade crate

- cli/crates/common/src/environment.rs
The Linear task is about implementing that behaviour, but I think this is already what we do, from reading the code. The warning is misleading, so it got removed.
closes GB-6600
> cli: silently ignore schema.graphql when grafbase.config.ts exists

- cli/crates/server/src/bun.rs
> GB-6628 - Update Bun to 1.1.6

- Cargo.lock
- Cargo.toml
- gqlint/Cargo.toml
- gqlint/README.md
- gqlint/src/main.rs
- graphql-lint/Cargo.toml
- graphql-lint/README.md
- Adds a `gqlint` binary that runs `graphql-lint`
> GB-6512 - Add `gqlint` binary

- Cargo.lock
- engine/crates/federated-graph/src/federated_graph/v3.rs
- engine/crates/integration-tests/Cargo.toml
- engine/crates/integration-tests/src/federation/builder.rs
- engine/crates/integration-tests/src/federation/mod.rs
- engine/crates/integration-tests/tests/federation/basic/empty_config.rs
- engine/crates/integration-tests/tests/federation/basic/mod.rs
We want to clean up the empty state for federated graphs in the API. This is the state right after the federated graph is created, when no subgraph has been published yet. This commit implements an "empty" state for FederatedGraph that cleanly converts to an engine_v2::Schema, with a test to check that the engine can start with that schema.
Part of GB-6537
> engine-v2: implement and test empty schema

- engine/crates/engine/registry-upgrade/src/lib.rs
- engine/crates/engine/registry-v1/src/lib.rs
- engine/crates/engine/registry-v2/src/codegen.rs
- engine/crates/engine/registry-v2/src/lib.rs
- engine/crates/engine/registry-v2/src/writer.rs
This was added to the original Registry on friday, so porting it over to the new registry setup while I remember.
> chore: port CodegenConfig to new registry code

- Cargo.lock
- engine/crates/engine/derive/src/complex_object.rs
- engine/crates/engine/derive/src/object.rs
- engine/crates/engine/derive/src/simple_object.rs
- engine/crates/engine/registry-for-cache/src/extensions.rs
- engine/crates/engine/registry-for-cache/src/generated.rs
- engine/crates/engine/registry-for-cache/src/generated/metatype.rs
- engine/crates/engine/registry-for-cache/src/generated/others.rs
- engine/crates/engine/registry-for-cache/src/ids.rs
- engine/crates/engine/registry-for-cache/src/lib.rs
- engine/crates/engine/registry-for-cache/src/writer.rs
- engine/crates/engine/registry-upgrade/src/partial_cache_registry.rs
- engine/crates/engine/registry-v1/Cargo.toml
- engine/crates/engine/registry-v1/src/cache_pruning.rs
- engine/crates/engine/registry-v1/src/lib.rs
- engine/crates/engine/registry-v1/src/registry_impl.rs
- engine/crates/engine/registry-v2-generator/domain/registry-for-cache.graphql
- engine/crates/engine/src/registry/tests.rs
- engine/crates/engine/validation/src/registries/partial_caching_registry.rs
- engine/crates/gateway-core/src/cache/build_key.rs
- engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__array_input_value.snap
- engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__conversion.snap
- engine/crates/parser-openapi/src/output/federation.rs
- engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__flat_output-2.snap
- engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__petstore_output-2.snap
- gateway/crates/gateway-binary/tests/.integration_tests.rs.pending-snap
The caching registry was just stripping out types that didn't have a cache_config on them.  This was too simple and had some problems:
- If a field on a cached type contains e.g. `String!` then the registry is invalid as `String!` isn't a cached type and isn't included in the registry.
- If a cached type is nested inside a non-cached type then the path to that cached type won't be in the `Registry` so the visitor in `validation` won't have `current_type` info and that type won't be correctly included in the cache key in the gateway.
- Possibly other problems, but those are the main ones.
This PR fixes that: we now do a proper traversal of the type graph to make sure we include all the cached types, their cached fields, the types their cached fields point to and any intermediate types …
> fix: correctly prune the caching registry

- engine/crates/composition/src/validate.rs
- engine/crates/composition/tests/composition/requires_not_providing_required_argument/federated.graphql
- engine/crates/composition/tests/composition/requires_not_providing_required_argument/subgraphs/faulty.graphql
- engine/crates/composition/tests/composition/requires_with_arguments_validation/federated.graphql
Also an improvement in other `@requires` validations error messages (we weren't telling _which_ require was at fault).
closes GB-6319
> composition: validate that required arguments are provided in @requires selections

- Cargo.lock
- cli/crates/cli/tests/graphql-directive/transforms.rs
- cli/crates/cli/tests/openapi/main.rs
- cli/crates/gateway/src/lib.rs
- engine/crates/engine/Cargo.toml
- engine/crates/engine/registry-for-cache/src/lib.rs
- engine/crates/engine/registry-v2/src/common/iter.rs
- engine/crates/engine/registry-v2/src/lib.rs
- engine/crates/engine/scalars/src/lib.rs
- engine/crates/engine/scalars/src/simple_json.rs
- engine/crates/engine/src/registry/mod.rs
- engine/crates/engine/src/registry/tests.rs
- engine/crates/engine/src/resolver_utils/container.rs
- engine/crates/engine/validation/src/utils.rs
- engine/crates/gateway-core/src/cache/build_key.rs
- engine/crates/gateway-core/src/cache/mod.rs
- engine/crates/integration-tests/tests/postgres/introspection.rs
- engine/crates/parser-sdl/Cargo.toml
- engine/crates/parser-sdl/src/lib.rs
- engine/crates/parser-sdl/src/rules/connector_transforms/mod.rs
- engine/crates/parser-sdl/src/rules/default_directive_types.rs
- gateway/crates/gateway-binary/tests/.integration_tests.rs.pending-snap
- Some snapshot updates (because new registry does things alphabetically)
- Added SimpleJSON scalar, which postgres uses but didn't exist.
- Re-implemented validation for default values
- Fixed some incorrect binary searches
- Added a way to create an empty PartialCacheRegistry
- Some other misc things the api repo needed
> fix: the rest of the tests for new registry

- gateway/crates/federated-server/src/server.rs
- gateway/crates/federated-server/src/server/otel.rs
- gateway/crates/gateway-binary/src/main.rs
- gateway/crates/gateway-binary/tests/.integration_tests.rs.pending-snap
- gateway/crates/gateway-binary/tests/telemetry/mod.rs
Currently when the gateway is bootstrapped as follows:
1. Immediately setup OTEL metrics & tracing
2. Set up a watcher for the engine and a background task that loads GDN data to update it at regular intervals
3. Start the HTTP server
However, as we do need metadata from the GDN (branch_id typically), there is an async reload mechanism that is used to update the OTEL/tracing setup. Unfortunately, this doesn't work well for the HTTP request metrics as we need a `MeterProvider` at step 3., because it's used to setup a `tower::Layer`, even though neither the GDN call nor the OTEL reload may have happened yet.
So we need to wait for the reload mechanism to happen before starting the HTTP server. We could be lazy with the `MeterProvider`, a bit like the `tracing` integration of metrics is, but …
> fix: wait for GDN reload to happen before retrieving the meter prodiver for OTEL metrics

- packages/grafbase-sdk/src/type.ts
- packages/grafbase-sdk/tests/unit/types.test.ts
Before this commit, we show a very vague and unhelpful error from async-graphql-parser. This commit moves the error earlier on in the process when rendering SDL from SDK.
The potentially controversial bit in this PR is that I think we don't throw in any other case in that stage of the process. But better handling on the engine side is not possible without replacing async-graphql-parser.
closes GB-6604
> sdk: better error reporting for the empty object case

- Cargo.lock
- engine/crates/tracing/Cargo.toml
- engine/crates/tracing/src/config.rs
- engine/crates/tracing/src/otel/metrics.rs
- engine/crates/tracing/src/otel/traces.rs
- gateway/crates/federated-server/src/config/telemetry.rs
- gateway/crates/federated-server/src/server/graph_fetch_method.rs
- gateway/crates/gateway-binary/Cargo.toml
- gateway/crates/gateway-binary/src/args.rs
- gateway/crates/gateway-binary/src/args/lambda.rs
- gateway/crates/gateway-binary/src/args/std.rs
- gateway/crates/gateway-binary/src/main.rs
I'm hardcoding our OTEL endpoint whenever a graph reference is used. We don't fail if the token isn't present because the gateway will fail later with a better error message anyway. Using native certs ended up being as easy as just adding the right feature flag in `tonic`...
> feat: hardcode grafbase otel endpoint

- engine/crates/gateway-core/src/trusted_documents.rs
Rename to handle_trusted_document_query / handle_apq.
Move one level deeper so we only have that span when trusted documents or APQ are actually relevant for the query.
Current traces:
> gateway: move handle_persisted_query span one level deeper and rename

- Cargo.lock
- engine/crates/parser-sdl/Cargo.toml
- engine/crates/parser-sdl/src/directive_de.rs
- engine/crates/parser-sdl/src/rules/openapi_directive.rs
It's nearly as terse, and one dependency fewer.
> Replace maplit with HashMap::from([(K, V); N])

- engine/crates/parser-openapi/src/graph/operations.rs
- engine/crates/parser-openapi/src/tests/mod.rs
- engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__amadeus_schema.snap
- engine/crates/parser-openapi/test_data/amadeus.json
The OpenAPI connector only supports JSON content-types, so it looks for responses w/ `application/json` as the content-type.  But some APIs use an application specific content type such as `application/vnd.amadeus+json`.
> fix: support `application/vnd.whatever+json` in OpenAPI.

- Cargo.lock
- engine/crates/parser-openapi/Cargo.toml
- engine/crates/parser-openapi/src/parsing/v2/mod.rs
- engine/crates/parser-openapi/src/tests/mod.rs
- engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__amadeus_ratings_schema.snap
- engine/crates/parser-openapi/test_data/amadeus-ratings.json
OpenAPI lets you put a `{"$ref": "#/components/whatever"}` in a lot of places to refer to another bit of the JSON document.  The library we were using for v2 parsing didn't support these in the response map though, which a spec we're trying to use was doing.
I updated our fork to support this [here][1] and pulled it into this PR.  I also had to add support for schemas that aren't explicitly labelled with a type, which this schema is also doing.  I think is valid OpenAPI but wasn't supported by the existing code.
[1]: https://github.com/grafbase/openapi/commit/f1f45282c17d07881bb76a8ba50d1960fdf3c810
> fix: refs in v2 openapi response map

- Cargo.lock
- cli/crates/server/src/errors.rs
- cli/crates/server/src/servers.rs
- engine/crates/engine/registry-upgrade/Cargo.toml
- engine/crates/engine/registry-upgrade/src/lib.rs
- engine/crates/engine/registry-upgrade/src/partial_cache_registry.rs
- engine/crates/engine/src/registry/tests.rs
- engine/crates/engine/validation/src/test_harness.rs
- engine/crates/engine/validation/src/visitors/alias_count.rs
- engine/crates/engine/validation/src/visitors/depth.rs
- engine/crates/engine/validation/src/visitors/height.rs
- engine/crates/engine/validation/src/visitors/root_field_count.rs
- engine/crates/gateway-core/src/cache/build_key.rs
- engine/crates/integration-tests/src/engine/builder.rs
- engine/crates/integration-tests/tests/tracing/v1.rs
registry-upgrade currently panics if you pass it a registry that references a type that dopesn't exist.  The thinking here was that _ideally_ we validate schemas before we even parse them, so that we can give the users a good error message.  And then hopefully our code doesn't do anything to make the registry invalid between validation and passing it to registry-upgrade.
This was wishful thinking - I'm not sure we _do_ validate the schema, and parser-sdl (and probably the connectors) are also perfectly capable of generating bad registries.
This updates registry-upgrade to be more tolerant of these kinds of problems:
1. Where possible it'll just skip any fields with missing types.  We could raise these as errors to the user, but I think they're _usually_ a sign of a bug elsewhere - either …
> fix: make registry-upgrade more tolerant of problems

- engine/crates/parser-sdl/src/lib.rs
- engine/crates/parser-sdl/src/rules/basic_type.rs
- engine/crates/parser-sdl/src/rules/extend_connector_types.rs
- engine/crates/parser-sdl/src/rules/extend_field.rs
- engine/crates/parser-sdl/src/rules/federation/field_set.rs
- engine/crates/parser-sdl/src/rules/federation/key.rs
- engine/crates/parser-sdl/src/rules/join_directive.rs
- engine/crates/parser-sdl/src/rules/visitor/context.rs
- engine/crates/parser-sdl/src/validations.rs
I was helping Fredrik setup for a sales demo last week, and we ran into some problems with the fairly common pattern of extending types from another subgraph:
```graphql
extend type Whatever @key(fields: "id") {
id: String,
someField: String @join(...)
}
```
1. It would complain that `id` didn't have a join or custom resolver on it.
2. It'd complain that `Whatever` didn't exist for extension.
It's quite easy to work around this by removing the `extend` keyword, but we should probably be friendlier to users and just let them do this.
Fixes GB-6682
Fixes GB-6678
> fix: allow users to extend federation types

- cli/crates/backend/src/api/consts.rs
- cli/crates/backend/src/api/create.rs
- cli/crates/backend/src/api/deploy.rs
- cli/crates/backend/src/api/graphql/types/mutations.rs
- cli/crates/backend/src/api/graphql/types/queries/deployment_domains.rs
- cli/crates/backend/src/api/graphql/types/queries/mod.rs
- cli/crates/cli/src/create.rs
- cli/crates/cli/src/deploy.rs
- cli/crates/cli/src/output/report.rs
- Shows a dashboard link when creating a project
> GB-6683 - Show a link to the dashboard when running create

- engine/crates/federated-graph/src/render_sdl/render_api_sdl.rs
- engine/crates/federated-graph/src/render_sdl/render_federated_sdl.rs
They are not valid GraphQL. It's better to render an empty string, so let's do that.
closes GB-6715
> federated-graph: do not render empty types, empty enums in SDL

- cli/crates/backend/src/api/types.rs
- engine/crates/engine/src/registry/mod.rs
- rust-toolchain.toml
That was an attempt at fixing the windows CLI build in https://github.com/grafbase/grafbase/pull/1727 that I forgot to revert. This commit brings us back to the latest stable release.
> Revert rust toolchain downgrade

- Cargo.lock
- Cargo.toml
- cli/crates/gateway/Cargo.toml
- engine/crates/common-types/src/auth.rs
- engine/crates/engine/registry-for-cache/src/lib.rs
- engine/crates/gateway-core/Cargo.toml
- engine/crates/gateway-core/src/cache/mod.rs
- engine/crates/gateway-core/src/cache/partial.rs
- engine/crates/gateway-core/src/lib.rs
- engine/crates/partial-caching/Cargo.toml
- engine/crates/partial-caching/src/execution.rs
- engine/crates/partial-caching/src/fetching/keys.rs
- engine/crates/partial-caching/src/fetching/mod.rs
- engine/crates/partial-caching/src/lib.rs
- engine/crates/partial-caching/src/planning/mod.rs
- engine/crates/partial-caching/src/query_subset.rs
- engine/crates/partial-caching/tests/cache-fetching.rs
- engine/crates/partial-caching/tests/query-splitting.rs
- engine/crates/runtime/src/cache/mod.rs
This implements the logic for building cache keys out of the various cachable query partitions, along with fetching them from the cache and then determining the final query to send along to the executor.
I've introduce the notion of "phases" to the partial-caching crate - we enter a "CacheFetchPhase", represented by a struct, that exposes functions to handle all the logic of this phase.  When done you can call ".finish()" which will either move to an execution phase or some as yet unnamed final phase.
I've also started integrating this with the gateway_core crate.  This is a very broken implementation, but one that will only be called if you enable partial caching in your registry (don't do that) and you have the cargo feature flag enabled (which it is in the CLI, so that I can work on …
> feat: partial cache fetching logic

- Cargo.lock
- engine/crates/partial-caching/src/planning/mod.rs
- engine/crates/partial-caching/src/planning/variables.rs
- engine/crates/partial-caching/src/query_subset.rs
- engine/crates/partial-caching/tests/query-splitting.rs
For the sake of time I skipped figuring out which variables apply to which query partitions earlier in the week.  This revisits and fixes those.
Fixes GB-6776
> fix: support variables in partial caching

- engine/crates/composition/CHANGELOG.md
- engine/crates/composition/src/compose.rs
- engine/crates/composition/src/ingest_subgraph.rs
- engine/crates/composition/src/ingest_subgraph/fields.rs
- engine/crates/composition/src/ingest_subgraph/schema_definitions.rs
- engine/crates/composition/tests/composition/subgraph_query_fields_service_entities/api.graphql
- engine/crates/composition/tests/composition/subgraph_query_fields_service_entities/federated.graphql
- engine/crates/composition/tests/composition/subgraph_query_fields_service_entities/subgraphs/lentils.graphql
- engine/crates/composition/tests/composition/subgraph_query_fields_service_entities/subgraphs/rice.graphql
Subgraphs must expose the _entities and _service fields (and the corresponding _Entity and _Service types) in order to function as subgraphs behind the federated gateway. Depending on how you introspect them, these fields and types may end up in the subgraph SDL sent for composition. Since these fields are not part of the domain API, and they do not compose cleanly (duplicated fields and types across subgraphs), composition can and should ignore them.
This is what is implemented in this commit.
closes GB-6830
> composition: ignore subgraph federation mandated fields and types

- Cargo.lock
- Cargo.toml
- cli/CHANGELOG.md
- cli/changelog/0.74.0.md
- cli/crates/backend/Cargo.toml
- cli/crates/cli/Cargo.toml
- cli/crates/federated-dev/Cargo.toml
- cli/crates/server/Cargo.toml
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
**Fixes**
-  Ignore subgraph federation mandated fields and types in federated graph composition (#1743). This is only relevant in `grafbase dev` in federated graphs.
> cli: release 0.74.0

- cli/crates/cli/src/cli_input.rs
- cli/crates/cli/src/main.rs
- cli/crates/common/src/consts.rs
I was trying to debug partial caching yesterday but my `trace::info!` calls weren't appearing in my terminal, causing much confusion.  This turned out to be because my trace calls were in `gateway_core` which is not in the log filter that's set when you do `--trace 2`.  So, I've done a few things to fix:
1. Added a default of info to the `--trace 2` filter, to make it easier to get everything.  We have too many crates (and introduce new ones all the time) to expect this list to always be exhaustive.
2. I've added a hidden `--custom-trace-filter` argument that lets you provide a specific filter on the CLI.
3. I've added support for the `RUST_LOG` env var if neither of the CLI arguments are provided.
This made it much easier to debug my code, as I could ask for `gateway_core` traces …
> feat: tracing tweaks for CLI

- Cargo.lock
- engine/crates/partial-caching/src/planning/fragments/ancestry.rs
- engine/crates/partial-caching/src/planning/fragments/graph.rs
- engine/crates/partial-caching/src/planning/fragments/mod.rs
- engine/crates/partial-caching/src/planning/fragments/spread_set.rs
- engine/crates/partial-caching/src/planning/fragments/tracker.rs
- engine/crates/partial-caching/src/planning/mod.rs
- engine/crates/partial-caching/src/planning/query_partitioner.rs
- engine/crates/partial-caching/src/planning/variables.rs
- engine/crates/partial-caching/src/query_subset.rs
- engine/crates/partial-caching/src/updating/ser.rs
- engine/crates/partial-caching/tests/query-splitting.rs
This updates the partial caching implementation to handle propagate settings from types & settings onto their descendants.  So if a type `User` as a cache control, then all the fields inside `User` will inherit those settings.
If a field _and_ the type that field contains both have a cache control then we'll give preference to the field setting, as it's more specific.
This complicated the fragment logic a bit, as we have to propagate through a fragment spread as well - which means we potentially need to process fragments multiple times if they are spread multiple times with different inherited cache settings. So were we were before just keying fragments by their id, we're now using a `FragmentKey` - which takes the inhereted cache control value into account as well. 
Fixes GB-6777
> feat: partial cache settings propagation

- engine/crates/gateway-core/src/cache/partial.rs
- engine/crates/integration-tests/tests/tracing/cache.rs
- engine/crates/partial-caching/src/execution.rs
- engine/crates/partial-caching/src/fetching/mod.rs
- engine/crates/partial-caching/src/headers.rs
- engine/crates/partial-caching/src/hit.rs
- engine/crates/partial-caching/src/lib.rs
- engine/crates/partial-caching/src/response.rs
- engine/crates/partial-caching/tests/cache-fetching.rs
- engine/crates/partial-caching/tests/response-merging.rs
- engine/crates/partial-caching/tests/update-serialization.rs
- engine/crates/runtime-local/src/cache.rs
- engine/crates/runtime/src/cache/cached.rs
- engine/crates/runtime/src/cache/mod.rs
This updates partial caching to respect an incoming `Cache-Control` header and also provide outgoing `x-grafbase-cache` & `Cache-Control` headers.
The maxAge of a returned `Cache-Control` header is set to whatever the lowest `maxAge` of the individual partitions is. As part of this I had to update the `Entry` interface to return the current TTLof a hit, as otherwise we'd have no way to know whether that TTL is actually lower than any of the maxAge values of the freshly fetched partitions.
Fixes GB-6806
Fixes GB-6819
> fix: handle headers in partial caching

- Cargo.lock
- Cargo.toml
- cli/crates/cli/Cargo.toml
- engine/crates/runtime-local/Cargo.toml
I just released a new version of this with some small breaking changes, so doing this manually instead of waiting for renovate.
> chore: pull in graphql-ws-client 0.10.1

- Cargo.lock
- engine/crates/engine/registry-v2/src/cache_control.rs
- engine/crates/engine/validation/src/lib.rs
- engine/crates/engine/validation/src/visitors/cache_control.rs
- engine/crates/integration-tests/tests/caching/mod.rs
When demoing partial caching last week, I first showed an example of how things work with non-partial caching.  While doing this we came to the conclusion that the current behaviour is confusing: if you have 2 fields in a query `cacheMe` and `noCache` - then the query will always be cached, even though `noCache` is not marked to be cached.
This was harder to fix than you'd think.  I needed to make enough changes that I suspect caching has always behaved like this.  Or if this was a regression, it's not clear when it regressed.
To fix this:
1. If a field doesn't have a `CacheControl` we need to treat it as having the default cache control (i.e. one with `maxAge: 0`).
2. I needed to update the `CacheControl::merge` function to not ignore `maxAge: 0`.  Previously if one of the cache controls …
> fix: non-partial caching behaviour

- Cargo.lock
- engine/crates/engine/registry-v1/src/types.rs
- engine/crates/integration-tests/tests/execution/interfaces.rs
- engine/crates/integration-tests/tests/execution/mod.rs
- engine/crates/integration-tests/tests/execution/unions.rs
- engine/crates/parser-sdl/src/lib.rs
- engine/crates/parser-sdl/src/rules/mod.rs
- engine/crates/parser-sdl/src/rules/union.rs
For a while grafbase didn't support unions, because our execution was based around our old database feature and we hadn't built support for unions into that.  That changed when we added our OpenAPI & GraphQL connectors though - both of those connectors make use of union types, so execution needed to support union types.
However, we didn't come back and allow users to add unions into their schemas when doing this - they're only supported via one of the connectors.
A user on discord is trying to use unions now and is running into this limitation.
This PR updates parser-sdl to pull in unions, solving this problem.  It does not add support for them to the SDK for now - if we want that it'll need to be a separate PR.
> feat: support unions in SDL

- Cargo.lock
- engine/crates/engine/registry-v1/src/types.rs
- engine/crates/engine/src/registry/resolvers/postgres/context/filter/complex.rs
- engine/crates/integration-tests/tests/postgres/find_many.rs
- engine/crates/integration-tests/tests/postgres/introspection.rs
- engine/crates/parser-postgres/Cargo.toml
- engine/crates/parser-postgres/src/registry/context/output.rs
- engine/crates/parser-postgres/src/registry/types/scalar.rs
It produces a `LIKE` clause (https://www.postgresql.org/docs/current/functions-matching.html).
The feature request was for a `contains` filter, but:
1. The `contains` name is already used for the array membership filter
2. "like" better matches database terminology
3. LIKE is more powerful. It can also serve as `startsWith`, `endsWith`, ...
closes GB-6869
> postgres connector: implement "like" filter

- cli/crates/gateway/Cargo.toml
- cli/crates/gateway/src/executor.rs
- engine/crates/integration-tests/src/engine_v1/builder.rs
- engine/crates/postgres-connector-types/src/transport/tcp/pooled.rs
- engine/crates/runtime-local/src/pg.rs
- flake.nix
This is a problem as soon as concurrent requests are involved.
We defer the size of the pool to the pooling library (deadpool). It defaults to  cpu_count * 4 ([source](https://docs.rs/deadpool/latest/deadpool/managed/struct.PoolConfig.html#structfield.max_size)).
closes GB-6874
> grafbase start: use a postgres connection pool instead of a single connection

- Cargo.lock
- Cargo.toml
- cli/CHANGELOG.md
- cli/changelog/0.75.0.md
- cli/crates/backend/Cargo.toml
- cli/crates/cli/Cargo.toml
- cli/crates/federated-dev/Cargo.toml
- cli/crates/server/Cargo.toml
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
Features
- You can now filter on text columns with the LIKE operator on the postgres connector (https://www.postgresql.org/docs/current/functions-matching.html). #1764
- The postgres connector now uses a connection pool instead of a single connection in `grafbase start`. #1771
- The postgres connector now supports multiple relations between two tables. See the pull request (https://github.com/grafbase/grafbase/pull/1770) for an example.
- Fixed a bug with enum values sent to subgraphs in `grafbase dev` for federated graphs. #1766
- Expand the scope of files watched for changes in `grafbase dev`. #1774
> cli: release 0.75.0

- .dockerignore
- .github/actions/test/action.yml
- .github/workflows/binaries.yml
- Cargo.lock
- Cargo.toml
- Dockerfile
- cli/Dockerfile
- cli/crates/common/src/environment.rs
- cli/crates/docker-tests/Cargo.toml
- cli/crates/docker-tests/README.md
- cli/crates/docker-tests/src/lib.rs
- cli/crates/docker-tests/tests/docker_tests.rs
- cli/crates/docker-tests/tests/resolvers/hello_world.rs
- cli/crates/docker-tests/tests/resolvers/mod.rs
- cli/crates/server/src/bridge/udf.rs
- cli/crates/server/src/bun.rs
- cli/crates/server/src/config/mod.rs
- cli/crates/server/src/udf_builder.rs
- cli/docker-entrypoint.sh
- cli/nix/wrappers.nix
A user had trouble setting up a docker image with Grafbase, so I thought I would just revive an older docker PR and add a simple sanity check test. I didn't realize how much time I would spend on it 😅 
It took me an absurd amount of time to have a working docker image because of permissions issues, missing assets, and just incredibly slow build times. What I expect to be the linking stage still stakes forever in Docker in release, but I improved as much as I reasonably could the Dockerfile by using a separate step for building dependencies and using https://github.com/LukeMathWalker/cargo-chef. Unfortunately, limiting the preparation step to a single binary didn't work,  but it still avoids dependency download and some of the compilations. A bunch of those are recompiled likely because of …
> chore: Add cli docker image

- Cargo.lock
- engine/crates/partial-caching/src/fetching/keys.rs
- engine/crates/partial-caching/src/lib.rs
- engine/crates/partial-caching/src/query_subset.rs
- engine/crates/partial-caching/src/query_subset/display.rs
- engine/crates/partial-caching/src/query_subset/field_iter.rs
- engine/crates/partial-caching/src/query_subset/mod.rs
- engine/crates/partial-caching/src/updating/ser.rs
Splitting out some reorganisation from my defer work so it's easier to review.
There's no functional changes here, so should be fairly easy to review.
- Moved query_subset to a folder
- Split it up a bit
- Moved FieldIter into the query_subset module so it can be shared in a few places.
> chore: reorg some partial caching stuff

- engine/crates/partial-caching/src/lib.rs
- engine/crates/partial-caching/src/output/mod.rs
- engine/crates/partial-caching/src/output/shapes/building.rs
- engine/crates/partial-caching/src/output/shapes/fragment_iter.rs
- engine/crates/partial-caching/src/output/shapes/mod.rs
- engine/crates/partial-caching/src/parser_extensions.rs
I'm adding support for `@defer` to our partial caching.  When handling responses & cache entries in the presence of `@defer` we need to be able to tell whether or not the field we're currently processing is inside a `@defer` or not.
This sounds simple but has a lot of complicating factors:
1. The JSON structure of responses & cache chunks doesn't always match the GraphQL AST structure.  Fragments add an additional level of nested to the AST, but not to the JSON.
2. Type conditions on fragments add branching into the equation.
3. A given field of an object could theoretically be present both inside and outside a defer, with the difference between those selections being nested several levels deep in the GraphQL AST.
At present most of the partial caching response handling is a fairly simple …
> feat: calculate output shapes in partial caching

- engine/crates/graph-entities/src/response/mod.rs
- engine/crates/partial-caching/src/output/engine_response.rs
- engine/crates/partial-caching/src/output/mod.rs
- engine/crates/partial-caching/src/output/ser.rs
- engine/crates/partial-caching/src/output/shapes/building.rs
- engine/crates/partial-caching/src/output/shapes/mod.rs
- engine/crates/partial-caching/src/output/store.rs
- engine/crates/partial-caching/src/output/tests.rs
- engine/crates/partial-caching/src/updating/ser.rs
Adding defer support to partial caching is going to mean keeping response values around in memory for a while.  We can't write to the cache until the full request is finished, so we need to keep the initial response and all it's deferred chunks in memory until the request is finished, when we can write the whole thing into the cache.
Because of this, I want to keep the memory footprint of this data small.  This PR contains an `OutputStore` type that I'll use to store the output, code for writing a QueryResponse into this structure, and a quick sanity test to make sure it works.
There's a lot of todos in this PR, which I'll come back to later.
Part of GB-6940
> feat: add OutputStore to partial-caching

- engine/crates/partial-caching/src/output/engine_response.rs
- engine/crates/partial-caching/src/output/mod.rs
- engine/crates/partial-caching/src/output/shapes/building.rs
- engine/crates/partial-caching/src/output/shapes/fragment_iter.rs
- engine/crates/partial-caching/src/output/shapes/mod.rs
- engine/crates/partial-caching/src/output/tests.rs
In #1786 I started calculating the shape of output for partial-caching, which we can use to tell whether or not we're inside a defer when traversing some JSON.
In #1791 I added an "OutputStore" that ties into this, which stores objects something like this:
```
struct Object {
shape_id: ObjectShapeId,
fields: Vec<Value>
}
```
This saves having to store the keys of objects alongside the data, as you can just grab them from the associated shape.
The problem is, in #1786 I was building up multiple shape heirarchies - one for each partition of the query.  So when it comes time to merge those partitions together there's no single object shape that has all the fields we need an object to have.  Oops.
This PR fixes that by generating a single heirarchy for the entire query.  This is also simpler, …
> fix: a single shape hierarchy per query in partial-caching

- engine/crates/engine-v2/axum/src/websocket/accepter.rs
- engine/crates/engine-v2/src/engine.rs
- engine/crates/integration-tests/src/federation/builder/user_hooks.rs
- engine/crates/integration-tests/tests/federation/user_hooks.rs
- engine/crates/runtime-local/src/user_hooks.rs
- engine/crates/runtime-noop/src/user_hooks.rs
- engine/crates/runtime/src/user_hooks.rs
- engine/crates/wasi-component-loader/examples/crates/dir_access/src/bindings.rs
- engine/crates/wasi-component-loader/examples/crates/dir_access/src/lib.rs
- engine/crates/wasi-component-loader/examples/crates/error/src/bindings.rs
- engine/crates/wasi-component-loader/examples/crates/error/src/lib.rs
- engine/crates/wasi-component-loader/examples/crates/missing_callback/src/bindings.rs
- engine/crates/wasi-component-loader/examples/crates/missing_callback/src/lib.rs
- engine/crates/wasi-component-loader/examples/crates/missing_callback/wit/world.wit
- engine/crates/wasi-component-loader/examples/crates/networking/src/bindings.rs
- engine/crates/wasi-component-loader/examples/crates/networking/src/lib.rs
- engine/crates/wasi-component-loader/examples/crates/simple/src/bindings.rs
- engine/crates/wasi-component-loader/examples/crates/simple/src/lib.rs
- engine/crates/wasi-component-loader/examples/wit/world.wit
- engine/crates/wasi-component-loader/src/callbacks/gateway.rs
- engine/crates/wasi-component-loader/src/context.rs
- engine/crates/wasi-component-loader/src/lib.rs
- engine/crates/wasi-component-loader/src/names.rs
- engine/crates/wasi-component-loader/src/tests.rs
We need a context object for the full request lifecycle which can be used for storing and retrieving data in the engine hooks. The issue is that we need to pass it by-value, and the request metadata is either passed by reference or as an Arc. So, to plan for that, we store the context data in a mutex. Yes, I know, but this data is always per-request, meaning the locks will not block other requests anyhow. In the upcoming hooks, we need to lock the mutex, get a mutable reference to the context object, use some `std::mem` tricks to get a value out of it and again return the possible changes to the request metadata.
Or, all the calls need to have a mutable reference to the metadata struct (which will be annoying in the websocket code)...
Closes: GB-6958
> feat: passable context object for hooks

- engine/crates/partial-caching/src/output/cache_merging.rs
- engine/crates/partial-caching/src/output/engine_response.rs
- engine/crates/partial-caching/src/output/mod.rs
- engine/crates/partial-caching/src/output/shapes/mod.rs
- engine/crates/partial-caching/src/output/store.rs
- engine/crates/partial-caching/src/output/tests.rs
#1791 added an `OutputStore` and some code to write the initial response from the engine into that.  This PR handles merge cache response into the OutputStore.  This is a bit more involved than the initial response, because we need to be careful not to add any deferred fields into the response, and instead save them for when the deferred chunks come in.
Still a bunch of TODOs in here.  Will revisit these later though.
Fixes GB-6940
> feat: merge partial cache entries into initial response

- engine/crates/engine-v2/schema/src/builder/coerce/mod.rs
- engine/crates/engine-v2/schema/src/builder/graph.rs
- engine/crates/engine-v2/schema/src/builder/mod.rs
- engine/crates/engine-v2/schema/src/builder/requires.rs
- engine/crates/engine-v2/schema/src/ids.rs
- engine/crates/engine-v2/schema/src/input_value/mod.rs
- engine/crates/engine-v2/schema/src/lib.rs
- engine/crates/engine-v2/schema/src/requires.rs
- engine/crates/engine-v2/schema/src/walkers/requires.rs
- engine/crates/engine-v2/src/operation/bind/mod.rs
- engine/crates/engine-v2/src/operation/bind/variables.rs
- engine/crates/engine-v2/src/operation/build.rs
- engine/crates/engine-v2/src/operation/input_value/query/mod.rs
- engine/crates/engine-v2/src/operation/input_value/variable/mod.rs
- engine/crates/engine-v2/src/operation/variables.rs
- engine/crates/engine-v2/src/operation/walkers/argument.rs
- engine/crates/engine-v2/src/operation/walkers/field.rs
- engine/crates/engine-v2/src/operation/walkers/variable.rs
- engine/crates/engine-v2/src/plan/planning/boundary.rs
- engine/crates/engine-v2/src/plan/planning/planner.rs
In a next PR I'll need required field to be deduplicated, before I only
deduplicated arguments, not the full field itself. This makes it a lot
easier to track requirements later.
I'm also adding a `Unavailable` case for variables, planning will be
done without variables to be cache-able. This can lead us to add extra
fields which aren't actually required for some variables, but that's
something to optimize for later.
I've fixed what would definitely be bugs in field comparison between
required ones and operation ones. I was assuming a specific ordering
of input values at various places that wasn't guaranteed. I really
need to add tests for this...
> chore(engine-v2): Refactor required fields

- engine/crates/integration-tests/src/engine_v1/builder.rs
- engine/crates/integration-tests/src/engine_v1/gateway.rs
- engine/crates/integration-tests/tests/tracing/v1.rs
I was trying to integration test partial caching, but the partial cache registry inside the tests always had partial caching disabled, no matter what I put into my schema. This turned out to be because it was always hardcoded to empty.  
This PR fixes that - instead of constructing a GatewayBuilder directly we construct it from the EngineBuilder, which allows us to pass through the correct partial caching registry.
> fix: provide GatewayBuilder with an actual partial_cache_registry

- engine/crates/composition/CHANGELOG.md
- engine/crates/composition/src/compose/entity_interface.rs
- engine/crates/composition/src/compose/interface.rs
- engine/crates/composition/src/compose/object.rs
- engine/crates/composition/src/composition_ir.rs
- engine/crates/composition/src/emit_federated_graph.rs
- engine/crates/composition/src/emit_federated_graph/attach_argument_selection.rs
- engine/crates/composition/src/ingest_subgraph.rs
- engine/crates/composition/src/ingest_subgraph/directives.rs
- engine/crates/composition/src/ingest_subgraph/directives/authorized.rs
- engine/crates/composition/src/ingest_subgraph/directives/consts.rs
- engine/crates/composition/src/ingest_subgraph/enums.rs
- engine/crates/composition/src/ingest_subgraph/fields.rs
- engine/crates/composition/src/subgraphs/directives.rs
- engine/crates/composition/src/validate.rs
- engine/crates/composition/src/validate/input_selection.rs
- engine/crates/composition/tests/composition/authorized_basic/api.graphql
- engine/crates/composition/tests/composition/authorized_basic/federated.graphql
- engine/crates/composition/tests/composition/authorized_basic/subgraphs/bank_account.graphql
- engine/crates/composition/tests/composition/authorized_validation/federated.graphql
- engine/crates/composition/tests/composition/authorized_validation/subgraphs/bank_account.graphql
- engine/crates/composition/tests/composition/requiresScopes_basic/api.graphql
- engine/crates/composition/tests/composition_tests.rs
- engine/crates/federated-graph/src/federated_graph/v1.rs
- engine/crates/federated-graph/src/federated_graph/v3.rs
- engine/crates/federated-graph/src/from_sdl.rs
- engine/crates/federated-graph/src/render_sdl/display_utils.rs
- engine/crates/federated-graph/src/render_sdl/render_federated_sdl.rs
This is a first version to unblock progress on further implementation.
Missing:
- Some validation on selections (nested selections on arguments and fields)
- Validation of metadata
- https://github.com/Authorized on objects, interfaces and fields of interfaces
That should already be captured in issues if I haven't forgotten anything.
closes gb-6961
> composition: implement @authorized

- engine/crates/engine-v2/schema/src/builder/graph.rs
- engine/crates/engine-v2/schema/src/builder/mod.rs
- engine/crates/engine-v2/schema/src/lib.rs
- engine/crates/engine-v2/schema/src/sources/introspection.rs
- engine/crates/engine-v2/schema/src/walkers/field.rs
- engine/crates/engine-v2/src/operation/selection_set.rs
- engine/crates/engine-v2/src/plan/collected.rs
- engine/crates/engine-v2/src/plan/flat.rs
- engine/crates/engine-v2/src/plan/mod.rs
- engine/crates/engine-v2/src/plan/planning/boundary.rs
- engine/crates/engine-v2/src/plan/planning/collect.rs
- engine/crates/engine-v2/src/plan/planning/planner.rs
- engine/crates/engine-v2/src/plan/state.rs
- engine/crates/engine-v2/src/plan/walkers/mod.rs
- engine/crates/engine-v2/src/response/write/deserialize/mod.rs
- engine/crates/engine-v2/src/sources/graphql/federation.rs
The current implementation wasn't handling properly requires within a
plan, it would have tried to create a new plan with resolvers that don't
exist if the fields were only providable by the current subgraph. This
will only happen with directives like `@authorized` which isn't tied to
subgraph boundaries.
The initial goal of this PR was to simplify the flatten of selection
sets I'm relying on during planning. It had complex logic to deal with
chains of type conditions, but it's actually irrelevant. Type conditions
are only useful to construct an appropriate query. Once we've identified
the field definitions, they will present if the response object matches
the field parent entity (object/interface).
Fixes: GB-6977
> chore(engine-v2): Simplify FlatSelectionSet + fix requires within plan

- engine/crates/engine-v2/src/execution/coordinator.rs
- engine/crates/engine-v2/src/operation/bind/mod.rs
- engine/crates/engine-v2/src/operation/ids.rs
- engine/crates/engine-v2/src/operation/mod.rs
- engine/crates/engine-v2/src/operation/path.rs
- engine/crates/engine-v2/src/operation/walkers/field.rs
- engine/crates/engine-v2/src/plan/collected.rs
- engine/crates/engine-v2/src/plan/ids.rs
- engine/crates/engine-v2/src/plan/mod.rs
- engine/crates/engine-v2/src/plan/planning/boundary.rs
- engine/crates/engine-v2/src/plan/planning/collect.rs
- engine/crates/engine-v2/src/plan/planning/planner.rs
- engine/crates/engine-v2/src/plan/state.rs
- engine/crates/engine-v2/src/plan/walkers/mod.rs
- engine/crates/engine-v2/src/plan/walkers/selection_set.rs
- engine/crates/engine-v2/src/response/read/mod.rs
- engine/crates/engine-v2/src/response/read/view.rs
- engine/crates/engine-v2/src/response/write/deserialize/selection_set/collected.rs
- engine/crates/engine-v2/src/response/write/mod.rs
To read the necessary input for children plan we keep track of the
root response objects for those. This avoids the need to traverse the
response graph with complex logic. As we would only track those at plan
boundaries the term "plan boundary" objects, refs, items etc. were used.
Now with features like `@authenticated` we'll need to track response
objects at various places. The immediate need was to be able to identify
which extra fields were added for a `@authenticated` requirements to
avoid retrieving those if access was denied. Those extra field would be
retrieved through the tuple `(PlanBoundaryId, RequiredFieldId)`, now
it's `(EntityLocation, RequiredFieldId)` making it work even outside
plan boundaries.
Fixes: GB-6978
> chore(engine-v2): Replace plan boundaries by entity locations

- engine/crates/composition/src/emit_federated_graph.rs
- engine/crates/composition/src/ingest_subgraph/directives/authorized.rs
- engine/crates/composition/src/subgraphs/directives.rs
- engine/crates/federated-graph/src/federated_graph/v3.rs
- engine/crates/federated-graph/src/render_sdl/render_federated_sdl.rs
We previously expected a serialized JSON string.
closes GB-6993
> composition: make metadata field on `@authorized` an arbitrary value

- engine/crates/gateway-core/src/lib.rs
- engine/crates/integration-tests/Cargo.toml
- engine/crates/integration-tests/src/engine_v1/gateway.rs
- engine/crates/integration-tests/src/udfs.rs
- engine/crates/integration-tests/tests/caching/mod.rs
- engine/crates/integration-tests/tests/caching/partial_caching_defer.rs
- engine/crates/partial-caching/src/output/cache_merging.rs
- engine/crates/partial-caching/src/output/store.rs
This adds a very simple integration test of partial caching w/ defer.  Had to add support for streaming requests to the gateway testing infra for this, but nothing too complicated.
This is just a really simple test - I don't want to do anything more in-depth, because I know there's a lot of broken things, and I want to get the transport code written for the demo first.  I've made a linear issue to ensure I revisit once more things are working.
> test: basic integration test of partial caching

- engine/crates/engine/response/src/cache_control.rs
I changed the CacheControl struct that's being used as part of caching.  I did not notice that the old one has skip serializing defaults on it, so the new struct is potentially incompatible with the old one.
> fix: defaults on CacheControl

- cli/crates/server/src/bun.rs
We already had the error ("Could not find a `bun` executable in PATH. Bun is required in order to evaluate your TypeScript configuration. Please install `bun` or run `nix shell nixpkgs#bun`."), so this is a short fix.
closes GB-7005
> cli: error early when we fail to find bun on NixOS

- engine/crates/gateway-core/src/cache/partial.rs
- engine/crates/graph-entities/src/response/mod.rs
- engine/crates/integration-tests/tests/caching/partial_caching_defer.rs
- engine/crates/partial-caching/src/execution/defer.rs
- engine/crates/partial-caching/src/execution/mod.rs
- engine/crates/partial-caching/src/lib.rs
- engine/crates/partial-caching/src/output/cache_merging.rs
- engine/crates/partial-caching/src/output/engine_response.rs
- engine/crates/partial-caching/src/output/incremental_merging.rs
- engine/crates/partial-caching/src/output/mod.rs
- engine/crates/partial-caching/src/output/shapes/building.rs
- engine/crates/partial-caching/src/output/shapes/mod.rs
- engine/crates/partial-caching/src/output/store.rs
- engine/crates/partial-caching/src/output/tests.rs
- engine/crates/partial-caching/src/parser_extensions.rs
- engine/crates/partial-caching/src/planning/defers.rs
- engine/crates/partial-caching/src/planning/mod.rs
- engine/crates/partial-caching/src/query_subset/mod.rs
While writing the partial caching defer support, I made the assumpption that defers always have labels.  That was incorrect, they can be unlabelled.
This updates the code to account for that: instead of using the defer label to refer to defers we parse them out as part of the planning phase, assign them ids and then use those ids to refer to them.
One place this got complicated is when we receive deferred payloads for a defer without a label: we need to figure out which defer it's referring to based on the path.  This is relatively easy if there's only one defer inside an object, but gets complicated if there's more than one.  Managed it in the end though.
Fixes GB-6981
> fix: support defers without labels in partial caching

- engine/crates/engine-v2/src/execution/coordinator.rs
- engine/crates/engine-v2/src/operation/bind/mod.rs
- engine/crates/engine-v2/src/operation/mod.rs
- engine/crates/engine-v2/src/plan/mod.rs
- engine/crates/engine-v2/src/plan/planning/collect.rs
- engine/crates/engine-v2/src/response/write/mod.rs
- engine/crates/integration-tests/benches/federation.rs
- engine/crates/integration-tests/src/federation/builder/bench.rs
- engine/crates/integration-tests/tests/federation/basic/errors.rs
- engine/crates/integration-tests/tests/federation/hooks/authorize_node_pre_execution.rs
Ugly commit, but works.
`@authorized` directive on a root type (Query, Mutation, etc..) wouldn't be taken into account as they no field within the query.
So adding a root condition, if it fails it populates errors that will be immediately used to generate a response. Reworked a bit the no IO/deterministic test utilities but they're not great yet.
> fix(engine-v2): Properly handle authorize nodes on root types

- cli/crates/backend/src/api/graphql/types/queries/fetch_federated_graph_schema.rs
- cli/crates/backend/src/api/schema.rs
The `grafbase schema` command returns the API schema for federated graphs, but that can already be fetched with `grafbase introspect`.
This commit:
- Makes it return the federated SDL for federated graphs
- Makes it work with graph refs that don't contain a branch (it then defaults to the graph's production branch)
Alternatively, we could add a flag to return either api schema or federated sdl.
closes GB-7015
> cli: make grafbase schema return federated SDL

- engine/crates/wasi-component-loader/examples/crates/authorization/src/bindings.rs
- engine/crates/wasi-component-loader/examples/crates/authorization/src/lib.rs
- engine/crates/wasi-component-loader/examples/crates/authorization/wit/world.wit
- engine/crates/wasi-component-loader/examples/crates/dir_access/src/bindings.rs
- engine/crates/wasi-component-loader/examples/crates/dir_access/src/lib.rs
- engine/crates/wasi-component-loader/examples/crates/error/src/bindings.rs
- engine/crates/wasi-component-loader/examples/crates/error/src/lib.rs
- engine/crates/wasi-component-loader/examples/crates/missing_hook/src/bindings.rs
- engine/crates/wasi-component-loader/examples/crates/missing_hook/src/lib.rs
- engine/crates/wasi-component-loader/examples/crates/missing_hook/wit/world.wit
- engine/crates/wasi-component-loader/examples/crates/networking/src/bindings.rs
- engine/crates/wasi-component-loader/examples/crates/networking/src/lib.rs
- engine/crates/wasi-component-loader/examples/crates/simple/src/bindings.rs
- engine/crates/wasi-component-loader/examples/crates/simple/src/lib.rs
- engine/crates/wasi-component-loader/examples/wit/world.wit
- engine/crates/wasi-component-loader/gateway-hooks.wit
- engine/crates/wasi-component-loader/src/error.rs
- engine/crates/wasi-component-loader/src/error/guest.rs
- engine/crates/wasi-component-loader/src/lib.rs
- engine/crates/wasi-component-loader/src/tests.rs
A small rename, the error-response type should be just error for the user-facing parts of the hooks.
> chore(wasi): rename error-response to error

- cli/about.toml
That currently is blocking the release on `cargo about` because they aren't in our allowlist (see https://github.com/grafbase/grafbase/actions/runs/9765727643).
Both permissive open source, so that shouldn't be a problem.
> Add licenses used by wasmtime to allowed licenses

- flake.nix
- gateway/nix/grafbase-gateway.nix
Allows building grafbase-gateway through nix.
```bash
nix build .#grafbase-gateway
```
> feat(nix): build script for grafbase-gateway

- Cargo.lock
- gateway/CHANGELOG.md
- gateway/changelog/0.4.0.md
- gateway/crates/federated-server/Cargo.toml
- gateway/crates/gateway-binary/Cargo.toml
- Custom hooks with WebAssembly components ([docs](https://grafbase.com/docs/self-hosted-gateway/hooks))
- Support for `@authorized` directive ([docs](https://grafbase.com/docs/federation/federation-directives#authorized))
- Automatically generate an operation name from the first query field in OTEL traces & metrics if none was provided
- Proper error propagation of authenticated & requiresScopes (#1813)
> chore: bump gateway to 0.4.0

- engine/crates/wasi-component-loader/src/lib.rs
This fixes weird libunwind asserts.
Closes: GB-7032
> fix: disable wasm native unwind info

- .github/workflows/binaries.yml
- Cargo.lock
- engine/crates/wasi-component-loader/Cargo.toml
https://github.com/bytecodealliance/wasmtime/releases/tag/v22.0.0
This release has a regression preventing linking if compiling against musl. I bisected and found the issue in wasmtime that caused this. What we do here is we remove the three lines in wasmtime build.rs which link against libm, and we have a working build.
Context: https://github.com/bytecodealliance/wasmtime/issues/8898
Changes against wasmtime 22: https://github.com/grafbase/wasmtime/commit/e55186fe62b56ceb5a168a79ecd773dea6bdcca6
Closes: GB-7038
> chore: update wasmtime crates to 22.0.0

- engine/crates/engine/registry-for-cache/src/ids.rs
- engine/crates/engine/registry-for-cache/src/lib.rs
- engine/crates/engine/registry-for-cache/src/type_relations.rs
- engine/crates/engine/registry-for-cache/src/writer.rs
- engine/crates/engine/registry-upgrade/src/partial_cache_registry.rs
- engine/crates/parser-sdl/src/rules/interface.rs
Partial caching needs to know the relationships between types in order to handle type conditions correctly.  This is essential for us to support APIs that use unions or interfaces.
This PR is pretty simple: it just adds those details into the PartialCacheRegistry (which I have realised is named somewhat ambiguously - it's a partial registry for caching, not a registry for partial caching.  May need to fix that sometime).
I am very aware that this could bump up the size of the caching registry a bit, and therefore slow down cache responses.  I have tried to minimise that as much as possible though.  It's structured as a map of `StringId -> IdRange<SupertypeId>`, where `SupertypeId` is an index into a separate Vec.  Using this separate Vec allows us to deduplicate things a bit - if we have …
> chore: add supertype info to partial caching registry

- Cargo.lock
- engine/crates/engine-v2/schema/Cargo.toml
- engine/crates/engine-v2/schema/src/lib.rs
- engine/crates/engine-v2/schema/tests/conversion.rs
- engine/crates/engine-v2/src/engine/cache.rs
- examples/gateway-hooks/flake.lock
The engine caches will panic if engine is not compiled from a git environment. E.g. if using nix, which does not want any git files in its build environment. This patch uses the build timestamp as an identifier if git hash is not available.
> fix: use timestamp for cache identifier if git hash is not available

- engine/crates/integration-tests/tests/partial_caching/type_conditions.rs
- engine/crates/partial-caching/src/execution/defer.rs
- engine/crates/partial-caching/src/output/cache_merging.rs
- engine/crates/partial-caching/src/output/response_merging.rs
- engine/crates/partial-caching/src/output/ser.rs
- engine/crates/partial-caching/src/output/store.rs
When partial caching encounters a type condition, it will add a `__typename` field into the query if one is not already present.  These `__typenames` are not written into the `OutputStore` as actual `__typename` fields, so don't currently get written to the cache.  But this means when we read from the cache we don't know which type that object is meant to be.
This commit fixes that by storing the typename in a new `typename` field on the `Object`.  We intern these to save on space, and only write them if the query doesn't have a user provided `__typename` on it.
Now that this is in place I've updated the associated tests to hit the cache and make sure that works.
Fixes GB-7037
> fix: write typename to partial caches

- engine/crates/composition/src/compose/context.rs
- engine/crates/composition/src/compose/entity_interface.rs
- engine/crates/composition/src/compose/interface.rs
- engine/crates/composition/src/composition_ir.rs
- engine/crates/composition/src/emit_federated_graph.rs
- engine/crates/composition/tests/composition/authorized_basic/api.graphql
- engine/crates/composition/tests/composition/authorized_basic/federated.graphql
- engine/crates/composition/tests/composition/authorized_basic/subgraphs/bank_account.graphql
- engine/crates/federated-graph/src/federated_graph/v3.rs
- engine/crates/federated-graph/src/from_sdl.rs
- engine/crates/federated-graph/src/render_sdl/render_federated_sdl.rs
- On the interface itself
- On the fields of the interface
- On entity interfaces and their fields
We should be at parity with objects now.
closes GB-6968
> composition: compose @authorized on interfaces

- engine/crates/engine-v2/src/operation/bind/mod.rs
- engine/crates/engine-v2/src/operation/bind/validation.rs
- engine/crates/engine-v2/src/operation/validation/operation_limits.rs
- engine/crates/engine-v2/src/operation/walkers/field.rs
In a further commit checking for fragment cycles is pretty hard, so
doing it just after parsing in a separate step now. I've also moved
all operation limits check that could be verified at this step (all but
height).
> chore(engine-v2): Early validation of parsed operation

- engine/crates/engine-v2/src/lib.rs
- engine/crates/engine-v2/src/operation/bind/field.rs
- engine/crates/engine-v2/src/operation/bind/mod.rs
- engine/crates/engine-v2/src/operation/build.rs
- engine/crates/engine-v2/src/operation/ids.rs
- engine/crates/engine-v2/src/operation/logical_planner/logic.rs
- engine/crates/engine-v2/src/operation/logical_planner/mod.rs
- engine/crates/engine-v2/src/operation/logical_planner/selection_set.rs
- engine/crates/engine-v2/src/operation/mod.rs
- engine/crates/engine-v2/src/operation/walkers/field.rs
- engine/crates/engine-v2/src/plan/mod.rs
- engine/crates/engine-v2/src/plan/planning/collect.rs
- engine/crates/engine-v2/src/plan/planning/mod.rs
- engine/crates/engine-v2/src/plan/walkers/field.rs
- engine/crates/integration-tests/tests/federation/basic/errors.rs
I'm not super happy with the name, but I find `Plan` and
`ExecutionPlan` is too ambiguous in some places. Couldn't find
a better name than that.
> chore(engine-v2): Move "logical planning" to operation module.

- engine/crates/integration-tests/tests/partial_caching/defer.rs
- engine/crates/partial-caching/src/execution/defer.rs
- engine/crates/partial-caching/src/lib.rs
- engine/crates/partial-caching/src/planning/defers.rs
- engine/crates/partial-caching/src/planning/mod.rs
- engine/crates/partial-caching/src/query_subset/mod.rs
When testing defer on production, I saw some weird behaviour: sometimes a cached defer would not return some of the fields.
This turned out to be because I'd forgotten to account for the case where a defer is served entirely from the cache and doesn't make it as far as the query we send to the executor.
Easy to fix though: just need to check which defers aren't in the executor partition and then count those amongst the active defers when doing the initial cache merge.
> fix: defer served entirely from partial cache

- engine/crates/engine-v2/src/engine.rs
- engine/crates/engine-v2/src/sources/graphql/federation.rs
- engine/crates/engine-v2/src/sources/graphql/mod.rs
- engine/crates/engine/src/schema.rs
- engine/crates/gateway-core/src/lib.rs
- engine/crates/integration-tests/tests/tracing/v1.rs
- engine/crates/integration-tests/tests/tracing/v2.rs
- engine/crates/tracing/src/span.rs
- engine/crates/tracing/src/span/gql.rs
- engine/crates/tracing/src/span/subgraph.rs
Adding missing (sanitized) GraphQL query in traces and cleaning up a few things. Renamed `gql.document` to `gql.operation.query` as it's more accurate. Removed some of the tracing v2 tests, the tracing mock ones are super hard to get right and understand. We should just test against the output in ClickHouse as we do for metrics.
> fix(engine-v2): Add missing (sanitized) query in traces

- Cargo.lock
- engine/crates/engine/query-path/Cargo.toml
- engine/crates/engine/query-path/src/lib.rs
- engine/crates/engine/response/src/streaming.rs
- engine/crates/engine/src/schema.rs
- engine/crates/gateway-core/src/cache/partial.rs
- engine/crates/graph-entities/src/response/mod.rs
- engine/crates/graph-entities/src/value/mod.rs
- engine/crates/integration-tests/src/helpers.rs
- engine/crates/integration-tests/tests/defer/mod.rs
- engine/crates/integration-tests/tests/partial_caching/defer.rs
- engine/crates/partial-caching/src/execution/defer.rs
- engine/crates/partial-caching/src/output/response_merging.rs
- engine/crates/partial-caching/src/output/ser.rs
- engine/crates/partial-caching/src/output/tests.rs
- engine/crates/partial-caching/tests/response-merging.rs
I've been updating the `api` repo to use `execute_stream_v2` instead of `execute_stream`.  The main difference between these two is that `v2` returns a `Stream<StreamingPayload>`, where as the original returned an `http::Response.
In the API these functions need to make an HTTP call to another worker, so I needed to serialise & deserialise the `StreamingPayload` on either side of this HTTP call.  This turned out to be quite hard, because `StreamingPayload` didn't implement `Deserialize`.  Implementing `Deserialize` was also tricky, because it contained an `engine::Response`, but didn't make use of the `engine::Response` impl of `Serialize` but instead serialized to response format JSON.  There's no existing deserialize impl from response format JSON into an engine::Response, and we also …
> fix: use `CompactValue` directly inside `StreamingPayload`

- Cargo.lock
- engine/crates/engine-v2/Cargo.toml
- engine/crates/engine-v2/src/execution/mod.rs
- engine/crates/engine-v2/src/execution/planner/mod.rs
- engine/crates/engine-v2/src/execution/planner/partition.rs
- flake.nix
Add the logic to partition the output of a field into distinct object ID subsets with the same object fields (shape)
> chore(engine-v2): Add shape partitioning

- engine/crates/engine-v2/src/execution/walkers/selection_set.rs
- engine/crates/engine-v2/src/operation/bind/field.rs
- engine/crates/engine-v2/src/operation/bind/selection_set.rs
- engine/crates/engine-v2/src/operation/build.rs
- engine/crates/engine-v2/src/operation/logical_planner/mod.rs
- engine/crates/engine-v2/src/operation/logical_planner/selection_set.rs
- engine/crates/engine-v2/src/operation/selection_set.rs
- engine/crates/engine-v2/src/operation/variables.rs
- engine/crates/engine-v2/src/operation/walkers/field.rs
- engine/crates/engine-v2/src/operation/walkers/mod.rs
- engine/crates/engine-v2/src/operation/walkers/selection_set.rs
- engine/crates/engine-v2/src/response/key/mod.rs
- engine/crates/engine-v2/src/sources/graphql/query.rs
When generating the GraphQL query for subgraph we aggregate the field per parent object and order by query position. I was doing it with a hashmap, but I can just keep the array sorted instead.
> chore(engine-v2): order selection set fields

- cli/crates/cli/tests/federation.rs
- cli/crates/federated-dev/src/dev.rs
- engine/crates/engine-v2/axum/src/lib.rs
- engine/crates/engine-v2/schema/src/builder/external_sources.rs
- engine/crates/engine-v2/schema/src/sources/graphql.rs
- engine/crates/engine-v2/schema/src/walkers/mod.rs
- engine/crates/engine-v2/src/engine.rs
- engine/crates/engine-v2/src/http_response/mod.rs
- engine/crates/engine-v2/src/response/mod.rs
- engine/crates/engine-v2/src/sources/graphql/federation.rs
- engine/crates/engine-v2/src/sources/graphql/mod.rs
- engine/crates/engine-v2/src/sources/graphql/subscription.rs
- engine/crates/gateway-core/src/lib.rs
- engine/crates/gateway-v2/auth/src/lib.rs
- engine/crates/integration-tests/tests/federation/auth/jwt.rs
- engine/crates/integration-tests/tests/federation/auth/multiple.rs
- gateway/crates/federated-server/src/server/engine.rs
Initially wanted to apply default headers rules once before hooks and
authorization, but realized:
1. Their purpose is to define what we send to subgraphs, so applying
them before auth/hook doesn't make sense
2. Would need to rework the apply_header_rules function which I wanted
to avoid.
So just ended up with better request context initialization and
added some missing error code in some errors.
> chore(engine-v2): Add missing error codes & better request context initialization

- Cargo.lock
- gateway/CHANGELOG.md
- gateway/changelog/0.5.0.md
- gateway/crates/federated-server/Cargo.toml
- gateway/crates/gateway-binary/Cargo.toml
- Add error code for all GraphQL errors (#1871)
- Health checks endpoint (#1870)
- Rule-based header handling (#1872)
This can be merged when we have docs for the graphql errors.
> chore(gateway): bump to 0.5.0

- cli/npm/x86_64-unknown-linux-musl/package.json
If you try to `npx grafbase` on certain linux installs (WSL, apparently also NixOS) it'll silently do nothing.  Digging in some more the error apppears to be:
> Unsupported platform for @grafbase/cli-x86_64-unknown-linux-musl@0.77.0: wanted {"os":"linux","cpu":"x64","libc":"musl"} (current: {"os":"linux","cpu":"x64","libc":"glibc"})
The platform has `glibc` installed (pretty normal in linux) but our package.json is saying it needs musl.  This isn't technically correct - we _use_ musl, but we don't need it installed.  A musl binary should work fine on a system with glibc.
This PR removes the constraint from the package.json, hopefully fixing the issue.
> fix: remove musl constraint from linux-x86_64 `package.json`

- engine/crates/engine-v2/src/execution/hooks/authorized.rs
- engine/crates/runtime-local/src/hooks.rs
- engine/crates/runtime-local/src/hooks/authorized.rs
- engine/crates/runtime/src/hooks.rs
- engine/crates/runtime/src/hooks/test_utils.rs
Add the missing method and split the authorization part of the `Hooks` into a different one. It started to be overcrowded.
Using generics for all inputs for more flexibility.
> chore(hooks): add missing node_post_execution method, more generics and split trait

- packages/grafbase-sdk/src/define.ts
- packages/grafbase-sdk/src/query.ts
- packages/grafbase-sdk/tests/unit/cache.test.ts
I'm writing up docs & changelog for partial caching, and I was trying to convert the following SDL into TS:
```graphql
type Query {
field: String @cache(maxAge: 120)
}
```
Seems like this isn't something the SDK supports right now.  I could probably write an equivalent using the `extend schema @cache` syntax, but I'd rather just fix it.
> feat: cache directive on query extension fields in sdk

- Cargo.lock
- engine/crates/graphql-schema-diff/CHANGELOG.md
- engine/crates/graphql-schema-diff/Cargo.toml
Changed
- The library no longer produces changes for fields of newly added types, variants of newly added unions, values of enums, etc. This turned out to be too verbose. This could be made configurable if there is interest. (https://github.com/grafbase/grafbase/pull/1421)
Fixed
- Handle empty schema strings gracefully
> graphql-schema-diff: release 0.2.0

- Cargo.lock
- engine/crates/engine-v2/id-newtypes/Cargo.toml
- engine/crates/engine-v2/id-newtypes/src/bitset.rs
- engine/crates/engine-v2/id-newtypes/src/lib.rs
- engine/crates/engine-v2/id-newtypes/src/many.rs
- engine/crates/engine-v2/id-newtypes/src/range.rs
- engine/crates/engine-v2/schema/src/walkers/enum.rs
- engine/crates/engine-v2/schema/src/walkers/field.rs
- engine/crates/engine-v2/schema/src/walkers/input_object.rs
- engine/crates/engine-v2/schema/src/walkers/interface.rs
- engine/crates/engine-v2/schema/src/walkers/object.rs
- engine/crates/engine-v2/src/execution/coordinator.rs
- engine/crates/engine-v2/src/operation/walkers/argument.rs
- engine/crates/engine-v2/src/response/write/mod.rs
Adding two new structs: BitSet and IdToMany. The first is obvious, the second is used to store a list of `(Id, Value)` to provide all `Value` associated with an `Id`. It's not great yet, might never be. It's an attempt to avoid using `usize::from(id)` too much to access data for an id, as we lose type safety, and have one correct implementation. I made the mistake initially of using `binary_search` rather than `partition_point` here for exampe.
> chore(engine-v2/id-newtypes): few improvements, bitset and idtomany

- engine/crates/engine-v2/src/sources/graphql/deserialize/response.rs
- engine/crates/engine-v2/src/sources/graphql/federation.rs
- engine/crates/engine-v2/src/sources/graphql/mod.rs
Was missing status for federated entity subgraph call. And was overly complex for some reason.
> chore(engine-v2): better subgrpah span status handling

- engine/crates/engine-v2/src/execution/coordinator.rs
- engine/crates/engine-v2/src/sources/graphql/subscription.rs
- engine/crates/engine-v2/src/sources/mod.rs
Will be modifying the `ExecutorFutureSet` a bit later and realized the
type were more complex than necessary. Removed the `ExecutorCoordinator`
as it's now only a wrapper of the `ExecutionContext` and simplified the
subscription flow, it was passing down unnecessary types to the
executor.
> chore(engine-v2): simplify execution coordinator types

- cli/crates/federated-dev/src/dev/subgraph_config_watcher.rs
- engine/crates/engine-config-builder/src/lib.rs
- engine/crates/engine-v2/config/src/v5.rs
- engine/crates/engine-v2/schema/src/builder/mod.rs
- engine/crates/engine-v2/schema/src/lib.rs
- engine/crates/engine-v2/schema/src/walkers/header.rs
- engine/crates/engine-v2/src/execution/context.rs
- engine/crates/integration-tests/tests/federation/basic/headers.rs
- engine/crates/parser-sdl/src/federation/header.rs
- gateway/crates/federated-server/src/config.rs
- gateway/crates/federated-server/src/config/header.rs
Adds a rule for headers that forwards a header and duplicates it with a different name.
> feat(engine-v2): duplicating header rename

- gateway/crates/federated-server/src/config.rs
- gateway/crates/federated-server/src/server.rs
- gateway/crates/federated-server/src/server/gateway.rs
- gateway/crates/gateway-binary/tests/integration_tests.rs
Having that value as the only top-level, non-nested setting feels weird
> gateway: nest gateway timeout config under `[gateway]`

- engine/crates/parser-sdl/src/rules/auth_directive/providers.rs
- Fixes the detection of JWKS endpoints for issuers that contain a subpath (https://example.com/issuer)
> Fix auto-detection of JWKS urls for issuers with subpaths

- engine/crates/telemetry/src/config.rs
- engine/crates/telemetry/src/config/exporters.rs
- engine/crates/telemetry/src/config/exporters/otlp.rs
There's been problems pulling this repo into our `api` repo in the past couple of days.  This seems to be because the clickhouse tests require in a bunch of structs that are hidden behind the `oltp` feature flag in the `grafbase_telemetry` crate, and as soon as you enable that flag you pull in a bunch of additional crates, that don't play well with the set of dependencies we have in `api`, and unpicking that is nightmarish.
Prior to https://github.com/grafbase/grafbase/commit/0f4cdd3bc2cfe92feeb77cb81bf548cddb35d87d these structs were all exposed even when the `oltp` feature was turned off, which allowed the clickhouse tests to compile without introducing this dependency hell situation.
This commit removes the oltp feature flag from these structs so that the clickhouse tests compile, …
> fix: expose otlp config structs regardless of otlp feature

- cli/crates/federated-dev/Cargo.toml
- cli/crates/gateway/Cargo.toml
- engine/crates/integration-tests/Cargo.toml
- engine/crates/runtime-local/Cargo.toml
- engine/crates/runtime-local/src/rate_limiting.rs
- engine/crates/telemetry/src/config/exporters/otlp.rs
- gateway/crates/federated-server/Cargo.toml
I'm trying to pull the latest grafbase into api and getting some mismatch in rustls versions in the redis crate.  Don't think we actually need redis in `api` right now, so putting it behind a feature flag that `api` can opt out of.
> fix: feature flag redis in runtime-local

- engine/crates/engine-v2/src/execution/coordinator.rs
- engine/crates/engine-v2/src/execution/mod.rs
- engine/crates/engine-v2/src/execution/planner/builder.rs
- engine/crates/engine-v2/src/execution/planner/mod.rs
- engine/crates/engine-v2/src/execution/state.rs
- engine/crates/engine-v2/src/operation/bind/mod.rs
- engine/crates/engine-v2/src/operation/blueprint/plan.rs
- engine/crates/engine-v2/src/operation/input_value/query/mod.rs
- engine/crates/engine-v2/src/operation/input_value/query/view.rs
- engine/crates/engine-v2/src/operation/location.rs
- engine/crates/engine-v2/src/operation/logical_planner/mod.rs
- engine/crates/engine-v2/src/operation/logical_planner/selection_set.rs
- engine/crates/engine-v2/src/operation/mod.rs
- engine/crates/engine-v2/src/response/mod.rs
- engine/crates/engine-v2/src/response/object_set.rs
- engine/crates/engine-v2/src/response/read/mod.rs
- engine/crates/engine-v2/src/response/read/selection_set.rs
- engine/crates/engine-v2/src/response/read/ser.rs
- engine/crates/engine-v2/src/response/read/view/de.rs
- engine/crates/engine-v2/src/response/read/view/mod.rs
- engine/crates/engine-v2/src/response/read/view/ser.rs
- engine/crates/engine-v2/src/response/shape.rs
- engine/crates/engine-v2/src/response/value.rs
- engine/crates/engine-v2/src/response/write/deserialize/object/concrete.rs
- engine/crates/engine-v2/src/response/write/deserialize/scalar.rs
- engine/crates/engine-v2/src/response/write/mod.rs
- engine/crates/engine-v2/src/sources/graphql/request.rs
- engine/crates/engine-v2/src/sources/introspection/writer.rs
- engine/crates/graphql-mocks/src/slow.rs
- engine/crates/integration-tests/tests/federation/timeouts.rs
Response objects are just a sorted list of `(ResponseEdge, ResponseValue)` with `ResponseEdge = QueryPosition + ResponseKey` to have the right ordering.
When reading the required inputs for a plan I used to create a `ReadSelectionSet` which reads fields from a list of `ResponseObject` through `ResponseEdge` (best-effort guess) and falls back to finding the one with the right `ResponseKey` if I made a mistake. This kind of worked for plans, but wasn't great and not that easy to build.
So instead of relying of trying to determine the right `ResponseEdge` / `ResponseKey`, I associated a `FieldId`s with their `RequiredFieldId` (deduplicated), so now when building their field shapes I can keep track of whether it matches a specific requirements. When writing into the response we copy that id …
> chore(engine-v2): Identify requirements by their id rather than response key in the response

- engine/crates/engine-v2/id-newtypes/src/lib.rs
- engine/crates/engine-v2/src/execution/ids.rs
- engine/crates/engine-v2/src/execution/mod.rs
- engine/crates/engine-v2/src/execution/planner/builder.rs
- engine/crates/engine-v2/src/execution/planner/mod.rs
- engine/crates/engine-v2/src/execution/planner/query_modifier.rs
- engine/crates/engine-v2/src/execution/state.rs
- engine/crates/engine-v2/src/execution/walkers/mod.rs
- engine/crates/engine-v2/src/operation/bind/field.rs
- engine/crates/engine-v2/src/operation/bind/mod.rs
- engine/crates/engine-v2/src/operation/bind/modifier.rs
- engine/crates/engine-v2/src/operation/blueprint/mod.rs
- engine/crates/engine-v2/src/operation/blueprint/plan.rs
- engine/crates/engine-v2/src/operation/ids.rs
- engine/crates/engine-v2/src/operation/logical_planner/mod.rs
- engine/crates/engine-v2/src/operation/logical_planner/selection_set.rs
- engine/crates/engine-v2/src/operation/mod.rs
- engine/crates/engine-v2/src/operation/modifier.rs
- engine/crates/engine-v2/src/operation/selection_set.rs
- engine/crates/engine-v2/src/operation/walkers/field.rs
So adjusting the `ResponseModifier` creation to be the same as the `QueryModiifer`, used a different data layout initially, but was a mistake. So a modifier is roughly just a rule (which `@authorized` directive basically) and a list of impacted fields.
Now I'm defining whenever a SelectionSet object needs to be tracked in the "logical planning" phase, the "shape" phase then create an appropriate `ResponseObjectSetId` whenever necessary. Had to do this because now a ResponseModifier points to its impacted fields (where we need to track objects), rather than the opposite.
In the execution planning phase, I'm building `ResponseModifierExecutor` which will do the actual modification if the field is still queried after the query modifications. This is also where I define all the dependencies …
> chore(engine-v2): Create response modifier executor with proper dependencies

- engine/crates/engine-v2/schema/src/walkers/directives.rs
- engine/crates/engine-v2/src/execution/coordinator.rs
- engine/crates/engine-v2/src/execution/hooks/authorized.rs
- engine/crates/engine-v2/src/execution/mod.rs
- engine/crates/engine-v2/src/execution/planner/mod.rs
- engine/crates/engine-v2/src/execution/planner/query_modifier.rs
- engine/crates/engine-v2/src/execution/response_modifier.rs
- engine/crates/engine-v2/src/execution/state.rs
- engine/crates/engine-v2/src/operation/blueprint/plan.rs
- engine/crates/engine-v2/src/operation/logical_planner/mod.rs
- engine/crates/engine-v2/src/operation/logical_planner/selection_set.rs
- engine/crates/engine-v2/src/response/error.rs
- engine/crates/engine-v2/src/response/object_set.rs
- engine/crates/engine-v2/src/response/value.rs
- engine/crates/engine-v2/src/response/write/mod.rs
- engine/crates/graphql-mocks/src/secure.rs
- engine/crates/integration-tests/tests/federation/hooks/authorize_parent_edge_post_execution.rs
- engine/crates/integration-tests/tests/federation/hooks/mod.rs
- engine/crates/runtime/src/error.rs
So this applies the response modifiers, once all the requirements are present, and adds some basic tests for them for the case:
```graphql
type User {
name @authorized(fields: "id")
}
```
> feat(engine-v2): authorized parent edge post execution

- engine/crates/engine-config-builder/src/lib.rs
- engine/crates/engine-v2/config/src/lib.rs
- engine/crates/engine-v2/config/src/v2/mod.rs
- engine/crates/engine-v2/config/src/v5.rs
- engine/crates/engine-v2/schema/src/builder/external_sources.rs
- engine/crates/engine-v2/schema/src/builder/mod.rs
- engine/crates/engine-v2/schema/src/lib.rs
- engine/crates/engine-v2/schema/src/sources/graphql.rs
- engine/crates/engine-v2/src/sources/graphql/federation.rs
- engine/crates/engine-v2/src/sources/graphql/mod.rs
- engine/crates/engine-v2/src/sources/graphql/request.rs
- engine/crates/gateway-v2/auth/src/jwt.rs
- engine/crates/integration-tests/src/federation/builder.rs
- engine/crates/integration-tests/tests/federation/entity_caching.rs
- engine/crates/integration-tests/tests/federation/mod.rs
- engine/crates/jwt-verifier/src/lib.rs
- engine/crates/parser-sdl/src/federation.rs
- engine/crates/parser-sdl/src/rules/all_subgraphs_directive.rs
- engine/crates/parser-sdl/src/rules/subgraph_directive.rs
- engine/crates/runtime-local/src/kv.rs
- engine/crates/runtime-noop/src/kv.rs
- engine/crates/runtime/src/kv.rs
- gateway/crates/federated-server/src/config.rs
- gateway/crates/federated-server/src/server/gateway.rs
This adds entity caching for requests to top level fields.  The name entity caching isn't _really_ accurate for these, since they're not neccesarily entities, but whatever.
The implementation is very barebones at the moment: we just hash the query, and look that up in the cache.  We don't yet bother with auth scopes, cache invalidation, or even much of the configuration concerns for this feature (beyond what I needed for tests).
Fixes GB-7148
> feat: entity caching for top level fields

- engine/crates/composition/src/emit_federated_graph.rs
- engine/crates/composition/src/ingest_subgraph/directives/authorized.rs
- engine/crates/composition/src/subgraphs/directives.rs
- engine/crates/composition/tests/composition/authorized_basic/federated.graphql
- engine/crates/composition/tests/composition/authorized_basic/subgraphs/bank_account.graphql
- engine/crates/composition/tests/composition/authorized_validation/subgraphs/bank_account.graphql
- engine/crates/engine-v2/schema/src/builder/graph.rs
- engine/crates/engine-v2/schema/src/directives/authorized.rs
- engine/crates/engine-v2/schema/src/walkers/directives.rs
- engine/crates/engine-v2/src/execution/hooks/authorized.rs
- engine/crates/engine-v2/src/execution/mod.rs
- engine/crates/engine-v2/src/execution/planner/builder.rs
- engine/crates/engine-v2/src/execution/planner/mod.rs
- engine/crates/engine-v2/src/execution/response_modifier.rs
- engine/crates/engine-v2/src/operation/bind/modifier.rs
- engine/crates/engine-v2/src/operation/blueprint/mod.rs
- engine/crates/engine-v2/src/operation/logical_planner/mod.rs
- engine/crates/engine-v2/src/operation/logical_planner/selection_set.rs
- engine/crates/engine-v2/src/operation/modifier.rs
- engine/crates/federated-graph/src/federated_graph/v3.rs
- engine/crates/federated-graph/src/from_sdl.rs
- engine/crates/federated-graph/src/render_sdl/display_utils.rs
- engine/crates/graphql-mocks/src/secure.rs
- engine/crates/integration-tests/tests/federation/hooks/authorize_edge_node_post_execution.rs
- engine/crates/integration-tests/tests/federation/hooks/mod.rs
I added this hook which filters the _output_ of a field
```graphql
type Account {
transactions: [Transaction!] @authorized(node: "kind")
}
type Transaction {
kind: String
}
```
Here individual `Transaction` objects would be authorized or not, not the
`transactions` field. I'm re-using the structure I made for
`@authorized(fields: "...")` but reversing the SelectionSetId everywhere
basically, using the output instead of the parent one. It's pretty much
a hack. I'll separate a lot of that code in the next week.
Had to add the necessary code in composition also. We didn't parse `node` before.
> feat(engine-v2): authorize_edge_node_post_execution hook

- engine/crates/engine-v2/src/engine/rate_limiting.rs
- engine/crates/runtime-local/src/rate_limiting/redis.rs
- engine/crates/runtime/src/rate_limiting.rs
If subgraph has a name "global" we would be in trouble.
> chore: refine redis keys a bit nicer

- engine/crates/engine-v2/src/execution/response_modifier.rs
- engine/crates/graphql-mocks/src/lib.rs
- engine/crates/graphql-mocks/src/tea_shop.rs
- engine/crates/integration-tests/tests/federation/hooks/authorize_parent_edge_post_execution.rs
The post-execution mechanism, `ResponseModifierExecutor`, was expecting
its input, a `ResponseObjectSet`, to exist once its parent plans were
executed. However, with pre-execution auth we modify the subgraph query
to not retrieve any unauthorized fields. This could lead to the input
never being created. Added a test for it.
I'm also changing a bit how I'm testing type system directives. Before I
was adding them manually in the "secure" graphql-mock, but it's already
a mess today. So instead I created a simple TeaShop schema and I'm
overriding the SDL to add directives for a given test. Making it a lot
easier to follow and more reusable. Will try to move the other hook
stuff to this model over time.
> fix(engine-v2): Panic could happen with both pre & post execution auth

- gateway/crates/gateway-binary/src/args/log.rs
> chore(gateway): fix help text for debug logs

- examples/gateway-hooks/Cargo.lock
- examples/gateway-hooks/grafbase.toml
- Updated reqwest package in Cargo.lock from commit 7e26f0f to 6b23d746
- Changed hooks location in grafbase.toml to target/wasm32-wasip1/release/hooks.wasm
> chore: update dependencies and hooks configuration

- engine/crates/engine-v2/src/response/read/view/mod.rs
- engine/crates/engine-v2/src/sources/graphql/deserialize/entities.rs
- engine/crates/engine-v2/src/sources/graphql/federation.rs
- engine/crates/engine-v2/src/sources/graphql/mod.rs
- engine/crates/engine-v2/src/sources/graphql/subscription.rs
- engine/crates/engine-v2/src/sources/graphql/variables.rs
- engine/crates/graphql-mocks/src/federation/products.rs
- engine/crates/integration-tests/tests/federation/entity_caching.rs
- engine/crates/integration-tests/tests/federation/introspection.rs
Following on from #1931 - this adds caching on the entity requests to subgraphs.  These are a bit more complicated because one request will usually map to more than one cache entry.  We need to filter out any representations that have a cache hit from the request to the subgraph, and then make sure we use the cache entry for those during deserialisation rather than trying to read them from the response.
I've made use of `serde_json::RawValue` in quite a few places to try to make things more efficient - so we don't have to go through a bunch of extra serde roundtrips.
Fixes GB-7159
> feat: cache entity requests in engine-v2

- engine/crates/engine-config-builder/src/lib.rs
- engine/crates/engine-v2/config/src/lib.rs
- engine/crates/engine-v2/config/src/v2/mod.rs
- engine/crates/engine-v2/config/src/v5.rs
- engine/crates/engine-v2/schema/src/builder/external_sources.rs
- engine/crates/engine-v2/schema/src/builder/mod.rs
- engine/crates/engine-v2/schema/src/lib.rs
- engine/crates/engine-v2/schema/src/sources/graphql.rs
- engine/crates/engine-v2/src/sources/graphql/federation.rs
- engine/crates/engine-v2/src/sources/graphql/mod.rs
- engine/crates/integration-tests/src/federation/builder.rs
- engine/crates/integration-tests/tests/federation/entity_caching.rs
- engine/crates/parser-sdl/src/federation.rs
- engine/crates/parser-sdl/src/rules/all_subgraphs_directive.rs
- engine/crates/parser-sdl/src/rules/subgraph_directive.rs
- gateway/crates/federated-server/config/grafbase.toml
- gateway/crates/federated-server/src/config.rs
- gateway/crates/federated-server/src/config/entity_caching.rs
- gateway/crates/federated-server/src/server.rs
- gateway/crates/federated-server/src/server/gateway.rs
Adds entity caching config to the gateway toml.  Allowing users to set defaults and also enable/disable and set the TTL per subgraph.
Config should look something like:
```toml
[entity_caching]
enabled = true
ttl = "60s"
[subgraphs.products.entity_caching]
ttl = "30s"
[subgraphs.reviews.entity_caching]
enabled = false
```
This PR is just the config for enabling & setting the TTL: configuring redis etc. will come when I get to adding redis support.
Fixes GB-7160
Fixes GB-7051
> feat: gateway config for entity caching

- .dockerignore
- Cargo.lock
- Dockerfile
- engine/crates/engine-v2/Cargo.toml
- engine/crates/engine-v2/src/engine.rs
- engine/crates/engine-v2/src/operation/build.rs
- engine/crates/engine-v2/src/operation/metrics.rs
- engine/crates/engine-v2/src/operation/mod.rs
- engine/crates/engine/parser/Cargo.toml
- engine/crates/engine/parser/src/types/mod.rs
- engine/crates/engine/src/schema.rs
- engine/crates/engine/validation/src/lib.rs
- engine/crates/engine/validation/src/visitor.rs
- engine/crates/engine/validation/src/visitors/mod.rs
- engine/crates/engine/validation/src/visitors/used_fields.rs
- engine/crates/gateway-core/src/lib.rs
- engine/crates/telemetry/src/metrics/operation.rs
- engine/crates/telemetry/src/span.rs
- gateway/crates/gateway-binary/tests/telemetry/metrics.rs
- gateway/crates/gateway-binary/tests/telemetry/metrics/operation.rs
- gateway/crates/gateway-binary/tests/telemetry/metrics/request.rs
For a schema:
```graphql
type Query {
user(id: ID!): User
}
type User {
id: ID!
name: String
}
```
and query:
```graphql
query {
user(id: "0x1") {
id
name
}
}
```
We produce the following string
```
"Query.user,User.id+name"
```
I'm also renaming `gql.operation.normalized_query` to `gql.operation.query` in metrics for consistency with tracing. That's the only `query` we're sending and likely will ever send anyway.
> feat(engine): Expose used fields in OTEL metrics

- engine/crates/runtime-local/src/lib.rs
- engine/crates/runtime-local/src/rate_limiting/redis.rs
- engine/crates/runtime-local/src/redis.rs
- engine/crates/runtime-local/src/redis/pool.rs
- gateway/crates/federated-server/src/server/gateway.rs
I'm in the process of adding redis support to entity caching.  Rate limiting already uses redis, and ideally we want to be able to share the connection pool between caching & rate limiting, assuming the user is using the same redis settings for both.
This is a bit of prep work for that: extracting the generic redis connection code into it's own module with its own structs, where they were part of the rate limiting config/code before.
I've also added a `RedisPoolFactory` that is used to construct pools - it'll return the same pool if you give it the same details twice.  This should make it easy to share connection pools without having to explicity write code to compare a rate limiting config with an entity caching config.
Part of GB-6894
> chore: decouple redis pools from rate limiting

- engine/crates/engine-config-builder/src/from_sdl_config.rs
- engine/crates/parser-sdl/src/federation.rs
- engine/crates/parser-sdl/src/rules/subgraph_directive.rs
- gateway/crates/config/src/entity_caching.rs
This adds redis config for entity caching into the gateway toml structs. Doesn't actually do anything yet, that'll be my next PR.
Part of GB-6894
> feat: redis config for entity caching

- engine/crates/runtime-local/src/lib.rs
I didn't notice redis was feature flagged.
> fix: put my new redis stuff behind the redis flag

- engine/crates/telemetry/src/otel/exporter.rs
TLS was broken, wish we had a simple test for it
> fix(engine): Fix TLS for OTLP gRPC export

- engine/crates/engine-config-builder/src/from_toml_config.rs
- gateway/crates/config/src/lib.rs
It acts as a default subgraph timeout, which can be overriden per subgraph if needed.
> feat(config): Add subgraph_timeout configuration option

- engine/crates/engine-config-builder/src/from_toml_config.rs
- engine/crates/engine-v2/config/src/v2/mod.rs
- engine/crates/engine-v2/schema/src/sources/graphql.rs
- engine/crates/engine-v2/src/sources/graphql/mod.rs
- engine/crates/parser-sdl/src/federation.rs
- engine/crates/parser-sdl/src/rules/subgraph_directive.rs
- gateway/crates/config/src/lib.rs
A global setting to define retries for all subgraphs.
> feat(config): Global retry settings

- cli/crates/gateway/Cargo.toml
- engine/crates/engine-v2/Cargo.toml
- engine/crates/gateway-core/Cargo.toml
- engine/crates/gateway-core/src/cache/mod.rs
- engine/crates/gateway-core/src/lib.rs
- engine/crates/integration-tests/Cargo.toml
I had the partial-caching code in gateway-core behind a feature flag while I was developing it.  Now that it's out this flag is not worth keeping around.
Fixes GB-7072
> chore: unflag partial-caching feature in gateway-core

- engine/crates/integration-tests/tests/federation/trusted_documents.rs
- engine/crates/parser-sdl/src/federation.rs
- engine/crates/runtime-local/src/entity_cache.rs
- engine/crates/runtime-local/src/entity_cache/redis.rs
- engine/crates/runtime-local/src/lib.rs
- engine/crates/runtime-local/src/redis.rs
- gateway/crates/config/src/entity_caching.rs
- gateway/crates/federated-server/src/server/gateway.rs
As per the title this finishes adding redis entity caching support.  
I haven't written any tests of this yet because the existing tests of the gateway binary don't seem to call subgraphs, so there's a bit of setup I'd need to do for that.  Have added GB-7210 to handle that.
Fixes GB-6894
> feat: implement and hook up RedisEntityCache

- engine/crates/engine-v2/src/sources/graphql/federation.rs
- engine/crates/engine-v2/src/sources/graphql/root_fields.rs
- engine/crates/integration-tests/tests/federation/entity_caching.rs
One of the things we want to avoid in entity caching is sharing cache entries that shouldn't be shared: one way that could happen is if some kind of authentication header was included in a subgraph request.  This handles that case by adding subgraph headers into the entity caching key.
We probably still need to handle adding auth scopes and such into the caching key, but that's a bigger job - this should handle a lot of the obvious cases.
> fix: include headers in entity caching keys

- Cargo.lock
- Cargo.toml
- engine/crates/telemetry/src/otel/layer.rs
- engine/crates/telemetry/src/otel/logs.rs
- engine/crates/telemetry/src/otel/traces.rs
- gateway/crates/gateway-binary/Cargo.toml
- gateway/crates/gateway-binary/src/main.rs
Let's got some of the forks we need. The otel setup is now in http 1.0 and all that. Seems like we even get otel logs even when removing that provider set methods. Looks good.
> chore: switch to mainline otel

- .github/CODEOWNERS
The frontend team is not active in this repo, yet we get tagged for review in a lot of pull requests. I think it's better to manually tag us if needed.
> Remove frontend team from codeowners

- Cargo.lock
- Cargo.toml
- cli/CHANGELOG.md
- cli/changelog/0.78.0.md
- cli/crates/backend/Cargo.toml
- cli/crates/cli/Cargo.toml
- cli/crates/federated-dev/Cargo.toml
- cli/crates/server/Cargo.toml
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
**Features**
- The CLI gained a new `grafbase branch create` to create branches on self-hosted graphs (#1997)
**Fixes**
- Fix auto-detection of JWKS urls for issuers with subpaths (#1927)
- Fix the implementation of KvStoreInner (#1938)
> cli: release 0.78.0

- engine/crates/runtime-local/Cargo.toml
The versions don't match. This is making builds fail on main.
> Use correct version of wasi-component-loader in runtime-local

- cli/crates/cli/src/cli_input/project_ref.rs
- graph-ref/src/lib.rs
They should not be passed. Currently, you only get a warning that the schema cannot be found. With the change in this commit, you get a (hopefully) helpful error message.
closes GB-7251
> gateway: error with helpful message when account name provided in graph ref

- engine/crates/graphql-schema-diff/tests/diff_tests.rs
We can't reuse the spans across unices and windows, because of the different line endings. This is making CI fail as of right now.
> graphql-schema-diff: skip tests on windows

- Cargo.lock
- engine/crates/engine-v2/src/engine.rs
- engine/crates/engine-v2/src/sources/graphql/federation.rs
- engine/crates/engine-v2/src/sources/graphql/mod.rs
- engine/crates/engine-v2/src/sources/graphql/record.rs
- engine/crates/engine-v2/src/sources/graphql/request/execute.rs
- engine/crates/engine-v2/src/sources/graphql/root_fields.rs
- engine/crates/runtime-local/src/operation_cache.rs
- engine/crates/runtime/src/operation_cache.rs
- engine/crates/telemetry/Cargo.toml
- engine/crates/telemetry/src/metrics/operation.rs
- gateway/crates/federated-server/src/server/gateway.rs
- gateway/crates/gateway-binary/Cargo.toml
- gateway/crates/gateway-binary/tests/schemas/small.graphql
- gateway/crates/gateway-binary/tests/telemetry/metrics.rs
- gateway/crates/gateway-binary/tests/telemetry/metrics/operation.rs
- gateway/crates/gateway-binary/tests/telemetry/metrics/operation/subgraph.rs
- hits
- misses
- hits
- misses
- size
Also enables in-memory operation cache for gateway.
> feat: implement caching metrics

- cli/crates/backend/src/api/create.rs
- cli/crates/backend/src/api/graphql/types/mutations.rs
- cli/crates/cli/src/cli_input/create.rs
- cli/crates/cli/src/create.rs
Both interactively (we prompt the user) and through CLI args with the `--mode` argument. In both cases, we default to managed graphs.
```
Set up and deploy a new graph
Usage: grafbase create [OPTIONS]
Options:
-n, --name <NAME>
The name to use for the new graph
-a, --account <SLUG>
The slug of the account in which the new graph should be created
-m,  --mode <MODE>
Whether the graph is self-hosted or managed. Possible values: self-hosted or managed
(default)
-e, --env [<ENVIRONMENT_VARIABLES>...]
Adds an environment variable to the graph
-h, --help
Print help
```
closes GB-7297
> cli: make creating federated graphs possible in grafbase create

- engine/crates/engine-v2/src/engine.rs
- engine/crates/integration-tests/tests/federation/graphql_over_http/mod.rs
We accepted content-type: application/json;charset=utf-8 (and other parameters after the semicolon) before the graphql-over-http implementation. The spec says the content type should be application/json, but not that parameters are forbidden. Us rejecting it seems to be an error.
This commit makes the engine accept parameters in content type again.
> engine-v2: allow parameters in content-type header

- Cargo.lock
- gateway/CHANGELOG.md
- gateway/changelog/0.9.1.md
- gateway/crates/federated-server/Cargo.toml
- gateway/crates/gateway-binary/Cargo.toml
Fixes
- Fix rendering of multiline strings in federated graph SDL (https://github.com/grafbase/grafbase/pull/2021)
- Fix excessive strictness in the Content-Type headers we accepted following the strict implementation of Graphql-over-HTTP. Content-Type headers with parameters (for example "application/json;charset=utf-8") are now accepted again. (https://github.com/grafbase/grafbase/pull/2023)
> gateway: release 0.9.1

- Cargo.lock
- Cargo.toml
- cli/changelog/0.79.0.md
- cli/crates/backend/Cargo.toml
- cli/crates/cli/Cargo.toml
- cli/crates/federated-dev/Cargo.toml
- cli/crates/server/Cargo.toml
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
- engine/crates/runtime-local/Cargo.toml
Features
- The `grafbase create` command now supports creating self-hosted graphs, either through the interactive flow or through the `--mode=self-hosted` flag. (#2018)
Fixes
- Terminology improvements for consistency in multiple parts of the CLI ("project" -> "graph")
> cli: release 0.79.0

- gateway/crates/federated-server/src/server.rs
Sometimes, tasks cannot be terminated gracefully, and that results in the gateway not being responsive, not responding to CTRL+C anymore, and just hanging. I haven't been able to reproduce this, but this commit at least limits that time to three seconds.
> gateway: set a 3 second grace period for graceful shutdowns

- Cargo.lock
- gateway/CHANGELOG.md
- gateway/changelog/0.9.2.md
- gateway/crates/federated-server/Cargo.toml
- gateway/crates/gateway-binary/Cargo.toml
Fixes
- Limit the grace period to 3 seconds for graceful shutdowns (https://github.com/grafbase/grafbase/pull/2026)
> gateway: release 0.9.2

- Cargo.lock
- gateway/CHANGELOG.md
- gateway/changelog/0.9.3.md
- gateway/crates/federated-server/Cargo.toml
- gateway/crates/gateway-binary/Cargo.toml
The 0.9.2 release of the gateway accidentally included changes that will be released with 0.10.0. This version only includes the fixes present in the changelogs of versions 0.9.1 and 0.9.2.
> gateway: release 0.9.3

- engine/crates/telemetry/src/graceful_shutdown.rs
- engine/crates/telemetry/src/lib.rs
- gateway/crates/federated-server/src/server.rs
So the exporters have time to flush during the grace period.
> gateway: shut down tracer and logger providers in graceful shutdown

- gateway/crates/config/src/cors.rs
- gateway/crates/config/src/entity_caching.rs
- gateway/crates/config/src/health.rs
- gateway/crates/config/src/hooks.rs
- gateway/crates/config/src/lib.rs
- gateway/crates/config/src/telemetry/exporters.rs
- gateway/crates/config/src/telemetry/exporters/logs.rs
- gateway/crates/config/src/telemetry/exporters/metrics.rs
- gateway/crates/config/src/telemetry/exporters/otlp.rs
- gateway/crates/config/src/telemetry/exporters/stdout.rs
- gateway/crates/config/src/telemetry/exporters/tracing.rs
- gateway/crates/config/src/telemetry/mod.rs
- gateway/crates/gateway-binary/tests/integration_tests.rs
We weren't applying the same defaults everywhere for `Config::default()` and through deserialization.
> fix(gateway): Fix inconsistent defaults in the Gateway configuration

- engine/crates/engine-v2/src/execution/planner/mod.rs
- engine/crates/engine-v2/src/operation/logical_planner/mod.rs
- engine/crates/engine-v2/src/operation/logical_planner/selection_set.rs
- engine/crates/integration-tests/src/federation/builder.rs
- gateway/crates/gateway-binary/tests/integration_tests.rs
I use at various places `itertools.format_with` with `tracing::trace!` which works without a problem a
simple subscriber but panics with opentelemetry as it somehow gets
called multiple times.
> fix(gateway): Panic with `--log=trace`

- engine/crates/federated-graph/src/from_sdl.rs
- engine/crates/federated-graph/src/render_sdl/render_federated_sdl.rs
- engine/crates/integration-tests/data/federated-graph-schema.graphql
- engine/crates/integration-tests/src/federation/builder.rs
- engine/crates/integration-tests/tests/federation/issues.rs
- gateway/changelog/0.10.0.md
@join__field is only needed when a type (exception is the root type) belongs to more than one subgraph
> fix(federated-graph): `@join__field` may not be present

- engine/crates/integration-tests/tests/federation/entity_caching.rs
I'm adding CacheControl support to entity caching and I noticed what looked a lot like a bug.  I added this test to check whether it was - turns out it's not, but I think the test is useful just to make sure we don't regress.
> test: add an extra bit of entity cache testing

- Cargo.lock
- engine/crates/engine-v2/src/sources/graphql/federation.rs
- engine/crates/engine-v2/src/sources/graphql/mod.rs
- engine/crates/engine-v2/src/sources/graphql/request/execute.rs
- engine/crates/engine-v2/src/sources/graphql/root_fields.rs
- engine/crates/graphql-mocks/Cargo.toml
- engine/crates/graphql-mocks/src/lib.rs
- engine/crates/integration-tests/tests/federation/entity_caching.rs
- engine/crates/integration-tests/tests/federation/entity_caching/subgraph_cache_control.rs
Prior to this PR we'd always use the default cache TTL for a subgraph as provided in the configuration.  However, we want subgraphs to be able to override that on a per-response basis by returning a CacheControl header.
This PR implements that:
1. If a subgraph returns `no-store` or `private` directives we avoid writing to the entity cache.
2. If the `Age` header and the `max-age` directive are present we set the TTL to `age - max_age`
3. If the `max-age` directive is present with no `Age` header we take the `max-age` as the TTL
Fixes GB-7164
> feat: respect subgraph CacheControl headers

- Cargo.lock
- Cargo.toml
- cli/changelog/0.79.1.md
- cli/crates/backend/Cargo.toml
- cli/crates/cli/Cargo.toml
- cli/crates/federated-dev/Cargo.toml
- cli/crates/server/Cargo.toml
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
- engine/crates/runtime-local/Cargo.toml
__Fixes__
- cli: make grafbase.config.ts optional for gb create --mode=self-hosted. The configuration is not relevant in fully self-hosted deployments. (#2045)
> cli: release 0.79.1

- cli/crates/backend/src/api/create.rs
- cli/crates/backend/src/api/graphql/types/mutations.rs
We do rely on some globals lower down the call stack, that was not identified and addressed in https://github.com/grafbase/grafbase/pull/2045
> cli: fix grafbase create --mode=self-hosted outside of project context

- engine/crates/composition/src/compose/context.rs
- engine/crates/composition/src/compose/directives.rs
- engine/crates/composition/src/composition_ir.rs
- engine/crates/composition/src/composition_ir/directive.rs
- engine/crates/composition/src/emit_federated_graph.rs
- engine/crates/composition/src/emit_federated_graph/context.rs
- engine/crates/engine-v2/schema/src/builder/coerce/error.rs
- engine/crates/engine-v2/schema/src/builder/coerce/mod.rs
- engine/crates/engine-v2/schema/src/builder/graph.rs
- engine/crates/engine-v2/schema/src/builder/ids.rs
- engine/crates/engine-v2/schema/src/builder/input_values.rs
- engine/crates/engine-v2/schema/src/builder/interner.rs
- engine/crates/engine-v2/schema/src/lib.rs
- engine/crates/engine-v2/schema/src/walkers/enum.rs
- engine/crates/federated-graph/src/federated_graph/v1.rs
- engine/crates/federated-graph/src/federated_graph/v2.rs
- engine/crates/federated-graph/src/federated_graph/v4.rs
- engine/crates/federated-graph/src/from_sdl.rs
- engine/crates/federated-graph/src/render_sdl/display_utils.rs
- engine/crates/integration-tests/tests/federation/introspection.rs
- engine/crates/integration-tests/tests/federation/snapshots/integration_tests__federation__introspection__introspecting_with_grafbase_openapi_subgraph.snap
- engine/crates/integration-tests/tests/federation/snapshots/integration_tests__federation__introspection__raw_introspetion_output.snap
- gateway/crates/gateway-binary/tests/integration_tests.rs
The internal value type in engine-v2 has a variant for enum values that contains an enum id. Since composition produced Value::Enum(id) where id is a StringId, those were converted and rendered as strings.
There are two potential ways out of this situation: make engine-v2's value type less precise, or make federated-graph's value type more precise. The path taken in this PR is the second one. We introduce a Value::EnumValue() variant that takes an EnumId, but retain the variant with a StringId inside as Value::UnboundEnumValue. That is necessary because we don't have enum values in the schema for enums that are used in directives. We don't do enough analysis on directive definitions, but we still need to represent these values.
What we want to fix, and what is fixed in this PR, are enum …
> composition/engine-v2: fix introspection of defaults of enum type

- Cargo.lock
- engine/crates/engine-v2/src/sources/graphql/request/execute.rs
- engine/crates/telemetry/Cargo.toml
- engine/crates/telemetry/src/http.rs
- engine/crates/telemetry/src/lib.rs
- engine/crates/telemetry/src/otel/traces.rs
- engine/crates/telemetry/src/span/request.rs
- engine/crates/telemetry/src/tower.rs
- gateway/changelog/0.11.0.md
- gateway/crates/config/src/telemetry/exporters.rs
- gateway/crates/config/src/telemetry/exporters/tracing.rs
- gateway/crates/config/src/telemetry/mod.rs
- gateway/crates/federated-server/src/server/graph_fetch_method.rs
- gateway/crates/gateway-binary/Cargo.toml
- gateway/crates/gateway-binary/src/telemetry.rs
- gateway/crates/gateway-binary/tests/integration_tests.rs
- gateway/crates/gateway-binary/tests/telemetry/mod.rs
- gateway/crates/gateway-binary/tests/telemetry/tracing.rs
The gateway now implements tracing propagation: it can receive tracing context (trace id, parent span id, additional context) from headers in the requests it receives, and pass that context on to subgraphs when it makes requests to them. That enables correlation of requests across network boundaries.
There are different standards for propagation. In this release, we implement [Trace Context](https://www.w3.org/TR/trace-context/) and [Baggage](https://opentelemetry.io/docs/concepts/signals/baggage/) — the standard OpenTelemetry mechanisms for trace parent and trace context propagation respectively —, and AWS X-Ray. Multiple mechanisms can be combined.
This is configurable through the `telemetry.tracing.propagation` key in the configuration. For example:
```toml …
```
> gateway: tracing context propagation

- .github/actions/test/action.yml
- Cargo.lock
- gateway/CHANGELOG.md
- gateway/changelog/0.11.0.md
- gateway/crates/federated-server/Cargo.toml
- gateway/crates/gateway-binary/Cargo.toml
Bump gateway to 0.11.0
**Description:**
This change updates the `federated-server` and `grafbase-gateway` crates to their latest version, 0.11.0.
**Changes:**
* Updated Cargo.toml files in `gateway` crate to reflect new versions.
* Updated CHANGELOG.md file in `gateway` crate with a note about the release.
* Updated changelog document for gateway version 0.11.0 with details about the changes.
> chore: bump gateway to 0.11.0

- cli/crates/federated-dev/src/dev.rs
- cli/crates/federated-dev/src/dev/gateway_nanny.rs
- engine/crates/composition/CHANGELOG.md
- engine/crates/engine-config-builder/src/from_sdl_config.rs
- engine/crates/engine-config-builder/src/from_toml_config.rs
- engine/crates/engine-v2/schema/src/builder/mod.rs
- engine/crates/engine-v2/schema/src/lib.rs
- engine/crates/engine-v2/src/lib.rs
- engine/crates/federated-graph/src/from_sdl.rs
- engine/crates/federated-graph/src/render_sdl/render_federated_sdl.rs
- engine/crates/integration-tests/src/federation/builder.rs
- gateway/crates/federated-server/src/error.rs
- gateway/crates/federated-server/src/server/gateway.rs
- gateway/crates/federated-server/src/server/graph_fetch_method.rs
- gateway/crates/federated-server/src/server/graph_updater.rs
When you start the gateway with `--schema` and federated SDL that contains an interface with an `@join__type` directive _without keys argument_, the gateway fails to start with the following error:
```
Error: internal error: Failed to generate engine Schema:  --> 1:4
|
1 | {  }
|    ^---
|
= expected selection
```
This error comes from `graphql_federated_graph::from_sdl()`, because we try to parse an empty string as a selection set.
The SDL that triggers the error when generating the engine Schema contains something like:
```
@join__type(graph: MY_GRAPH, key: "")
```
which is not valid. But the original SDL passed to the engine contains something like:
```
@join__type(graph: MY_GRAPH)
```
which is valid.
**How does that happen?**
The root cause is the following: …
> graphql-federated-graph: fix rendering of @join__type on interfaces without keys

- Cargo.lock
- engine/crates/integration-tests/Cargo.toml
- engine/crates/integration-tests/tests/federation/entity_caching.rs
- engine/crates/integration-tests/tests/federation/entity_caching/redis.rs
- gateway/crates/gateway-binary/tests/entity_caching/mod.rs
- gateway/crates/gateway-binary/tests/integration_tests.rs
A very simple test of the gateways redis entity caching functionality, just to make sure we don't regress.  Didn't have time to add this earlier.
Fixes GB-7179
> test: redis entity caching

- engine/crates/composition/README.md
- engine/crates/federated-graph/src/render_sdl/display_utils.rs
- engine/crates/federated-graph/src/render_sdl/render_api_sdl.rs
- engine/crates/federated-graph/src/render_sdl/render_federated_sdl.rs
While working on this morning's fix, I noticed this module could really do with some love. Here's what this PR starts to address:
- Align render_federated_sdl() and render_api sdl() on `fmt::Formatter` based APIs instead of writing directly to a `String`.
- Reduce the number of different ways we render directives. This PR introduces a `DirectiveWriter` abstraction that should work in the whole crate.
- Avoid the proliferation of types that only hold FederatedGraph, an item and implement Display. Functions are more concise and easy to follow.
These changes should not affect the output in any way. We have pretty extensive tests in the graphql-federated-graph and graphql-composition crates so I am fairly confident that this is the case.
> federated-graph: start decluttering render_federated_sdl()

- cli/crates/federated-dev/src/dev.rs
- cli/crates/federated-dev/src/dev/gateway_nanny.rs
- engine/crates/engine-config-builder/src/from_sdl_config.rs
- engine/crates/engine-config-builder/src/from_toml_config.rs
- engine/crates/engine-v2/config/src/lib.rs
- engine/crates/engine-v2/config/src/v6.rs
- engine/crates/engine-v2/schema/src/builder/external_sources.rs
- engine/crates/engine-v2/schema/src/builder/graph.rs
- engine/crates/engine-v2/schema/src/builder/mod.rs
- engine/crates/engine-v2/schema/tests/conversion.rs
- engine/crates/integration-tests/src/federation/builder.rs
- engine/crates/integration-tests/src/federation/builder/bench.rs
- gateway/crates/federated-server/src/server/gateway.rs
This is a follow up to https://github.com/grafbase/grafbase/pull/2064.
We went into cycles of rendering and parsing federated SDL, creating the conditions for the bug in render_federated_sdl() to manifest on engine start up.
This change makes sure we parse only once, _either_ when constructing it when instantiating Config directly, _or_ during deserialization.
closes GB-7388
> engine-v2: avoid re-parsing of federated SDL

- Cargo.lock
- Cargo.toml
- cli/CHANGELOG.md
- cli/changelog/0.79.2.md
- cli/crates/backend/Cargo.toml
- cli/crates/cli/Cargo.toml
- cli/crates/federated-dev/Cargo.toml
- cli/crates/server/Cargo.toml
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
- engine/crates/runtime-local/Cargo.toml
__Fixes__
- federated dev:
- Less strict handling of Accept header (#2051)
- Remove subgraph urls from subgraph request errors (#2052)
- Fix introspection of defaults of enum type (#2057)
- fix grafbase create --mode=self-hosted outside of project context (#2054)
> cli: release 0.79.2

- engine/crates/engine-v2/schema/src/directives/requires_scopes.rs
- engine/crates/engine-v2/schema/src/walkers/field.rs
- engine/crates/engine-v2/src/operation/build.rs
- engine/crates/engine-v2/src/operation/cache_scopes.rs
- engine/crates/engine-v2/src/operation/mod.rs
- engine/crates/engine-v2/src/operation/modifier/query.rs
- engine/crates/engine-v2/src/operation/walkers/selection_set.rs
- engine/crates/engine-v2/src/sources/graphql/federation.rs
- engine/crates/engine-v2/src/sources/graphql/root_fields.rs
- engine/crates/federated-graph/src/federated_graph/v3.rs
- engine/crates/federated-graph/src/render_sdl/render_federated_sdl.rs
- engine/crates/graphql-mocks/src/federation/mod.rs
- engine/crates/graphql-mocks/src/federation/secure.rs
- engine/crates/graphql-mocks/src/lib.rs
- engine/crates/graphql-mocks/src/secure.rs
- engine/crates/integration-tests/tests/federation/entity_caching.rs
- engine/crates/integration-tests/tests/federation/entity_caching/directive_scopes.rs
When we're doing entity caching we need to consider whether the entity that we are caching was contained inside a type or field with `@authenticated` or `@requiresScopes`.  If it was we should include that fact in the cache key, so that we don't share a cache entry from an authenticated user with that of an unauthed user etc.
Fixes GB-7179
> feat: scope entity cache entries by auth directives

- .github/workflows/binaries.yml
- cli/Dockerfile
- docker/README.md
- docker/build.sh
- docker/mimalloc.diff
- gateway/Dockerfile
To read a full explanation: https://www.tweag.io/blog/2023-08-10-rust-static-link-with-mimalloc/
It's an old problem that profoundly bothered me. As Graeme started taking a look at build times in general, got me curious again as to why cargo builds were so much slower within a docker build than without on my machine. Almost an order of magnitude.
The short version is that the musl allocator behaves poorly in multi-threaded scenarios. So the author patched musl to use mimalloc. Now on my machine build times are comparable to those without docker instead of spending an absurd amount of time in kernel threads.
|               | Gateway | CLI   |
|---------------|---------|-------|
| base          | 15m30   | 19m50 |
| mimalloc musl | 5m30    | 6m35  |
| 8 -> 16 cores | 4m      | 4m40  |
> chore: Improve docker build time

- .github/actions/test/action.yml
This will download a binary instead of compiling cargo-component every single time.  Saves a couple of minutes per CI run - not a massive saving, but also not very much work to implement.
> chore: binstall cargo-component

- Cargo.lock
- engine/crates/telemetry/src/otel/layer.rs
- gateway/crates/gateway-binary/Cargo.toml
- gateway/crates/gateway-binary/src/args.rs
- gateway/crates/gateway-binary/src/args/lambda.rs
- gateway/crates/gateway-binary/src/args/log.rs
- gateway/crates/gateway-binary/src/args/std.rs
- gateway/crates/gateway-binary/src/main.rs
- gateway/crates/gateway-binary/src/telemetry.rs
By default "debug" and "trace" produce way too much information with h2,
hyper etc. So forcing them to stay at info. I'm also adding the
possibility to fully customize the log filter with a custom input. The
goal is to remove `__GRAFBASE_RUST_LOG` and be able to adjust the log
levels as needed. This will also help figuring out the best default
values.
> feat(gateway): better logs part 2

- engine/crates/telemetry/src/span/request.rs
Deleted in https://github.com/grafbase/grafbase/pull/2044 because we thought it was dead code. But there is at least one instance where it is used in the control plane.
> telemetry: re-add HttpRequestSpan::with_ray_id()

- Cargo.lock
- engine/crates/runtime/Cargo.toml
- engine/crates/runtime/src/hooks.rs
Otherwise the engine stops working on wasm32-unknown-unknown
> Use web_time::Instant instead of Instant from std in runtime::hooks

- .github/workflows/rust-prs.yml
I made a release of what-rust-changed so updating CI to download that instead of compiling from source every time.
> chore: fetch binaries of what-rust-changed

- engine/crates/graphql-schema-diff/src/patch/paths.rs
- engine/crates/graphql-schema-diff/src/patch/schema_definitions.rs
- engine/crates/graphql-schema-diff/src/patch/type_definitions.rs
- engine/crates/graphql-schema-diff/tests/patch/repro.graphql
- Removing a root from a schema definition now works. We would previously end up with declarations like:
```graphql
schema {
query: Query
mutation:
}
```
The reason being that graphql-schema-diff expresses removal as `ChangeQueryType` (or mutation, subscription, respectively) with an empty string as the type name. We may want to change that.
- In Paths::iter_exact(), we were taking the index of the path instead of the index of the change, which was incorrect any time the changes aren't sorted by path, which we can't guarantee.
> graphql-schema-diff: fix two bugs

- .github/what-rust-changed.toml
- .github/workflows/rust-prs.yml
Prior to this change the order of things was:
1. Debug clippy run of all pacakges
2. Tests
3. Debug build of binaries
Not certain but I suspect that this ends up duplicating some work - my theory is that the cargo check that clippy runs is discarding some work that the later cargo build needs to duplicate.  It's also possible that the test in the middle is picking up a slightly different set of features to the original check and that is causing some rebuilds.
This PR changes the order to build, clippy, tests.
Anyway, as always it's hard to be certain but the two times I've ran this in CI it ran in about 16 minutes - which is faster than the 20ish we had before.
> chore: build before clippy

- .github/what-rust-changed.toml
#2100 built the whole repository even though it should have only built wasi-component-loader and dependants.  The examples folder was also changed but it should have been ignored.
Turns out I'd messed up some globs in what-rust-changed.toml
> chore: fix globs in what-rust-changed.toml

- .github/actions/test_upload_datadog/action.yml
The junit upload to datadog step takes 2 minutes on windows.  That is ridiculously slow - it takes about 20 seconds on all other platforms.  As far as I can tell this is mostly the npm install - so I'm trying out downloading binaries directly on windows instead.
> chore: download datadog binaries on windows

- .github/actions/install-rust/action.yml
- .github/actions/install-what-rust-changed/action.yml
- .github/workflows/rust-prs.yml
This PR fixes a couple of things I noticed:
1. Somehow the action I was using to download what-rust-changed was consistently taking 3 minutes to run.  It only took around a minute to compile so 3 minutes to download was not an improvement. I've replaced it with a custom action that just downloads it directly and runs in a reasonable time.
2. I noticed that cargo was picking up the full list of targets from `rust-toolchain.toml` and installing all of them in every CI job.  Not a big deal, but it was slowing things down by a little bit for every job.  Using `rustup override set` causes rust to ignore the toolchains file, so I've done that.
3. Also extracted the rust install stuff into an action.  (There is the existing init-rust-job action I could put that in, but I want to leave the …
> chore: more ci tweaks

- Cargo.lock
- engine/crates/federated-graph/Cargo.toml
- engine/crates/federated-graph/src/from_sdl.rs
- engine/crates/federated-graph/src/from_sdl/arguments.rs
- engine/crates/federated-graph/src/from_sdl/value.rs
- engine/crates/federated-graph/src/render_sdl/display_utils.rs
- engine/crates/federated-graph/src/render_sdl/render_federated_sdl.rs
For `from_sdl()`. We are standardizing on cynic-parser, and we want to make that function more robust, progressively, so this has to happen.
> Replace async-graphql-parser with cynic-parser in graphql-federated-graph

- engine/crates/federated-graph/src/from_sdl.rs
When converting values from the parser to a FederatedGraph, until now, when encountering `null` in the schema, that was translated to `"null"` as a string. We have Value::Null, so that feels like a mistake.
Noticed by @obmarg [here](https://github.com/grafbase/grafbase/pull/2105#discussion_r1747177815).
> graphql-federated-graph: translate Null to Null and not "null"

- engine/crates/engine-v2/src/operation/bind/field.rs
- engine/crates/engine-v2/src/operation/bind/mod.rs
- engine/crates/federated-graph/src/federated_graph/v4.rs
- engine/crates/integration-tests/tests/federation/basic/errors.rs
- engine/crates/integration-tests/tests/federation/inaccessible.rs
- engine/crates/integration-tests/tests/federation/mod.rs
An argument with `@inaccessible` should be treated as if it wasn't defined at all. What I found out testing this is that so far, we have not been validating against the usage of unknown arguments (they were just ignored). So there are two tests in this commit: one for the general case, and one for inaccessible. The implementation is the same, becausue we were already (correctly) removing inaccessible arguments in the conversion from FederatedGraph to engine_v2::Schema.
> engine-v2: enforce inaccessibility of inaccessible arguments

- Cargo.lock
- engine/crates/engine-v2/Cargo.toml
- engine/crates/engine-v2/axum/Cargo.toml
- engine/crates/engine-v2/schema/Cargo.toml
- engine/crates/gateway-core/Cargo.toml
- gateway/CHANGELOG.md
- gateway/Makefile.toml
- gateway/crates/config/Cargo.toml
- gateway/crates/federated-server/Cargo.toml
- gateway/crates/gateway-binary/Cargo.toml
- gateway/crates/rolling-logger/Cargo.toml
In version 0.12.0, we introduced a streamlined method for logging and storing access information using the Gateway Hooks. In this version we rewrote the logger into a faster and more minimal version. Now, you can rotate the log based on file size, configurable as follows:
```toml
[gateway.access_logs]
enabled = true
path = "./logs"
rotate.size = 10_000_000 # bytes
```
The rotation mechanism is now standardized. The active log file is named `access.log`. When a rotation occurs, we rename this file to `access.log.X`, where X is the timestamp of the original log file's creation.
- Enforced inaccessibility of inaccessible arguments.
- Engine returns `null` for inaccessible enum values.
- Parser correctly handles null values.
- Replaced the parser crate with a faster alternative, improving …
> chore: bump gateway to 0.13.0

- Cargo.lock
- gateway/changelog/0.14.0.md
- gateway/crates/config/Cargo.toml
- gateway/crates/config/src/lib.rs
- gateway/crates/config/src/size_ext.rs
- gateway/crates/federated-server/src/server/access_logs.rs
Support:
```toml
[gateway.access_logs]
enabled = true
path = "./logs"
rotate.size = "200MiB"
```
> feat(gateway-config): Support specifying access log size as 2kiB

- .github/workflows/rust-prs.yml
For some reason I thought this was already the case, but it wasn't - which was allowing issues like #2124 to get through CI
> chore: deny warnings on pull requests

- .github/workflows/rust-prs.yml
Some steps in the build job should only be run if one of the previous jobs has been run.  Instead of encoding that specifically I'd copied over the `if` statement from the previous job.  This is kinda fragile because if you change one condition you have to remember to change the other, which obviously is going to be forgotten and lead to problems.
> fix: some better conditionals in pr action

- .github/workflows/rust-prs.yml
- Cargo.lock
Not sure how, but missed this in 27b885a.  May have been a merge thing, or may have been broken on the branch because CI wasn't doing `--locked` (which I've also fixed in this)
> fix: update Cargo.lock

- renovate.json
The workspace-hack Cargo.toml is generated with cargo hakari - if renovate goes in there and tries to update it will not do the right thing, so we should just ignore it for now.
A side effect of this that I hadn't considered is that we'll almost definitely need to run `cargo hakari` manually on renovate branches which is a little bit annoying.  Would be nice if there was some way to automate it though I can't see any obvious options. Although it does seem like these often need manual intervention anyway, so I'm not sure if this is a new problem.
> chore: renovate should ignore workspace-hack

- engine/crates/engine-v2/codegen/domain/schema.graphql
- engine/crates/engine-v2/codegen/src/domain.rs
- engine/crates/engine-v2/codegen/src/domain/record.rs
- engine/crates/engine-v2/codegen/src/generation/object/debug.rs
- engine/crates/engine-v2/codegen/src/loader.rs
- engine/crates/engine-v2/schema/src/generated/field.rs
- engine/crates/engine-v2/schema/src/interface.rs
- engine/crates/engine-v2/schema/src/object.rs
Debug impl of an object adds the object fields to the output. If one of these fields references the same object, we have endless recursion.
This fix just prints the field name, not the whole field.
> fix(engine-v2): fix endless recursion in object debug

- .github/actions/test/action.yml
I'd disabled the audit tests in the PR workflow, but not the release & main workflows.
Going to enable it again in the PR CI later, but defnitely don't want it causing problems on main/release.
> fix: disable audit tests in other ci workflows

- .github/workflows/federation-audit.yml
- engine/crates/federation-audit-tests/tests/checkout.rs
Added the federation-audit-tests into their own workflow.  These will not fail the build, and will just post a comment summarising the current state of the audit tests.  
I wanted to output a non-failing check with more details but I couldn't find a way to make it non-failing, and having that red cross on every single build seemed annoying.
> feat: run federation-audit-tests on ci

- engine/crates/graphql-schema-diff/src/patch.rs
- engine/crates/graphql-schema-diff/src/patch/directives.rs
- engine/crates/graphql-schema-diff/src/patch/schema_definitions.rs
- engine/crates/graphql-schema-diff/src/patch/type_definitions.rs
- engine/crates/graphql-schema-diff/tests/patch/no_change.graphql
Before this commit, the "extend ..." would be lost in patching.
Additionally, two small fixes:
- Missing comma separator between arguments of directives, now correctly inserted.
- Do not render the curly braces in a schema definition / extension if it defines no root type.
closes GB-7600
> graphql-schema-diff: handle schema and type definition extensions

- .github/workflows/federation-audit.yml
- engine/crates/federation-audit-tests/tests/audit_tests.rs
Our implementation of the audit tests and the original one from the guild disagreed slightly: we had 2 more failures than they did.
This turned out to be the mysterious-external tests: their test data contains `price: 100` but the engine is returning `price: 100.0`. `serde_json` considers these to not be equal, so we were getting a false failure.
I've fixed that in this PR by just converting all numbers to floats before comparing.  There may be some edge cases for which this doesn't work, but it does give us the same numbers as the guild so I think we're good for now.
> fix: the mysterious-external audit tests

- engine/crates/federation-audit-tests/src/audit_server.rs
- engine/crates/federation-audit-tests/src/lib.rs
- engine/crates/federation-audit-tests/src/response.rs
- engine/crates/federation-audit-tests/tests/audit_tests.rs
We were simplfiying to `errors: bool` for the sake of comparison but it's useful to actually see the errors when you get some unexpected errors.
> fix: show error details in failed audit tests

- engine/crates/federation-audit-tests/src/audit_server.rs
- engine/crates/federation-audit-tests/src/response.rs
- engine/crates/federation-audit-tests/tests/audit_tests.rs
Using the similar_asserts inners gets us a couple of improvements:
1. We can label the diffs with expected & actual rather than left & right.
2. We can diff on JSON which is less noisy than diffing on the Debug output that similar_asserts uses by default.
Before:
After:
> fix: better diffs in failed audit tests

- Cargo.lock
- Cargo.toml
- engine/crates/engine-v2/codegen/src/loader.rs
- engine/crates/federated-graph/src/from_sdl.rs
- engine/crates/federated-graph/src/from_sdl/value.rs
- engine/crates/federation-audit-tests/Cargo.toml
- engine/crates/federation-audit-tests/src/audit_server.rs
- engine/crates/federation-audit-tests/src/cache.rs
- engine/crates/federation-audit-tests/tests/composition_comparisons.rs
- engine/crates/partial-caching/src/planning/visitor.rs
- engine/crates/partial-caching/src/query_subset/display.rs
- engine/crates/partial-caching/src/query_subset/field_iter.rs
- engine/crates/partial-caching/src/query_subset/mod.rs
- engine/crates/partial-caching/src/updating/ser.rs
- workspace-hack/Cargo.toml
Runnable with
```sh
CLICOLOR_FORCE=1 cargo nextest run -p federation-audit-tests  --no-fail-fast --test composition_comparisons --run-ignored all
```
> test: use audit tests to compare composition outputs

- engine/crates/engine-v2/src/execution/hooks/authorized.rs
- engine/crates/engine-v2/src/execution/hooks/responses.rs
- engine/crates/engine-v2/src/execution/hooks/subgraph.rs
- engine/crates/engine-v2/src/sources/graphql/context.rs
- engine/crates/engine-v2/src/sources/graphql/request/execute.rs
- engine/crates/engine-v2/src/sources/graphql/subscription.rs
- engine/crates/telemetry/src/span/subgraph.rs
So this goes from this trace:
Into this:
And as a comparison, if disabling the access log hooks, we get this:
And as a final thing, I added a span for the actual http request and renamed the subgraph span with the subgraph name, so now we look like this:
> fix(tracing): remove spammy spans and nest subgraph things under subgraph request

- engine/crates/composition/src/compose/context.rs
- engine/crates/composition/src/composition_ir.rs
- engine/crates/composition/src/emit_federated_graph.rs
- engine/crates/engine-v2/schema/src/builder/graph.rs
- engine/crates/engine-v2/schema/src/builder/ids.rs
- engine/crates/engine-v2/schema/src/builder/mod.rs
- engine/crates/federated-graph/src/federated_graph/v4.rs
- engine/crates/federated-graph/src/federated_graph/v4/type.rs
- engine/crates/federated-graph/src/federated_graph/v4/type_definitions.rs
- engine/crates/federated-graph/src/from_sdl.rs
- engine/crates/federated-graph/src/render_sdl/render_api_sdl.rs
- engine/crates/federated-graph/src/render_sdl/render_federated_sdl.rs
That already allows us to delete federated_graph::Scalar.
> federated-graph: migrate more fields to TypeDefinition

- engine/crates/composition/CHANGELOG.md
- engine/crates/composition/src/lib.rs
- engine/crates/composition/src/subgraphs.rs
- engine/crates/composition/tests/composition_special_cases.rs
- engine/crates/composition/tests/composition_tests.rs
- engine/crates/federation-audit-tests/tests/composition_comparisons.rs
- engine/crates/integration-tests/src/federation/builder/engine.rs
- gateway/crates/gateway-binary/tests/entity_caching/mod.rs
- gateway/crates/gateway-binary/tests/telemetry/tracing.rs
To avoid exposing async_graphql_parser as part of our public API.
> composition: add Subgraph::ingest_str()

- Cargo.lock
- Cargo.toml
- engine/crates/engine-v2/query-planning/Cargo.toml
- engine/crates/engine-v2/query-planning/src/graph.rs
- engine/crates/engine-v2/query-planning/src/graph/builder.rs
- engine/crates/engine-v2/query-planning/src/graph/edge.rs
- engine/crates/engine-v2/query-planning/src/graph/node.rs
- engine/crates/engine-v2/query-planning/src/lib.rs
- engine/crates/engine-v2/query-planning/src/tests.rs
- engine/crates/engine-v2/schema/src/field.rs
- engine/crates/engine-v2/schema/src/field_set/requires.rs
- engine/crates/engine-v2/schema/src/resolver.rs
- engine/crates/engine-v2/schema/src/subgraph.rs
- engine/crates/engine-v2/src/execution/planner/builder.rs
- engine/crates/engine-v2/src/operation/logical_planner/selection_set.rs
- engine/crates/engine/parser/src/types/executable.rs
- engine/crates/wrapping/src/lib.rs
Simple initial PR to generate the operation graph with all fields and
requirements recursively. Taken from the tests:
```graphql
enum join__Graph {
ACCOUNTS @join__graph(name: "accounts", url: "http://accounts:4001/graphql")
INVENTORY @join__graph(name: "inventory", url: "http://inventory:4002/graphql")
PRODUCTS @join__graph(name: "products", url: "http://products:4003/graphql")
REVIEWS @join__graph(name: "reviews", url: "http://reviews:4004/graphql")
}
type Product
@join__type(graph: INVENTORY, key: "upc")
@join__type(graph: PRODUCTS, key: "upc")
@join__type(graph: REVIEWS, key: "upc")
{
upc: String!
weight: Int @join__field(graph: INVENTORY, external: true) @join__field(graph: PRODUCTS)
price: Int @join__field(graph: INVENTORY, external: true) @join__field(graph: PRODUCTS)
inStock: …
```
> feat(engine-v2/qp): Generate operation graph.

- cli/crates/backend/src/api/graphql/api.graphql
- cli/crates/backend/src/api/graphql/types/mutations.rs
- cli/crates/backend/src/api/graphql/types/queries/project_slug_by_id.rs
- cli/crates/backend/src/api/graphql/types/queries/viewer_for_link.rs
- cli/crates/backend/src/api/link.rs
- cli/crates/backend/src/api/logs.rs
- cli/crates/backend/src/api/publish.rs
- cli/crates/backend/src/api/types.rs
- cli/crates/cli/src/cli_input/publish.rs
- cli/crates/cli/src/link.rs
- cli/crates/cli/src/output/report.rs
- cli/crates/cli/src/publish.rs
The presence of the argument will cause a newly produced schema version to be annotated with the provided message.
> GB-7696: Add support for the `message` argument to the `publish` command

- engine/crates/composition/tests/composition/authenticated_basic/api.graphql
- engine/crates/composition/tests/composition/requiresScopes_basic/api.graphql
- engine/crates/federated-graph/src/render_sdl/render_api_sdl.rs
These are not public directives.
closes GB-7761
> federated-graph: stop rendering @authenticated and @requiresScope in api SDL

- engine/crates/validation/CHANGELOG.md
- engine/crates/validation/src/context.rs
- engine/crates/validation/src/validate.rs
- engine/crates/validation/src/validate/schema_definition.rs
- engine/crates/validation/tests/valid_schemas/schema_extension_then_definition.graphql
For the purpose of duplicate schema definition validation.
closes GB-7760
> validation: do not consider schema extensions as schema definitions

- engine/crates/runtime-local/src/hooks/pool.rs
- gateway/crates/gateway-binary/tests/telemetry/metrics/access_log.rs
New metric: `grafbase.hook.pool.instances.busy`, which is a up/down counter of the number of wasi instances in use in the pool. Goes up when taking an instance from the pool, and down when an instance is returned. Holds an attribute `grafbase.hook.interface` marking the interface instantiated in the pool.
> feat: metrics for wasm pool size

- engine/crates/integration-tests/src/federation/builder/engine.rs
- engine/crates/runtime-local/src/hooks.rs
- engine/crates/runtime-local/src/hooks/pool.rs
- engine/crates/wasi-component-loader/src/config.rs
- gateway/crates/config/src/hooks.rs
- gateway/crates/federated-server/src/server.rs
The user can now configure the size of an instance pool in the hooks:
```toml
[hooks]
location = "target/wasm32-wasip1/release/hooks.wasm"
max_pool_size = 1000
```
If not set, the default is four times the number of CPUs.
> feat: wasm pool size configuration option

- Cargo.lock
- gateway/CHANGELOG.md
- gateway/changelog/0.16.0.md
- gateway/crates/config/Cargo.toml
- gateway/crates/federated-server/Cargo.toml
- gateway/crates/gateway-binary/Cargo.toml
- gateway/crates/rolling-logger/Cargo.toml
Added a new configuration option to override the subgraph URL in the TOML configuration file. This option allows you to specify the URL of the subgraph that the gateway should use. By default the gateway uses the URL specified in the schema registry. By setting a different URL in the TOML configuration file, you can override the default behavior.
Example configuration:
```toml
[subgraphs.products]
url = "https://example.com/graphql"
```
Introduced a new configuration option for hooks pool size. This configuration option allows you to set the maximum number of hooks that can be executed concurrently. The default value is four times the number of CPUs, but now you can adjust this value based on your requirements.
Example configuration:
```toml
[hooks]
max_pool_size = 1000
```
Added metrics …
> chore: bump Gateway to 0.16.0

- Cargo.lock
- engine/crates/engine-v2/Cargo.toml
- engine/crates/engine-v2/src/engine/execute.rs
- engine/crates/engine-v2/src/engine/execute/prepare.rs
- engine/crates/engine-v2/src/engine/execute/single.rs
- engine/crates/engine-v2/src/execution/context.rs
- engine/crates/engine-v2/src/execution/coordinator.rs
- engine/crates/engine-v2/src/execution/planner/mod.rs
- engine/crates/engine-v2/src/sources/graphql/federation.rs
- engine/crates/engine-v2/src/sources/graphql/root_fields.rs
- engine/crates/integration-tests/src/lib.rs
This PR improves our latencies with two improvements:
- use of `spawn_blocking`/ `block_inplace` in the most CPU-consuming parts to improve Tokio's scheduling. This improved my tail latencies in a few cases, but hard to measure accurately. This comes at the cost of additional CPU use.
- The core inner loop of the operation execution is roughly:
```rust
let subgraph_requests = FuturesUnordered::new();
while let Some(...) = subgraph_requests.next().await {
// ingest response
// prepare next subgraph requests
}
```
The problem is that we're not awaiting the `subgraph_requests` while doing the ingestion/preparation so it's not moved forward by Tokio. I've changed that so they're executed simultaneously
> Coordinator futures

- Cargo.lock
- engine/crates/engine-v2/id-newtypes/Cargo.toml
- engine/crates/engine-v2/id-newtypes/src/bitset.rs
- engine/crates/engine-v2/src/operation/blueprint/mod.rs
- engine/crates/engine-v2/src/operation/logical_planner/mod.rs
- engine/crates/engine-v2/src/operation/modifier/query.rs
- engine/crates/integration-tests/benches/federation/basic.rs
- engine/crates/integration-tests/benches/federation/complex_shape.rs
- engine/crates/integration-tests/benches/federation/introspection.rs
- engine/crates/wasi-component-loader/Cargo.toml
- workspace-hack/Cargo.toml
We're fixing dependency versions quite strictly for a reason that escapes me. We miss updates like this one: https://github.com/serde-rs/json/pull/1206. So relaxed a few of those. And fixed the benchmarks now that we're using `spawn_blocking` inside the engine
> Update deps & fix benchmarks

- engine/crates/engine-v2/src/engine/execute/prepare.rs
- engine/crates/engine-v2/src/sources/graphql/context.rs
- engine/crates/engine-v2/src/sources/graphql/request/execute.rs
- engine/crates/runtime-local/src/rate_limiting/redis.rs
- engine/crates/runtime/src/fetch.rs
This was a bit trickier. So my first try was to just add the span if we define a global or subgraph limit, but the result was not quite right:
As we can see, in the subgraph, we have the rate limit span, but the request was never sent because we hit the rate limit. We still have the span `POST /graphql`, which was never actually requested.
Eventually the right fix to do is to create one `POST /graphql` span per HTTP request. First thing is that we create the span _only_ when we call the subgraph. This means if we retry, we will have more `POST /graphql` spans per retry. This makes the propagated spans from the subgraphs look nicer, because we can track which HTTP request triggered which span.
The result of the rate limited trace looks pretty nice after this PR:
And this is how a …
> fix: add rate limit span if using redis

- engine/crates/composition/CHANGELOG.md
- engine/crates/composition/tests/composition/authorized_basic/federated.graphql
- engine/crates/composition/tests/composition/authorized_basic/subgraphs/bank_account.graphql
- engine/crates/federated-graph/src/render_sdl/display_utils.rs
We were erroneously quoting the keys, like in a JSON object, that is `{"a": true}` instead of the correct GraphQL literal `{a: true}`.
closes GB-7797
> Fix rendering of object literals in render_federated_sdl()

- engine/crates/composition/src/lib.rs
- engine/crates/composition/tests/composition_tests.rs
- engine/crates/engine-v2/config/src/lib.rs
- engine/crates/federated-graph/src/federated_graph/v1.rs
- engine/crates/federated-graph/src/federated_graph/v4.rs
- engine/crates/federated-graph/src/lib.rs
- engine/crates/federated-graph/src/render_sdl/render_federated_sdl.rs
- engine/crates/federation-audit-tests/tests/composition_comparisons.rs
- engine/crates/integration-tests/src/federation/builder/engine.rs
- gateway/crates/federated-server/src/server/gateway.rs
- gateway/crates/gateway-binary/tests/entity_caching/mod.rs
- gateway/crates/gateway-binary/tests/telemetry/tracing.rs
When composition produces a FederatedGraph, and a rendering error in graphql-federated-graph produces bad SDL, that SDL gets parsed and the result unwrapped in `VersionedFederatedGraph::into_latest()`.
This makes `into_latest()` return a `Result`, and introduces `FederatedGraph::from_sdl()` for convenience. Errors are handled everywhere outside of tests now.
closes GB-7796
> graphql-federated-graph: handle us producing bad SDL without panicking

- gateway/crates/config/src/lib.rs
- gateway/crates/config/src/message_signatures.rs
Adds the config for message signatures as outlined in the RFC.  This doesn't do anything yet, I'll hook it up in a future PR.
Fixes GB-7772
> feat: add gateway config for message signatures

- engine/crates/composition/CHANGELOG.md
- engine/crates/composition/src/ingest_subgraph/directives.rs
- engine/crates/composition/tests/composition/authorized_with_composeDirective/api.graphql
- engine/crates/composition/tests/composition/authorized_with_composeDirective/federated.graphql
- engine/crates/composition/tests/composition/authorized_with_composeDirective/subgraphs/pets.graphql
- engine/crates/composition/tests/composition/authorized_with_composeDirective/subgraphs/users.graphql
This fixes composed schemas with subgraphs schemas introspected from async-graphql having `@authorized` twice on fields.
The `@authorized` directive is a special case. Directives used in subgraph schemas are either built-in federation directives (`@requires`, `@key`, etc.) or custom, composed directives with `@composeDirective`. Since `@authorized` is not part of the federation spec, some frameworks like async-graphql (Rust) will produce an `@composeDirective` with the `@authorized` directive. We should not consider `@authorized` as a composed directive however, because that means we would emit it again.
closes GB-8706
> composition: ignore `@composeDirective(name: "@authorized")`

- engine/crates/engine-v2/src/sources/graphql/federation.rs
This is not useful in our tracing.
> chore: remove prepare_request span

- Cargo.lock
- gateway/CHANGELOG.md
- gateway/changelog/0.17.0.md
- gateway/crates/config/Cargo.toml
- gateway/crates/federated-server/Cargo.toml
- gateway/crates/gateway-binary/Cargo.toml
- gateway/crates/rolling-logger/Cargo.toml
- Include spans from Redis rate limiting in the tracing data (#2244)
- Fix for propagating the correct span to subgraphs (#2243)
- Hide a few unnecessary spans from the tracing data (#2268)
> chore: bump gateway to 0.17.0

- engine/crates/validation/CHANGELOG.md
- engine/crates/validation/src/validate/directive_definitions.rs
- engine/crates/validation/src/validate/type_definition.rs
- engine/crates/validation/tests/valid_schemas/yoga_subgraph.graphql
- engine/crates/validation/tests/validation_errors/directive_name_and_args.errors.txt
Validation of the types of arguments inside directive definitions worked only for types defined before the directive definition. That would lead to incorrect validation errors about scalar or input types not existing. Validation of argument types in directive definitions now properly takes all types into account.
The solution is, like for fields of types, to move validation of the arguments to the second pass of schema validation, where all types are known.
closes GB-7859
> graphql-schema-validation: fix validation of directive definition argument types

- Cargo.lock
- engine/crates/engine-v2/Cargo.toml
- engine/crates/engine-v2/query-planning/src/graph.rs
- engine/crates/engine-v2/query-planning/src/graph/builder.rs
- engine/crates/engine-v2/query-planning/src/steiner_tree/shortest_path.rs
- engine/crates/engine-v2/query-planning/src/tests/mod.rs
- engine/crates/engine-v2/src/operation/mod.rs
- engine/crates/engine-v2/src/operation/modifier/mod.rs
- engine/crates/engine-v2/src/operation/plan/adapter.rs
- engine/crates/engine-v2/src/operation/plan/error.rs
- engine/crates/engine-v2/src/operation/plan/mod.rs
- engine/crates/engine-v2/src/operation/prepare.rs
- engine/crates/engine-v2/src/operation/selection_set.rs
Adapter between the current `engine_v2::Operation` and query planning crate. Only running it with a feature flag that I use manually for now.
> chore(engine-v2/qp): run initial part of QP on feature flag

- engine/crates/engine-v2/query-planning/src/graph.rs
- engine/crates/engine-v2/query-planning/src/graph/builder.rs
- engine/crates/engine-v2/query-planning/src/tests/mod.rs
- engine/crates/engine-v2/src/operation/plan/adapter.rs
- engine/crates/engine-v2/src/operation/plan/mod.rs
When adding extra fields I don't generate a response key immediately for them as they may not be needed. Once I know which one I need I do while ensuring it doesn't clash with any existing field in the same selection set.
The response key is the key in the final JSON response, so taking into account aliases, I also use it internally to keep track of the response path for errors and in the internal response data. So every field must have one.
> chore(engine-v2/qp): Generate response keys for extra fields

- engine/crates/engine-v2/codegen/domain/schema.graphql
- engine/crates/engine-v2/codegen/src/domain/record.rs
- engine/crates/engine-v2/codegen/src/domain/union.rs
- engine/crates/engine-v2/codegen/src/generation/docstr.rs
- engine/crates/engine-v2/codegen/src/generation/object/struct_.rs
- engine/crates/engine-v2/codegen/src/generation/object/walker.rs
- engine/crates/engine-v2/codegen/src/generation/union/enum_.rs
- engine/crates/engine-v2/codegen/src/generation/union/walker.rs
- engine/crates/engine-v2/codegen/src/loader.rs
- engine/crates/engine-v2/schema/src/composite_type.rs
- engine/crates/engine-v2/schema/src/generated/composite_type.rs
- engine/crates/engine-v2/schema/src/generated/mod.rs
- engine/crates/engine-v2/schema/src/lib.rs
Today I use `SelectionSetType` which isn't that great. So using the term the GraphQL spec used to use.
> chore(engine-v2): Add CompositeType for union/object/interface

- engine/crates/runtime-local/src/fetch/signing.rs
- gateway/crates/config/src/message_signatures.rs
When implementing this I realised that the configuration I'd specified for message signing probably didn't make sense:
1. I'm not sure there's ever any harm in including a created date - httpsig does it by default, and if we removed it that could cause a panic if the user provided expiry.  Additionally its recommended that you include it in the spec. So unless someone requests that we remove I think it makes sense to just always have it
2. If we have a KID I think we should just include it, same with the algorithm.
This just leaves the nonce parameter, which I've added support for.
Fixes GB-7858
> feat: signature parameters for message signing

- engine/crates/integration-tests/data/sse-subgraph/Dockerfile
Apparently semgrep is complaining that this Dockerfile doesn't have a user in it.  It's only for tests so it really doesn't matter, but it's also easy to fix.
Fixes GB-7912
> chore: add a user in dockerfile

- engine/crates/composition/src/compose/enums.rs
- engine/crates/composition/tests/composition/enum_unused/api.graphql
- engine/crates/composition/tests/composition/enum_unused/federated.graphql
While testing a separate composition change I wrote a schema that didn't use an enum.  I was surprised to find that enum wasn't in the output of composition.  
It seems like this was intentional, but have been speaking to @tomhoule and we agreed it's probably not right.  It shouldn't _hurt_ to remove these types since they're not used, but we don't treat any other unused types like this so it's a bit surprising.
> fix: dont omit unused enums in composition

- cli/about.toml
- Approve SSLeay-standalone and OpenSSL-standalone licenses, needed for `ring`
> SSLeay-standalone and OpenSSL-standalone licenses

- Cargo.lock
- gateway/crates/gateway-binary/Cargo.toml
- gateway/crates/gateway-binary/src/args/std.rs
- gateway/crates/gateway-binary/src/telemetry.rs
- Removes use of `atty` due to low level CVE and native Rust support
> GB-7972 - Remove `atty` due to security issues and native support

- engine/crates/composition/CHANGELOG.md
- engine/crates/composition/README.md
- engine/crates/composition/src/compose.rs
- engine/crates/composition/src/compose/reserved_names.rs
- engine/crates/composition/tests/composition/subgraph_defining_join__Graph/federated.graphql
- engine/crates/composition/tests/composition/subgraph_defining_join__Graph/subgraphs/bad.graphql
It's a reserved name for the enum defined in the federated SDL.
closes GB-7946
> composition: validate that subgraphs do not define join__Graph

- Cargo.lock
- engine/crates/composition/Cargo.toml
- engine/crates/composition/src/ingest_subgraph/directives.rs
- engine/crates/federated-graph/Cargo.toml
- engine/crates/federated-graph/src/directives/complexity_control.rs
- engine/crates/federated-graph/src/directives/deprecated.rs
- engine/crates/federated-graph/src/directives/mod.rs
- engine/crates/federated-graph/src/from_sdl.rs
- engine/crates/federated-graph/src/lib.rs
This PR has two changes:
1. It pulls the crate I introduced in #2329 into composition so we can derive directive parsing based on structs.
2. It adds structs to cover `@cost` & `@deprecated` into `federated-graph` and updates the directive handling in `composition` & `federated-graph` to use them.
If we like this approach we can expand to the other directives later, this seemed like a small enough change to gather feedback & make sure things actually work.
> chore: consolidate parsing of `@cost` & `@deprecated`

- crates/engine/schema/src/builder/graph.rs
- crates/graphql-composition/src/compose.rs
- crates/graphql-composition/src/compose/context.rs
- crates/graphql-composition/src/compose/directives.rs
- crates/graphql-composition/src/compose/entity_interface.rs
- crates/graphql-composition/src/compose/fields.rs
- crates/graphql-composition/src/compose/interface.rs
- crates/graphql-composition/src/compose/object.rs
- crates/graphql-composition/src/compose/roots.rs
- crates/graphql-composition/src/composition_ir.rs
- crates/graphql-composition/src/composition_ir/directive.rs
- crates/graphql-composition/src/emit_federated_graph.rs
- crates/graphql-composition/src/emit_federated_graph/context.rs
- crates/graphql-composition/src/emit_federated_graph/emit_list_sizes.rs
- crates/graphql-composition/src/subgraphs/directives.rs
- crates/graphql-composition/tests/composition/list_size/api.graphql
- crates/graphql-composition/tests/composition/list_size/federated.graphql
- crates/graphql-composition/tests/composition/list_size/subgraphs/a.graphql
- crates/graphql-federated-graph/src/directives/complexity_control.rs
- crates/graphql-federated-graph/src/federated_graph.rs
- crates/graphql-federated-graph/src/federated_graph/directives.rs
- crates/graphql-federated-graph/src/federated_graph/directives/list_size.rs
- crates/graphql-federated-graph/src/from_sdl.rs
- crates/graphql-federated-graph/src/from_sdl/list_size.rs
- crates/graphql-federated-graph/src/render_sdl/display_utils.rs
- crates/graphql-federated-graph/src/render_sdl/render_api_sdl.rs
- crates/graphql-federated-graph/src/render_sdl/render_federated_sdl.rs
I added support for `@listSize` in #2338 - but once I started trying to use it in engine I realised that I'd done a bad job.  I'd kept the two `[String]` arguments as strings - but these refer to fields & arguments so would be better converted into the corresponding Ids so that the engine doesn't have to do a bunch of string lookups when it's trying to calculate the complexity.
This was harder than it sounds, because the `sizedFields` argument refers to the fields of another object, which isn't necessarily available at the point where we're handling most of the directives.  Got there in the end though.
Fixes GB-7642 (again)
> fix: redo `@listSize` in composition

- crates/engine/codegen/domain/schema.graphql
- crates/engine/codegen/domain/solved_operation.graphql
- crates/engine/query-solver/src/lib.rs
- crates/engine/query-solver/src/solve/solution.rs
- crates/engine/query-solver/src/tests/mod.rs
- crates/engine/schema/src/builder/graph.rs
- crates/engine/schema/src/generated/field.rs
- crates/engine/schema/src/introspection.rs
- crates/engine/src/operation/bind/field.rs
- crates/engine/src/operation/bind/model/selection_set.rs
- crates/engine/src/operation/bind/selection_set.rs
- crates/engine/src/operation/plan/model/field/data.rs
- crates/engine/src/operation/solve/model/generated/field/data.rs
- crates/engine/src/operation/solve/model/prelude.rs
- crates/engine/src/operation/solve/solver/adapter.rs
- crates/engine/src/operation/solve/solver/mod.rs
- crates/engine/src/operation/solve/solver/shapes/mod.rs
- crates/engine/src/resolver/graphql/request/prepare.rs
- crates/engine/src/resolver/introspection/writer.rs
- crates/engine/src/response/key/private.rs
- crates/engine/src/response/shape/field.rs
- crates/federation-audit-tests/tests.json
- crates/graphql-composition/src/emit_federated_graph.rs
- crates/graphql-federated-graph/src/federated_graph.rs
- crates/graphql-federated-graph/src/from_sdl.rs
- crates/graphql-federated-graph/src/render_sdl/render_federated_sdl.rs
- flake.nix
Had to add the `JoinFields` struct in federated graph to keep track of the `type` in `@join__field`. I'll change that in a further PR to keep track of all the `@join_field` information in a `directives` attributes.
Explained the problem there https://github.com/grafbase/grafbase/pull/2344/files#diff-ac90207e5a538e9a94040951df4e2fcc504f9ecad005a706274a4a1709764479 near the end. In short, the subgraph has a field of type `ID!` and in the supergraph it ends being `ID`. That's fine most of time except when you send an union to the subgraph where it can break with something like:
```graphql
{ ... on User { id } ... on Account { id } }
```
In the supergraph both have the same type `ID`, but in the subgraph one has `ID!` and the other has `ID`, so the query fails. So we need to send the …
> chore(engine): Fix child-type-mismatch

- crates/graphql-composition/src/compose/context.rs
- crates/graphql-composition/src/compose/entity_interface.rs
- crates/graphql-composition/src/composition_ir.rs
- crates/graphql-composition/src/composition_ir/field_ir.rs
- crates/graphql-composition/src/emit_federated_graph.rs
These are just indices into fields Vec, they shouldn't be typed as FieldIds because they wouldn't refer to valid fields in the federated graph.
> composition: remove the usage of FieldId in CompositionIr

- crates/graphql-composition/src/compose.rs
- crates/graphql-composition/src/compose/context.rs
- crates/graphql-composition/src/compose/entity_interface.rs
- crates/graphql-composition/src/compose/interface.rs
- crates/graphql-composition/src/compose/object.rs
- crates/graphql-composition/src/compose/roots.rs
- crates/graphql-composition/src/composition_ir.rs
- crates/graphql-composition/src/composition_ir/field_ir.rs
- crates/graphql-composition/src/emit_federated_graph.rs
- crates/graphql-composition/src/emit_federated_graph/emit_fields.rs
Remove object_fields_from_entity_interfaces. That required changing the parent definition from DefinitionId to StringId in FieldIr, because we may not have the definition for the implementers of the interface yet when we compose the interface.
> composition: simplify entity interfaces in composition IR

- crates/graphql-composition/src/diagnostics.rs
- crates/graphql-composition/src/ingest_subgraph/directives.rs
- crates/graphql-composition/src/subgraphs.rs
- crates/graphql-composition/tests/composition/subgraph_defining_join__Graph/federated.graphql
This change is up for debate, but it would have saved me an hour or two of digging and seems like something a customer could run into.
I was trying to integration test `@cost`, but for some reason none of the validations were failing.  This turned out to be because the `@link` directive was used in my schema but didn't explicitly list `@cost`.  In this scenario we still support `@cost` but we expect it to be named something like `@federated__cost` - if we see `@cost` it is just ignored.
The behaviour around renames is correct, but we could make it a lot easier to notice when this sort of thing has happpened.  This PR is an attempt to do that: when we encounter a directive that we do not know about we'll put out a warning telling the user.
> feat: warn on unknown directive in composition

- .github/workflows/binaries.yml
- .github/workflows/rust-prs.yml
The `docker push --all-tags` pushes all local image tags, that includes
`latest` that the CI always pulls to speed up a bit the docker image
build.
So our feature branch ended up pushing whatever latest tag they
retrieved, overwriting any docker image pushed by a commit merged to
main in the meantime.
> fix(ci): broken latest dockage image push

- .github/workflows/rust-prs.yml
Caching _should_ be able to use ubicloud transparently now, let's test it out.
> chore: remove buildjet caching

- cli/nix/cli.nix
- flake.lock
- flake.nix
- gateway/nix/grafbase-gateway.nix
They haven't been maintained in a while, they were broken with the recent cleanups.
This commit freshens up flake.nix, and makes `nix build .#cli` and `nix build .#gateway` work again.
> Fix nix derivations for gateway and cli

- crates/engine/codegen/domain/solved_operation.graphql
- crates/engine/schema/src/generated/field.rs
- crates/engine/src/operation/plan/model/plan.rs
- crates/engine/src/operation/plan/query_modifications.rs
- crates/engine/src/operation/solve/model/generated/query_partition.rs
- crates/engine/src/operation/solve/model/prelude.rs
- crates/engine/src/operation/solve/solver/mod.rs
- crates/engine/src/operation/solve/solver/shapes/mod.rs
- crates/engine/src/resolver/introspection/writer.rs
- crates/engine/src/response/shape/concrete.rs
- crates/engine/src/response/shape/field.rs
- crates/engine/src/response/shape/mod.rs
- crates/engine/src/response/shape/polymorphic.rs
- crates/engine/src/response/write/deserialize/field.rs
- crates/engine/src/response/write/deserialize/mod.rs
- crates/engine/src/response/write/deserialize/object/concrete.rs
- crates/engine/src/response/write/deserialize/object/polymorphic.rs
- crates/engine/src/response/write/mod.rs
Was confused for a moment as to why `ConcreteObjectShape` could have
interfaces/unions. But it's just ill-named, it's a `ConcreteShape` with
known fields. It doesn't mean it's only a single object. So renamed
`ConcreteObjectShape` to `ConcreteObject` and `PolymorphicObjectShape`
to `PolymorphicShape`.
> chore(engine): Rename Concrete/PolymorphicObjectShape

- crates/engine/src/prepare/operation/mod.rs
This case should never really happen, but it'd be better to not be completely silent if it does.
> fix: add error message on unlikely complexity control path

- cli/src/cli_input/publish.rs
What is up with that argument? It is not used, and there is no introspection involved in publish, so it is misleading.
> cli: remove --header argument in publish

- Cargo.lock
- crates/telemetry/Cargo.toml
Was playing about with prometheus & jaeger locally just there, and configured my gateway to export otlp using http, but on startup the server got this message:
> Error: unable to configure span exporter: Exporter otlp encountered the following error(s): no http client, you must select one from features or provide your own implementation
Enabling one of the http client feature flags fixes this.
> fix: otlp http exporters

- crates/engine/query-solver/src/solution/dot_graph.rs
- crates/engine/query-solver/src/solve/solution.rs
- crates/engine/query-solver/src/tests/mutation.rs
- crates/engine/query-solver/src/tests/snapshots/engine_query_solver__tests__mutation__audit_test-finalized-solution.snap
- crates/engine/query-solver/src/tests/snapshots/engine_query_solver__tests__mutation__audit_test-graph.snap
- crates/engine/query-solver/src/tests/snapshots/engine_query_solver__tests__mutation__audit_test-partial-solution.snap
- crates/engine/query-solver/src/tests/snapshots/engine_query_solver__tests__mutation__audit_test-solved.snap
- crates/engine/query-solver/src/tests/snapshots/engine_query_solver__tests__mutation__audit_test-solver.snap
- crates/engine/query-solver/src/tests/snapshots/engine_query_solver__tests__mutation__consecutive_subgraphs-finalized-solution.snap
- crates/engine/query-solver/src/tests/snapshots/engine_query_solver__tests__mutation__consecutive_subgraphs_with_multiple_fields-finalized-solution.snap
- crates/engine/query-solver/src/tests/snapshots/engine_query_solver__tests__mutation__interleaved_subgraph_fields-finalized-solution.snap
- crates/engine/query-solver/src/tests/snapshots/engine_query_solver__tests__mutation__single_subgraph-finalized-solution.snap
There are two ordering problems with the query partitions generated by the query-solver:
- mutation ordering is ignored
- dependencies: a -> b -> c with a & c coming from the same subgraph. a and c have to be resolved in two steps.
Both have dedicated functions and I was running the latter the same way for mutations and queries. So the second would change whatever the first one did for mutations. I just go lucky in my tests that it worked.
I also realized I had the inverted ordering of mutations... as I didn't use the usual arrow shape for requirements.
> fix(engine): mutation test

- crates/engine/src/operation/input_value/query/walker/mod.rs
- crates/engine/src/prepare/operation/complexity_control.rs
- crates/integration-tests/tests/federation/complexity_control.rs
This includes the cost of argument values in complexity calculations.  
Currently we do this by serialising argument values into a `serde_json::Value` which is not ideal.  The current setup for values in `engine` is quite complicated - there's 3 or 4 different enums that represent values, and `serde::Deserialize` is currently the only way to avoid dealing with that complexity.  I did briefly try to write a `Deserialize` impl instead of using `serde_json::Value` but that proved to be more complicated than it was worth.  If we ever refactor values in engine we could probably revisit this.
Fixes GB-8014
> fix: include argument values in complexity cost

- crates/graphql-schema-diff/CHANGELOG.md
- crates/graphql-schema-diff/src/change.rs
- crates/graphql-schema-diff/src/lib.rs
- crates/graphql-schema-diff/src/patch/paths.rs
- crates/graphql-schema-diff/src/patch/schema_definitions.rs
- crates/graphql-schema-diff/src/path.rs
- crates/graphql-schema-diff/src/path/display.rs
- crates/graphql-schema-diff/src/path/parse.rs
- crates/graphql-schema-diff/src/state.rs
- crates/graphql-schema-diff/tests/diff/add_schema_definition.snapshot.json
- crates/graphql-schema-diff/tests/diff/add_schema_extension.snapshot.json
- crates/graphql-schema-diff/tests/diff/interface_implements_interface.snapshot.json
- crates/graphql-schema-diff/tests/diff/mutation_type_changed.snapshot.json
- crates/graphql-schema-diff/tests/diff/object_interface.snapshot.json
- crates/graphql-schema-diff/tests/diff/query_type_changed.snapshot.json
- crates/graphql-schema-diff/tests/diff/subscription_type_changed.snapshot.json
- crates/operation-checks/src/check/rules.rs
- crates/operation-checks/tests/cases/remove_used_interface_implementer.snapshot
Until now, the paths in a change have been of the format `a.b.c`, just nesting a path. This PR introduces a more structured representation, along with a new string representation, that should address three problems and allow us to represent any path within a GraphQL schema.
1. We need to be able to address items that don't have their own names. These are schema and type extensions, as well as repeatable directives. So I introduced indexing, like `:schema[2]`, `Query[0]`, `@tag[3]`, etc.
2. Introduce tokens to distinguish between different namespaces that could be addressed by a path. On type definitions, we want to distinguish paths leading to fields (or enum values, etc.) and paths to directives on the types. To give an example, disambiguate cases like this:
```graphql
type Test …
```
> graphql-schema-diff: overhaul path strings

- crates/engine/codegen/domain/schema.graphql
- crates/engine/codegen/src/domain.rs
- crates/engine/codegen/src/generation/id.rs
- crates/engine/codegen/src/loader.rs
- crates/engine/id-derives/src/id.rs
- crates/engine/schema/src/directive/requires_scopes.rs
- crates/engine/schema/src/field_set/mod.rs
- crates/engine/schema/src/generated/composite_type.rs
- crates/engine/schema/src/generated/definition.rs
- crates/engine/schema/src/generated/directive.rs
- crates/engine/schema/src/generated/directive/authorized.rs
- crates/engine/schema/src/generated/entity.rs
- crates/engine/schema/src/generated/enum_def.rs
- crates/engine/schema/src/generated/enum_value.rs
- crates/engine/schema/src/generated/field.rs
- crates/engine/schema/src/generated/header_rule.rs
- crates/engine/schema/src/generated/input_object.rs
- crates/engine/schema/src/generated/input_value.rs
- crates/engine/schema/src/generated/interface.rs
- crates/engine/schema/src/generated/object.rs
- crates/engine/schema/src/generated/resolver.rs
- crates/engine/schema/src/generated/scalar.rs
- crates/engine/schema/src/generated/union.rs
- crates/engine/schema/src/ids.rs
- crates/engine/schema/src/prelude.rs
- crates/engine/src/operation/solve/model/mod.rs
Remove the max id stuff, useless. And added support to just have `u32`
instead of `NonZero<u32>`. I put a lot of `NonZero`, but not sure it's
that useful.
> chore(engine): Simplify id_derives

- cli/src/output/report.rs
- cli/src/publish.rs
- crates/grafbase-local-backend/src/api/graphql/api.graphql
- crates/grafbase-local-backend/src/api/graphql/types/mutations.rs
- crates/grafbase-local-backend/src/api/publish.rs
Now the CLI will report when you publish a subgraph and neither the subgraph schema nor the url changes (they are identical to what is already published). In that case, no deployment will be created in the schema registry. This is not an error, so the exit code remains 0.
The noise in the diff is from updating the platform's GraphQL schema (in particular the api keys removal).
Companion platform PR: https://github.com/grafbase/api/pull/4269
> cli: make publish idempotent

- Cargo.lock
- Cargo.toml
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/changelog/0.81.0.md
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
- crates/grafbase-local-backend/Cargo.toml
- crates/runtime-local/Cargo.toml
- The `grafbase publish` command will now report when you publish a subgraph and neither the subgraph schema nor the url changes (they are identical to what is already published). In that case, no deployment will be created in the schema registry. (https://github.com/grafbase/grafbase/pull/2401)
> cli: release 0.81.0

- crates/graphql-schema-diff/CHANGELOG.md
- crates/graphql-schema-diff/src/state.rs
- crates/graphql-schema-diff/tests/diff/add_fields_with_arguments.graphql
- crates/graphql-schema-diff/tests/diff/add_fields_with_arguments.snapshot.json
We do not emit, for example, AddField changes in a new type (e.g. AddObjectType). But we do emit AddFieldArgument changes in a new field. This is not consistent. This commit changes the behavior to not emit AddFieldArgument changes in a new field.
> graphql-schema-diff: do not emit AddArgument on top of AddField

- crates/engine/schema/src/builder/coerce/mod.rs
- crates/engine/schema/src/introspection.rs
- crates/engine/schema/src/ty.rs
- crates/engine/src/operation/bind/coercion/query.rs
- crates/engine/src/operation/bind/coercion/variable.rs
- crates/engine/src/operation/bind/variables.rs
- crates/engine/src/resolver/introspection/writer.rs
- crates/engine/src/response/write/deserialize/field.rs
- crates/engine/src/response/write/deserialize/object/concrete.rs
- crates/graphql-composition/src/emit_federated_graph/field_types_map.rs
- crates/graphql-federated-graph/src/from_sdl.rs
- crates/graphql-wrapping-types/src/lib.rs
- crates/graphql-wrapping-types/src/mutable.rs
Today Wrapping is mutable, is itself an iterator and Copy which makes it easy
to misuse. So made it more explicit by separating the mutations to a
wrapper type which is also the iterator `MutableWrapping`. Reduced the
size to a u16, which is still 11 list wrappings
> chore(engine): Make non-mutable Wrapping

- Cargo.lock
- crates/grafbase-hooks/Cargo.toml
- crates/wasi-component-loader/examples/Cargo.lock
- crates/wasi-component-loader/examples/Cargo.toml
- examples/access-logs/Cargo.lock
- examples/access-logs/hooks/Cargo.toml
- examples/gateway-hooks/Cargo.lock
- examples/gateway-hooks/hooks/Cargo.toml
- examples/hooks-template/Cargo.lock
- examples/hooks-template/Cargo.toml
- examples/request-hook/Cargo.lock
- examples/request-hook/request-hook/Cargo.toml
The users will always want it anyhow.
> fix: make derive as a default feature for grafbase-hooks

- .github/workflows/rust-prs.yml
- cli/src/dev.rs
- crates/grafbase-hooks/README.md
- crates/integration-tests/src/federation/builder/engine.rs
- crates/integration-tests/tests/federation/hooks/on_subgraph_request.rs
- crates/wasi-component-loader/README.md
- crates/wasi-component-loader/src/tests.rs
- examples/access-logs/README.md
- examples/access-logs/grafbase.toml
- examples/gateway-hooks/README.md
- examples/gateway-hooks/grafbase.toml
- examples/gateway-hooks/rust-toolchain.toml
- examples/hooks-template/README.md
- examples/request-hook/README.md
- flake.nix
- gateway/tests/access_logs/mod.rs
- gateway/tests/telemetry/metrics/access_log.rs
- gateway/tests/telemetry/metrics/operation/hooks.rs
- rust-toolchain.toml
All examples can now be compiled with
```bash
cargo build --target wasm32-wasip2
```
> chore: start using wasm32-wasip2 target instead of cargo-component

- crates/engine/query-solver/src/operation/builder.rs
- crates/engine/schema/src/builder/graph.rs
- crates/engine/schema/src/interface.rs
- crates/engine/schema/src/lib.rs
- crates/engine/schema/src/union.rs
- crates/engine/src/operation/plan/model/plan.rs
- crates/engine/src/operation/plan/model/query_partition.rs
- crates/engine/src/operation/plan/model/selection_set.rs
- crates/engine/src/operation/solve/solver/mod.rs
- crates/engine/src/operation/solve/solver/shapes/mod.rs
- crates/engine/src/resolver/introspection/writer.rs
- crates/engine/src/response/shape/field.rs
- crates/engine/src/response/write/deserialize/enum.rs
- crates/engine/src/response/write/deserialize/field.rs
- crates/engine/src/response/write/deserialize/object/concrete.rs
- crates/engine/src/response/write/deserialize/object/polymorphic.rs
- crates/integration-tests/tests/federation/inaccessible/mod.rs
- crates/integration-tests/tests/federation/inaccessible/object_behind_interface.rs
- crates/integration-tests/tests/federation/inaccessible/object_behind_union.rs
When encountering an inaccessible object behind an interface/union we have to propagate a null without any error.
So keeping track of unions & interfaces with inaccessible possible types and forcing the type detection for those to ensure we only return accessible objects.
> fix(engine): propagate null for inaccessible objects found behind an interface/object

- crates/engine/query-solver/src/lib.rs
- crates/engine/query-solver/src/operation/builder/alternative.rs
- crates/engine/query-solver/src/operation/builder/mod.rs
- crates/engine/query-solver/src/operation/builder/prune.rs
- crates/engine/query-solver/src/operation/mod.rs
- crates/engine/query-solver/src/operation/node.rs
- crates/engine/query-solver/src/tests/interface.rs
- crates/engine/query-solver/src/tests/mod.rs
- crates/engine/query-solver/src/tests/snapshots/engine_query_solver__tests__interface__interface_field_providing_object_field-finalized-solution.snap
- crates/engine/query-solver/src/tests/snapshots/engine_query_solver__tests__interface__interface_field_providing_object_field-graph.snap
- crates/engine/query-solver/src/tests/snapshots/engine_query_solver__tests__interface__interface_field_providing_object_field-partial-solution.snap
- crates/engine/query-solver/src/tests/snapshots/engine_query_solver__tests__interface__interface_field_providing_object_field-solved.snap
- crates/engine/query-solver/src/tests/snapshots/engine_query_solver__tests__interface__interface_field_providing_object_field-solver.snap
- crates/engine/schema/src/entity.rs
- crates/engine/src/operation/solve/solver/adapter.rs
- crates/engine/src/operation/solve/solver/requires.rs
With a schema like:
```graphql
type Query {
node: Node! @join__field(graph: B)
}
interface Node {
id: ID
}
type User implements Node @join__type(graph: A) {
id: ID
name: String
}
```
and a query:
```graphql
{
node {
... on User { name }
}
}
```
We need to retrieve the `User.id` but the `B` graph cannot provide it, instead it can provide `Node.id` which represents the same underlying data. So adding the necessary code to add it. It's not perfect and will improve it a bit later, but for now the new problem is that we don't track in the composition that fields we add to an object from entity interfaces are only resolvable through the interface
> fix(engine): Replace object field by parent interface field.

- crates/grafbase-local-backend/src/dev/configurations.rs
- examples/gateway-hooks/grafbase.toml
- examples/gateway-hooks/overrides.toml
Nice catch after releasing the CLI. If you didn't pass config file to it, the dev would just panic. What we do here is we either load the config, or load a default config and let the merges happen after that.
> fix: do not panic if no config is passed for dev

- gateway/data/clickhouse/docker-entrypoint-initdb.d/init-db.sh
- gateway/docker-compose.yml
We've been hitting this bug in the otel-collector:
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36540
Let's put the clickhouse image to create the otel database.
> fix: update otel-collector and manually create the otel database

- Cargo.lock
- crates/engine-config-builder/src/from_toml_config.rs
- crates/gateway-config/src/lib.rs
- crates/grafbase-local-backend/Cargo.toml
- crates/grafbase-local-backend/src/dev.rs
- crates/grafbase-local-backend/src/dev/configurations.rs
- dev is always enabled, if the setting is explicitly false, we log a nag
- prod is by default false
> chore: make introspection optional in config

- crates/engine/src/resolver/graphql/request/prepare.rs
Sometimes queries end up with a case like:
```
products {
... on Oven { id }
... on Kettle { id }
}
```
where in the subgraph `Oven` doesn't implement `Product` even if it exists in the subgraph. Oven implements it in another subgraph. I'm not sure if this is really the right way to do it, planning should likely take this into account. But still an improvement.
> fix(engine): Do not send subgraph request with impossible implementors

- crates/engine/codegen/domain/schema.graphql
- crates/engine/schema/src/builder/graph.rs
- crates/engine/schema/src/generated/field.rs
- crates/engine/schema/src/generated/field/subgraph_type.rs
- crates/engine/schema/src/introspection.rs
- crates/engine/src/operation/solve/solver/adapter.rs
- crates/engine/src/resolver/graphql/request/prepare.rs
- crates/graphql-composition/src/emit_federated_graph/field_types_map.rs
- crates/graphql-federated-graph/src/federated_graph/type.rs
- crates/graphql-federated-graph/src/from_sdl/directive.rs
Subgraph may have a different but compatible type for a field:
```graphql
type Query {
node: [Node] @join__field(graph: A, type: "[Product]") @join__field(graph: B)
}
```
this means that in subgraph A we have:
```graphql
type Query {
product: [Product]
}
```
So we have to take it into account during query generation. If we do:
```graphql
{
nodes {
... on Table { id }
}
}
```
and it ends up being sent to subgraph A, we have to ensure that `Table` is a possible type of `Product`, not `Node`.
> fix(engine): Take into account type overrides when generatin subgraph query

- crates/engine/src/analytics/mod.rs
This slipped from my previous PR. We must pass the normalized document here, so the telemetry-sink has access to it and can calculate the hash accordingly.
> fix: add normalized document to OperationAnalytics for telemetry

- crates/engine/src/engine.rs
- crates/engine/src/engine/runtime.rs
- crates/engine/src/lib.rs
- crates/engine/src/prepare/context.rs
- crates/engine/src/prepare/mod.rs
- crates/engine/src/prepare/operation/mod.rs
- crates/federated-server/src/server/gateway/gateway_runtime.rs
- crates/integration-tests/src/federation/builder/bench.rs
- crates/integration-tests/src/federation/builder/test_runtime.rs
- crates/runtime-local/src/lib.rs
- crates/runtime-local/src/operation_cache.rs
- crates/runtime/src/operation_cache.rs
To do query warming I need to reach into the operation cache to fetch queries to prewarm.  I wanted to do this in the runtime, but currently the runtime doesn't have access to the operation cache, only an OperationCacheFactory.  
I can't see much reason for this factory.  Things seem to work fine without it, so I've removed it.  If I've missed something please let me know and I'll revert.
> chore: remove OperationCacheFactory trait

- Cargo.lock
- Cargo.toml
- crates/engine/axum/src/websocket/accepter.rs
- crates/federated-server/Cargo.toml
- crates/federated-server/src/server.rs
- crates/federated-server/src/server/engine_reloader.rs
- crates/federated-server/src/server/gateway.rs
- crates/federated-server/src/server/graph_fetch_method.rs
- crates/federated-server/src/server/graph_updater.rs
- crates/federated-server/src/server/health.rs
- crates/grafbase-local-backend/src/dev.rs
- crates/grafbase-local-backend/src/dev/hot_reload.rs
- gateway/src/args/lambda.rs
- gateway/src/args/std.rs
- gateway/src/main.rs
I need to hook into the engine creation process in the gateway to add query warming.  Prior to this change that happened in three places: inside the GraphUpdater when using a graph ref to fetch from the GDN & a couple of places inside GraphFetchMethod::start when using a schema file.  This made it a bit awkward to add in query warming.
This refactors things a bit so that GraphUpdater & GraphFetchMethod::start both just send a `GraphDefinition` on a channel, where a new `EngineReloader` (name suggestions welcome) is listening and will handle the update.  There's also some logic to cancel a running reload if another one comes in afterwards.
I also separated out config updates from graph updates in the `reload_signal` used by federated dev - config updates now go over their own …
> chore: rework engine & config updates in gateway

- Cargo.lock
- crates/graphql-schema-diff/CHANGELOG.md
- crates/graphql-schema-diff/Cargo.toml
- crates/graphql-schema-diff/src/state.rs
- crates/graphql-schema-diff/tests/diff/add_interface_with_implementers.graphql
- crates/graphql-schema-diff/tests/diff/add_interface_with_implementers.snapshot.json
- crates/graphql-schema-diff/tests/diff_tests.rs
- crates/graphql-schema-diff/tests/patch_tests.rs
- crates/operation-checks/Cargo.toml
- crates/operation-checks/src/check/rules.rs
- crates/operation-checks/src/schema.rs
- crates/operation-checks/src/schema/async_graphql.rs
- crates/operation-checks/tests/operation_check_tests.rs
That is, added interface implementations for new objects and interfaces, and removed interface implementations for removed interfaces and objects.
closes GB-8195
> graphql-schema-diff: do not emit unnecessary {Add,Remove}InterfaceImplementation

- crates/integration-tests/docker-compose.yml
- gateway/docker-compose.yml
I started using a distro with SELinux enabled. This is one of the things you _have to do_ with docker mounts to work. It does absolutely nothing on systems which do not use SELinux.
https://www.perplexity.ai/search/what-does-z-do-in-docker-mount-CD3IfXHRSUiZZeI5Yyrr.w
> fix: selinux compatible compose mounts

- crates/engine/src/operation/bind/mod.rs
- crates/engine/src/operation/parse/mod.rs
- crates/engine/src/operation/plan/mod.rs
- crates/engine/src/operation/solve/mod.rs
- crates/engine/src/prepare/operation/before_variables.rs
- crates/engine/src/prepare/operation/mod.rs
- crates/engine/src/prepare/trusted_documents.rs
As I mentioned in my demo last week, it's not super obvious from traces whether or not you hit the operation cache.  This is because it all happens under the "prepare operation" span.  We could put a `is_cached` property on this span, but I think there's an opportunity to show users how they could/couldn't benefit from better caching.  This PR is an attempt to do that:
1. Added a span on `build_cached_operation` - which builds the operation that will be cached.  I named it build operation because `build_cached_operation` seems a little ambiguous to me  - very much sounds like it could be building an operation that _was_ cached.
2. Added some spans on fetching a trusted document, since that also seemed like a faintly sensible thing.
3. Moved the spans I'd added on bind/parse/plan etc. to …
> chore: more traces for caching 

- cli/src/backend/dev.rs
- crates/federated-server/src/server/graph_updater.rs
This pull request includes changes to improve the clarity and consistency of log messages and output labels in the codebase. The most important changes include renaming variables for better readability and updating log messages for consistency.
Improvements to output labels and log messages:
* [`cli/src/backend/dev.rs`](diffhunk://#diff-5f7d6465b742be2714e2323e82d686408101a4f2b5f3f9cdb10058c7a236cb6eL173-R173): Renamed `pathfinder_url` to `explorer_url` and updated the corresponding output label from "Pathfinder" to "Explorer". [[1]](diffhunk://#diff-5f7d6465b742be2714e2323e82d686408101a4f2b5f3f9cdb10058c7a236cb6eL173-R173) [[2]](diffhunk://#diff-5f7d6465b742be2714e2323e82d686408101a4f2b5f3f9cdb10058c7a236cb6eL182-R185)
* [`crates/federated-server/src/server/graph_updater.rs`](diffhunk://# …
> rename pathfinder to explorer

- Cargo.lock
- crates/graphql-composition/CHANGELOG.md
- crates/graphql-composition/Cargo.toml
- crates/graphql-federated-graph/Cargo.toml
Features
- Added composition for default values of output field arguments and input fields. They are now reflected in the federated graph.
- Selection sets inside `@requires` and `@provides` directives can now include inline fragments.
- The selection sets in the "fields:" argument on `@requires` are now validated against the schema, with proper errors with context when invalid.
- A new Subgraphs::ingest_str() method has been added to ingest a federated graph from a string, instead of from an async_graphql_parser AST. This is both for convenience and because async_graphql parser will soon not be part of the public API anymore.
- There is no longer a VersionedFederatedGraph. The serializable version of the federated graph is dropped — that role will be fulfilled by the federated SDL …
> Release graphql-composition and graphql-federated-graph 0.5.0

- Cargo.lock
- crates/graphql-federated-graph/Cargo.toml
- crates/graphql-wrapping-types/Cargo.toml
Needed for the graphql-federated-graph, and transitively for the graphql-composition release.
> Release graphql-wrapping-types 0.3.0

- .github/renovate.json
- .github/scripts/renovate-post-upgrade.sh
We do a few things here that's annoying when Renovate PRs appear:
- Renovate should run `cargo hakari generate` and commit the lockfile. No need to do this manually every time.
- Avoid updating graphql-mocks axum until async-graphql-axum's next version with axum 0.8 is out.
Hopefully this avoids some of the busywork with every Renovate PR.
> fix: reduce Renovate busywork

- crates/engine-config-builder/src/from_toml_config.rs
- crates/engine/config/src/lib.rs
- crates/engine/config/src/trusted_documents.rs
- crates/engine/schema/src/builder/mod.rs
- crates/engine/schema/src/lib.rs
- crates/engine/src/prepare/mod.rs
- crates/engine/src/prepare/trusted_documents.rs
- crates/federated-server/src/server/gateway.rs
- crates/federated-server/src/server/trusted_documents_client.rs
- crates/gateway-config/src/lib.rs
- crates/gateway-config/src/log_level.rs
- crates/gateway-config/src/trusted_documents.rs
- crates/integration-tests/src/federation/builder.rs
- crates/integration-tests/src/mock_trusted_documents.rs
- crates/integration-tests/tests/federation/trusted_documents.rs
- crates/runtime-noop/src/trusted_documents.rs
- crates/runtime/src/trusted_documents_client.rs
- gateway/changelog/unreleased.md
The aim of this change is to offer an incremental adoption path for trusted documents.
Until now, trusted documents would be either disabled, or fully enforced. However in practice, organizations follow a more incremental migration path. The following options are now available in `grafbase.toml`:
```toml
[trusted_documents]
enabled = true # default: false
enforced = true # default: false
bypass_header_name = "my-header-name" # default null
bypass_header_value = "my-secret-is-{{ env.SECRET_HEADER_VALUE }}" # default null
document_id_unknown_log_level = "error" # default: info
document_id_and_query_mismatch_log_level = "off" # default: info
inline_document_unknown_log_level = "warn" # default: info
```
The `bypass_header_name` and `bypass_header_value` settings are unchanged.
The `enabled` …
> engine: implement trusted documents incremental adoption

- crates/engine/src/response/write/deserialize/object/concrete.rs
- crates/integration-tests/tests/federation/issues.rs
I was expecting fields to be sorted and used binary search but this
changed at some point, sorting later. Didn't catch the regression with
existing tests.
As we have rarely more than few dozens of fields, linear search will do
perfectly fine here.
Fixes #2502
> fix(engine): incorrect handling of skip/include during deserialization

- crates/engine/src/prepare/trusted_documents.rs
- crates/integration-tests/src/federation/request.rs
- crates/integration-tests/tests/federation/apq.rs
- crates/integration-tests/tests/federation/basic/operations.rs
- crates/integration-tests/tests/federation/trusted_documents.rs
In our tests we were always sending an empty string and the previous
Request struct used to have `query: String`. But since the depreciation of
the previous engine we use `query: Option<String>` instead.
So now we weren't treating correctly a missing query field in the
request for APQ. Fixed that, added a few tests that send no `query`
field and put in common some code.
Fixes #2505
> fix(engine): Incorrect handling of missing query in request.

- crates/engine/src/prepare/trusted_documents.rs
- crates/integration-tests/tests/federation/trusted_documents.rs
In allow / audit mode, before this commit, we try to fetch the trusted document every time there is a trusted document id in the query, and we return an error if it doesn't exist. This is not in the spirit of allow mode: we have a setting to log, in that case. We should allow for a soft transition.
This commit changes the behaviour to try and fetch the trusted document from the trusted document id, but without hard error in case of failure, unless there is no inline document — there would be nothing to execute in that case, so we can't proceed to handle the request.
closes GB-8282
> engine: tolerate unknown trusted doc ids in Allow mode

- Cargo.lock
- gateway/CHANGELOG.md
- gateway/Cargo.toml
- gateway/changelog/0.26.0.md
The gateway implements the [graphql-transport-ws protocol](https://github.com/graphql/graphql-over-http/blob/main/rfcs/GraphQLOverWebSocket.md). In that protocol, the first message on a websocket connection will be connection_init. That message contains an optional payload field that is a JSON object with arbitrary values. Typically, information that would go in HTTP headers for queries and mutations flows instead in that connection_init message's payload. Data like tokens that would otherwise go into the `Authorization` header are passed there instead.
Before this release, the ConnectionInit payload was not forwarded to the subgraph resolving the subscription. It is now forwarded by default. That behaviour can be disabled with the following configuration:
```toml
[websockets] …
```
> gateway: release 0.26.0

- Cargo.lock
- gateway/CHANGELOG.md
- gateway/Cargo.toml
- gateway/changelog/0.27.1.md
- gateway/helm/README.md
This also adds helm chart to the release process:
- instead of using `latest` tag, use the current version tag
- bump the minor version of the chart
> chore: Bump Gateway to 0.27.1

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- crates/engine-config-builder/Cargo.toml
- crates/federation-audit-tests/Cargo.toml
- crates/grafbase-graphql-introspection/Cargo.toml
- crates/graph-ref/Cargo.toml
- crates/operation-checks/Cargo.toml
- crates/operation-normalizer/Cargo.toml
- crates/runtime-local/Cargo.toml
- crates/serde-dynamic-string/Cargo.toml
- crates/wasi-component-loader/Cargo.toml
- crates/wasi-component-loader/examples/crates/authorization/Cargo.toml
- crates/wasi-component-loader/examples/crates/dir_access/Cargo.toml
- crates/wasi-component-loader/examples/crates/error/Cargo.toml
- crates/wasi-component-loader/examples/crates/gateway_request_no_op/Cargo.toml
- crates/wasi-component-loader/examples/crates/http_client/Cargo.toml
- crates/wasi-component-loader/examples/crates/missing_hook/Cargo.toml
- crates/wasi-component-loader/examples/crates/response-hooks/Cargo.toml
- crates/wasi-component-loader/examples/crates/simple/Cargo.toml
- crates/wasi-component-loader/examples/crates/subgraph_request/Cargo.toml
- examples/access-logs/hooks/Cargo.toml
- examples/gateway-hooks/hooks/Cargo.toml
Until this commit, the CLI inherits its version from the workspace. So the workspace version is the CLI version. Other crates used to inherit it but that is no longer the case. The cli version shouldn't have precedence over versions for other crates that are decoupled from it, like the gateway or grafbase-composition.
So this commit scopes the version of the cli to the Cargo.toml of the grafbase crate.
> Scope the CLI version to the grafbase crate

- crates/federated-server/src/server/trusted_documents_client.rs
This is the URL used by clients by default. It contains trusted documents uploaded to the platform at grafbase.com. It is overridden in self-hosted enterprise platform deployments.
Note that the path of documents also changed.
closes GB-8327
> gateway: default to the new domain for hosted trusted documents

- Cargo.lock
- gateway/CHANGELOG.md
- gateway/Cargo.toml
- gateway/changelog/0.28.0.md
- The default download location for trusted documents has been updated to the new Grafbase CDN URL. This does not affect self-hosted enterprise platform deployments (https://github.com/grafbase/grafbase/pull/2530).
> gateway: release 0.28.0

- Cargo.lock
- crates/graphql-composition/CHANGELOG.md
- crates/graphql-composition/Cargo.toml
- crates/graphql-composition/src/ingest_subgraph.rs
- crates/graphql-composition/src/ingest_subgraph/directive_definitions.rs
- crates/graphql-composition/src/subgraphs/definitions.rs
- crates/graphql-composition/src/subgraphs/directives.rs
- crates/graphql-composition/src/subgraphs/directives/directive_definition.rs
- crates/graphql-composition/src/validate.rs
- crates/graphql-composition/src/validate/compose_directive.rs
- crates/graphql-composition/tests/composition/compose_directive_different_definitions/federated.graphql
- crates/graphql-composition/tests/composition/compose_directive_different_definitions/subgraphs/chocolate.graphql
- crates/graphql-composition/tests/composition/compose_directive_different_definitions/subgraphs/nougat.graphql
- crates/graphql-federated-graph/src/lib.rs
- crates/graphql-federated-graph/src/render_sdl.rs
- crates/graphql-federated-graph/src/render_sdl/display_utils.rs
As a first use case, this implements the federation spec rule that any directive composed using `@composeDirective` must have the same definition in all subgraphs.
closes GB-8317
> graphql-composition: ingest directive definitions

- Cargo.lock
- Cargo.toml
- crates/extension/Cargo.toml
- crates/extension/src/id.rs
- crates/extension/src/lib.rs
- crates/extension/src/manifest/mod.rs
- crates/extension/src/manifest/v1.rs
Defining the extension id which includes three core components:
- the name & version, coming from the manifest
- the origin of the manifest: This one will likely require further
processing later. But the idea is to distinguish a local extension
developed locally from one in our registry or a self-hosted one.
The federated SDL will associate every extension directive with a
relevant extension id. Every extension loaded by the gateway will also
have an id. The engine will then match those to find the relevant Wasm
to run for each directives if relevant.
> chore(extension): Initial manifest

- Cargo.lock
- Cargo.toml
- crates/grafbase-sdk/derive/Cargo.toml
- crates/grafbase-sdk/derive/src/lib.rs
- crates/grafbase-sdk/src/extension.rs
- crates/grafbase-sdk/src/extension/resolver.rs
- crates/grafbase-sdk/src/host_io/http.rs
- crates/grafbase-sdk/src/lib.rs
- crates/grafbase-sdk/src/types.rs
- crates/grafbase-sdk/wit/world.wit
- crates/grafbase-workspace-hack/Cargo.toml
- extensions/rest/Cargo.toml
- extensions/rest/src/lib.rs
Adds a very simple REST extension, which should show how an extension could look like. Notable things:
```rust
#[derive(grafbase_sdk::ResolverExtension)]
struct MyExtension;
```
This will generate the needed initialization code, and fail because the struct needs to implement the `Extension` and `Resolver` traits. The user implements these traits, the code compiles and should be ready to use in the gateway.
> feat: very basic rest extension that can do a GET

- crates/graphql-composition/CHANGELOG.md
- crates/graphql-composition/src/compose/object.rs
- crates/graphql-composition/src/subgraphs/fields.rs
- crates/graphql-composition/tests/composition/descriptions_basic/federated.graphql
- crates/graphql-composition/tests/composition/descriptions_basic/subgraphs/selfExplanatoryTofu.graphql
- crates/graphql-federated-graph/src/render_sdl/render_federated_sdl.rs
This was an omission. The composition rule is the same as for other descriptions: take the first non-null description we encounter.
closes GB-8353
> graphql-composition: compose descriptions of field arguments

- crates/graphql-composition/tests/composition/descriptions_basic/api.graphql
- crates/graphql-federated-graph/src/render_sdl/render_api_sdl.rs
Missed this function in https://github.com/grafbase/grafbase/pull/2544
> graphql-federated-graph: add forgotten description rendering in render_api_sdl()

- gateway/helm/Chart.yaml
- gateway/helm/values.yaml
HPA works based on pod resources.
This PR adds resources for the gateway deployment.
Values for resources where taken from [this](https://app.datadoghq.com/dashboard/svn-yjm-8zc/cf--grafbase-prod?fromUser=true&refresh_mode=sliding&tpl_var_deployment%5B0%5D=gateway&from_ts=1737581399819&to_ts=1738186199819&live=true) dashboard:
- with 4 cores and 70% HPA, it looks like most of the time it will only need 1 pod (with the caveat from the next change).
This also increases the number of min pods to 2, so that the gateway availability is not dependent on one single point of failure.
> add resources for gateway

- crates/engine-config-builder/src/from_toml_config/context.rs
- crates/engine/codegen/domain/schema.graphql
- crates/engine/config/src/subgraph.rs
- crates/engine/schema/src/builder/external_sources.rs
- crates/engine/schema/src/generated/subgraph/graphql.rs
- crates/engine/schema/src/lib.rs
- crates/engine/src/resolver/graphql/subscription.rs
- crates/gateway-config/src/lib.rs
- crates/gateway-config/src/subscriptions_protocol.rs
When the gateway receives a subscription request, it can use either server-sent events or websockets to communicate with the subgraph serving the subscription. This is independent from the protocol used by the client to connect to the gateway. Until now, the logic was that if a `websocket_url` was defined in the subgraph configuration, the gateway would use a websocket connection, otherwise default to server sent events. This is opaque, and not flexible enough.
This pull request introduces a new subgraph configuration option in `grafbase.toml`:
```toml
[subgraphs.my-subgraph]
subscriptions_protocol = "websockets"
```
The value must be either "websockets" or "server_sent_events". The gateway will follow the choice of protocol for the subgraph. If this option is omitted, the previous logic …
> gateway: config option for subscription transport to subgraphs

- Cargo.lock
- cli/Cargo.toml
- cli/src/extension/build.rs
- cli/tests/extension/mod.rs
- crates/engine/schema/src/lib.rs
- crates/extension-catalog/src/catalog.rs
- crates/federated-server/Cargo.toml
- crates/federated-server/src/server.rs
- crates/federated-server/src/server/engine_reloader.rs
- crates/federated-server/src/server/gateway.rs
- crates/federated-server/src/server/gateway/gateway_runtime.rs
- crates/gateway-config/Cargo.toml
- crates/gateway-config/src/extensions.rs
- crates/gateway-config/src/lib.rs
- crates/grafbase-sdk/Cargo.toml
- crates/grafbase-sdk/src/types.rs
- crates/grafbase-sdk/wit/world.wit
- crates/integration-tests/src/federation/runtime/extension.rs
- crates/runtime-local/Cargo.toml
- crates/runtime-local/src/wasi/extensions.rs
- crates/runtime/src/extension.rs
- crates/wasi-component-loader/examples/Cargo.lock
- crates/wasi-component-loader/src/instance/extensions/types.rs
- crates/wasi-component-loader/src/tests/extensions.rs
- extensions/rest/.gitignore
- extensions/rest/Cargo.lock
- extensions/rest/Cargo.toml
- extensions/rest/extension.toml
- extensions/rest/src/lib.rs
I need some schema to test this with. With just a random schema the gateway crashes with:
```
[crates/engine/schema/src/generated/subgraph/virtual_.rs:53:10] &self.schema = Schema { .. }
thread 'main' panicked at crates/engine/schema/src/generated/subgraph/virtual_.rs:53:28:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
> feat: generate extension catalog, generate the wasi loader on gateway launch

- crates/federated-server/src/server/gateway.rs
- crates/runtime-local/src/wasi/extensions.rs
They take a hot moment to load. If using more than a few extensions, this will add up. They can be loaded in parallel, so that's what we do here.
> fix: load extensions in parallel

- crates/federated-server/src/server.rs
- crates/gateway-config/src/lib.rs
- crates/integration-tests/src/federation/builder.rs
- crates/integration-tests/src/federation/builder/engine.rs
- crates/integration-tests/src/federation/builder/router.rs
- crates/integration-tests/src/federation/mod.rs
- crates/integration-tests/src/federation/websocket_request.rs
- crates/integration-tests/tests/federation/subscriptions/websockets.rs
- crates/integration-tests/tests/integration_tests.rs
The gateway has a configuration option for the graphql endpoint:
```toml
[graph]
path = "/custom" # default: "/graphql"
```
But the websocket endpoint is always exposed at `/ws`. This PR introduces a `websocket_path` option to configure this.
```toml
[graph]
path = "/custom" # default: "/graphql"
websocket_path = "/subscriptions" # default: "/ws"
```
closes GB-8392
> gateway: configurable websocket route

- cli/src/cli_input/extension.rs
- cli/src/extension/build.rs
It's confusing the default is --debug, and your extension is then easily 100 megabytes. The dev work is anyhow using cargo check, and rust-analyzer.
> fix: extension build defaults to release mode

- crates/engine/src/resolver/graphql/subscription.rs
- crates/graphql-composition/src/ingest_subgraph/directives.rs
- crates/graphql-composition/tests/composition_tests.rs
Might fix a SSE problem as we're sending `text/event-stream,application/json;q=0.9` instead of just `text/event-stream`. The underlying library already adds the ACCEPT header.
> fix(engine): Avoid sending duplicate ACCEPT header for SSE

- cli/src/backend/dev/hot_reload.rs
- cli/src/backend/dev/subgraphs.rs
- crates/federation-audit-tests/tests/composition_comparisons.rs
- crates/graphql-composition/CHANGELOG.md
- crates/graphql-composition/src/emit_federated_graph.rs
- crates/graphql-composition/src/ingest_subgraph.rs
- crates/graphql-composition/src/lib.rs
- crates/graphql-composition/src/subgraphs.rs
- crates/graphql-composition/src/subgraphs/top.rs
- crates/graphql-composition/tests/composition_special_cases.rs
- crates/graphql-composition/tests/composition_tests.rs
- crates/integration-tests/src/federation/builder/engine.rs
- gateway/tests/entity_caching/mod.rs
- gateway/tests/telemetry/tracing.rs
We have virtual subgraph support in graphql-federated-graph and the gateway, so this is just acknowledging it.
> composition: make the url optional in `Subgraphs::ingest()`

- crates/graphql-composition/src/emit_federated_graph/emit_extensions.rs
- crates/graphql-federated-graph/src/federated_graph/extensions.rs
- crates/graphql-federated-graph/src/from_sdl.rs
- crates/graphql-federated-graph/src/from_sdl/directive.rs
- crates/graphql-federated-graph/src/render_sdl/directive.rs
- crates/graphql-federated-graph/src/render_sdl/render_federated_sdl.rs
We want to treat the directives on the values differently, because we don't want a Directive::Other for `@extension__link`.
Also make sure we use schemaDirectives instead of schemaDirective as an argument name everywhere.
> graphql-federated-graph: completely special case ingestion of extension__Link

- Cargo.lock
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/changelog/0.84.6.md
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
**Features**
- Experimental support for Wasm extensions in `grafbase dev`. More docs to come.
> cli: release 0.84.6

- cli/tests/integration/data/echo_extension/src/lib.rs
- crates/engine/src/resolver/extension/field_resolver.rs
- crates/engine/src/response/write/deserialize/field_to_entity.rs
- crates/engine/src/response/write/deserialize/mod.rs
- crates/integration-tests/tests/federation/extensions/basic.rs
GraphQL resolvers always returned an object, but here a resolver returns
the value for an arbitrary type. Before for something like
```graphql
type Query {
countries: [String!]
}
```
I was wrongly expecting:
```json
{"countries": [...]}
```
So changed to accept the inner part.
> fix(engine): Do not expect field resolver to return an entity

- crates/graphql-composition/CHANGELOG.md
- crates/graphql-composition/src/ingest_subgraph/schema_definitions/link.rs
- crates/graphql-composition/tests/composition/link_import_as_errors/api.graphql.snap
- crates/graphql-composition/tests/composition/link_import_as_errors/federated.graphql.snap
- crates/graphql-composition/tests/composition/link_import_as_errors/subgraphs/tagged.graphql
- crates/graphql-composition/tests/composition/link_import_as_errors/test.md
- crates/graphql-composition/tests/composition/link_import_as_valid/api.graphql.snap
- crates/graphql-composition/tests/composition/link_import_as_valid/federated.graphql.snap
- crates/graphql-composition/tests/composition/link_import_as_valid/subgraphs/tagged.graphql
- crates/graphql-composition/tests/composition/link_import_as_valid/test.md
- crates/graphql-composition/tests/composition/shareable_basic/subgraphs/marketing.graphql
Take the `@` prefix into account in aliased imports from `@link` directives. Previously, the `as:` argument for individual directives would only work if you did not prefix the alias with an `@`. But the link spec is clear: if you import a directive, you have to import it with an `@` prefix, and other types should be imported without. This behaviour is fixed, and the presence or absence of `@` is now enforced.
By import types, "directive" or "not directive" is meant here.
closes GB-8446
> graphql-composition: fix @link aliased directive imports, and enforce import types

- extensions/rest/tests/integration_tests.rs
This is one case we should test. The subtle bug here can be improper usage of `Url`.
Example
- The base url is `http://127.0.0.1/foo`
- The path is `/bar`
- One can use `Url::join` and the final url becomes `http://127.0.0.1/bar`, which is wrong.
> fix: add test for base url with a path

- Cargo.lock
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/changelog/0.84.7.md
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
**Fixes**
- The GraphQL Explorer (Pathfinder) bundled in grafbase dev was not loading.
- In grafbase dev, new validations are introduced for bad imports and bad directive usages in subgraph SDLs. The optionality of the `url` argument is also now reflected in the emitted directive definitions for `@join__graph` (https://github.com/grafbase/grafbase/pull/2600).
> cli: release 0.84.7

- cli/tests/extension/mod.rs
- cli/tests/integration/data/Cargo.lock
- crates/wasi-component-loader/examples/Cargo.lock
With the newest release of grafbase sdk, the tests aren't passing on darwin x86 either.
> cli: ignore grafbase extension build tests on more platforms

- .github/workflows/rust-prs.yml
- crates/graphql-schema-diff/CHANGELOG.md
- crates/graphql-schema-diff/src/lib.rs
Instead of strings. I need this in the API, and it is useful in general as a lower level API.
> graphql-schema-diff: expose diffing of ASTs

- Cargo.lock
- cli/Cargo.toml
- cli/changelog/0.84.9.md
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
- `grafbase dev` now displays composition warnings, for example when it encounters unknown directives in subgraph schemas. (https://github.com/grafbase/grafbase/pull/2622)
> cli: release 0.84.9

- cli/install/upload.sh
This behaviour does not exist anymore in awscli v2.
> ci: use paths instead of taking file contents from stdin in upload.sh

- crates/engine/schema/src/builder/coerce/error.rs
- crates/engine/schema/src/builder/coerce/extension.rs
- crates/integration-tests/tests/federation/extensions/injection/input_value_set/selection_set.rs
- crates/integration-tests/tests/federation/extensions/validation/default_value.rs
Previously an extensions directive's default value such as:
```graphql
extend schema @link(url: "https://specs.grafbase.com/grafbase", import: ["InputValueSet"])
directive @echo(input: InputValueSet! = "*") on FIELD_DEFINITION
```
wouldn't be coerced into the right type.
Need to duplicate again the coercion logic. Input values are really
messy now will improve this once we remove `@authorized` in favor of
extensions.
> fix(engine): coerce extension directive default values

- extensions/jwt/Cargo.lock
- extensions/rest/Cargo.lock
- extensions/rest/README.md
- extensions/rest/definitions.graphql
- extensions/rest/src/types.rs
- extensions/rest/tests/integration_tests.rs
Mainly just using the new `UrlTemplate` type, testing fetching with an id, deletions and updates. Enables all verbs.
> feat(rest): use arguments to generate the path

- Cargo.lock
- gateway/CHANGELOG.md
- gateway/Cargo.toml
- gateway/changelog/0.28.5.md
- The `[authentication.providers.jwt.jwks]` section in gateway configuration can now take an array for the `audience` field. This allows the JWT to match any of the audiences in the array.
> gateway: release 0.28.5

- cli/install/upload.sh
aws cli introduced a new default checksum algorithm that R2 does not support. The solution is to explicitly set the checksum algorithm to CRC32. I confirmed this in manual testing.
See the "Compatibility" section here: https://developers.cloudflare.com/r2/examples/aws/aws-cli/
closes GB-8490
> ci: fix R2 uploads in release pipeline

- crates/engine/axum/src/middleware/telemetry.rs
- crates/engine/src/engine/execute/single.rs
- crates/engine/src/engine/execute/stream.rs
- crates/telemetry/src/metrics/engine.rs
- crates/telemetry/src/metrics/request.rs
Those are geared towards query/mutations, so latency in particular
doesn't make any sense. We have to come up with appropriate metrics for
subscriptions later.
> chore: Do not send any operation/request metrics for subscriptions

- Cargo.lock
- cli/templates/extension/src/resolver.rs.template
- cli/tests/extension/mod.rs
- cli/tests/integration/data/echo_extension/src/lib.rs
- crates/engine/Cargo.toml
- crates/engine/src/resolver/extension/mod.rs
- crates/engine/src/resolver/extension/subscription_resolver.rs
- crates/grafbase-sdk/Cargo.toml
- crates/grafbase-sdk/src/extension.rs
- crates/grafbase-sdk/src/extension/resolver.rs
- crates/grafbase-sdk/src/host_io.rs
- crates/grafbase-sdk/src/host_io/pubsub.rs
- crates/grafbase-sdk/src/host_io/pubsub/nats.rs
- crates/grafbase-sdk/wit/world.wit
- crates/integration-tests/src/federation/runtime/extension.rs
- crates/runtime/Cargo.toml
- crates/runtime/src/extension.rs
- crates/wasi-component-loader/Cargo.toml
- crates/wasi-component-loader/examples/extensions/simple-resolver/src/lib.rs
- crates/wasi-component-loader/src/extension/instance.rs
- crates/wasi-component-loader/src/extension/runtime.rs
- extensions/jwt/Cargo.lock
- extensions/nats/Cargo.lock
- extensions/nats/src/lib.rs
- extensions/nats/src/subscriber.rs
- extensions/nats/src/subscription.rs
- extensions/nats/src/types.rs
- extensions/rest/Cargo.lock
- extensions/rest/src/lib.rs
The user-facing API for subscriptions is now just one method. We will handle polling behind the scenes.
The host side returns stream instead of a channel.
> feat: after-merge fixes to the subscribe api

- Cargo.lock
- crates/wasi-component-loader/Cargo.toml
- crates/wasi-component-loader/src/extension/runtime.rs
- extensions/jwt/Cargo.lock
- extensions/nats/Cargo.lock
- extensions/rest/Cargo.lock
We avoid taking the instance out from the pool, and can reuse it for the next request.
> fix: utilize unfold with extension subscriptions

- Cargo.lock
- crates/grafbase-workspace-hack/Cargo.toml
- crates/integration-tests/tests/federation/basic/headers.rs
- crates/runtime-local/Cargo.toml
- gateway/changelog/unreleased.md
- gateway/tests/telemetry/tracing.rs
Adds support for gzip, brotli, zstd, deflate. The HTTP client used to issue requests to subgraphs will send them in the `Accept-Encoding` header and transparently decompress them.
> gateway: enable automatic subgraph response compression

- .github/renovate.json
There are a few crates we just cannot upgrade right now due to broken version compatibilities with other crates. We'll revisit when the other crates work better with these.
> fix: prevent renovate updates for certain crates

- .github/workflows/rust-prs.yml
We should make sure the binaries are built always if we run extension tests.
> fix: build cli and gateway always in extensions run

- Cargo.lock
- cli/tests/extension/mod.rs
- crates/grafbase-sdk/Cargo.toml
- crates/grafbase-sdk/README.md
- crates/grafbase-sdk/src/cbor.rs
- crates/grafbase-sdk/src/host_io/cache.rs
- crates/grafbase-sdk/src/lib.rs
- crates/grafbase-sdk/src/test/config.rs
- crates/grafbase-sdk/src/test/runner.rs
- crates/grafbase-sdk/src/types.rs
- extensions/jwt/Cargo.lock
- extensions/nats/Cargo.lock
- extensions/nats/definitions.graphql
- extensions/nats/src/lib.rs
- extensions/nats/src/types.rs
- extensions/nats/tests/integration_tests.rs
- extensions/rest/Cargo.lock
- extensions/rest/definitions.graphql
- extensions/rest/src/lib.rs
- extensions/rest/tests/integration_tests.rs
This starts the docs effort for NATS, but does not document anything NATS related yet. Preliminary things I found when testing:
- Minicbor is not serializing nulls correctly. We have an open PR but we need to vendor this code until it is merged
- Simplify NATS return types for static return values like booleans or integers
- document REST directives
> chore: add docs, fix cbor ser

- cli/src/cli_input/introspect.rs
Makes it impossible to write something like:
`grafbase introspect -H '...' <url>`
> fix(cli/introspect): header argument should not grab all values

- Cargo.lock
- crates/grafbase-hooks/Cargo.toml
- crates/wasi-component-loader/examples/Cargo.lock
- crates/wasi-component-loader/src/instance.rs
Changed the `extensions` field in `error` type to have a binary value rather than a String.
> hooks release 0.4

- cli/src/backend/api/graphql/api.graphql
- cli/src/backend/api/graphql/types/mutations.rs
- cli/src/backend/api/graphql/types/queries/subgraph_schemas_by_branch.rs
- cli/src/backend/api/publish.rs
- cli/src/backend/dev/hot_reload.rs
- cli/src/backend/dev/subgraphs.rs
- cli/src/cli_input/publish.rs
- cli/src/publish.rs
Add --virtual to the call to define the subgraph as virtual, e.g. to be managed by an extension.
> fix: subgraph url can be nullable

- Cargo.lock
- crates/engine/src/execution/error.rs
- crates/engine/src/resolver/graphql/request/execute.rs
- crates/grafbase-workspace-hack/Cargo.toml
- crates/integration-tests/src/fetch.rs
- crates/integration-tests/tests/federation/basic/headers.rs
- crates/integration-tests/tests/federation/subgraphs/not_reachable.rs
- crates/integration-tests/tests/federation/timeouts.rs
- crates/runtime-local/Cargo.toml
- crates/runtime-local/src/fetch.rs
- crates/runtime-local/src/fetch/signing.rs
- crates/runtime/Cargo.toml
- crates/runtime/src/fetch.rs
- gateway/tests/access_logs/mod.rs
- gateway/tests/integration_tests.rs
- gateway/tests/telemetry/metrics/operation.rs
- gateway/tests/telemetry/metrics/operation/subgraph.rs
- gateway/tests/telemetry/metrics/request.rs
A few improvements for HTTP requests:
- hide the error details in the GraphQL error and instead log it as `ERROR`. The error now displays more information as `reqwest` hides information with `std::fmt::Display` but not with `std::fmt::Debug`.
- Use hickory DNS resolver in reqwest
- Use a pool idle timeout of 5s. Unclear why, but this does help picking up DNS changes even within a benchmark that is ramping up traffic.
- disable zstd from reqwest, doesn't seem to work well.
> fix: runtime fetch fixes

- .github/actions/install-rust/action.yml
- Cargo.lock
- crates/engine/src/resolver/extension/subscription_resolver.rs
- crates/grafbase-sdk/src/component/extension.rs
- crates/grafbase-sdk/src/component/mod.rs
- crates/grafbase-sdk/src/extension/resolver.rs
- crates/grafbase-sdk/src/test/config.rs
- crates/grafbase-sdk/src/types/directive.rs
- crates/grafbase-sdk/wit/world.wit
- crates/integration-tests/src/federation/runtime/extension.rs
- crates/runtime/src/error.rs
- crates/runtime/src/extension.rs
- crates/wasi-component-loader/Cargo.toml
- crates/wasi-component-loader/src/extension/instance.rs
- crates/wasi-component-loader/src/extension/runtime.rs
- crates/wasi-component-loader/src/extension/runtime/subscription.rs
- crates/wasi-component-loader/src/extension/runtime/subscription/dedup.rs
- crates/wasi-component-loader/src/extension/runtime/subscription/unique.rs
- crates/wasi-component-loader/src/extension/wit/directive.rs
- crates/wasi-component-loader/src/tests/extensions.rs
- extensions/jwt/extension.toml
- extensions/nats/Cargo.lock
- extensions/nats/README.md
- extensions/nats/extension.toml
- extensions/nats/src/lib.rs
- extensions/nats/tests/integration_tests.rs
- extensions/rest/Cargo.lock
- extensions/rest/README.md
- extensions/rest/extension.toml
Extension has a new optional method to implement for returning a unique ID based on subscription input:
- If two subscription calls have the same unique ID, they will share one subscription and get the same data from that place.
- If the IDs are different, both callers use their own instances and streams
- If the ID is `None`, we continue to use the old path and every caller gets their own instance.
> feat: extension subscription deduplication

- .github/workflows/gateway-partial-release.yml
- .github/workflows/grafbase-partial-release.yml
This broke randomly in the last few days. Might be that our github runner has now too old aws, without --checksum-algorithm available. Oh well, let's try to install it manually!
> chore: install aws cli manually on release

- cli/templates/extension/src/auth.rs.template
- cli/templates/extension/src/resolver.rs.template
- cli/tests/extension/mod.rs
- cli/tests/integration/data/echo_extension/src/lib.rs
- crates/grafbase-sdk/src/component/state.rs
- crates/grafbase-sdk/src/extension.rs
- crates/grafbase-sdk/src/extension/authentication.rs
- crates/grafbase-sdk/src/extension/authorization.rs
- crates/grafbase-sdk/src/extension/resolver.rs
- crates/grafbase-sdk/src/lib.rs
- crates/grafbase-sdk/src/types.rs
- crates/wasi-component-loader/examples/extensions/caching-auth/src/lib.rs
- crates/wasi-component-loader/examples/extensions/simple-resolver/src/lib.rs
- extensions/jwt/Cargo.lock
- extensions/jwt/src/lib.rs
- extensions/nats/src/lib.rs
- extensions/rest/src/lib.rs
The `Extension` trait is redundant with the other `ResolverExtension` etc. trait. So moved the `new` method in there. This also cleans up the `new` for authentication & authorization as they will never receive any schema directives.
This plus the previous `Resolver` -> `ResolverExtension` rename, makes the extension definition simpler as a simple import is necessary the `XExtension` trait & macro.
I've changed the few uses I've seen of `Box<dyn std::error::Error>` also. We're returning GraphQL errors which can have extensions, so IMHO it's a better default type and makes this more consistent overall.
The SDK namespace is not very consistent though. `Error` and `Headers` are part of the root namespace but others like `QueryElements` for authorization aren't. Should we add all the types in …
> chore: Remove Extension trait

- crates/gateway-config/src/extensions.rs
- crates/serde-dynamic-string/src/lib.rs
Treat every string value inside `[extensions.<name>.config]` as a `DynamicString<String>`, meaning environment variables will be expanded:
```toml
[extensions.snowflake.config]
warehouse = "Test"
[extensions.snowflake.config.authentication]
private_key = "{{ env.SNOWFLAKE_PRIVATE_KEY }}"
```
closes GB-8647
> gateway-config: env var expansion in extensions config

- cli/src/backend/dev.rs
- cli/src/backend/dev/configurations.rs
- cli/src/backend/dev/extensions.rs
- cli/src/backend/dev/subgraphs.rs
- cli/src/cli_input.rs
- cli/src/cli_input/compose.rs
- cli/src/cli_input/graph_ref.rs
- cli/src/cli_input/sub_command.rs
- cli/src/compose.rs
- cli/src/dev.rs
- cli/src/errors.rs
- cli/src/main.rs
- cli/src/output/report.rs
This is long overdue. The options and the logic to fetch subgraph schemas are taken from `grafbase dev`. If `--graph-ref` is passed, the subgraphs from the given remote graph are taken into account, in addition to the subgraphs from the local configuration toml (if present). One of `--graph-ref` or the local paths must be present.
closes GB-6934
> cli: grafbase compose command

- crates/engine/codegen/domain/query_plan.graphql
- crates/engine/src/prepare/cached/builder/mod.rs
- crates/engine/src/prepare/cached/builder/shapes/mod.rs
- crates/engine/src/prepare/cached/query_plan/field/data.rs
- crates/engine/src/prepare/cached/query_plan/field/typename.rs
- crates/engine/src/prepare/cached/query_plan/generated/selection_set.rs
- crates/engine/src/prepare/cached/query_plan/selection_set.rs
- crates/engine/src/prepare/cached/shape/concrete.rs
- crates/engine/src/prepare/operation_plan/model/selection_set.rs
- crates/engine/src/resolver/graphql/request/prepare.rs
- crates/engine/src/response/write/deserialize/object/concrete.rs
- crates/integration-tests/tests/federation/extensions/authorization/deny_all.rs
- crates/integration-tests/tests/federation/response_extensions.rs
- extensions/requires-scopes/tests/integration_tests.rs
One of the parts that took significant time in deserialization was the
binary search to detect which field we're currently reading from the
subgraph response as we don't rely on any particular ordering.
I've replaced with a linear search with a increasing offset if the
subgraph response does come in the expected order (for a GraphQL query
at least). It's ~10% faster on big subgraph responses.
We shouldn't have any negative effects from switching to a linear search
as having more than a few dozens of fields is already very unlikely.
> feat(engine): Faster response deserialization

- Cargo.lock
- Cargo.toml
- crates/federated-server/Cargo.toml
- crates/gateway-config/Cargo.toml
- crates/gateway-config/src/telemetry/exporters/otlp.rs
- crates/gateway-config/src/telemetry/mod.rs
- crates/grafbase-workspace-hack/Cargo.toml
- crates/telemetry/Cargo.toml
- crates/telemetry/src/otel.rs
- crates/telemetry/src/otel/logs.rs
- crates/telemetry/src/otel/metrics.rs
- crates/telemetry/src/otel/traces.rs
- gateway/Cargo.toml
Remove useless flag and disable default feature of `opentelmetry-otlp`, they changed 2 months ago to use `reqwest-blocking-client` which led to a conflict with our own `reqwest-client` one.
> chore: Remove useless otlp feature flag and fix HTTP exporter

- .github/workflows/gateway-partial-release.yml
- .github/workflows/grafbase-partial-release.yml
- Cargo.lock
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/changelog/0.87.1.md
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
- extensions/nats/Cargo.lock
- gateway/CHANGELOG.md
- gateway/Cargo.toml
- gateway/changelog/0.30.1.md
Again AWS S3 upload issues with releases, let's pray this fix works and we get a release out.
> chore: bump gateway to 0.30.1, cli to 0.87.1

- Cargo.lock
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/changelog/0.87.2.md
- cli/install/upload.sh
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
- gateway/CHANGELOG.md
- gateway/Cargo.toml
- gateway/changelog/0.30.2.md
And remove the crc check from aws upload that fails on CI. This is automatic on newer aws-cli versions anyhow, and I don't have time to fight github the whole day.
> chore: bump gateway to 0.30.2, cli to 0.87.2

- .github/workflows/rust-prs.yml
We only want to test extensions when the gateway or cli changed (they both depend on the extension implementation crates), and we do not want to build them when unrelated crates changed, e.g. graphql-schema-diff.
closes GB-8681
> Repair filtering down of CI jobs in grafbase/grafbase

- .github/workflows/binaries.yml
- .github/workflows/build-gateway-chart.yml
- .github/workflows/cargo-hakari.yml
- .github/workflows/federation-audit.yml
- .github/workflows/gateway-partial-release.yml
- .github/workflows/grafbase-partial-release.yml
- .github/workflows/rust-prs.yml
- gateway/Dockerfile
Adds a few niceties
- sccache everywhere, so build most of the time just our own crates
- use the depot actions with a bit faster CPU and IO, much faster network
- use their docker setup, which caches heavily. so docker builds are extremely fast (when they most of the time just do nothing)
> chore(gb-8682): use depot and sccache to speed up builds

- Cargo.lock
- crates/engine/Cargo.toml
- crates/engine/src/engine/auth_extension.rs
- crates/engine/src/prepare/operation_plan/query_modifications.rs
- crates/integration-tests/src/federation/runtime/extension.rs
- crates/integration-tests/tests/federation/extensions/authorization/deny_all.rs
- crates/integration-tests/tests/federation/extensions/authorization/deny_some.rs
- crates/integration-tests/tests/federation/extensions/authorization/error_response.rs
- crates/integration-tests/tests/federation/extensions/authorization/grant_all.rs
- crates/integration-tests/tests/federation/extensions/authorization/injection/mod.rs
- crates/integration-tests/tests/federation/extensions/authorization/requires_scopes.rs
- crates/runtime/Cargo.toml
- crates/runtime/src/extension.rs
- crates/wasi-component-loader/src/extension/api/since_0_10_0/instance.rs
- crates/wasi-component-loader/src/extension/api/since_0_8_0/instance.rs
- crates/wasi-component-loader/src/extension/api/since_0_8_0/wit/directive.rs
- crates/wasi-component-loader/src/extension/api/since_0_9_0/instance.rs
- crates/wasi-component-loader/src/extension/api/since_0_9_0/wit/directive.rs
- crates/wasi-component-loader/src/extension/instance.rs
- crates/wasi-component-loader/src/extension/runtime.rs
- crates/wasi-component-loader/src/resources/mod.rs
Has two benefits:
- engine doesn't depend on tokio anymore and the lease logic which is
pecular to wasm is kept in wasi-component-loader. (can't pass references so we provide a lease on owned data we want back).
- the logic of whether to create a lock or not can be kept in
wasi-component-loader. If there is single authorization extension,
not only can we skip the lock for the headers but also for the
authorization state later. Not sure how much of a perf impact this
will make though.
> chore(extension): Moving lease logic into wasi-component-loader

- Cargo.lock
- crates/graphql-lint/Cargo.toml
- crates/graphql-lint/src/lib.rs
Types and fields prefixed with `_` like `_Service` are expected.
Imported, namespaced types like `federation__FieldSet` are expected.
closes GB-8713
> graphql-lint: case checks shouldn't fire on imported/federation types

- Cargo.lock
- crates/grafbase-workspace-hack/Cargo.toml
- crates/integration-tests/tests/federation/basic/headers.rs
- crates/integration-tests/tests/federation/extensions/authorization/headers.rs
- crates/runtime-local/Cargo.toml
Now that `reqwest` merged the multi-frame fix in `0.12.13`, should work just fine.
> feat(gateway): Add zstd support back for subgraph requests

- crates/grafbase-sdk/src/host_io/pubsub/nats.rs
- crates/wasi-component-loader/src/extension/runtime.rs
I wrote about using non-JSON payloads, so maybe we should make it easier to access the raw data in NATS.
> docs(gb-8698): add raw byte methods for nats

- .github/workflows/binaries.yml
They broke with the removal of the x86 darwin builds, since the matrix is gone but still referenced in the workflow.
This is currently preventing CLI and gateway releases (see https://github.com/grafbase/grafbase/actions/runs/13963279188/job/39089248373).
> ci: fix darwin artifact uploads

- .github/workflows/binaries.yml
Otherwise the binaries end up in target/release and not in target/aarch64-apple-darwin/release.
See https://github.com/grafbase/grafbase/actions/runs/13964594443/job/39092784514 for an example.
> ci: pass target to cargo build in darwin release pipeline

- Cargo.lock
- crates/federated-server/src/server/gateway.rs
- crates/federated-server/src/server/gateway/gateway_runtime.rs
- crates/wasi-component-loader/src/extension/manager/mod.rs
- gateway/Cargo.toml
- gateway/changelog/0.31.1.md
I was doing:
```rust
let parallelism = std::thread::available_parallelism()
.ok()
// Each extensions takes quite a lot of CPU.
.map(|num| num.get() / 8)
.unwrap_or(1);
```
which was fine on my 32 cores machine, but I guess the gateway has less than that in k8s. So it ended up being 0, and instead of panicking we were just waiting forever on something that will never start despite the fact that there were no tasks to do.
+ release `0.31.1`
> Fix: blocked gateway

- crates/grafbase-hooks/README.md
- examples/gateway-hooks/hooks/src/lib.rs
This patch update the doc and example for the `grafbase-hooks` to reflect the latest changes introduced in the [crate](https://crates.io/crates/grafbase-hooks) 
There's breaking change introduced in `grafbase-hooks-0.3.0`: A new parameter `url: String` is introduced but the doc is not update-to-date.
Before 0.3.0:
[link to the method signature for grafbase-hooks-0.2.0](https://docs.rs/grafbase-hooks/0.2.0/grafbase_hooks/trait.Hooks.html#method.on_gateway_request)
```Rust
fn on_gateway_request(&mut self, context: Context, headers: Headers) -> Result<(), ErrorResponse> {
todo!()
}
```
[link to the method signature for grafbase-hooks-0.4.1](https://docs.rs/grafbase-hooks/0.4.1/grafbase_hooks/trait.Hooks.html#method.on_gateway_request)
```Rust
fn on_gateway_request(&mut self, context: …
```
> docs: update on_gateway_request with the url parameter

- crates/engine/src/prepare/operation_plan/builder.rs
- crates/engine/src/prepare/operation_plan/mod.rs
- crates/engine/src/resolver/extension/mod.rs
- crates/engine/src/resolver/extension/query_or_mutation.rs
- crates/engine/src/resolver/extension/subscription.rs
- crates/engine/src/resolver/graphql/federation.rs
- crates/engine/src/resolver/mod.rs
- crates/integration-tests/src/federation/runtime/extension/dispatch.rs
- crates/integration-tests/src/federation/runtime/extension/test.rs
- crates/integration-tests/tests/federation/extensions/basic.rs
- crates/integration-tests/tests/federation/extensions/resolver/injection/field_set/arguments/mod.rs
- crates/integration-tests/tests/federation/extensions/resolver/injection/template/json.rs
- crates/integration-tests/tests/federation/extensions/resolver/mod.rs
- crates/integration-tests/tests/federation/extensions/resolver/validation/mod.rs
- crates/runtime/src/extension/authorization.rs
- crates/runtime/src/extension/mod.rs
- crates/runtime/src/extension/resolver.rs
- crates/runtime/src/extension/token.rs
- crates/wasi-component-loader/src/extension/runtime.rs
Allows extensions to prepare their execution and cache it as part of the
operation plan.
> feat: Add prepare_field to runtime extension trait

- Cargo.lock
- crates/engine/schema/Cargo.toml
- crates/engine/schema/src/builder/hash.rs
- crates/engine/schema/src/builder/mod.rs
- crates/engine/schema/src/lib.rs
- crates/engine/schema/src/tests.rs
- crates/engine/src/engine/cache.rs
- crates/engine/src/lib.rs
- crates/federated-server/src/server/gateway.rs
- crates/integration-tests/src/federation/builder/engine.rs
- crates/runtime/src/extension/mod.rs
- taplo.toml
Previously only the schema & grafbase code, through the commit hash, would be.
> feat: Include extension catalog as part of operation hash

- crates/grafbase-sdk/changelog/unreleased.md
- crates/grafbase-sdk/src/types/directive.rs
Small change, but it's standalone, so let's get it in independently.
> sdk: deserialize_seed for arguments

- crates/gateway-config/src/telemetry/exporters.rs
- crates/gateway-config/src/telemetry/exporters/otlp.rs
- crates/gateway-config/src/telemetry/exporters/stdout.rs
- crates/gateway-config/src/telemetry/mod.rs
- crates/grafbase-sdk/changelog/unreleased.md
- crates/grafbase-sdk/src/types/directive.rs
- crates/telemetry/src/otel/logs.rs
- crates/telemetry/src/otel/metrics.rs
- crates/telemetry/src/otel/traces.rs
- examples/access-logs/grafbase.toml
- examples/tracing/grafbase/v2/gateway-config.toml
- gateway/changelog/unreleased.md
- gateway/src/args.rs
- gateway/tests/access_logs/mod.rs
- gateway/tests/telemetry/logs.rs
- gateway/tests/telemetry/metrics.rs
- gateway/tests/telemetry/metrics/gdn.rs
- gateway/tests/telemetry/mod.rs
- gateway/tests/telemetry/tracing.rs
For consistency with the rest of the configuration, where we deserialize durations from strings with the `duration_str` crate (e.g. "60s"). This is also what's documented in the public docs. Here we expected integers.
closes GB-8828
> gateway-config: deserialize duration strings in telemetry exporters 

- crates/federated-server/src/error.rs
- crates/federated-server/src/server/graph_fetch_method.rs
- crates/federated-server/src/server/graph_updater/gdn.rs
- crates/gateway-config/src/graph.rs
- crates/gateway-config/src/lib.rs
- crates/serde-dynamic-string/src/lib.rs
- gateway/src/args/std.rs
This is for enterprise platform users who do not use the GDN (Graph Delivery Network), but instead their own HTTP endpoint to serve schemas.
The feature takes the form of a new gateway configuration option:
```
[graph]
schema-fetch-url = "https://my-custom-s3-bucket/my-account-id/{{ graph-ref.graph }}/{{ graph-ref.branch }}"
```
The following variables are available in the url template:
- `graph-ref.graph` : the graph name from the graph ref the gateway was started with.
- `graph-ref.branch`: the optional branch name from the graph ref the gateway was started with.
closes GB-8863
> gateway: configurable GDN poll url

- Cargo.lock
- gateway/Cargo.toml
- gateway/changelog/0.32.0.md
- gateway/changelog/unreleased.md
- The `scheduled_delay` and `timeout` configuration options for telemetry exporters have been updated to accept a duration string instead of a number (https://github.com/grafbase/grafbase/pull/2962).
- Made the GDN poll url configurable (#2990)
For enterprise platform users who do not use the GDN (Graph Delivery Network), but instead their own HTTP endpoint to serve schemas.
The feature takes the form of a new gateway configuration option:
```
[graph]
schema-fetch-url = "https://my-custom-s3-bucket/my-account-id/{{ graph-ref.graph }}/{{ graph-ref.branch }}"
```
The following variables are available in the url template:
- `graph-ref.graph` : the graph name from the graph ref the gateway was started with.
- `graph-ref.branch`: the optional branch name from the graph ref the gateway was …
> gateway: release 0.32.0

- Cargo.lock
- crates/engine/src/engine.rs
- crates/engine/src/execution/request/context.rs
- crates/engine/src/execution/request/errors.rs
- crates/engine/src/execution/request/mod.rs
- crates/engine/src/graphql_over_http/format.rs
- crates/engine/src/graphql_over_http/response.rs
- crates/integration-tests/Cargo.toml
- crates/integration-tests/tests/gateway/graphql_over_http/cbor.rs
- crates/integration-tests/tests/gateway/graphql_over_http/mod.rs
Wanted it for the mcp execute tool as it's faster, might as well just support it
> feat(gateway): Accept application/cbor content-type

- crates/engine/operation/src/bind/coercion/query.rs
- crates/engine/operation/src/bind/error.rs
- crates/engine/operation/src/bind/mod.rs
- crates/engine/operation/src/bind/operation.rs
- crates/engine/operation/src/error.rs
- crates/engine/operation/src/lib.rs
- crates/engine/operation/src/parse/mod.rs
- crates/engine/operation/src/validation/after_binding.rs
- crates/engine/operation/src/validation/after_parsing.rs
- crates/engine/schema/src/definition.rs
- crates/engine/schema/src/directive_site.rs
- crates/engine/schema/src/entity.rs
- crates/engine/schema/src/enum_value.rs
- crates/engine/schema/src/field.rs
- crates/engine/schema/src/input_value_def.rs
- crates/engine/schema/src/interface.rs
- crates/engine/schema/src/object.rs
- crates/engine/src/engine.rs
- crates/engine/src/prepare/mod.rs
- crates/engine/src/prepare/without_cache.rs
- crates/integration-tests/tests/gateway/basic/errors.rs
- crates/integration-tests/tests/gateway/basic/variables.rs
- crates/integration-tests/tests/gateway/graphql_over_http/application_graphql_response_json.rs
- crates/integration-tests/tests/gateway/graphql_over_http/application_json.rs
- crates/integration-tests/tests/gateway/graphql_over_http/batch.rs
- crates/integration-tests/tests/gateway/inaccessible/mod.rs
- crates/integration-tests/tests/gateway/introspection.rs
- crates/integration-tests/tests/gateway/subscriptions/sse.rs
- gateway/tests/telemetry/metrics/operation.rs
Until now we were stopping at the first error. But for MCP we want to
return as much information as possible and it's useful for clients anyway.
Additionally I'm now tracking relevant `DirectiveSiteId`s so that I can
later send the relevant SDL to the LLMs based on the errors. So instead
of just saying "Oops this field doesn't exist!" I'll include the type's
GraphQL definition.
> chore(engine): Better operation errors

- .github/workflows/binaries.yml
So we also publish arm64 images that will show up in pages like https://github.com/grafbase/grafbase/pkgs/container/gateway
Let's use the approach documented here: https://depot.dev/blog/multi-platform-docker-images-in-github-actions
closes GB-8876
> ci: make gateway docker images on GHCR multi-platform

- .github/workflows/rust-prs.yml
- crates/protoc-gen-grafbase-subgraph/src/render_graphql_sdl/graphql_types.rs
- crates/protoc-gen-grafbase-subgraph/src/render_graphql_sdl/services.rs
- crates/protoc-gen-grafbase-subgraph/tests/codegen/well-known-types/wkt.proto
- crates/protoc-gen-grafbase-subgraph/tests/snapshots/codegen_tests__graphql file@routeguide__route_guide.proto.snap
- crates/protoc-gen-grafbase-subgraph/tests/snapshots/codegen_tests__graphql file@taqueria__tacotruck.proto.snap
- crates/protoc-gen-grafbase-subgraph/tests/snapshots/codegen_tests__graphql file@well-known-types__wkt.proto.snap
Not _everything_, but the types we support in the extension so far.
See [the ProtoJSON format docs](https://protobuf.dev/programming-guides/json/) for the canonical mapping to JSON.
Also fix the field types of input types being rendered as output types.
closes GB-8845
> protoc-gen-grafbase-subgraph: well-known types support

- crates/grafbase-sdk/src/test/runner.rs
You get a generic `not found` error with no identifiable source and no useful backtrace when you start the TestRunner with a gateway binary that does not exist.
>  grafbase-sdk: add context to start_server() errors 

- Cargo.lock
- cli/Cargo.toml
- cli/changelog/0.91.0.md
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
- gateway/CHANGELOG.md
- gateway/Cargo.toml
- gateway/changelog/0.35.0.md
For compatibility with the new 0.14.0 release of grafbase-sdk.
> Release gateway 0.35.0 and CLI 0.91.0

- .github/workflows/protoc-gen-grafbase-subgraph-release.yml
v3 is deprecated and it does not work anymore, so the protoc-gen-grafbase-subgraph release workflow does not work
> ci: use upload-artifact v4

- .github/actions/test/action.yml
Exclude irrelevant crate that depends on the protoc binary from the tests in the release pipeline.
> ci: fix gateway and cli release pipelines

- crates/graphql-composition/CHANGELOG.md
- crates/graphql-composition/src/ingest_subgraph.rs
- crates/graphql-composition/src/lib.rs
- crates/graphql-composition/src/subgraphs/directives.rs
- crates/graphql-composition/tests/composition/extensions_basic/api.graphql.snap
- crates/graphql-composition/tests/composition/extensions_basic/federated.graphql.snap
- crates/graphql-composition/tests/composition/extensions_basic/subgraphs/doctors.graphql
Directives from extensions on enum definitions would sometimes fail to appear in the federated SDL.
Extra directives are sorted by directive site id. For every top level type definition, we ingest the type and its directives in a first pass, then the fields / union members in a second pass. Enums are the exception: we ingest the enum values right away. That lead the enum value's directives to come before the enum's directives although their directive side ids are greater. A binary search would then fail to find the enum's directives.
The fix is to ingest directives right after we generate the directive site id.
closes GB-8935
> composition: fix handling of extra directives on enums

- cli/src/dev.rs
- cli/src/dev/extensions.rs
- cli/src/dev/hot_reload.rs
- cli/src/dev/hot_reload/subgraph_watcher.rs
- cli/src/dev/subgraphs.rs
`SubgraphCache` is a type used by the `grafbase dev` command.
The original motivation of this PR is facilitating the integration of the new web UI for grafbase dev, where we will need to gather subgraph and composed schemas in one place to write them to a file.
Before this PR:
- Subgraphs with schemas loaded from files never touched the subgraph cache
- A new subgraph cache was instantiated every time the config was reloaded, but without replacing the existing subgraph cache. This is a bug, because new versions of schemas from files were not getting taken into account.
- Composition logic was in multiple places
This PR centralizes the logic of loading and composing subgraph schemas into the SubgraphCache type.
- `SubgraphCache::new()` instantiates subgraphs at the start.
- …
> cli: make SubgraphCache the source of truth for subgraphs

- cli/changelog/unreleased.md
- cli/src/dev/hot_reload.rs
- cli/src/dev/hot_reload/subgraph_watcher.rs
Sometimes, the command becomes unresponsive. That happens because of the file watcher receiving too many events, causing the gateway embedded in grafbase dev to restart over and over again.
The reason for the flood of events is that the watcher doesn't only watch for created, modified or deleted file events, but also any file access. Other processes and other watchers can cause these events.
I confirmed that the reload behaviour is more reasonable now with manual testing.
closes GB-8626
closes GB-8625
> cli: fix infinite loop in `grafbase dev`

- Cargo.lock
- crates/graphql-composition/Cargo.toml
- crates/graphql-composition/src/compose/directives.rs
- crates/graphql-composition/src/composition_ir/directive.rs
- crates/graphql-composition/src/emit_federated_graph.rs
- crates/graphql-composition/src/emit_federated_graph/context.rs
- crates/graphql-composition/src/emit_federated_graph/context/used_directives.rs
- crates/graphql-composition/src/emit_federated_graph/directive.rs
- crates/graphql-composition/src/ingest_subgraph/directives.rs
- crates/graphql-composition/src/ingest_subgraph/directives/consts.rs
- crates/graphql-composition/src/ingest_subgraph/directives/match_name.rs
- crates/graphql-composition/src/subgraphs.rs
- crates/graphql-composition/src/subgraphs/directives.rs
- crates/graphql-composition/src/subgraphs/linked_schemas.rs
- crates/graphql-composition/tests/composition/composite_schema/federated.graphql.snap
- crates/graphql-composition/tests/composition/composite_schema/subgraphs/b.graphql
- crates/graphql-federated-graph/src/directives/mod.rs
- crates/graphql-federated-graph/src/directives/require.rs
- crates/graphql-federated-graph/src/render_sdl/directive.rs
- crates/graphql-federated-graph/src/render_sdl/render_api_sdl.rs
Before this PR, we supported integrating [composite schemas spec](https://github.com/graphql/composite-schemas-spec/) directives in the federated SDL as a special case of Grafbase extensions by linking "https://specs.grafbase.com/composite-schema/v1".
This worked as a first shallow integration, but we now need to consider `@key`s and `@lookup` directives from the composite schemas spec as defining entities, just like directives from the federation spec.
This PR bakes the composite spec into graphql-composition's understanding of entitiess for validation and federated graph purposes, and emits `@composite__lookup()` and `@composite__require` directives in the federated graph where appropriate.
closes GB-8947
> graphql-composition: limited native composite schemas spec support

- Cargo.lock
- crates/graphql-composition/Cargo.toml
Fixes
- Corrected a bug that made directive imports with `@link(imports:)` sometimes exceed the scope of their subgraph.
Changelog is already up to date.
> graphql-composition: release 0.7.2

- Cargo.lock
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/changelog/0.93.0.md
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
- This release introduces the new revamped web UI exposed by `grafbase dev`. In addition to the GraphQL explorer, it now includes the schema explorer and the AI chat features.
- Introducing a new `grafbase compose` command to compose a federated graph from subgraph schemas. The input subgraphs are discovered in the same way as in `grafbase dev`, that is to say through the `subgraphs.$subgraph_name.schema_path` and `subgraph.$subgraph_name.introspection_url` configuration options, as well as the `--graph-ref` argument.
- Support Postgres extensions in `grafbase dev`
- Fixed infinite loops in file watcher causing `grafbase dev` to become unresponsive
- Fixed schemas from locally running subgraphs not being updated anymore after the first hot reload in `grafbase dev` …
> Release grafbase 0.93.0

- gateway/Dockerfile
remove duplicated USER in Dockerfile: user is already set to `USER grafbase`
> remove duplicated USER in Dockerfile

- crates/graphql-composition/src/ingest_subgraph/directives/match_name.rs
- crates/graphql-composition/src/subgraphs/definitions.rs
- crates/graphql-composition/src/subgraphs/ids.rs
- crates/graphql-composition/src/subgraphs/top.rs
- crates/integration-tests/tests/gateway/extensions/selection_set_resolver/subgraph_schema.rs
That behaviour is for backwards compatibility. Virtual subgraphs are new, let's start clean there.
> composition: no auto-importing federation directives in virtual subgraphs

- Cargo.lock
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/changelog/0.93.1.md
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
- cli/tests/extension/authorization.rs
- cli/tests/extension/mod.rs
- cli/tests/integration/data/Cargo.lock
- The `grafbase dev` web app now correctly injects the MCP server url into the chat page.
> cli: release 0.93.1

- Cargo.lock
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/changelog/0.93.2.md
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
- The `grafbase dev` web app now correctly injects the MCP server url into the chat page.
> cli: release 0.93.2

- crates/engine/codegen/domain/query_plan.graphql
- crates/engine/codegen/domain/schema.graphql
- crates/engine/error/src/path.rs
- crates/engine/schema/src/field.rs
- crates/engine/schema/src/generated/field.rs
- crates/engine/src/prepare/cached/builder/mod.rs
- crates/engine/src/prepare/cached/builder/shapes/mod.rs
- crates/engine/src/prepare/cached/query_plan/field/data.rs
- crates/engine/src/prepare/cached/query_plan/field/lookup.rs
- crates/engine/src/prepare/cached/query_plan/generated/selection_set.rs
- crates/engine/src/prepare/cached/query_plan/selection_set.rs
- crates/engine/src/response/write/deserialize/ctx.rs
- crates/engine/src/response/write/deserialize/list.rs
- crates/engine/src/response/write/deserialize/object/concrete.rs
- crates/integration-tests/tests/gateway/composite/lookup/mod.rs
- crates/integration-tests/tests/gateway/composite/lookup/shape.rs
A classic problem with an index range, taking the start index before
processing sub-fields and the end after. So we ended up with a root
selection set with all nested fields.
Fixed/Improved a few other things also, the problem was here: https://github.com/grafbase/grafbase/pull/3109/files#diff-90b9bc3a66d5fa7490c5eaee0eab69e1cd092e1dbee66fc3218e7177b7908342
> fix(engine): Proper shape computation for lookup fields

- cli/src/compose.rs
- cli/src/dev.rs
- cli/src/dev/hot_reload.rs
- cli/src/dev/subgraphs.rs
- crates/graphql-composition/src/compose/context.rs
- crates/graphql-composition/src/subgraphs.rs
- crates/graphql-composition/src/validate/extension_names.rs
- crates/graphql-composition/tests/composition/extensions_name_collision/federated.graphql.snap
- crates/graphql-composition/tests/composition/extensions_same_extension_ingested_twice/api.graphql.snap
- crates/graphql-composition/tests/composition/extensions_same_extension_ingested_twice/extensions.toml
- crates/graphql-composition/tests/composition/extensions_same_extension_ingested_twice/federated.graphql.snap
- crates/graphql-composition/tests/composition/extensions_same_extension_ingested_twice/subgraphs/irrelevant.graphql
- crates/graphql-composition/tests/composition/extensions_same_extension_ingested_twice/test.md
Until this commit, if you imported the same extension in multiple subgraphs, grafbase dev would ingest it twice and that would trigger a name collision error at the composition stage.
Composition now accepts multiple loaded extension definitions, as long as their urls are compatible (see explanation in the diff).
In addition, grafbase dev also adds extensions from grafbase.toml to the composition input compose now, just so configuration takes precedence for names over auto-detected extensions.
closes GB-8977
> cli: fix extension name collisions in grafbase dev

- Cargo.lock
- cli/Cargo.toml
- cli/changelog/unreleased.md
- cli/src/dev/subgraphs.rs
In both `grafbase dev` and `grafbase compose`.
closes GB-8981
> cli: validate schemas before composition

- Cargo.lock
- crates/graphql-federated-graph/Cargo.toml
- crates/graphql-federated-graph/src/federated_graph.rs
- crates/graphql-federated-graph/src/federated_graph/root_operation_types.rs
- crates/graphql-federated-graph/src/from_sdl.rs
- crates/graphql-federated-graph/src/render_sdl/render_federated_sdl.rs
We don't need to do anything fancy anymore because the engine schema is instantiated from SDL now.
>  graphql-federated-graph: simplify FederatedGraph::default() 

- Cargo.lock
Fixes [AIKIDO-2025-10275](https://security.aikido.dev/cve/AIKIDO-2025-10275)
> upgrade jaq-core

- Cargo.lock
- Cargo.toml
- crates/engine/field-selection-map/Cargo.toml
- crates/engine/field-selection-map/src/lib.rs
- crates/engine/field-selection-map/src/model.rs
- crates/engine/field-selection-map/src/parser.rs
Parser for [FieldSelectionMap](https://github.com/graphql/composite-schemas-spec/blob/main/spec/Appendix%20A%20--%20Field%20Selection.md).
We don't do anything with it yet though.
Fixes: GB-8914
> feat(engine): Add FieldSelectionMap parser

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/changelog/unreleased.md
- cli/src/cli_input.rs
- cli/src/cli_input/sub_command.rs
- cli/src/main.rs
- cli/src/plugins.rs
Like cargo and git.
For example, if you have a `grafbase-postgres` binary installed, you can call it with `grafbase postgres`.
This PR includes:
- Executing third-party plugins when available
- Advertising them in the help text
- A `grafbase list-third-plugins` command to list them
- Handling of bad arguments, unknown third party plugins, etc.
The gateway (`grafbase-gateway`) is given special treatment and excluded from plugins, since it is its own thing, and it would be confusing if `grafbase gateway` worked locally, but not in an environment where the CLI is not installed.
closes GB-8998
> cli: add third-party plugins support

- Cargo.lock
- crates/engine/field-selection-map/Cargo.toml
- crates/engine/field-selection-map/src/model.rs
- crates/engine/field-selection-map/src/parser.rs
- crates/engine/operation/src/bind/coercion/query.rs
- crates/engine/schema/Cargo.toml
- crates/engine/schema/src/builder/coerce/field_selection_map/bind.rs
- crates/engine/schema/src/builder/coerce/field_selection_map/mod.rs
- crates/engine/schema/src/builder/coerce/field_selection_map/target.rs
- crates/engine/schema/src/builder/coerce/field_set.rs
- crates/engine/schema/src/builder/coerce/mod.rs
- crates/engine/schema/src/builder/graph/directives/composite/mod.rs
- crates/engine/schema/src/builder/graph/mod.rs
- crates/engine/schema/src/builder/sdl/directives.rs
- crates/engine/schema/src/ty.rs
- crates/graphql-wrapping-types/src/lib.rs
- crates/graphql-wrapping-types/src/mutable.rs
- crates/integration-tests/tests/gateway/composite/is/argument.rs
- crates/integration-tests/tests/gateway/composite/is/field.rs
- crates/integration-tests/tests/gateway/composite/is/mod.rs
- crates/integration-tests/tests/gateway/composite/mod.rs
I'm binding the `FieldSelectionMap` in the engine now. Validation isn't
finished though, especially for its original use in `@lookup`. But that should be enough for me to get started on the computed fields
> feat(engine): @is binding & initial validation

- Cargo.lock
- cli/Cargo.toml
- cli/changelog/0.94.0.md
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
- gateway/Cargo.toml
- gateway/changelog/0.37.1.md
- Added support for CLI plugins (https://github.com/grafbase/grafbase/pull/3133).
Any binary in your `$PATH` that starts with `grafbase-` will be automatically detected and usable as a subcommand. For example, if you have the `grafbase-postgres` plugin installed, you can run it with `grafbase postgres`. Subsequent arguments are forwarded to the plugin. A new `grafbase list-plugins` command is also introduced. If you are familiar with these, this is similar to how cargo and git plugins work.
- `grafbase dev` and `grafbase extension install` now only download extensions that are not already installed.
- Composition no longer requires `Query` to be non-empty. At least one field must be defined across the query, mutation and subscription roots instead.
- Improvements to composite schema spec …
> Release grafbase 0.94.0 and grafbase-gateway 0.37.1

- cli/changelog/unreleased.md
- cli/src/plugins.rs
If the plugin is available twice, in different directories that are part of `$PATH`, it would should up twice. Deduplicate the list before we print it to avoid that.
closes GB-9030
> cli: fix duplicate entries in `grafbase list-plugins`

- cli/tests/extension/authorization.rs
- cli/tests/extension/mod.rs
- cli/tests/integration/data/Cargo.lock
- crates/federated-server/src/server.rs
- crates/integration-tests/tests/gateway/compression.rs
Using compression with a stream ends up in a panic today:
```
thread 'grafbase-gateway' panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/unfold.rs:108:21:
Unfold must not be polled after it returned `Poll::Ready(None)`
stack backtrace:
0: rust_begin_unwind
1: core::panicking::panic_fmt
2: core::panicking::panic
3: <futures_util::stream::unfold::Unfold<T,F,Fut> as futures_core::stream::Stream>::poll_next
4: <multipart_stream::serializer::Serializer<S,E> as futures_core::stream::Stream>::poll_next
5: <futures_util::stream::try_stream::MapOk<St,F> as futures_core::stream::Stream>::poll_next
6: <axum_core::body::StreamBody<S> as http_body::Body>::poll_frame
7: <http_body_util::combinators::map_err::MapErr<B,F> as …
```
> fix(gateway): panic when using compression with streams

- cli/changelog/unreleased.md
- cli/src/dev/assets.rs
- cli/src/errors.rs
Just so we start clean every time.
closes GB-9062
> cli: delete cli_app directory before unpacking new version

- Cargo.lock
- cli/Cargo.toml
- cli/changelog/0.94.1.md
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
- gateway/Cargo.toml
- New version of the web app served by `grafbase dev` with the explorer, schema viewer and AI chat.
- The assets directory in ~/.grafbase is now cleaned up every time a new assets version is unpacked.
- `grafbase list-plugins` would list plugins that were installed in multiple directories in `$PATH` multiple times. That list is now dedpuplicated. (https://github.com/grafbase/grafbase/pull/3140)
> cli: release 0.94.1

- cli/changelog/unreleased.md
- cli/src/cli_input.rs
- cli/src/cli_input/sub_command.rs
- cli/src/main.rs
- cli/src/plugins.rs
Fits better with the conventions in the rest of the CLI.
> cli: rename list-plugins subcommand to plugins

- crates/engine/field-selection-map/src/model.rs
- crates/engine/field-selection-map/src/parser.rs
- crates/engine/schema/src/builder/coerce/field_selection_map/mod.rs
- crates/engine/schema/src/builder/coerce/field_selection_map/model.rs
- crates/engine/schema/src/builder/graph/directives/composite/derive.rs
Add Identify `.`  for `@derive`
```
type Post {
commentIds: [ID!]
comments: [Comment!] @derive @is(field: "commentIds[{ id: . }]")
}
```
And list without path wich will be used for `@require` with batching:
```
type Post {
commentId: ID
comment(ids: [ID!]! @require(field: "[commentId]")): Comment
}
```
(note: The batching detection with `@require` is pretty hidden and a bit weird, but not sure yet if we can do better.)
> feat(field-selection-map): Add identity "." and list without path

- Cargo.lock
- cli/tests/extension/authorization.rs
- cli/tests/extension/mod.rs
- cli/tests/integration/data/Cargo.lock
- crates/grafbase-sdk/Cargo.toml
- crates/grafbase-sdk/changelog/0.15.6.md
- crates/graphql-composition/CHANGELOG.md
- crates/graphql-composition/Cargo.toml
- crates/graphql-federated-graph/Cargo.toml
https://github.com/grafbase/extensions/pull/90 needs to happen to comply with current composition logic, but the crate isn't published, so the SDK test harness hasn't picked up the change yet.
> Release graphql-composition and grafbase-sdk

- .github/workflows/rust-prs.yml
Couldn't share an image otherwise.
> Add arm64 for rust-pr docker-gateway build

- crates/engine/src/resolver/graphql/request/execute.rs
Instead of error.
closes GB-9095
> gateway: make subgraph request failure log level debug

- cli/tests/integration/data/Cargo.lock
- crates/engine/src/prepare/trusted_documents.rs
- crates/federated-server/src/lib.rs
- crates/federated-server/src/server.rs
- crates/federated-server/src/server/gateway.rs
- crates/federated-server/src/server/graph_fetch_method.rs
- crates/federated-server/src/server/graph_updater.rs
- crates/federated-server/src/server/graph_updater/object_storage.rs
- crates/federated-server/src/server/trusted_documents_client.rs
- crates/gateway-config/src/trusted_documents.rs
- gateway/changelog/unreleased.md
- gateway/tests/integration_tests.rs
- gateway/tests/mocks/mod.rs
- gateway/tests/mocks/object_storage.rs
- gateway/tests/telemetry/metrics.rs
- gateway/tests/telemetry/metrics/object_storage.rs
Most of the PR is renaming. The actual changes are:
- metric names (will update the docs)
- the name of the env var for the URL
- the paths of graphs in the service itself
closes GB-9149
> gateway: replace GDN with new object storage

- Cargo.lock
Otherwise we can't compile on systems with recent versions of oniguruma.
> deps: update onig and onig_sys

- crates/grafbase-sdk/src/types/configuration.rs
- crates/integration-tests/src/gateway/builder/engine.rs
- crates/integration-tests/src/gateway/runtime/extension/builder.rs
- crates/integration-tests/src/gateway/runtime/mod.rs
- crates/integration-tests/tests/gateway/extensions/selection_set_resolver/config.rs
- crates/wasi-component-loader/src/extension/manager/mod.rs
- crates/wasi-component-loader/src/extension/manager/pool.rs
- SDK error is clearer if configuration is null
- We immediately try to load one extension when creating the pool and
made the error a bit clearer.
> feat(gateway): Better errors for extension configuration failures

- cli/Makefile.toml
`pushd` & `popd` are not available in some shells (like Ubuntu's & WSL) so the script won't work there.
So does the final behaviour change if it's replaced by `cd` ?
> chore: use `cd` instead of `pushd` in cli fetch-assets script

- crates/mcp/src/tools/execute.rs
The JSON schema says `variables` is optional in the request, but the implementation requires it. That leads to errors in Cursor.
We can either advertise the `variables` parameter as required, or make it optional to align schema and implementation.
This commit does both, because I couldn't persuade Cursor that it's OK for variables to be optional. So make the variables parameter explicitly required, so Cursor always sends it, but in case it doesn't, it is actually optional.
closes GB-9184
> mcp: align JSON schema and implementation for variables

- cli/src/api/extension_publish.rs
For extension uploads. This too will go away.
> cli: switch from api.ep.grafbase.com to upload.grafbase.com

- Cargo.lock
- crates/engine/Cargo.toml
- crates/engine/codegen/domain/query_plan.graphql
- crates/engine/query-solver/src/solution_space/builder/providable_fields.rs
- crates/engine/schema/src/generated/resolver/lookup.rs
- crates/engine/src/prepare/cached/builder/mod.rs
- crates/engine/src/prepare/cached/query_plan/generated/response_object_set.rs
- crates/engine/src/prepare/operation_plan/builder.rs
- crates/integration-tests/src/gateway/runtime/extension/impls/resolver.rs
- crates/integration-tests/tests/gateway/extensions/resolver/mod.rs
- crates/integration-tests/tests/gateway/extensions/resolver/nested.rs
Previously we wouldn't handle correctly the following:
```graphql
extend schema
@link(url: "resolver-1.0.0", import: ["@resolve"])
scalar JSON
type Query {
me: User @resolve(data: { id: "1", name: "Josh" })
}
type User {
id: ID!
name: String!
friends: [User!]! @resolve(data: [{ id: "2", name: "Alice"}])
}
```
for two reasons:
- we would treat it like a graphql subgraph, meanings `friends` is part of the subgraph, so provideable by the resolver providing `Query.me` which obviously doesn't work here.
- We wouldn't correctly keep track of the dependency from `User.friends` on `Query.me` because there are no field dependencies involved here. We still need the `User` object to be present though.
> fix(engine): Handle nested resolvers within a subgraph

- Cargo.lock
- crates/grafbase-sdk/src/host_io/http.rs
- crates/grafbase-sdk/src/types/headers.rs
- crates/grafbase-sdk/src/wit/mod.rs
- crates/grafbase-sdk/wit/since_0_17_0/headers.wit
- crates/grafbase-sdk/wit/since_0_17_0/http-client.wit
- crates/graphql-composition/src/lib.rs
- crates/wasi-component-loader/Cargo.toml
- crates/wasi-component-loader/src/extension/api/since_0_10_0/wit/headers.rs
- crates/wasi-component-loader/src/extension/api/since_0_17_0/wit/http_client.rs
- crates/wasi-component-loader/src/extension/api/since_0_17_0/wit/mod.rs
- crates/wasi-component-loader/src/http_client.rs
- crates/wasi-component-loader/src/resources/mod.rs
Makes it easier to re-use subgraph headers and error happen earlier in the guest
rather than host side for invalid name/value.
> feat(wit): Improve http client to re-use the http headers resource.

- Cargo.lock
- cli/Cargo.toml
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
Dummy release as I yanked 0.97.0, but didn't know it would break the cli
install script...
I've yanked 0.97.0 because I'm changing the Grafbase SDK wit for the
rest example
> release 0.97.1

- crates/engine/error/src/lib.rs
- crates/engine/src/execution/request/errors.rs
- crates/engine/src/execution/request/mod.rs
- crates/engine/src/graphql_over_http/response.rs
- crates/engine/src/prepare/mod.rs
- crates/engine/src/prepare/operation_plan/error.rs
- crates/engine/src/prepare/operation_plan/mod.rs
- crates/engine/src/response/mod.rs
- crates/grafbase-sdk/src/types/error_response.rs
- crates/integration-tests/data/extensions/Cargo.lock
- crates/integration-tests/data/extensions/crates/auth-017/.gitignore
- crates/integration-tests/data/extensions/crates/auth-017/Cargo.toml
- crates/integration-tests/data/extensions/crates/auth-017/extension.toml
- crates/integration-tests/data/extensions/crates/auth-017/src/lib.rs
- crates/integration-tests/tests/gateway/extensions/authentication/headers.rs
- crates/integration-tests/tests/gateway/extensions/authentication/mod.rs
- crates/integration-tests/tests/gateway/extensions/authorization/error_response.rs
- crates/wasi-component-loader/src/error.rs
- crates/wasi-component-loader/src/extension/api/since_0_17_0/instance/authentication.rs
- crates/wasi-component-loader/src/extension/api/since_0_17_0/instance/authorization.rs
- crates/wasi-component-loader/src/extension/api/since_0_17_0/instance/hooks.rs
- crates/wasi-component-loader/src/extension/api/since_0_17_0/wit/error.rs
- crates/wasi-component-loader/src/extension/api/since_0_9_0/wit/error.rs
- crates/wasi-component-loader/src/extension/runtime/authentication.rs
- crates/wasi-component-loader/src/extension/runtime/authorization.rs
- crates/wasi-component-loader/src/extension/runtime/hooks.rs
- crates/wasi-component-loader/src/tests/extensions.rs
- gateway/tests/hooks/mod.rs
Allows e.g. authentication extensions to return error responses with headers like `WWW-Authenticate`.
> sdk: add headers to ErrorResponse

- Cargo.lock
- cli/Cargo.toml
- cli/changelog/0.98.1.md
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
- cli/src/extension/build.rs
- cli/tests/extension/mod.rs
- cli/tests/integration/data/Cargo.lock
- crates/integration-tests/data/extensions/Cargo.lock
- crates/integration-tests/data/extensions/Cargo.toml
This commit fixes multiple path resolution issues when using the `grafbase extension build` command with the --source-dir flag:
1. **Fixed default scratch_dir path resolution**: When using --source-dir without --scratch-dir, the default "./target" directory is now correctly resolved relative to the source directory rather than the current working directory.
2. **Fixed nested directory creation**: When explicitly providing both --source-dir and --scratch-dir with relative paths, the CLI no longer creates nested directory structures (e.g., "extension/extension/target"). This is achieved by converting relative paths to absolute paths before passing them to cargo.
3. **Fixed workspace configuration**: Excluded the empty "crates/build" directory from the integration test workspace to prevent …
> fix(gb-9252): path issues with extension building

- cli/changelog/unreleased.md
- cli/src/api/graphql/types/queries/subgraph_schemas_by_branch.rs
- cli/src/dev/data_json.rs
- cli/src/dev/hot_reload/subgraph_watcher.rs
- cli/src/dev/subgraphs.rs
Only for subgraphs loaded from the schema registry.
closes GB-9274
>  cli: add subgraph owners to data.json for grafbase dev app

- Cargo.lock
- Cargo.toml
- crates/integration-tests/tests/gateway/mcp/basic.rs
2.0 and 2.1 were just released last week.
> rmcp: use released version instead of git dependency

- cli/changelog/unreleased.md
- cli/src/cli_input/compose.rs
- cli/src/cli_input/dev.rs
- cli/src/cli_input/extension.rs
- cli/src/dev/hot_reload.rs
- cli/src/extension/install.rs
- crates/gateway-config/src/lib.rs
- crates/integration-tests/src/gateway/builder/engine.rs
- gateway/src/args/std.rs
Currently, if the configuration is not found, an empty configuration is assumed. This leads to commands like `grafbase extension install` returning with a successful exit status when no configuration is present. Since the user would expect a failure in this case, the CLI should return with a non-zero exit status.
This commit makes it happen.
closes GB-9277
> cli: error in extension commands when config is not found

- gateway/Dockerfile
- gateway/helm/Chart.yaml
- gateway/helm/values.yaml
Before this commit:
- The grafbase user inside the container is created without a hardcoded UID. In practice, it ends up being 1000
- The podSecurityContext in the helm chart makes the gateway run with user 1001
That leads to a mismatch, with the gateway running as a completely unpriviledged user, that doesn't have access to any files baked into the docker image in later steps.
This is in particular a problem when you install and bake gateway extensions into the docker image. The gateway doesn't have permissions to read them.
In this commit,
- the grafbase user gets UID 1000 assigned explicitly, so it shouldn't change in practice for existing deployments (less breaking)
- the helm chart runs containers as user 1000
So the gateway should run as the grafbase user and have access to the …
> gateway(docker/helm): align UIDs between podSecurityContext and image

- gateway/helm/templates/deployment.yaml
- gateway/helm/values.yaml
And increase the defaults. The gateway can take longer to start because of extensions compilation.
We should work on precompilation.
> gateway/helm: make readiness probe timeouts configurable

- crates/grafbase-sdk/src/extension/contracts.rs
- crates/grafbase-sdk/src/host_io/event_queue.rs
- crates/grafbase-sdk/src/host_io/http.rs
- crates/grafbase-sdk/src/types/authentication.rs
- crates/grafbase-sdk/src/types/headers.rs
- crates/grafbase-sdk/src/types/hooks.rs
- crates/grafbase-sdk/src/wit/mod.rs
- crates/integration-tests/data/extensions/Cargo.lock
- crates/integration-tests/data/extensions/crates/auth-017/Cargo.toml
- crates/integration-tests/data/extensions/crates/auth-017/src/lib.rs
- crates/integration-tests/data/extensions/crates/hooks-19/src/lib.rs
- crates/integration-tests/tests/gateway/extensions/hooks/backwards_compatibility/events_sdk18.rs
- crates/integration-tests/tests/gateway/extensions/hooks/backwards_compatibility/mod.rs
- crates/integration-tests/tests/gateway/extensions/hooks/mod.rs
The `HttpHeaders` were split into `OwnedHttpHeade`, `SharedHttpHeaders` and a `HttpHeaders` trait which really makes way too complex imho. The reason for this was how the events of the event queue were structured. Changed them to struct with `#[non_exhaustive]` and with a function that takes ownership of the headers rather than using references everywhere. In pure Rust you would receive owned variant of the events.
> chore(sdk): Bring back HttpHeaders from SDK 17

- crates/engine/schema/src/builder/graph/directives/common/mod.rs
- crates/engine/schema/src/builder/mod.rs
- crates/engine/schema/src/builder/mutable.rs
- crates/integration-tests/data/extensions/crates/authenticated-19/Cargo.toml
- crates/integration-tests/data/extensions/crates/authenticated-19/definitions.graphql
- crates/integration-tests/data/extensions/crates/authenticated-19/extension.toml
- crates/integration-tests/data/extensions/crates/authenticated-19/src/lib.rs
- crates/integration-tests/data/extensions/crates/authenticated-19/tests/hydra.rs
- crates/integration-tests/data/extensions/crates/authenticated-19/tests/integration_tests.rs
- crates/integration-tests/tests/gateway/extensions/contracts/sdk19/unreachable_types.rs
- crates/integration-tests/tests/gateway/inaccessible/consistency.rs
- crates/integration-tests/tests/gateway/inaccessible/mod.rs
- gateway/changelog/0.44.0.md
If an required argument has an inaccessible type, the parent field/input object will be inaccessible as a client it's not possible to construct a valid operation with it. 
Object, interfaces and input objects without fields, and unions without members will also be marked as inaccessible. Those can't be present in a valid GraphQL schema.
Marked as a breaking change of `0.44` just in case.
> chore: Consistent inaccessible

- examples/authorization/Dockerfile.gateway
- examples/authorization/Dockerfile.rust
- gateway/tests/access_logs/mod.rs
Will pass the CI once I've publised the latest CLI & gateway.
Add a `policy` extension in our authorization example, following the same logic as Apollo federation `@policy`. It requests data from an external auth service.
> feat(examples): Policy example

- .rules.md
- cli/changelog/unreleased.md
- cli/src/cli_input.rs
- cli/src/common.rs
- cli/src/common/log.rs
- cli/src/main.rs
Like the gateway --log-style=pretty. It's more readable.
closes GB-9483
>  cli: output pretty logs by default

- crates/graphql-composition/src/subgraphs/field_types.rs
- crates/graphql-composition/src/subgraphs/fields.rs
- crates/graphql-composition/src/subgraphs/ids.rs
Instead of a BTreeMap. Primary storage access should always be O(1). The existing data structure that holds arguments by name is now an index of top of the new Vec<ArgumentRecord>.
>  graphql-composition: store argument records in Vec 

- crates/graphql-composition/CHANGELOG.md
- crates/graphql-composition/src/validate/selection.rs
- crates/graphql-composition/tests/composition/provides/provides_scalar/api.graphql.snap
- crates/graphql-composition/tests/composition/provides/provides_scalar/diagnostics.snap
- crates/graphql-composition/tests/composition/provides/provides_scalar/federated.graphql.snap
- crates/graphql-composition/tests/composition/provides/provides_scalar/subgraphs/test.graphql
Incidentally found that panic, just fixing it.
> graphql-composition: fixed panic in @provides validation on fields of built-in scalar type

- crates/graphql-composition/CHANGELOG.md
- crates/graphql-composition/src/diagnostics.rs
It would iterate over the errors instead.
> graphql-composition: fix Diagnostics::iter_warnings()

- crates/graphql-composition/CHANGELOG.md
- crates/graphql-composition/src/compose/enums.rs
- crates/graphql-composition/src/subgraphs/fields.rs
- crates/graphql-composition/src/validate.rs
This delivers a significant performance improvement. We measured a 66% improvement on a very large federated graph.
The substance of the optimization is simple: we iterate over BTrees to compose enums, when checking in which positions they are used. This PR changes these code paths to iterate over flat vectors instead.
>  graphql-composition: speed up enum composition 

- crates/engine/src/resolver/extension/query_or_mutation.rs
- crates/engine/src/resolver/extension/selection_set/query_or_mutation.rs
Fixes a panic in itertools because somehow `std::fmt::Display.fmt` gets called twice with opentelemetry and the result of `format_with` doesn't support it.
```
FormatWith: was already formatted once
```
> fix tracing debug

- crates/graphql-composition/src/compose/context.rs
- crates/graphql-composition/src/compose/directives.rs
- crates/graphql-composition/src/composition_ir.rs
- crates/graphql-composition/src/emit_federated_graph/emit_extensions.rs
- crates/graphql-composition/src/ingest_subgraph/directives/match_name.rs
- crates/graphql-composition/src/ingest_subgraph/schema_definitions/link.rs
- crates/graphql-composition/src/lib.rs
- crates/graphql-composition/src/subgraphs.rs
- crates/graphql-composition/src/subgraphs/extensions.rs
- crates/graphql-composition/src/subgraphs/linked_schemas.rs
- crates/graphql-composition/tests/composition/grafbase_extensions/extensions_directives_on_schema_definition/api.graphql.snap
- crates/graphql-composition/tests/composition/grafbase_extensions/extensions_directives_on_schema_definition/extensions.toml
- crates/graphql-composition/tests/composition/grafbase_extensions/extensions_directives_on_schema_definition/federated.graphql.snap
- crates/graphql-composition/tests/composition/grafbase_extensions/extensions_directives_on_schema_definition/subgraphs/init.graphql
- crates/graphql-composition/tests/composition_tests.rs
The changes in #3334 make the logic easier, but also order dependent: you have to ingest extensions, then subgraphs, otherwise your extensions are silently ignored. We do it the other way around in the schema registry.
No changelog because the original change hasn't been released yet.
> graphql-composition: fix ingesting extensions after subgraphs

- crates/grafbase-sdk/changelog/unreleased.md
- crates/grafbase-sdk/src/types/context.rs
Renaming the `authorization_icontext_by_key` on `AuthorizedOperationContext` to `authorization_context_by_key`.
> sdk: fix typo in public API

- .github/workflows/binaries.yml
It broke in https://github.com/grafbase/grafbase/pull/3340
The issue is that the docker-gateway job was changed from depending on test (which depended on lint, which depended on detect-change-type) to depending only on check. However, the job still references needs.detect-change-type.outputs.build in its condition, but detect-change-type is no longer in its dependency chain. This causes the condition to always evaluate to false for non-tag pushes, so the job never runs on main branch pushes anymore - only on tags.
> ci: push latest gateway docker image tag again

- cli/src/dev/subgraphs.rs
- cli/src/mcp.rs
- crates/federation-audit-tests/tests/composition_comparisons.rs
- crates/graphql-composition/CHANGELOG.md
- crates/graphql-composition/src/compose/fields.rs
- crates/graphql-composition/src/compose/object.rs
- crates/graphql-composition/src/ingest_subgraph/fields.rs
- crates/graphql-composition/src/lib.rs
- crates/graphql-composition/src/subgraphs.rs
- crates/graphql-composition/src/subgraphs/fields.rs
- crates/graphql-composition/tests/composition/federation_v1/big_subgraph/api.graphql.snap
- crates/graphql-composition/tests/composition/federation_v1/big_subgraph/diagnostics.snap
- crates/graphql-composition/tests/composition/federation_v1/big_subgraph/federated.graphql.snap
- crates/graphql-composition/tests/composition/federation_v1/big_subgraph/subgraphs/big.graphql
- crates/graphql-composition/tests/composition_special_cases.rs
- crates/graphql-composition/tests/composition_tests.rs
- crates/integration-tests/src/gateway/builder.rs
- gateway/tests/entity_caching/mod.rs
- gateway/tests/telemetry/tracing.rs
This is important for federation v1. If there are definitions in-between, subgraph schemas with something like:
```graphql
extend type A {
fieldC: String
}
type A @key(fields: "a b") {
a: Int
b: Int
}
```
would lead to non-contiguous sections of `subgraphs.keys.keys` to have the same definition id. So when we end up binary searching there, we would land in either section, and miss the key. This is solved by sorting the keys after subgraph ingestion.
To avoid the same problems with extra directives and fields in the future, this PR also makes sure we do this there, and stop relying on the BTreeMap with fields sorted by name, so the bug would manifest immediately for fields too if we didn't sort.
> graphql-composition: handle entities with type extensions

- crates/engine/operation/src/model/response_key.rs
- crates/engine/query-solver/src/solution_space/builder/operation_fields.rs
- crates/engine/src/execution/operation/response_modifier.rs
- crates/engine/src/prepare/cached/builder/shapes/mod.rs
- crates/engine/src/prepare/cached/query_plan/selection_set.rs
- crates/engine/src/prepare/cached/shape/field.rs
- crates/engine/src/prepare/cached/shape/mod.rs
- crates/engine/src/resolver/graphql/federation.rs
- crates/engine/src/response/data.rs
- crates/engine/src/response/path.rs
- crates/engine/src/response/value.rs
- crates/engine/src/response/write/deserialize/object/derive.rs
- crates/engine/src/response/write/deserialize/object/fields.rs
- crates/engine/src/response/write/deserialize/root/fields_guest_batch.rs
- crates/engine/src/response/write/deserialize/root/fields_host_batch.rs
- crates/engine/src/response/write/deserialize/state.rs
We the track the position of every field within the query as a `QueryPosition`. Later it becomes a `Option<QueryPosition>` as fields we add for requirements don't have any.
We use it to return fields in the right order in the response as that's part of the GraphQL spec. The problem is that we need to create those while we're exploding fragments which can result in a huge number of fields, beyond what `u16` supports. De-duplication can only happen after as we might need to plan things differently.
As I've changed this, we increased the size of both `ResposneValueId`, used in the response object path and `FieldShapeRecord`. I could fix the first. But the second requires really complex logic. Unfortunately, it's a really sensible struct for the shape generation so it slowed us down in the …
> Change QueryPosition to be a u32 rather than u16

- Cargo.lock
- crates/graphql-composition/CHANGELOG.md
- crates/graphql-composition/Cargo.toml
- crates/graphql-composition/src/compose.rs
- crates/graphql-composition/src/compose/context.rs
- crates/graphql-composition/src/compose/directives.rs
- crates/graphql-composition/src/compose/entity_interface.rs
- crates/graphql-composition/src/compose/enums.rs
- crates/graphql-composition/src/compose/fields.rs
- crates/graphql-composition/src/compose/input_object.rs
- crates/graphql-composition/src/compose/interface.rs
- crates/graphql-composition/src/compose/object.rs
- crates/graphql-composition/src/compose/roots.rs
- crates/graphql-composition/src/compose/scalar.rs
- crates/graphql-composition/src/compose/validate.rs
- crates/graphql-composition/src/emit_federated_graph/directive.rs
- crates/graphql-composition/src/subgraphs/definitions.rs
- crates/graphql-composition/src/subgraphs/directives.rs
- crates/graphql-composition/src/subgraphs/enums.rs
- crates/graphql-composition/src/subgraphs/fields.rs
- crates/graphql-composition/src/validate.rs
- crates/graphql-composition/src/validate/composite_schemas/post_merge.rs
- crates/graphql-composition/src/validate/composite_schemas/source_schema.rs
- crates/graphql-composition/src/validate/selection.rs
The first commit in this PR is a refactoring. See the commit message.
- Significant performance improvements. We saw a 66% improvement on a very large federated graph, from various optimizations, including iterating over flat data structures instead of BTrees.
- `Diagnostic::composite_schemas_error_code` is now exposed. Note that as the spec and this implementation evolve, more error codes will be added to this enum and its variants.
- Implemented some composite schemas spec validations for the `@override` directive, resulting in more consistent logic and better diagnostics (https://github.com/grafbase/grafbase/pull/3374)
- Implemented the composite schemas spec validation rules for `@shareable`. It makes the validation more relaxed: if any subgraph defines the field as shareable, then …
> graphql-composition: release 0.11.0

- crates/graphql-composition/CHANGELOG.md
- crates/graphql-composition/src/compose/directives.rs
- crates/graphql-composition/src/ingest_subgraph/schema_definitions/link.rs
- crates/graphql-composition/src/subgraphs/directives/link.rs
- crates/graphql-composition/src/subgraphs/extensions.rs
- crates/graphql-composition/tests/composition/composed_directives_basic/diagnostics.snap
- crates/graphql-composition/tests/composition/grafbase_extensions/extensions_basic/diagnostics.snap
- crates/graphql-composition/tests/composition/grafbase_extensions/linked_schemas_with_file_url_are_extensions/api.graphql.snap
- crates/graphql-composition/tests/composition/grafbase_extensions/linked_schemas_with_file_url_are_extensions/diagnostics.snap
- crates/graphql-composition/tests/composition/grafbase_extensions/linked_schemas_with_file_url_are_extensions/federated.graphql.snap
- crates/graphql-composition/tests/composition/grafbase_extensions/linked_schemas_with_file_url_are_extensions/subgraphs/my_extension_subgraph.graphql
- crates/graphql-composition/tests/composition/grafbase_extensions/linked_schemas_with_file_url_are_extensions/test.md
- crates/graphql-composition/tests/composition/namespaced_directive_without_import_are_ignored/subgraphs/diagnostics.snap
- crates/graphql-composition/tests/composition/namespaced_directives_basic/diagnostics.snap
When we encounter an `@link` directive with the `file` schema for its url, we now consider it an extension and use the namespace in `as:` as the extension name.
closes GB-9595
> graphql-composition: automatically define local extensions

- cli/changelog/unreleased.md
- cli/src/api/graphql/api.graphql
- cli/src/api/graphql/types/mutations.rs
- cli/src/api/publish.rs
- cli/src/publish.rs
If you explicitly pass `--virtual` to the `publish` command, and the subgraph already has a URL, it will now become virtual, instead of keeping its URL previously.
closes GB-9610
> cli: allow making an existing subgraph virtual in `grafbase publish`

- crates/graphql-composition/src/ingest_subgraph/schema_definitions/link.rs
- crates/graphql-composition/tests/composition/grafbase_extensions/linked_schemas_with_file_url_are_extensions/api.graphql.snap
- crates/graphql-composition/tests/composition/grafbase_extensions/linked_schemas_with_file_url_are_extensions/federated.graphql.snap
- crates/graphql-composition/tests/composition/grafbase_extensions/linked_schemas_with_file_url_are_extensions/subgraphs/my_other_extension_without_name.graphql
For `@link` imports with file urls without a namespace (`as:`), do not give up immediately on treating them as an extension, but try and infer an extension name from the path:
- if the directory name is "build/", this is probably a locally built extension, in which case the parent directory is a more informative name.
- in all other cases, use the directory name.
> graphql-composition: detect grafbase extensions even without explicit namespace

- Cargo.lock
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/changelog/0.102.5.md
- cli/changelog/unreleased.md
- cli/npm/aarch64-apple-darwin/package.json
- cli/npm/aarch64-unknown-linux-musl/package.json
- cli/npm/cli/package.json
- cli/npm/x86_64-apple-darwin/package.json
- cli/npm/x86_64-pc-windows-msvc/package.json
- cli/npm/x86_64-unknown-linux-musl/package.json
- If you explicitly pass `--virtual` to the `publish` command, and the subgraph already has a URL, it will now become virtual, instead of keeping its URL previously.
- Clearer rules for composition extensions, that are now documented in [the online docs](https://grafbase.com/docs/gateway/extensions/composition) and the graphql-composition crate [`README`](https://github.com/grafbase/grafbase/blob/main/crates/graphql-composition/README.md). This release also includes propagating the `@link` directives to import directives composed with `@composeDirective` in the federated schema.
> cli: release 0.102.5
