grafbase/grafbase

cli/README.md
- Updates the CLI README.md folder structure
=> Update the CLI README folder structure

cli/README.md
=> Readme changes requested by @fbjork

cli/CHANGELOG.md, cli/crates/cli/README.md, cli/crates/cli/src/cli_input.rs
- Updates `init` command description
- Removes the `init` `--template` flag as it's not implemented yet
=> update init description and remove template flag temporarily

cli/CHANGELOG.md, cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/cli/src/cli_input.rs, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml
- Includes the assets when publishing to crates.io
- Fixes the `completions` shell argument not being required
Version bumps
=> CLI alpha version fixes

cli/CHANGELOG.md, cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/cli/src/errors.rs, cli/crates/cli/src/output.rs, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml
- Removes the `v` from version output
- Shortens Node.js error hints
=> Fixes based on feedback

cli/Cargo.lock, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml
- Normalizes dependency versions
- Updates `Cargo.lock`
=> updates, version normalization

cli/Cargo.lock, cli/crates/cli/Cargo.toml, cli/crates/cli/src/cli_input.rs
- Allows tracing only in dev mode
=> allow tracing only in dev

cli/crates/cli/src/output.rs
=> Clippy fix

cli/CHANGELOG.md, cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- Bumps the version of all crates / packages to 0.2.0
=> Bump versions

cli/crates/cli/README.md, cli/npm/cli/README.md
- Removes the `--trace` flag from the README files
=> remove trace from the readme

examples/nextjs/README.md
=> docs(examples/nextjs): update readme instructions

examples/nextjs/src/graphql/codegen.yml, examples/nextjs/src/utils/server-side-fetch.ts, examples/nuxt/codegen.yml, examples/nuxt/src/server/api/graphql.post.ts
In accordance with https://github.com/grafbase/website/pull/698
=> Switch to new x-api-key header

templates/blog/grafbase/schema.graphql, templates/commerce/grafbase/schema.graphql, templates/hackernews/grafbase/schema.graphql
Adds the unique directive to templates.
=> adds unique directive to templates

.prettierrc.js, examples/nuxt/src/components.d.ts, examples/nuxt/src/components/dropdown/index.vue, examples/nuxt/src/components/dropdown/item.vue, examples/nuxt/src/components/theme-switcher.vue, examples/nuxt/src/components/todo/item/create.vue, examples/nuxt/src/components/todo/item/index.vue, examples/nuxt/src/components/todo/list/create.vue, examples/nuxt/src/components/todo/list/index.vue, examples/nuxt/src/composables/getColor.ts, examples/nuxt/src/graphql/schema.ts, examples/nuxt/src/graphql/urql.exchange.ts, examples/nuxt/src/pages/index.vue, examples/nuxt/src/plugins/urql.ts, examples/nuxt/src/server/api/graphql.post.ts
=> add prettier config

examples/nextjs/README.md, examples/nextjs/next.config.js, examples/nextjs/package.json, examples/nextjs/postcss.config.js, examples/nextjs/src/components/dropdown.tsx, examples/nextjs/src/components/layout.tsx, examples/nextjs/src/components/logo.tsx, examples/nextjs/src/components/new-todo-list.tsx, examples/nextjs/src/components/spinner.tsx, examples/nextjs/src/components/theme-switch.tsx, examples/nextjs/src/components/todo-list.create-todo.tsx, examples/nextjs/src/components/todo-list.todo.tsx, examples/nextjs/src/components/todo-list.tsx, examples/nextjs/src/graphql/document.graphql, examples/nextjs/src/graphql/schema/index.ts, examples/nextjs/src/graphql/uqrl.error.ts, examples/nextjs/src/graphql/urql.exchange.ts, examples/nextjs/src/graphql/urql.ts, examples/nextjs/src/pages/_app.tsx, examples/nextjs/src/pages/api/graphql.ts, examples/nextjs/src/pages/index.tsx, examples/nextjs/src/utils/get-color.ts, examples/nextjs/src/utils/server-side-fetch.ts, examples/nextjs/tailwind.config.js, examples/nextjs/yarn.lock
I have fixed the issues with title being undefined/null.
Updated deps.
Some random styling issues
Moved some functions to the top
Applied prettier
=> Small fixes nextjs example

examples/nextjs/src/utils/server-side-fetch.ts, examples/sveltekit/src/routes/graphql/index.ts
Which might be undefined, but we require it.
=> Fix TS errors for GRAFBASE_API_KEY env var

examples/nextjs/src/components/dropdown.tsx, examples/nextjs/src/components/layout.tsx, examples/nextjs/src/components/new-todo-list.tsx, examples/nextjs/src/components/spinner.tsx, examples/nextjs/src/components/theme-switch.tsx, examples/nextjs/src/components/todo-list.create-todo.tsx, examples/nextjs/src/components/todo-list.todo.tsx, examples/nextjs/src/components/todo-list.tsx
=> prettify tailwind classes

cli/CHANGELOG.md, cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- Bumps versions
- Adds changelog
=> bump versions and add changelog

cli/crates/cli/src/errors.rs
- Adds a hint for windows users using the reset command while the CLI is running
=> Reset Windows hint

cli/crates/cli/src/output.rs
- Adds a reset hint for unix users to know to reset any running instances
=> Add reset hint for unix

cli/.gitignore, cli/crates/cli/tests/graphql/default/query.graphql, cli/crates/cli/tests/graphql/pagination/mutation.graphql, cli/crates/cli/tests/graphql/pagination/paginate-todo-lists.graphql, cli/crates/cli/tests/graphql/pagination/paginate-todos.graphql, cli/crates/cli/tests/graphql/pagination/schema.graphql, cli/crates/cli/tests/graphql/relations/link-blog-to-author.graphql, cli/crates/cli/tests/graphql/relations/link-secondary-author-to-blog.graphql, cli/crates/cli/tests/graphql/relations/mutation.graphql, cli/crates/cli/tests/graphql/relations/rename-author.graphql, cli/crates/cli/tests/graphql/relations/unlink-authors-from-blog.graphql, cli/crates/cli/tests/graphql/relations/unlink-blog-from-author.graphql, cli/crates/cli/tests/pagination.rs, cli/crates/cli/tests/relations.rs, cli/crates/cli/tests/utils/consts.rs
- Add tests to cover all SQL statements / operations
- Removes `license.html` from `.gitignore`
=> add tests and cover all SQL / used operation cases

cli/CHANGELOG.md, cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/cli/tests/graphql/scalars/mutation.graphql, cli/crates/cli/tests/graphql/scalars/query.graphql, cli/crates/cli/tests/graphql/scalars/schema.graphql, cli/crates/cli/tests/scalars.rs, cli/crates/cli/tests/utils/consts.rs, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- Adds tests for JSON, URL, Email, Timestamp and IPAddress
- Bumps versions
- Updates CHANGELOG.md
=> scalars, tests

cli/CHANGELOG.md, cli/crates/cli/tests/graphql/scalars/mutation.graphql
- Use millisecond precision timestamp in test
- Adds a missing change to the changelog
=> Add missing change to changelog, Fix timestamp format in test

templates/blog/grafbase/schema.graphql, templates/commerce/grafbase/schema.graphql, templates/hackernews/grafbase/schema.graphql
Updates templates to use the newly launched `Email` and `URL` scalars.
=> update templates to use new scalars

cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml
=> normalize versions

cli/.config/nextest.toml
And fix nextest for everyone trying to run tests with it.
=> Make it explicit that tests don't work concurrently

cli/crates/cli/tests/dev.rs, cli/crates/cli/tests/graphql/concurrency/mutation.graphql, cli/crates/cli/tests/graphql/concurrency/query.graphql, cli/crates/cli/tests/graphql/default/mutation.graphql, cli/crates/cli/tests/graphql/default/query.graphql, cli/crates/cli/tests/graphql/pagination/mutation.graphql, cli/crates/cli/tests/graphql/pagination/paginate-todo-lists.graphql, cli/crates/cli/tests/graphql/relations/mutation.graphql, cli/crates/cli/tests/graphql/relations/query.graphql, cli/crates/cli/tests/relations.rs
- Modifies the existing tests for nested pagination (needs a worker update)
=> Add tests for nested pagination

examples/nuxt/package.json, examples/nuxt/src/components.d.ts, examples/nuxt/src/graphql/schema.ts, examples/nuxt/yarn.lock
=> patch: update nuxt

cli/CHANGELOG.md, cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- Bumps versions and updates the changelog
=> bump versions and changelog

cli/rust-toolchain.toml
=> update rust to 1.64.0

examples/nextjs/src/components/todo-list.tsx, examples/nextjs/src/graphql/document.graphql, examples/nextjs/src/graphql/schema/index.ts, examples/nuxt/grafbase/schema.graphql, examples/nuxt/src/components.d.ts, examples/nuxt/src/components/todo/list/index.vue, examples/nuxt/src/graphql/document.graphql, examples/nuxt/src/graphql/schema.ts, examples/remix/app/components/todo-list.tsx, examples/remix/app/graphql/document.graphql, examples/remix/app/graphql/schema.ts, examples/sveltekit/.env.example, examples/sveltekit/src/graphql/document.graphql, examples/sveltekit/src/graphql/schema/index.ts, examples/sveltekit/src/lib/TodoList.svelte
Recent changes to nested pagination need to be reflected in all examples.
=> Fix pagination in examples

cli/CHANGELOG.md
=> Changelog update

.github/actions/init_rust_job/action.yml, .github/workflows/cli.yml, .github/workflows/partial-release.yml, cli/CHANGELOG.md, cli/changelog/0.1.0-pre.0.md, cli/changelog/0.1.0-pre.1.md, cli/changelog/0.1.0-pre.2.md, cli/changelog/0.1.0-pre.3.md, cli/changelog/0.1.0-pre.4.md, cli/changelog/0.1.0-pre.5.md, cli/changelog/0.1.0-pre.6.md, cli/changelog/0.1.0-pre.7.md, cli/changelog/0.10.0.md, cli/changelog/0.10.1.md, cli/changelog/0.2.0.md, cli/changelog/0.2.1.md, cli/changelog/0.2.2.md, cli/changelog/0.3.0.md, cli/changelog/0.4.0.md, cli/changelog/0.4.1.md, cli/changelog/0.5.0.md, cli/changelog/0.5.1.md, cli/changelog/0.6.0.md, cli/changelog/0.7.0.md, cli/changelog/0.8.0.md, cli/changelog/0.9.0.md, cli/changelog/0.9.1.md, cli/rust-toolchain.toml
Adds the workflow to automate the release based on tags
=> GB-1499: CLI release pipeline

examples/nextjs/src/graphql/document.graphql, examples/nuxt/src/graphql/document.graphql, examples/remix/app/graphql/document.graphql, examples/sveltekit/src/graphql/document.graphql
=> update examples to use by arg for update/delete

.github/workflows/cli.yml
- Uses a specific gateway version rather than latest
=> Set a specific gateway version

examples/nextjs-clerk/package.json, examples/nextjs-clerk/pages/index.tsx, examples/nextjs-clerk/yarn.lock, examples/nextjs/package.json, examples/nextjs/yarn.lock
=> Upgrade to Next.js 13

cli/.gitignore, flake.lock, flake.nix
Add a simple Nix Flake for development shell in Linux.
=> Add Nix Flake for dev shell (linux)

.github/workflows/cli.yml
- db listener
- cleanup
- clippy fix
- fix typing for stream router req
- parity with aws format
- clarfy comment
- add comment
- typo fix
- cleanup
- add approximate datetime to trigger, prevent race condition with existing modifications
- const cleanup
- remove comment
- clarify wording
- fix(live queries): Buf fix & more tracing
- Disable deeply nested check (#144)
- Pass regsitry location to parser-wasm
- fix(cli/tests): Fix auth test
- fix(ci): Update assets
=> db listener assets update

flake.lock, flake.nix
=> Update Flake & add sccache

.github/actions/init_rust_job/action.yml, .github/workflows/cli.yml, cli/Cargo.lock, cli/crates/server/Cargo.toml
Adds the necessary changes to deal with openssl requirement when targeting musl
=> fix: openssl issue for linux

.github/workflows/cli.yml
=> fix(server/assets): Update to avoid invalid symlink problem

cli/.cargo/config.toml, cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/backend/src/errors.rs, cli/crates/backend/src/project.rs, cli/crates/cli/Cargo.toml, cli/crates/cli/README.md, cli/crates/cli/src/cli_input.rs, cli/crates/cli/src/errors.rs, cli/crates/cli/src/init.rs, cli/crates/cli/src/main.rs, cli/crates/cli/tests/init.rs, cli/crates/cli/tests/utils/environment.rs, cli/crates/server/Cargo.toml, cli/crates/server/src/servers.rs, cli/npm/cli/README.md
- Supports named and URL based init templates
- Cleans up dependencies
=> GB-1504 - Init templates

templates/blog/grafbase/schema.graphql, templates/commerce/grafbase/schema.graphql, templates/hackernews/grafbase/schema.graphql, templates/todo/grafbase/schema.graphql
=> remove id from templates

examples/README.md, examples/eleventy/.eleventy.js, examples/eleventy/.env.example, examples/eleventy/.gitignore, examples/eleventy/README.md, examples/eleventy/grafbase/schema.graphql, examples/eleventy/package-lock.json, examples/eleventy/package.json, examples/eleventy/src/_data/messages.js, examples/eleventy/src/_includes/base.njk, examples/eleventy/src/index.njk, examples/eleventy/src/messages/id.njk, examples/fresh/README.md
=> feat(examples): add eleventy example

.github/workflows/cli.yml, cli/crates/cli/tests/dev.rs, cli/crates/cli/tests/graphql/default/create.graphql, cli/crates/cli/tests/graphql/default/update.graphql, cli/crates/cli/tests/graphql/default_directive/create-user1.graphql, cli/crates/cli/tests/graphql/default_directive/create-user2.graphql, cli/crates/cli/tests/graphql/default_directive/schema.graphql, cli/crates/cli/tests/graphql/reserved_dates/create-todo-list.graphql, cli/crates/cli/tests/graphql/reserved_dates/create-todo.graphql, cli/crates/cli/tests/graphql/reserved_dates/nested-creation.graphql, cli/crates/cli/tests/utils/consts.rs, flake.nix
The update mutation was returning stale data before, improving a e2e
test to check for it.
=> tests: Improve e2e dev test case

cli/crates/cli/tests/scalars.rs
=> tests: fix duplicated scalar e2e test

cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/backend/src/errors.rs, cli/crates/backend/src/project.rs, cli/crates/cli/README.md, cli/crates/cli/src/cli_input.rs, cli/crates/cli/src/errors.rs, cli/crates/cli/tests/init.rs, cli/crates/cli/tests/utils/environment.rs, cli/npm/cli/README.md
- Adds default branch detection to the init template mechanism
- Corrects some of the backend error codes
- Fixes extraction to the incorrect location when using `init` with a named project
- Removes an unused error type
=> Fix named dir, allow branchless URL

cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml
- Use the same rustls feature for all reqwest dependencies
=> normalize reqwest features

.github/actions/cdn_assets/action.yml, .github/actions/init_rust_job/action.yml, .github/actions/sanitize/action.yml, .github/workflows/cli.yml, .github/workflows/partial-release.yml
=> Refactor pipeline and review build cache

cli/about.toml
=> add bsd 2 clause

examples/qwik/.env, examples/qwik/src/routes/index.tsx
update env vars for qwik example
=> refactor: update env vars

flake.lock, flake.nix
- Add proper darwin support for nix flake
- Add nightly clippy
- Update flake lock
=> flake darwin

.github/workflows/sanitize-alert-schedule.yml
Adds a scheduled daily sanitization with alerting
=> feat: add a scheduled sanitization with latest assets

.github/workflows/cli.yml
=> fix(ci): add push tags trigger

cli/crates/cli/tests/coercion.rs, cli/crates/cli/tests/graphql/coercion/create-dummy.graphql, cli/crates/cli/tests/graphql/coercion/schema.graphql, cli/crates/cli/tests/graphql/pagination/paginate-todo-lists.graphql, cli/crates/cli/tests/graphql/pagination/paginate-todos.graphql, cli/crates/cli/tests/pagination.rs, cli/crates/cli/tests/utils/consts.rs, flake.lock
=> tests: Add pagination tests for ordering

packages/grafbase-nextjs-plugin/README.md, packages/grafbase-nextjs-plugin/package.json, packages/grafbase-nextjs-plugin/src/index.ts
=> packages(nextjs-plugin): add docs and release

cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/backend/src/consts.rs, cli/crates/backend/src/errors.rs, cli/crates/backend/src/lib.rs, cli/crates/backend/src/login.rs, cli/crates/backend/src/logout.rs, cli/crates/backend/src/types.rs, cli/crates/cli/Cargo.toml, cli/crates/cli/src/cli_input.rs, cli/crates/cli/src/errors.rs, cli/crates/cli/src/login.rs, cli/crates/cli/src/logout.rs, cli/crates/cli/src/main.rs, cli/crates/cli/src/output.rs, cli/crates/common/src/consts.rs, cli/crates/common/src/environment.rs, cli/crates/server/src/consts.rs, cli/crates/server/src/servers.rs
=> GB-1500 - Login

cli/Cargo.lock, cli/crates/backend/src/server_api.rs, cli/crates/cli/Cargo.toml, cli/crates/cli/src/dev.rs, cli/crates/cli/tests/coercion.rs, cli/crates/cli/tests/graphql/search/create-list.graphql, cli/crates/cli/tests/graphql/search/create-optional.graphql, cli/crates/cli/tests/graphql/search/create-required.graphql, cli/crates/cli/tests/graphql/search/schema.graphql, cli/crates/cli/tests/graphql/search/search-list.graphql, cli/crates/cli/tests/graphql/search/search-optional.graphql, cli/crates/cli/tests/graphql/search/search-required.graphql, cli/crates/cli/tests/scalars.rs, cli/crates/cli/tests/search.rs, cli/crates/cli/tests/utils/consts.rs, cli/crates/cli/tests/utils/environment.rs, cli/crates/server/Cargo.toml, cli/crates/server/src/bridge.rs, cli/crates/server/src/bridge/errors.rs, cli/crates/server/src/bridge/search.rs, cli/crates/server/src/bridge/server.rs, cli/crates/server/src/bridge/types.rs, cli/crates/server/src/servers.rs, cli/scripts/dev.sh, flake.lock, flake.nix
- Create an in-memory Tantivy index for search requests
- Added a `./scripts/dev.sh` to run grafbase with custom assets pushed by the api CI.
Resolves: GB-2982
=> features(search): Add local search with basic API

cli/scripts/load-assets.sh
=> fix(cli/scripts): Simplify load-assets script

.github/workflows/cli.yml, cli/crates/cli/tests/search.rs, cli/crates/server/src/bridge/search.rs, cli/crates/server/src/bridge/types.rs, cli/crates/server/src/servers.rs
=> Fixes: Increase request limit & fix search tests

cli/crates/server/src/bridge.rs, cli/crates/server/src/bridge/errors.rs, cli/crates/server/src/bridge/resolvers.rs, cli/crates/server/src/bridge/server.rs, cli/crates/server/src/bridge/types.rs, cli/crates/server/src/custom_resolvers.rs, cli/crates/server/src/servers.rs
Adds support for running resolvers in the dev mode.
=> GB-3086: Add support for running resolvers in the dev mode

examples/README.md, examples/nextjs-auth0/.env.example, examples/nextjs-auth0/.eslintrc.json, examples/nextjs-auth0/.gitignore, examples/nextjs-auth0/README.md, examples/nextjs-auth0/grafbase/.env.example, examples/nextjs-auth0/grafbase/schema.graphql, examples/nextjs-auth0/next-env.d.ts, examples/nextjs-auth0/next.config.js, examples/nextjs-auth0/package-lock.json, examples/nextjs-auth0/package.json, examples/nextjs-auth0/pages/_app.tsx, examples/nextjs-auth0/pages/api/auth/[...auth0].ts, examples/nextjs-auth0/pages/api/auth/token.ts, examples/nextjs-auth0/pages/index.tsx, examples/nextjs-auth0/tsconfig.json
=> feat(examples): add auth0 example

cli/crates/server/src/bridge/resolvers.rs, cli/crates/server/src/bridge/server.rs, cli/crates/server/src/custom_resolvers.rs, cli/crates/server/src/servers.rs
=> Add support for environment variables to resolvers

cli/crates/server/src/bridge/resolvers.rs, cli/crates/server/src/bridge/server.rs, cli/crates/server/src/bridge/types.rs
Signed-off-by: Anthony Griffon <anthony@griffon.one>
=> GB-3143: Add parent payload for resolvers

cli/crates/server/src/bridge/resolvers.rs, cli/crates/server/src/bridge/server.rs, cli/crates/server/src/bridge/types.rs, cli/crates/server/src/custom_resolvers.rs
=> Escape environment variables that get added to wrangler.toml

.github/workflows/cli.yml, cli/Cargo.lock, cli/crates/backend/src/api/graphql/api.graphql, cli/crates/cli/Cargo.toml, cli/crates/cli/tests/graphql/owner/global/todo/todo-create.graphql, cli/crates/cli/tests/graphql/owner/global/todo/todo-delete.graphql, cli/crates/cli/tests/graphql/owner/global/todo/todo-get.graphql, cli/crates/cli/tests/graphql/owner/global/todo/todo-list.graphql, cli/crates/cli/tests/graphql/owner/global/todo/todo-schema.graphql, cli/crates/cli/tests/graphql/owner/global/todo/todo-update.graphql, cli/crates/cli/tests/graphql/owner/global/twitter/twitter-schema.graphql, cli/crates/cli/tests/graphql/owner/global/twitter/user-create.graphql, cli/crates/cli/tests/graphql/owner/global/twitter/user-get-by-email.graphql, cli/crates/cli/tests/graphql/owner/global/twitter/user-get-by-id.graphql, cli/crates/cli/tests/openapi/petstore.json, cli/crates/cli/tests/owner.rs, cli/crates/cli/tests/snapshots/owner__global__todo__list-empty.snap, cli/crates/cli/tests/snapshots/owner__global__todo__user1-create.snap, cli/crates/cli/tests/snapshots/owner__global__todo__user1-delete.snap, cli/crates/cli/tests/snapshots/owner__global__todo__user1-get.snap, cli/crates/cli/tests/snapshots/owner__global__todo__user1-list-2.snap, cli/crates/cli/tests/snapshots/owner__global__todo__user1-list.snap, cli/crates/cli/tests/snapshots/owner__global__todo__user1-update.snap, cli/crates/cli/tests/snapshots/owner__global__todo__user2-get-fail.snap, cli/crates/cli/tests/snapshots/owner__global__twitter__user1-create.snap, cli/crates/cli/tests/snapshots/owner__global__twitter__user1-get.snap, cli/crates/cli/tests/snapshots/owner__global__twitter__user2-get-empty.snap, cli/crates/cli/tests/utils/client.rs, cli/crates/cli/tests/utils/consts.rs, cli/crates/server/src/servers.rs
Add tests covering working parts of owner-based auth.
=> GB-3413: Add cli tests for owner based auth

cli/crates/cli/tests/auth.rs, cli/crates/cli/tests/coercion.rs, cli/crates/cli/tests/concurrency_process.rs, cli/crates/cli/tests/concurrency_thread.rs, cli/crates/cli/tests/custom_resolvers.rs, cli/crates/cli/tests/default_directive.rs, cli/crates/cli/tests/dev.rs, cli/crates/cli/tests/dev_watch.rs, cli/crates/cli/tests/length.rs, cli/crates/cli/tests/openapi/main.rs, cli/crates/cli/tests/pagination.rs, cli/crates/cli/tests/relations.rs, cli/crates/cli/tests/reserved_dates.rs, cli/crates/cli/tests/scalars.rs, cli/crates/cli/tests/search.rs, cli/crates/cli/tests/unique.rs, cli/crates/cli/tests/utils/async_client.rs, cli/crates/cli/tests/utils/client.rs
=> GB-3383: Prepare for turning off auth bypass in CLI

.github/workflows/cli.yml, cli/Cargo.lock, cli/changelog/0.18.0-rc.5.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Add a change log for 0.18.0-rc.5.
=> Add a change log for 0.18.0-rc.5 and bump the versions

.github/workflows/cli.yml, cli/changelog/0.18.0-rc.6.md, cli/crates/cli/src/dev.rs, cli/crates/cli/src/output/report.rs, cli/crates/cli/tests/custom_resolvers.rs, cli/crates/server/src/custom_resolvers.rs, cli/crates/server/src/servers.rs
=> Update assets and tests in preparation for another RC

cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
=> Bump the versions.

cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
=> 0.18.0-rc.7

cli/changelog/0.18.0-rc.7.md
- Add changelog for 0.18.0-rc.7
=> add changelog

.github/workflows/cli.yml, cli/crates/cli/tests/auth.rs, cli/crates/cli/tests/graphql/owner/global/todo/todo-mixed-schema.graphql, cli/crates/cli/tests/graphql/owner/global/todo/todo-owner-create-schema.graphql, cli/crates/cli/tests/graphql/owner/global/twitter/tweet-create.graphql, cli/crates/cli/tests/graphql/owner/global/twitter/user-and-tweets-get-by-id.graphql, cli/crates/cli/tests/owner.rs, cli/crates/cli/tests/snapshots/auth__introspection.snap, cli/crates/cli/tests/snapshots/owner__global__todo__get-fail.snap, cli/crates/cli/tests/snapshots/owner__global__todo__get.snap, cli/crates/cli/tests/snapshots/owner__global__todo__list-fail.snap, cli/crates/cli/tests/snapshots/owner__global__todo__list.snap, cli/crates/cli/tests/snapshots/owner__global__twitter__user1-and-tweets-get.snap, cli/crates/cli/tests/snapshots/owner__global__twitter__user1-create-tweet.snap, cli/crates/cli/tests/snapshots/owner__global__twitter__user1-create.snap, cli/crates/cli/tests/snapshots/owner__global__twitter__user1-get.snap, cli/crates/cli/tests/snapshots/owner__global__twitter__user2-create-tweet-fail.snap, cli/crates/cli/tests/utils/consts.rs
=> GB-3483: Add owner-based tests

cli/rust-toolchain.toml
=> attempt to compile with 1.68.2 again

cli/crates/backend/assets/default.env, cli/crates/backend/src/api/client.rs, cli/crates/backend/src/api/errors.rs, cli/crates/backend/src/consts.rs, cli/crates/backend/src/errors.rs, cli/crates/backend/src/project.rs, cli/crates/cli/src/errors.rs, cli/crates/common/src/consts.rs, cli/rust-toolchain.toml
- Creates a default `.env` file when running `init`
- Adds additional API error hints
=> Add additional hints

.github/workflows/cli-partial-release.yml, .github/workflows/cli.yml, .github/workflows/packages.yml, .github/workflows/sanitize-alert-schedule.yml
=> upgrade to larger runners

cli/crates/backend/assets/default-schema.graphql
=> update default schema

cli/CHANGELOG.md, cli/Cargo.lock, cli/changelog/0.18.4.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/crates/server/src/types.rs, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- Fixes an issue with `rust-embed` on crates.io
=> use interpolated path

.github/workflows/cli.yml, cli/CHANGELOG.md, cli/changelog/0.18.4.md
Bump assets, update the changelog for 0.18.4
=> Prepare 0.18.4

.github/workflows/cli-partial-release.yml, .github/workflows/cli.yml, cli/Cargo.lock, cli/crates/server/Cargo.toml, cli/crates/server/src/types.rs
These changes seem to have broken the release process, so reverting for now.
Also made an attempt at fixing the assets in the cargo release.
=> Revert cargo assets changes from #310

.envrc.example, flake.lock, flake.nix
=> Nix flake update & add .envrc example

cli/CHANGELOG.md, cli/Cargo.lock, cli/changelog/0.18.10.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
=> Version bumps and changelog

examples/nextjs-server-actions/.eslintrc.json, examples/nextjs-server-actions/.gitignore, examples/nextjs-server-actions/README.md, examples/nextjs-server-actions/grafbase/schema.graphql, examples/nextjs-server-actions/next.config.js, examples/nextjs-server-actions/package-lock.json, examples/nextjs-server-actions/package.json, examples/nextjs-server-actions/postcss.config.js, examples/nextjs-server-actions/src/app/globals.css, examples/nextjs-server-actions/src/app/grafbase.ts, examples/nextjs-server-actions/src/app/layout.tsx, examples/nextjs-server-actions/src/app/page.tsx, examples/nextjs-server-actions/tailwind.config.js, examples/nextjs-server-actions/tsconfig.json, pnpm-lock.yaml
=> feat(examples): nextjs server actions

cli/Makefile.toml
- Adds a `release` cargo make command
=> Add release script

cli/Makefile.toml
- Adds more cargo make scripts and descriptions
=> More cargo make improvements

.github/workflows/cli.yml, .github/workflows/packages.yml
This aims to improve the reliability and consistency of change detection for the CLI and Packages
=> Update Path filter checks

cli/Makefile.toml
- Add additional semver validation for `cargo-make`
=> Add additional semver validation

cli/crates/cli/src/dev.rs
- Simplify the loop listening for server messages in the CLI
=> simplify message loop

cli/CHANGELOG.md, cli/Cargo.lock, cli/changelog/0.20.0-rc.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- Add `@graphql` directive to generate queries and mutations to an upstream GraphQL API.
- Add `JWKS` provider.
- Initial support for TypeScript configuration.
=> Release 0.20.0-rc.1

packages/grafbase-sdk/package.json
- OpenAPI connector definitions
- GraphQL connector definitions
- Flatten the query and mutation extends into one block
=> Bump SDK to 0.0.4

packages/grafbase-sdk/package.json, packages/grafbase-sdk/src/connector/openapi.ts, packages/grafbase-sdk/tests/unit/openapi.test.ts
=> Transforms needs queryNaming to work

.github/workflows/cli.yml, cli/Cargo.lock, cli/changelog/0.20.0-rc.4.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- use camelCase for `@graphql` directive field name
=> Release 0.20.0-rc.4

cli/Cargo.lock, cli/changelog/0.20.0-rc.5.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- fix GraphQL input type introspection stringification
=> Release 0.20.0-rc.5

packages/grafbase-sdk/package.json
Fixes: https://github.com/grafbase/grafbase/pull/382
=> Bump SDK to 0.0.7

.github/workflows/cli.yml, cli/Cargo.lock, cli/changelog/0.20.0-rc.6.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
re-release of #381, now with the actual assets embedded.
=> Release 0.20.0-rc.6

.github/workflows/cli.yml, cli/crates/cli/tests/auth.rs, cli/crates/cli/tests/graphql/auth/jwks-issuer-endpoint.graphql
=> GB-3681: Add test for oidc discovery URL containing path

cli/crates/common/src/environment.rs
If we have a project structure such as this one:
```
- grafbase
- schema.graphql
- other project
- grafbase
- grafbase.config.ts
```
And we run the CLI in the `other project` directory, we got a warning of having both config files even though they were in different projects. We should check that the parent directories are the same and only warn if needed.
=> GB-3811: Do not show a warning in the CLI when the TS config and schema aren't on the same level

cli/Cargo.lock, cli/changelog/0.21.0-rc.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Prepare next RC containing bugfix for Azure AD.
=> Release 0.21.0-rc.1

cli/crates/cli/src/cli_input.rs
- Fixes `login` and `logout` panicking
=> fix login and logout

packages/grafbase-sdk/package.json
=> chore(sdk): Bump to version 0.0.12

cli/.config/nextest.toml
=> chore(test): Add 2 retries to nextest configuration

cli/crates/cli/tests/README.md
=> chore(doc): Update dynamodb instructions

cli/Cargo.lock, cli/changelog/0.22.0-rc.4.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
=> 0.22.0-rc.4

.github/workflows/cli.yml, cli/Cargo.lock, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
=> 0.22.0-rc.5

cli/crates/cli/src/create.rs, cli/crates/common/src/consts.rs
- Default to `y` when confirming `create`
=> GB-3896 - Default to Y in create confirm

templates/openapi-mux/README.md, templates/openapi-mux/grafbase/.env, templates/openapi-mux/grafbase/schema.graphql
=> feat(templates): add openapi mux template

packages/grafbase-sdk/README.md
=> docs(sdk): update readme to properly reference groups rule definition

.github/workflows/cli.yml, cli/crates/cli/tests/relations.rs
A user found a bug with unlinking entities recently.  It's been fixed in the latest assets, but this is adding some tests to cover it from the CLI side.
=> Pull in relation unlinking fix and add tests

cli/crates/cli/tests/auth.rs
=> GB-3415: Make error message verification more generic

cli/Cargo.toml, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/Cargo.toml, cli/crates/server/Cargo.toml
Share common keys  across the workspace. [Docs](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table)
=> chore: Share package table across the workspace

cli/crates/backend/src/api/create.rs, cli/crates/backend/src/api/deploy.rs, cli/crates/backend/src/api/errors.rs, cli/crates/backend/src/api/graphql/api.graphql, cli/crates/backend/src/api/graphql/types.rs, cli/crates/backend/src/errors.rs, cli/crates/cli/src/errors.rs, cli/crates/common/src/errors.rs, cli/crates/server/src/errors.rs
- Adds new error variants to the `create` operation
- Outputs the name of unknown API errors
- Updates the internal API SDL
=> Update API SDL

packages/grafbase-sdk/src/auth.ts, packages/grafbase-sdk/tests/unit/auth.openid.test.ts, packages/grafbase-sdk/tests/unit/model.test.ts
Companion piece for https://github.com/grafbase/api/pull/2323
=> feat(sdk): Public auth rules

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.0.22.md, packages/grafbase-sdk/package.json
=> chore(sdk): Bump to 0.0.22

.github/workflows/cli.yml, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.23.0-rc.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
_waiting for CI to be fixed, before I fill in the actual Git ref for the assets_
=> release 0.23.0-rc.1

.github/workflows/cli.yml, cli/crates/server/src/servers.rs
This fixes a regression from https://github.com/grafbase/grafbase/pull/357.
=> fix(build): fix the build of grafbase-local-server with the 'dynamodb' feature enabled

.github/workflows/cli.yml, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.23.0-rc.2.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- Resolve issues with namespace-less GraphQL connector queries
=> release 0.23.0-rc.2

cli/crates/cli/src/output/report.rs
=> update deploy copy

cli/Cargo.lock, cli/crates/cli/src/dev.rs, cli/crates/cli/src/output/report.rs, cli/crates/common/Cargo.toml, cli/crates/common/src/types.rs, cli/crates/server/src/bridge.rs, cli/crates/server/src/bridge/errors.rs, cli/crates/server/src/bridge/server.rs, cli/crates/server/src/bridge/types.rs, cli/crates/server/src/bridge/udf.rs, cli/crates/server/src/errors.rs, cli/crates/server/src/lib.rs, cli/crates/server/src/servers.rs, cli/crates/server/src/types.rs, cli/crates/server/src/udf_builder.rs
Rename resolver occurrences to udf / user-defined function
=> GB-3975: Rename names from resolver to user defined functions

cli/crates/cli/tests/init.rs
Fix test after templates have been changed.
=> chore: Fix init test

cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.24.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/cli/tests/init.rs, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
A hotfix for typescript template handling.
=> chore(cli): Bump to 0.24.1

cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.25.0-rc.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
=> 0.25.0 rc.1

.github/workflows/cli.yml, cli/crates/cli/tests/snapshots/auth__introspection.snap
We added `__Schema::description` into the introspection, so a snapshot test needs updated in this repository.
=> Update snapshot after introspeciton changes

.github/workflows/cli.yml, cli/Cargo.lock, cli/crates/cli/Cargo.toml, cli/crates/cli/tests/graphql-directive/main.rs, cli/crates/cli/tests/graphql-directive/server.rs, cli/crates/cli/tests/graphql-directive/snapshots/graphql_directive__namespaced-issue.snap, cli/crates/cli/tests/graphql-directive/snapshots/graphql_directive__namespaced-null.snap, cli/crates/cli/tests/graphql-directive/snapshots/graphql_directive__namespaced-pull-request-with-bot.snap, cli/crates/cli/tests/graphql-directive/snapshots/graphql_directive__namespaced-pull-request-with-user.snap, cli/crates/cli/tests/graphql-directive/snapshots/graphql_directive__unnamespaced-issue.snap, cli/crates/cli/tests/graphql-directive/snapshots/graphql_directive__unnamespaced-null.snap, cli/crates/cli/tests/graphql-directive/snapshots/graphql_directive__unnamespaced-pull-request-with-bot.snap, cli/crates/cli/tests/graphql-directive/snapshots/graphql_directive__unnamespaced-pull-request-with-user.snap
Particularly it's behaviour around interfaces, unions, fragments and namespacing.
Note that this will require some assets form the api repo to pass.
=> Add some tests of `@graphql`

cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.25.2.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
As the title says - releases 0.25.2.
This requires #503 to be merged first (which pulls in the assets)
=> Release 0.25.2

.github/workflows/cli.yml
This will allow us to test PRs much faster.
=> chore(ci): Upload final binaries for various architectures as workflow artifacts

cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.26.0.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- Change the working directory in which resolver builds take place allowing them to import files relative to the project directory
=> Release 0.26.0.

.github/workflows/cli.yml, cli/changelog/0.27.0.md, cli/crates/cli/tests/batch.rs, cli/crates/cli/tests/dev.rs, cli/crates/cli/tests/graphql/batch/collect.graphql, cli/crates/cli/tests/graphql/batch/create.graphql, cli/crates/cli/tests/graphql/batch/schema.graphql, cli/crates/cli/tests/graphql/batch/update.graphql, cli/crates/cli/tests/graphql/default/create.graphql, cli/crates/cli/tests/graphql/default/schema.graphql, cli/crates/cli/tests/graphql/default/update.graphql, cli/crates/cli/tests/graphql/owner/global/todo/todo-update.graphql, cli/crates/cli/tests/owner.rs, cli/crates/cli/tests/snapshots/auth__introspection.snap, cli/crates/cli/tests/utils/consts.rs, cli/crates/server/src/bridge/search.rs, flake.nix
fix: add tests for batch ops & specifying null removes field in the update
=> fix: add tests for batch ops & specifying null removes field in the update

.github/workflows/cli.yml, cli/crates/cli/tests/graphql-directive/headers.rs, cli/crates/cli/tests/openapi/headers.rs
A test for a fix in the `api` repo.
Needs a bump of assets after a PR is merged, but should be reviewable.
=> chore: test that header forwarding is case insensitive

.github/workflows/cli.yml, cli/changelog/0.27.0.md, cli/crates/cli/tests/batch.rs, cli/crates/cli/tests/graphql/batch/delete.graphql, cli/crates/cli/tests/snapshots/auth__introspection.snap, cli/crates/cli/tests/utils/consts.rs
=> feat: Add batch delete mutation

.github/workflows/cli.yml, cli/crates/server/src/bridge/udf.rs
This updates the invocation protocol that we changed in the gateway.
=> Update the assets after UDF changes

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.2.1.md, packages/grafbase-sdk/package.json, packages/grafbase-sdk/src/connector/dynamodb/model.ts, packages/grafbase-sdk/src/connector/mongodb.ts, packages/grafbase-sdk/src/connector/mongodb/model.ts, packages/grafbase-sdk/src/field.ts, packages/grafbase-sdk/src/grafbase-schema.ts, packages/grafbase-sdk/src/index.ts, packages/grafbase-sdk/src/model.ts, packages/grafbase-sdk/src/type.ts, packages/grafbase-sdk/src/typedefs.ts, packages/grafbase-sdk/src/typedefs/auth.ts, packages/grafbase-sdk/src/typedefs/cache.ts, packages/grafbase-sdk/src/typedefs/default.ts, packages/grafbase-sdk/src/typedefs/enum.ts, packages/grafbase-sdk/src/typedefs/length-limited-string.ts, packages/grafbase-sdk/src/typedefs/list.ts, packages/grafbase-sdk/src/typedefs/map.ts, packages/grafbase-sdk/src/typedefs/reference.ts, packages/grafbase-sdk/src/typedefs/resolver.ts, packages/grafbase-sdk/src/typedefs/scalar.ts, packages/grafbase-sdk/src/typedefs/unique.ts, packages/grafbase-sdk/tests/unit/model.test.ts, packages/grafbase-sdk/tests/unit/mongodb.test.ts
The SDK part of a MongoDB connector definition. Let's merge it quietly now, and add it to the docs and all that when the connector is closer to done.
=> feat(sdk): MongoDB connector

cli/rust-toolchain.toml
=> Update the CLI to rust 1.71.0

.github/workflows/cli.yml, cli/crates/cli/tests/mongodb/create_one.rs, cli/crates/cli/tests/mongodb/delete_one.rs, cli/crates/cli/tests/mongodb/find_one.rs, cli/crates/cli/tests/mongodb/main.rs
Mock tests to see that the whole house of cards is what it says it is.
=> test: MongoDB findOne, createOne and deleteOne

.gitignore, flake.lock, flake.nix
=> chore: Nix flake update

.github/workflows/cli.yml, cli/crates/cli/tests/graphql/pagination/paginate-todos.graphql, cli/crates/cli/tests/pagination.rs, cli/crates/cli/tests/snapshots/auth__introspection.snap
=> feat: Add id filter to collection query

.github/actions/cdn_assets/action.yml, .github/workflows/cli.yml
- Embeds Pathfinder in the CLI
=> Add pathfinder to tar in CI

.github/workflows/cli.yml, cli/crates/cli/tests/mongodb/create_one.rs, cli/crates/cli/tests/mongodb/delete_one.rs, cli/crates/cli/tests/mongodb/find_many.rs, cli/crates/cli/tests/mongodb/find_one.rs, cli/crates/cli/tests/mongodb/main.rs
Tests the findMany calls, missing the page info tests due to them not working yet.
=> test: MongoDB findMany, round 1

cli/Cargo.lock, cli/crates/cli/Cargo.toml, cli/crates/cli/src/dev.rs, cli/crates/cli/src/output/report.rs, cli/crates/cli/tests/compilation_error.rs, cli/crates/cli/tests/custom_resolvers.rs, cli/crates/server/src/servers.rs, cli/crates/server/src/types.rs, cli/crates/server/src/udf_builder.rs
We've decided not to have an automated 'npm install'/'yarn install'/'pnpm install' step run by the CLI in dev mode.
=> breaking(udf): Stop running the installation step for user-defined functions with npm/pnpm/yarn in the dev mode

templates/graphql-dgraph/README.md, templates/graphql-dgraph/grafbase/.env, templates/graphql-dgraph/grafbase/grafbase.config.ts, templates/graphql-dgraph/package-lock.json, templates/graphql-dgraph/package.json
New template for Dgraph Cloud article.
=> feat(templates): dgraph cloud

.github/workflows/cli.yml, cli/Cargo.lock, cli/crates/server/Cargo.toml, cli/crates/server/src/bridge/api_counterfeit/search/mod.rs, cli/crates/server/src/bridge/api_counterfeit/search/paginated_searcher.rs, cli/crates/server/src/bridge/api_counterfeit/search/protocol.rs, cli/crates/server/src/bridge/errors.rs, cli/crates/server/src/bridge/search.rs
=> fix: update search protocol

cli/rust-toolchain.toml, flake.lock
- Updates Rust to 1.71.1
- Updates the Nix flake lockfile
=> Update rust and flake

packages/grafbase-sdk/README.md
* Add header forwarding
* Update README format to match CLI/Examples/Templates
* Add note about `grafbase/.env`
Requires #577
=> docs(sdk): update readme

examples/README.md, examples/resolvers-fauna/README.md, examples/resolvers-fauna/grafbase/.env.example, examples/resolvers-fauna/grafbase/grafbase.config.ts, examples/resolvers-fauna/grafbase/resolvers/products/all.ts, examples/resolvers-fauna/grafbase/resolvers/products/create.ts, examples/resolvers-fauna/grafbase/resolvers/products/delete.ts, examples/resolvers-fauna/grafbase/resolvers/products/single.ts, examples/resolvers-fauna/grafbase/resolvers/products/update.ts, examples/resolvers-fauna/package-lock.json, examples/resolvers-fauna/package.json, examples/resolvers-planetscale/readme.md
=> feat(examples): resolvers + fauna

.github/workflows/cli.yml, cli/crates/cli/tests/mongodb/find_many.rs, cli/crates/cli/tests/mongodb/main.rs
Tests reflecting the changes to pagination and cursors.
API PR: https://github.com/grafbase/api/pull/2560
=> test: MongoDB pagination

packages/grafbase-sdk/src/cache.ts, packages/grafbase-sdk/src/typedefs/cache.ts, packages/grafbase-sdk/tests/unit/cache.test.ts, packages/grafbase-sdk/tests/unit/types.test.ts
Adds cache access scopes support in the sdk.
=> feat(cache): add cache access scopes to the sdk

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.5.0.md, packages/grafbase-sdk/package.json
=> SDK - 0.5.0

cli/crates/cli/tests/init_ts.rs, cli/crates/common/src/consts.rs, examples/resolvers-planetscale/package.json, templates/blog/package.json, templates/chatroom/package.json, templates/commerce/package.json, templates/graphql-cloudflare-analytics/package.json, templates/graphql-contentful/package.json, templates/graphql-dgraph/package.json, templates/graphql-fauna/package.json, templates/graphql-github/package.json, templates/graphql-saleor/package.json, templates/graphql-shopify-storefront/package.json, templates/graphql-strapi/package.json, templates/hackernews/package.json, templates/openapi-github/package.json, templates/openapi-mux/package.json, templates/openapi-neon/package.json, templates/openapi-openai/package.json, templates/openapi-stripe/package.json, templates/openapi-tinybird/package.json, templates/todo/package.json, templates/twitter/package.json
We need to find a way to make this easier...
=> chore: Bump SDK to 0.5.0 in consts and in all examples

.github/workflows/cli.yml, cli/crates/cli/tests/mongodb/create_many.rs, cli/crates/cli/tests/mongodb/create_one.rs, cli/crates/cli/tests/mongodb/delete_many.rs, cli/crates/cli/tests/mongodb/find_many.rs, cli/crates/cli/tests/mongodb/main.rs, cli/crates/cli/tests/mongodb/update_many.rs, cli/crates/cli/tests/mongodb/update_one.rs
Some of the last mock tests. Soon to follow real database tests.
=> test: MongoDB UpdateOne, DeleteMany, CreateMany

.github/workflows/cli.yml, cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.32.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/cli/tests/graphql-directive/main.rs, cli/crates/cli/tests/graphql-directive/server.rs, cli/crates/cli/tests/graphql-directive/snapshots/graphql_directive__namespaced-issue.snap, cli/crates/cli/tests/graphql-directive/snapshots/graphql_directive__namespaced-null.snap, cli/crates/cli/tests/graphql-directive/snapshots/graphql_directive__namespaced-pull-request-with-bot.snap, cli/crates/cli/tests/graphql-directive/snapshots/graphql_directive__namespaced-pull-request-with-user.snap, cli/crates/cli/tests/graphql-directive/snapshots/graphql_directive__unnamespaced-issue.snap, cli/crates/cli/tests/graphql-directive/snapshots/graphql_directive__unnamespaced-null.snap, cli/crates/cli/tests/graphql-directive/snapshots/graphql_directive__unnamespaced-pull-request-with-bot.snap, cli/crates/cli/tests/graphql-directive/snapshots/graphql_directive__unnamespaced-pull-request-with-user.snap, cli/crates/cli/tests/graphql-directive/transforms.rs, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Also includes some tests of top level scalars in `@graphql`
=> Release v0.32.1

flake.nix
- Allow `jj` users to use the nix flake
=> GB-4583 - Allow jj users to use flake

cli/crates/cli/Cargo.toml, cli/crates/cli/src/output/report.rs
A small tweak to how we print URLs.
=> fix(logging): Tweak how we print URLs

.github/workflows/cli.yml, cli/crates/cli/tests/mongodb/create_many.rs, cli/crates/cli/tests/mongodb/create_one.rs, cli/crates/cli/tests/mongodb/delete_many.rs, cli/crates/cli/tests/mongodb/delete_one.rs, cli/crates/cli/tests/mongodb/find_many.rs, cli/crates/cli/tests/mongodb/find_one.rs, cli/crates/cli/tests/mongodb/main.rs, cli/crates/cli/tests/mongodb/update_many.rs, cli/crates/cli/tests/mongodb/update_one.rs
Tests for PR https://github.com/grafbase/api/pull/2627
=> test: MongoDB namespacing

examples/README.md, examples/resolvers-ts-codegen/README.md, examples/resolvers-ts-codegen/codegen.ts, examples/resolvers-ts-codegen/grafbase/__generated/resolvers.ts, examples/resolvers-ts-codegen/grafbase/context.ts, examples/resolvers-ts-codegen/grafbase/grafbase.config.ts, examples/resolvers-ts-codegen/grafbase/resolvers/sum.ts, examples/resolvers-ts-codegen/grafbase/types.ts, examples/resolvers-ts-codegen/package-lock.json, examples/resolvers-ts-codegen/package.json, examples/resolvers-ts-codegen/tsconfig.json
Basic example showing how to use graphql-codegen and Grafbase resolvers for typed args/response.
=> feat(examples): resolvers + codegen

examples/README.md, examples/resolvers-couchbase/README.md, examples/resolvers-couchbase/grafbase/.env.example, examples/resolvers-couchbase/grafbase/grafbase.config.ts, examples/resolvers-couchbase/grafbase/resolvers/products/all.ts, examples/resolvers-couchbase/grafbase/resolvers/products/create.ts, examples/resolvers-couchbase/package-lock.json, examples/resolvers-couchbase/package.json
=> feat(examples): couchbase + resolver example

examples/resolvers-couchbase/README.md
=> docs(readme): update couchbase example readme to include guide link

.github/workflows/cli.yml, cli/changelog/0.32.4.md, cli/crates/cli/tests/relations.rs
Fix bug with relations not being updated correctly
=> fix: Update bug in the @model

cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.32.4.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
=> Release 0.32.4

.github/workflows/cli.yml, cli/crates/cli/tests/graphql-directive/headers.rs, cli/crates/cli/tests/graphql-directive/main.rs, cli/crates/cli/tests/graphql-directive/transforms.rs, cli/crates/cli/tests/mongodb/main.rs, cli/crates/cli/tests/openapi/headers.rs, cli/crates/cli/tests/openapi/main.rs, cli/crates/cli/tests/openapi/remote_unions.rs, cli/crates/cli/tests/openapi/transforms.rs, packages/grafbase-sdk/README.md, packages/grafbase-sdk/src/connector/graphql.ts, packages/grafbase-sdk/src/connector/mongodb.ts, packages/grafbase-sdk/src/connector/openapi.ts, packages/grafbase-sdk/src/grafbase-schema.ts, packages/grafbase-sdk/src/index.ts, packages/grafbase-sdk/tests/unit/env.test.ts, packages/grafbase-sdk/tests/unit/graphql.test.ts, packages/grafbase-sdk/tests/unit/mongodb.test.ts, packages/grafbase-sdk/tests/unit/openapi.test.ts
The SDK side of https://github.com/grafbase/api/pull/2678
=> fix(sdk): Name is now a mandatory param to all connectors

cli/.cargo/config.toml, cli/crates/cli/tests/custom_resolvers.rs, cli/crates/cli/tests/pagination.rs, cli/crates/cli/tests/search.rs, cli/crates/cli/tests/utils/kill_with_children.rs, cli/crates/common/src/environment.rs, cli/rust-toolchain.toml, flake.lock
- Updates Rust to `1.72.0`
- Updates the Nix flake
=> GB-4738 - Rust 1.72.0

templates/graphql-storyblok/README.md, templates/graphql-storyblok/grafbase/grafbase.config.ts, templates/graphql-storyblok/package-lock.json, templates/graphql-storyblok/package.json
=> feat(templates): storyblok

templates/graphql-datocms/README.md, templates/graphql-datocms/grafbase/grafbase.config.ts, templates/graphql-datocms/package-lock.json, templates/graphql-datocms/package.json
=> feat(templates): add DatoCMS template

engine/.config/nextest.toml
=> Remove e2e related profiles

engine/.prettierignore, engine/.prettierrc.json, engine/config.toml
- Adds `engine/.cargo/config.toml`
- Adds a specific prettier config
=> Add `.cargo/config.toml`

engine/crates/sdl-parser/src/lib.rs, engine/crates/sdl-parser/src/snapshots/sdl_parser__tests__schema.snap, engine/crates/sdl-parser/src/snapshots/sdl_parser__tests__test_model_reserved_fields-req-a.snap, engine/crates/sdl-parser/src/snapshots/sdl_parser__tests__test_model_reserved_fields-req-b.snap, engine/crates/sdl-parser/src/tests.rs, engine/crates/sdl-parser/src/usage.rs
=> chore(parser): Parse used directives in a schema

.github/actions/cdn_assets/action.yml, cli/crates/server/src/consts.rs, cli/crates/server/src/errors.rs, cli/crates/server/src/udf_builder.rs
This PR configures KV for local usage
=> feat(resolvers): add local kv

engine/crates/runtime-protocol/src/lib.rs
Makes `runtime_protocol::GatewayRequest` a bit more flexible.
=> chore(runtime-protocol): adjust GatewayRequest

.github/workflows/cli.yml, cli/Cargo.lock, cli/crates/cli/Cargo.toml, cli/crates/cli/tests/defer/main.rs, cli/crates/cli/tests/snapshots/auth__introspection.snap, cli/crates/cli/tests/utils/async_client.rs
This adds some basic tests of the changes in #689 & https://github.com/grafbase/api/pull/2769.  
Requires https://github.com/grafbase/api/pull/2769 to be merged & some assets updated first.
=> test: add tests of SSE & incremental delivery in CLI

.github/curl_options, .github/workflows/cli.yml, .github/workflows/engine.yml
These are not run anywhere right now.
=> chore(ci): Run the engine integration tests

engine/README.md, engine/crates/engine/src/http/pathfinder.html, engine/crates/gateway-adapter/Cargo.toml
-  Add a README.md for `engine`
=> Engine README.md

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.6.2.md, packages/grafbase-sdk/package.json, packages/grafbase-sdk/src/connector/neon.ts, packages/grafbase-sdk/src/grafbase-schema.ts, packages/grafbase-sdk/src/index.ts, packages/grafbase-sdk/tests/unit/neon.test.ts
Adds a new connector: Neon. Bumps SDK to 0.6.2.
=> feat(sdk): Neon connector init

.github/workflows/cli.yml, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.35.0-rc.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Has the bare minimum to run PostgreSQL queries on Neon.
=> chore(cli): Bump to version 0.35.0-rc.1

engine/README.md, engine/crates/gateway-adapter-local/Cargo.toml, engine/crates/runtime-local/Cargo.toml
=> chore: reformulate some crate descriptions

engine/crates/dynamodb/Cargo.toml, engine/crates/dynamodb/src/batch_getitem.rs, engine/crates/dynamodb/src/graph_transaction/dynamodb.rs, engine/crates/dynamodb/src/paginated.rs, engine/crates/dynamodb/src/query.rs, engine/crates/dynamodb/src/query_by_type.rs, engine/crates/dynamodb/src/query_by_type_paginated.rs, engine/crates/dynamodb/src/query_single_by_relation.rs, engine/crates/dynamodb/src/transaction.rs, engine/crates/engine/Cargo.toml, engine/crates/engine/src/registry/mod.rs, engine/crates/engine/src/registry/resolvers/custom.rs, engine/crates/engine/src/registry/resolvers/dynamo_mutation/delete.rs, engine/crates/engine/src/registry/resolvers/graphql/response.rs, engine/crates/engine/src/registry/resolvers/mod.rs, engine/crates/engine/src/resolver_utils/container.rs, engine/crates/engine/src/resolver_utils/field.rs, engine/crates/gateway-adapter-local/Cargo.toml, engine/crates/integration-tests/Cargo.toml, engine/crates/parser-openapi/Cargo.toml, engine/crates/parser-sdl/Cargo.toml
=> chore: remove useless tracing feature flags

.github/workflows/cli.yml, cli/crates/cli/tests/kv.rs, cli/crates/common/src/environment.rs, cli/crates/common/src/errors.rs, cli/crates/server/src/bridge/api_counterfeit/registry.rs, cli/crates/server/src/bridge/search.rs, cli/crates/server/src/bridge/udf.rs, cli/crates/server/src/udf_builder.rs
Enable KV only if `@experimental` is properly configured.
=> feat(kv): optional kv

packages/grafbase-sdk/src/config.ts, packages/grafbase-sdk/src/experimental.ts, packages/grafbase-sdk/tests/unit/experimental.test.ts
Adds `@experimental` support to the typescript sdk.
=> feat(kv): sdk @experimental support

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.6.3.md, packages/grafbase-sdk/package.json
=> chore(sdk): Bump to version 0.6.3

.github/workflows/cli.yml, cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.36.0-rc.2.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
=> chore(cli): Bump to version 0.36.0-rc.2

engine/crates/common-types/src/lib.rs, engine/crates/gateway-core/src/lib.rs
This is mostly an internal change that adds another variant to the log event type required for some changes upstream in the platform.
=> feat(logs): Changes in the engine to enable log events for the outer HTTP requests

engine/Cargo.lock, engine/crates/gateway-adapter-local/src/execution.rs, engine/crates/graphql-extensions/src/runtime_log.rs, engine/crates/integration-tests/src/engine/builder.rs, engine/crates/runtime-local/Cargo.toml, engine/crates/runtime-local/src/log.rs, engine/crates/runtime/Cargo.toml, engine/crates/runtime/src/lib.rs, engine/crates/runtime/src/log.rs
An internal change needed for the platform.
=> Propagate `x-grafbase-request-log-event-id` properly for parent<->child relationship

engine/crates/common-types/src/lib.rs
Derive `Clone` and `Copy` to `OperationType`
=> chore(types): Derive `Clone` and `Copy` on `OperationType`

.github/workflows/cli.yml, cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.36.0-rc.3.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/cli/tests/kv.rs, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
=> chore: Bump to version 0.36.0-rc.3

examples/react-apollo/README.md
Started using this example to test `@defer` with apollo client and the README seemed to be wrong.
=> Fix instructions in react-apollo example

cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.36.0.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
=> chore(cli): Bump to version 0.36.0

cli/Cargo.lock, cli/crates/cli/Cargo.toml, cli/crates/cli/tests/caching.rs, cli/crates/gateway/src/lib.rs, engine/Cargo.lock, engine/crates/engine/src/response/mod.rs, engine/crates/gateway-core/src/cache/mod.rs, engine/crates/runtime-local/Cargo.toml, engine/crates/runtime-local/src/cache.rs, engine/crates/runtime-local/src/lib.rs, engine/crates/runtime-noop/src/cache.rs, engine/crates/runtime/src/cache.rs
=> fix: Add cache back to CLI

.github/workflows/cli.yml, cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.37.0.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/crates/server/src/servers.rs, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
=> release 0.37.0

engine/crates/common-types/src/lib.rs
A small change needed for a platform feature.
=> Add `url` to `LogEventType::UdfMessage`

.github/workflows/cli.yml, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.38.0.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
=> chore(cli): Bump to 0.38.0

cli/crates/server/src/proxy.rs
- Holds the connection to the CLI proxy if the gateway is not ready
=> GB-4669 - Hold the connection on proxy connect errors

engine/crates/common-types/src/lib.rs, engine/crates/engine/parser/src/types/mod.rs, engine/crates/engine/src/response/mod.rs, engine/crates/engine/src/schema.rs, engine/crates/engine/src/subscription.rs, engine/crates/engine/src/types/empty_subscription.rs, engine/crates/gateway-core/src/lib.rs, engine/crates/graphql-extensions/src/lib.rs, engine/crates/graphql-extensions/src/runtime_log.rs
Necessary for some of the changes on the platform.
=> Refactor a little bit how the operation type gets propagated from the executor to the gateway

engine/crates/engine/src/registry/cache_control.rs
=> chore: Add PartialEq, Eq to CachePartialRegistry for testing purposes in api

engine/crates/engine/src/registry/mod.rs, engine/crates/engine/src/registry/tests.rs, engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__array_input_value.snap, engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__conversion.snap, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__flat_output-2.snap, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__petstore_output-2.snap, engine/crates/parser-sdl/src/rules/experimental.rs, engine/crates/parser-sdl/src/snapshots/parser_sdl__tests__schema.snap, engine/crates/parser-sdl/src/snapshots/parser_sdl__tests__test_experimental-sdl.snap, engine/crates/parser-sdl/src/snapshots/parser_sdl__tests__test_model_reserved_fields-req-a.snap, engine/crates/parser-sdl/src/snapshots/parser_sdl__tests__test_model_reserved_fields-req-b.snap, packages/grafbase-sdk/src/experimental.ts, packages/grafbase-sdk/tests/unit/experimental.test.ts
Adds support for AI in @experimental
=> feat(ai): add experimental ai support

packages/grafbase-sdk/src/config.ts, packages/grafbase-sdk/src/federation.ts, packages/grafbase-sdk/tests/unit/federation.test.ts
- Allows setting the federation version in the SDK
=> GB-5006 - Add federation to SDK

.github/workflows/cli.yml
=> chore: bump assets

cli/crates/cli/tests/home.rs, cli/crates/cli/tests/start.rs, cli/crates/server/src/servers.rs
Somehow a change wasn't added to the last PR and the test for the TS config wasn't really testing that it worked.
=> fix: Fix grafbase dev with TS config

cli/Cargo.lock, cli/crates/cli/tests/init.rs
Update the CLI tests after some database-based templates have been deleted in #821
=> Update the CLI tests after some database-based templates have been deleted in #821

engine/crates/integration-tests/docker-compose.yml
Let's upgrade our tests to the latest stable Postgres.
=> chore(ci): Upgrade Postgres to version 16

cli/Makefile.toml, cli/crates/server/README.md
And document it as the preferred way in cli/crates/server/README.md.
=> feat(cli): add a cargo-make target to build packages/cli-app

packages/grafbase-sdk/src/typedefs/resolver.ts, packages/grafbase-sdk/tests/unit/types.test.ts
=> feat: add `@requires` support to SDK

cli/crates/typed-resolvers/src/codegen.rs, cli/crates/typed-resolvers/tests/schema_types/with_resolvers.expected.ts
It's a bit less generated code, so it's a win. SDK part of this implemented in https://github.com/grafbase/grafbase/pull/848
closes GB-5163
=> cli: import ResolverFn from @grafbase/sdk in generated TS code

cli/changelog/0.41.0.md
- Implements subgraph introspection support (#842)
=> chore(cli): add forgotten changelog entry

crates/composition/src/compose_supergraph.rs, crates/composition/src/ingest_subgraph.rs, crates/composition/src/subgraphs.rs, crates/composition/src/subgraphs/definitions.rs, crates/composition/src/subgraphs/unions.rs, crates/composition/src/supergraph.rs, crates/composition/src/supergraph/render.rs, crates/composition/tests/composition/unions_basic/subgraphs/pizza.graphql, crates/composition/tests/composition/unions_basic/subgraphs/sushi.graphql, crates/composition/tests/composition/unions_basic/supergraph.graphql
The rule is to just merge them.
Part of GB-5176
=> composition: implement union composition

cli/crates/gateway/src/executor.rs
=> feat(cli): add missing postgres transport factory

cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.41.3.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Patch to enable Postgres queries in CLI.
=> chore(cli): Bump to 0.41.3

crates/composition/Cargo.toml, crates/composition/src/compose_supergraph.rs, crates/composition/src/compose_supergraph/input_object.rs, crates/composition/src/compose_supergraph/object.rs, crates/composition/src/ingest_subgraph.rs, crates/composition/src/ingest_subgraph/field.rs, crates/composition/src/strings.rs, crates/composition/src/subgraphs.rs, crates/composition/src/subgraphs/definitions.rs, crates/composition/src/subgraphs/field_types.rs, crates/composition/src/subgraphs/fields.rs, crates/composition/src/subgraphs/walkers.rs, crates/composition/src/supergraph.rs, crates/composition/src/supergraph/render.rs, crates/composition/tests/composition/input_object_basic/subgraphs/emailbook.graphql, crates/composition/tests/composition/input_object_basic/subgraphs/phonebook.graphql, crates/composition/tests/composition/input_object_basic/supergraph.graphql, crates/composition/tests/composition/input_objects_nonshared_required_field/subgraphs/cyclist.graphql, crates/composition/tests/composition/input_objects_nonshared_required_field/subgraphs/event.graphql, crates/composition/tests/composition/input_objects_nonshared_required_field/subgraphs/withCoach.graphql, crates/composition/tests/composition/input_objects_nonshared_required_field/supergraph.graphql, crates/composition/tests/composition/object_field_arguments_basic/subgraphs/history.graphql, crates/composition/tests/composition/object_field_arguments_basic/subgraphs/inventory.graphql, crates/composition/tests/composition/object_field_arguments_basic/subgraphs/performance.graphql, crates/composition/tests/composition/object_field_arguments_basic/supergraph.graphql
=> composition: implement input type and object field arguments

cli/Cargo.lock, engine/Cargo.lock, engine/crates/postgres-types/Cargo.toml, engine/crates/postgres-types/src/transport/tcp.rs
We'll be using this in the schema registry.
=> feat(connector): Add cloudflare support back to pg tcp transport

engine/crates/postgres-types/src/transport.rs
=> chore: Use the transaction from transport

README.md
The current one leads to a page that doesn't exist. It's been added to redirects now, but better to link directly to the correct page.
=> Update quickstart URL

engine/Cargo.lock
Explanation in here: https://github.com/grafbase/rust-postgres/pull/6
=> fix(postgres): prepare and execute unnamed statements in one roundtrip

crates/composition/src/emit_federated_graph.rs, crates/composition/src/lib.rs, crates/composition/src/result.rs, crates/composition/tests/composition/custom_scalars_basic/federated.graphql, crates/composition/tests/composition/custom_scalars_basic/subgraphs/foo.graphql, crates/composition/tests/composition/enum_unused/federated.graphql, crates/composition/tests/composition/enum_unused/subgraphs/theschema.graphql, crates/composition/tests/composition/interfaces_basic/federated.graphql, crates/composition/tests/composition/interfaces_basic/subgraphs/social.graphql, crates/composition/tests/composition/objects_basic/federated.graphql, crates/composition/tests/composition/objects_basic/subgraphs/a.graphql, crates/composition/tests/composition/shareable_basic/federated.graphql, crates/composition/tests/composition/shareable_basic/subgraphs/accounts.graphql, crates/composition/tests/composition/unions_basic/federated.graphql, crates/composition/tests/composition/unions_basic/subgraphs/pizza.graphql, engine/Cargo.lock, engine/Cargo.toml, engine/crates/engine-v2/Cargo.toml, engine/crates/engine-v2/graph/Cargo.toml, engine/crates/engine-v2/graph/src/conversion.rs, engine/crates/engine-v2/graph/src/lib.rs, engine/crates/engine-v2/src/lib.rs, engine/crates/engine-v2/src/parser.rs
Adding a base structure to work on, will definitely iterate a lot on it.
It's almost a copy paste from the federated-graph for now.
I don't think unit tests for the conversion itself are meaningful. This should
be tested through integration tests like composition. But instead of
checking a SDL output we would check introspection and that the engine
behaves as expected.
=> Add engine-v2 graph

packages/grafbase-sdk/src/field.ts, packages/grafbase-sdk/src/type.ts, packages/grafbase-sdk/src/typedefs/auth.ts, packages/grafbase-sdk/src/typedefs/cache.ts, packages/grafbase-sdk/src/typedefs/default.ts, packages/grafbase-sdk/src/typedefs/deprecated.ts, packages/grafbase-sdk/src/typedefs/enum.ts, packages/grafbase-sdk/src/typedefs/inaccessible.ts, packages/grafbase-sdk/src/typedefs/list.ts, packages/grafbase-sdk/src/typedefs/override.ts, packages/grafbase-sdk/src/typedefs/provides.ts, packages/grafbase-sdk/src/typedefs/resolver.ts, packages/grafbase-sdk/src/typedefs/scalar.ts, packages/grafbase-sdk/src/typedefs/shareable.ts, packages/grafbase-sdk/src/typedefs/tag.ts, packages/grafbase-sdk/src/utils.ts, packages/grafbase-sdk/tests/unit/types.test.ts
I've added a lot of federation (and other) directives to the engine recently.  This adds them all in to the SDK.
=> feat: add federation directives & `@deprecated` to sdk

engine/crates/engine/src/registry/resolvers/graphql/serializer.rs, engine/crates/engine/src/registry/type_names.rs, engine/crates/integration-tests/src/mocks/graphql.rs, engine/crates/integration-tests/tests/graphql_connector/basic.rs, engine/crates/integration-tests/tests/graphql_connector/snapshots/integration_tests__graphql_connector__basic__namespaced-input-list.snap, engine/crates/integration-tests/tests/graphql_connector/transforms.rs
=> fix: Correctly rename input variables for GraphQL connector

cli/crates/server/src/bridge/udf.rs
=> Remove a print statement

cli/.prettierrc.json, cli/crates/backend/assets/default-schema.graphql, cli/crates/backend/assets/grafbase.default.config.ts, cli/crates/cli/src/output/report.rs, cli/crates/cli/tests/config/default.ts, cli/npm/cli/get-environment-data.js, cli/npm/cli/get-environment-data.test.js, cli/npm/cli/postinstall.js
* Updates the default SDL/TS config to use connectors instead of database models
* Updates the copy for newly initialized projects
=> updated default configuration files GB-4618

.github/workflows/cli.yml
=> chore(ci): report CLI release failures on slack

cli/rustfmt.toml, engine/rustfmt.toml
=> remove unstable features from rustfmt

engine/crates/composition/tests/composition/enum_only_outputs/federated.graphql, engine/crates/federated-graph/src/render_sdl.rs
=> fix(federated-graph): improve ugly formatting in @join__type rendering

engine/Cargo.lock, engine/crates/validation/Cargo.toml, engine/crates/validation/README.md, engine/crates/validation/tests/validation_errors.rs
This is the bare minimum we can do to get the crate published.
=> validation: release to crates.io

cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.44.4.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json, engine/Cargo.lock
=> Release 0.44.4

engine/crates/composition/src/compose.rs, engine/crates/composition/src/compose/context.rs, engine/crates/composition/src/compose/input_object.rs, engine/crates/composition/src/compose/interface.rs, engine/crates/composition/src/compose/object.rs, engine/crates/composition/src/composition_ir.rs, engine/crates/composition/src/emit_federated_graph.rs, engine/crates/composition/src/ingest_subgraph.rs, engine/crates/composition/src/ingest_subgraph/object.rs, engine/crates/composition/src/ingest_subgraph/schema_definitions.rs, engine/crates/composition/src/subgraphs/definitions.rs, engine/crates/composition/src/subgraphs/fields.rs, engine/crates/composition/src/subgraphs/keys.rs, engine/crates/composition/tests/composition/provides_basic/federated.graphql, engine/crates/composition/tests/composition/provides_basic/subgraphs/products.graphql, engine/crates/composition/tests/composition/provides_basic/subgraphs/users.graphql, engine/crates/composition/tests/composition/requires_basic/federated.graphql, engine/crates/composition/tests/composition/requires_basic/subgraphs/chilies.graphql, engine/crates/composition/tests/composition/requires_basic/subgraphs/farms.graphql, engine/crates/federated-graph/src/federated_graph.rs, engine/crates/federated-graph/src/render_sdl.rs
=> composition: implement @provides, @requires, @external

cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.44.5.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json, engine/Cargo.lock
Release 0.44.5 with the removal of a `println!()`.
=> Release 0.44.5

cli/Cargo.lock, engine/Cargo.lock, engine/crates/composition/tests/composition_tests.rs, engine/crates/federated-graph/Cargo.toml, engine/crates/federated-graph/src/federated_graph.rs, engine/crates/federated-graph/src/from_sdl.rs, engine/crates/federated-graph/src/lib.rs
=> federated-graph: implement conversion from join spec SDL

cli/CHANGELOG.md, cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.45.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/common/src/consts.rs, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json, engine/Cargo.lock, engine/crates/postgres-connector-types/Cargo.toml, engine/crates/postgres-connector-types/src/transport/tcp.rs
=> chore(release): Fix postgres crash, release 0.45.1

engine/crates/integration-tests/tests/postgres/introspection.rs, engine/crates/parser-postgres/src/registry/context/input.rs, engine/crates/parser-postgres/src/registry/queries/create_many.rs, engine/crates/parser-postgres/src/registry/queries/create_one.rs, engine/crates/parser-postgres/src/registry/queries/delete_many.rs, engine/crates/parser-postgres/src/registry/queries/delete_one.rs, engine/crates/parser-postgres/src/registry/queries/input/update.rs, engine/crates/parser-postgres/src/registry/queries/update_many.rs, engine/crates/parser-postgres/src/registry/queries/update_one.rs, engine/crates/parser-postgres/src/registry/types/order_direction.rs, engine/crates/parser-postgres/src/registry/types/page_info.rs, engine/crates/parser-postgres/src/registry/types/scalar.rs, engine/crates/parser-postgres/src/registry/types/table.rs, engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/registry/names.rs
Should fix issues with crashing Postgres connector using auth.
=> fix(postgres): Naming of types for auth

cli/Cargo.lock, cli/Cargo.toml, cli/changelog/0.45.2.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json, engine/Cargo.lock
=> chore(release): Bump to 0.45.2

Cargo.lock, cli/crates/federated-dev/Cargo.toml, cli/crates/federated-dev/src/dev.rs
=> fix: Pathfinder not showing on dev --federated command

cli/crates/gateway/src/executor.rs, engine/crates/engine/src/registry/resolvers/postgres.rs, engine/crates/engine/src/registry/resolvers/postgres/context.rs, engine/crates/integration-tests/src/engine/builder.rs, engine/crates/runtime-local/src/pg.rs, engine/crates/runtime/src/pg.rs
=> fix: Use try_get for the postgres runtime trait to allow caching

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.45.4.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
The release process for 0.45.3 encountered difficulties, this is a second release with the same changes.
=> cli: release 0.45.4

cli/crates/server/src/errors.rs, engine/crates/parser-sdl/src/lib.rs, engine/crates/postgres-connector-types/src/error.rs
- Reword connector and PG errors
=> GB-5408 - Cleanup PG error logs

.github/workflows/cli-partial-release.yml
=> pass cargo about config

engine/crates/composition/src/compose.rs, engine/crates/composition/src/compose/entity_interface.rs, engine/crates/composition/src/compose/input_object.rs, engine/crates/composition/src/compose/interface.rs, engine/crates/composition/src/compose/object.rs, engine/crates/composition/src/composition_ir.rs, engine/crates/composition/src/emit_federated_graph.rs, engine/crates/composition/src/ingest_subgraph.rs, engine/crates/composition/src/ingest_subgraph/object.rs, engine/crates/composition/src/ingest_subgraph/schema_definitions.rs, engine/crates/composition/src/subgraphs/fields.rs, engine/crates/composition/tests/composition/override_basic/federated.graphql, engine/crates/composition/tests/composition/override_basic/subgraphs/mangrove.graphql, engine/crates/composition/tests/composition/override_basic/subgraphs/steppe.graphql, engine/crates/composition/tests/composition/override_errors/federated.graphql, engine/crates/composition/tests/composition/override_errors/subgraphs/mangrove.graphql, engine/crates/composition/tests/composition/override_errors/subgraphs/steppe.graphql, engine/crates/federated-graph/src/federated_graph.rs, engine/crates/federated-graph/src/from_sdl.rs, engine/crates/federated-graph/src/render_sdl.rs
=> composition: implement @override

engine/crates/parser-openapi/src/output/mod.rs, engine/crates/parser-openapi/src/tests/mod.rs, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__greenlake_schema.snap
So we don't make breaking changes to this without noticing.
=> test: sdl test of greenlake schema

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.46.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Features
- Better, more informative terminal output in grafbase dev and grafbase publish --dev (#1046)
=> cli: release 0.46.1

Cargo.lock, engine/crates/composition/tests/composition/composed_directives_basic/federated.graphql, engine/crates/composition/tests/composition/custom_scalars_basic/federated.graphql, engine/crates/composition/tests/composition/entity_composite_key_basic/federated.graphql, engine/crates/composition/tests/composition/entity_composite_key_nested/federated.graphql, engine/crates/composition/tests/composition/entity_interface_basic/federated.graphql, engine/crates/composition/tests/composition/entity_interfaces_multi_subgraph/federated.graphql, engine/crates/composition/tests/composition/entity_multiple_keys_basic/federated.graphql, engine/crates/composition/tests/composition/entity_staggered_composite_key/federated.graphql, engine/crates/composition/tests/composition/enum_only_inputs/federated.graphql, engine/crates/composition/tests/composition/enum_only_outputs/federated.graphql, engine/crates/composition/tests/composition/enum_unused/federated.graphql, engine/crates/composition/tests/composition/inaccessible_basic/federated.graphql, engine/crates/composition/tests/composition/input_object_basic/federated.graphql, engine/crates/composition/tests/composition/interface_implementing_interface_basic/federated.graphql, engine/crates/composition/tests/composition/interfaces_basic/federated.graphql, engine/crates/composition/tests/composition/object_field_arguments_basic/federated.graphql, engine/crates/composition/tests/composition/objects_basic/federated.graphql, engine/crates/composition/tests/composition/override_basic/federated.graphql, engine/crates/composition/tests/composition/provides_basic/federated.graphql, engine/crates/composition/tests/composition/requires_basic/federated.graphql, engine/crates/composition/tests/composition/shareable_basic/federated.graphql, engine/crates/composition/tests/composition/unions_basic/federated.graphql, engine/crates/federated-graph/Cargo.toml, engine/crates/federated-graph/src/render_sdl.rs
These are mostly aimed at making the federation SDL parseable by regular GraphQL parsers.
=> fix(federation): Various changes to the federation graph SDL

packages/grafbase-sdk/src/type.ts, packages/grafbase-sdk/tests/unit/types.test.ts
=> feat: allow field extensions in SDK

engine/crates/engine-v2/schema/src/conversion.rs, engine/crates/engine-v2/schema/src/lib.rs, engine/crates/engine-v2/src/executor/graphql/deserialize/unique_root.rs, engine/crates/integration-tests/src/mocks/graphql/fake_github.rs, engine/crates/integration-tests/tests/federation/basic/mod.rs, engine/crates/integration-tests/tests/federation/basic/scalars.rs, engine/crates/integration-tests/tests/federation/introspection.rs
=> fix(engine-v2): Map unknown scalars to JSON and fix deserialization mistake

engine/crates/integration-tests/tests/graphql_connector/transforms.rs
Don't know when and how the test broke, probably staggered PR merges.
=> integration-tests: fix bad snapshot

cli/crates/backend/src/api/check.rs, cli/crates/backend/src/api/graphql/api.graphql, cli/crates/backend/src/api/graphql/types/mutations.rs, cli/crates/backend/src/api/mod.rs, cli/crates/cli/src/check.rs, cli/crates/cli/src/cli_input.rs, cli/crates/cli/src/cli_input/check.rs, cli/crates/cli/src/cli_input/publish.rs, cli/crates/cli/src/cli_input/sub_command.rs, cli/crates/cli/src/main.rs, cli/crates/cli/src/output/report.rs
=> cli: check command

engine/crates/composition/src/compose.rs, engine/crates/composition/src/compose/fields.rs, engine/crates/composition/src/compose/input_object.rs, engine/crates/composition/src/compose/interface.rs, engine/crates/composition/src/compose/object.rs, engine/crates/composition/src/subgraphs/field_types.rs, engine/crates/composition/src/subgraphs/fields.rs, engine/crates/composition/tests/composition/accessible_argument_with_inaccessible_type/federated.graphql, engine/crates/composition/tests/composition/enum_only_inputs/federated.graphql, engine/crates/composition/tests/composition/enum_only_outputs/federated.graphql, engine/crates/composition/tests/composition/field_type_composition/federated.graphql, engine/crates/composition/tests/composition/field_type_composition/subgraphs/spinners_a.graphql, engine/crates/composition/tests/composition/field_type_composition/subgraphs/spinners_b.graphql, engine/crates/composition/tests/composition/field_type_mismatch/federated.graphql, engine/crates/composition/tests/composition/field_type_mismatch/subgraphs/lettuces_a.graphql, engine/crates/composition/tests/composition/field_type_mismatch/subgraphs/lettuces_b.graphql, engine/crates/composition/tests/composition/interfaces_basic/federated.graphql, engine/crates/integration-tests/tests/federation/introspection.rs
In input (argument, input object) and output (interface, object) fields.
closes GB-5269
closes GB-5176
=> composition: implement field type composition

Cargo.lock, engine/crates/operation-normalizer/Cargo.toml, engine/crates/operation-normalizer/src/arguments.rs, engine/crates/operation-normalizer/src/directives.rs, engine/crates/operation-normalizer/src/lib.rs, engine/crates/operation-normalizer/src/operation.rs, engine/crates/operation-normalizer/src/selection_set.rs, engine/crates/operation-normalizer/src/tests.rs
Implements a normalizer to calculate distinct query ids.
Part of: GB-5519
=> feat: GraphQL Query Normalizer

engine/crates/engine-v2/src/request/bind.rs, engine/crates/integration-tests/tests/federation/basic/variables.rs
This implements & tests all the [GraphQL variable validations][1] in engine-v2 _except_ "All Variable Usages are Allowed" (because that one looks a bit more in-depth so will be in it's own PR/issue).
This should prevent an issue I found yesterday where undeclared variables cause a panic.
FIxes GB-5569
[1]: http://spec.graphql.org/October2021/#sec-Validation.Variables
=> feat: variable validations in engine-v2

cli/crates/cli/src/cli_input/sub_command.rs
=> cli: un-hide schema registry commands

cli/npm/cli/README.md
- Updates the NPM README.md for the CLI
=> GB-5223 - Update the NPM readme for the CLI

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.13.1.md, packages/grafbase-sdk/package.json
=> Version bump sdk

engine/crates/engine-v2/src/execution/coordinator.rs
For wasm the compiler complained about:
```
error: lifetime may not live long enough
--> /Users/brabier/.cargo/git/checkouts/grafbase-b286d81e76fb5b8e/bc562c6/engine/crates/engine-v2/src/execution/coordinator.rs:59:38
|
28 |   impl<'ctx> ExecutorCoordinator<'ctx> {
|        ---- lifetime `'ctx` defined here
...
59 |                           futures.push(Box::pin(make_send_on_wasm(
|  ______________________________________^
60 | |                             executor.execute().map(ExecutorFutResult::from),
61 | |                         )));
| |__________________________^ cast requires that `'ctx` must outlive `'static`
```
So made the output `'static` and it works now, not super clear to me off the top of my head why the future itself could be `'_` but the output couldn't be `'ctx`.
=> chore: engine-v2 static future for wasm

engine/crates/composition/src/compose/object.rs, engine/crates/composition/tests/composition/object_field_arguments_required_not_in_all_subgraphs/federated.graphql, engine/crates/composition/tests/composition/object_field_arguments_required_not_in_all_subgraphs/subgraphs/customer_feedback.graphql, engine/crates/composition/tests/composition/object_field_arguments_required_not_in_all_subgraphs/subgraphs/vendor_statistics.graphql
=> composition: validate that required arguments are present in all subgraphs

engine/crates/parser-openapi/src/parsing/v3/mod.rs, engine/crates/parser-openapi/src/tests/mod.rs, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__netlify_schema.snap, engine/crates/parser-openapi/test_data/netlify.json
I'd made a typo in `requestBodies`
=> fix: support netlify openapi schema

engine/crates/engine-v2/schema/src/walkers/definition.rs, engine/crates/engine-v2/schema/src/walkers/object.rs, engine/crates/engine-v2/src/request/mod.rs, engine/crates/engine-v2/src/request/walkers/selection_set.rs
=> simpler cache config computation

Cargo.lock, cli/crates/backend/src/api/check.rs, cli/crates/backend/src/api/errors.rs, cli/crates/backend/src/api/graphql/api.graphql, cli/crates/backend/src/api/graphql/types/mutations.rs, cli/crates/backend/src/api/publish.rs, cli/crates/cli/Cargo.toml, cli/crates/cli/src/errors.rs, cli/crates/cli/src/output/report.rs, cli/crates/cli/src/publish.rs
Handle the “branch does not exist” error in the CLI's publish command.
=> fix(messaging): GB-5625: Handle the “branch does not exist” error in the CLI's publish command

cli/about.toml
https://choosealicense.com/licenses/bsl-1.0/
=> fix: add BSL to the license whitelist

cli/about.toml
=> add missing comma

cli/crates/server/src/bridge/udf.rs, engine/crates/engine-v2/src/plan/planner.rs, engine/crates/engine/src/registry/resolvers/atlas_data_api/pagination.rs
https://grafbase.slack.com/archives/C02U36JQP7B/p1703232320589989
=> chore(engine): fix clippy errors on main

engine/crates/engine/src/registry/scalars/hex_bytes.rs, engine/crates/integration-tests/tests/postgres/find_many.rs, engine/crates/parser-postgres/src/registry/types/scalar.rs
=> fix: postgres connector should be able to search bytea fields

engine/crates/parser-openapi/src/lib.rs
=> `parser-openapi`: Tweak two error messages

Cargo.lock, Cargo.toml, engine/crates/composition/Cargo.toml, engine/crates/graphql-schema-diff/Cargo.toml, engine/crates/validation/Cargo.toml
Upgrades to v7, which contains an upgrade of the http dependency.
=> chore(deps): Upgrade async-graphql.

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.14.0.md, packages/grafbase-sdk/package.json
Adds a missing feature for a user on discord
=> chore: release sdk 0.14.0

engine/crates/operation-checks/src/aggregate_field_usage.rs, engine/crates/operation-checks/src/schema.rs
This is how we are going to take the configured threshold into account.
Closes GB-5770
=> operation-checks: implement FieldUsage::apply_request_count_threshold()

engine/crates/composition/tests/composition/subscriptions_basic/federated.graphql, engine/crates/composition/tests/composition/subscriptions_basic/subgraphs/products.graphql, engine/crates/composition/tests/composition/subscriptions_basic/subgraphs/reviews.graphql
There was a problem in my code while I was implementing subscriptions and I wasn't sure where it was.  I added this test as part of my debugging efforts as it didn't look like we had a test that specifically had a `Subscription` type in it.
=> test: very simple test of subscription composition

packages/grafbase-sdk/src/auth.ts, packages/grafbase-sdk/src/auth/jwt.ts, packages/grafbase-sdk/src/config.ts, packages/grafbase-sdk/src/index.ts, packages/grafbase-sdk/tests/unit/auth.jwt.test.ts
=> feat: Add auth for federated graph in SDK

.github/workflows/cli.yml, cli/crates/cli/tests/compilation_error.rs, cli/crates/cli/tests/dev_watch.rs, cli/crates/cli/tests/federation.rs, cli/crates/server/src/consts.rs
=> chore: add simple federation e2e-tests

Cargo.lock, engine/crates/engine/src/schema.rs, engine/crates/engine/src/validation/mod.rs, engine/crates/engine/src/validation/visitors/alias_count.rs, engine/crates/engine/src/validation/visitors/height.rs, engine/crates/engine/src/validation/visitors/mod.rs, engine/crates/engine/src/validation/visitors/root_field_count.rs
Add enforcement of operation limits as declared in the SDL to the 1st version of the engine.
=> feat(engine): Enforce operation limits in engine v1

cli/crates/cli/tests/federation.rs, engine/crates/engine-v2/src/request/bind.rs, engine/crates/integration-tests/src/mocks/graphql/fake_github.rs, engine/crates/integration-tests/tests/federation/basic/fragments.rs, engine/crates/integration-tests/tests/federation/introspection.rs
=> feat: fragment cycle detection

cli/crates/backend/src/api/graphql/api.graphql, cli/crates/backend/src/api/graphql/types/mutations.rs, cli/crates/cli/src/check.rs, cli/crates/cli/src/output/report.rs
They became available in the API today.
closes GB-5785
=> cli: display operation check errors

Cargo.lock, cli/crates/gateway/Cargo.toml, cli/crates/gateway/src/auth.rs, engine/crates/gateway-core/src/auth.rs, engine/crates/runtime-noop/src/kv.rs, engine/crates/runtime/src/kv.rs
Remove hardcoded KV namepsace JWKS_CACHE
=> remove hardcoded jwks cache namespace

cli/crates/backend/src/api/check.rs, cli/crates/backend/src/api/graphql/api.graphql, cli/crates/backend/src/api/graphql/types/mutations.rs, cli/crates/cli/src/check.rs, cli/crates/cli/src/output/report.rs
We now have warnings in addition to errors, we have to handle them.
closes GB-5812
=> cli: handle warnings in `grafbase check`

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.16.0.md, packages/grafbase-sdk/package.json
Add a change log and bump the version.
=> chore(sdk): Prepare the 0.16.0 release of the SDK

.github/workflows/cli.yml, Cargo.lock, Cargo.toml, cli/changelog/0.52.5.md, cli/changelog/0.53.0.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
=> chore(release): Prepare the 0.53.0 release of the CLI

engine/crates/graphql-schema-diff/CHANGELOG.md, engine/crates/graphql-schema-diff/Cargo.toml, engine/crates/graphql-schema-diff/README.md, engine/crates/graphql-schema-diff/src/change.rs, engine/crates/graphql-schema-diff/src/lib.rs
=> graphql-schema-diff: release 0.1.0

cli/crates/cli/README.md, cli/crates/cli/src/cli_input/sub_command.rs, cli/npm/cli/README.md
=> cli: update help text

engine/crates/graphql-mocks/src/lib.rs, engine/crates/integration-tests/tests/federation/subscriptions.rs
I broke an integration test in #1278 - did try to push this fix to that PR, but automerge had got to it before I managed to.  Not sure why it got merged since the tests are failing but 🤷
=> fix: a broken integration test

templates/graphql-vendure/README.md, templates/graphql-vendure/grafbase.config.ts, templates/graphql-vendure/package-lock.json, templates/graphql-vendure/package.json
=> adds Vendure template

engine/crates/integration-tests/tests/openapi/headers.rs
=> fix: fix openapi integration-tests

Cargo.lock, Cargo.toml
=> 0.54.0-fix

cli/npm/cli/package.json, packages/cli-app/package.json, packages/cli-app/src/app.tsx, packages/pnpm-lock.yaml
=> pathfinder-0.5.0

Cargo.lock, Cargo.toml, cli/crates/server/Cargo.toml
=> chore(deps): Update serde_with

Cargo.lock, Cargo.toml, engine/crates/engine/Cargo.toml, engine/crates/engine/src/current_datetime.rs
Using a new, nicer branch of our fork of ulid-rs.
=> chore(deps): GB-5891: Use our new branch of ulid-rs

engine/crates/engine-v2/src/execution/variables.rs, engine/crates/engine-v2/src/request/bind.rs, engine/crates/engine-v2/src/request/location.rs, engine/crates/engine-v2/src/request/mod.rs, engine/crates/engine-v2/src/request/parse.rs, engine/crates/engine-v2/src/request/selection_set.rs, engine/crates/engine-v2/src/request/variable.rs, engine/crates/engine-v2/src/request/walkers/field_definition.rs, engine/crates/engine-v2/src/response/error.rs
Hesitated to change `engine_parser` directly. Using a full `usize` for
both line & columns felt huge. A u16 is more than enough.
=> chore: Using smaller Location with u16 rather than usize

Cargo.lock, cli/crates/server/Cargo.toml, cli/crates/server/src/bridge/udf.rs, cli/crates/server/src/consts.rs, cli/crates/server/src/udf_builder.rs, cli/udf-wrapper/package.json
- Fix Bun flakiness issue
- Remove additional Bun build
- Update Bun
- Remove a few unnecessary file copies and writes
=> Fix Bun flakiness issue and remove additional build

cli/udf-wrapper/tsconfig.json, engine/crates/composition/README.md, engine/crates/graphql-schema-diff/README.md, engine/crates/validation/README.md
=> graphql-schema-diff: improve README

Cargo.lock, engine/crates/composition/CHANGELOG.md, engine/crates/composition/Cargo.toml, engine/crates/federated-graph/Cargo.toml, engine/crates/graphql-schema-diff/CHANGELOG.md, engine/crates/graphql-schema-diff/Cargo.toml, engine/crates/validation/CHANGELOG.md, engine/crates/validation/Cargo.toml
I'll tag and do the releases once this PR is merged.
=> Release crates.io crates with improved READMEs

.dockerignore, Cargo.lock, cli/crates/cli/tests/utils/async_client.rs, cli/crates/federated-dev/Cargo.toml, cli/crates/federated-dev/src/dev.rs, cli/crates/federated-dev/src/dev/gateway_nanny.rs, cli/crates/gateway/src/serving.rs, engine/crates/engine-v2/Cargo.toml, engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/execution/prepared.rs, engine/crates/engine-v2/src/request/parse.rs, engine/crates/engine/src/lib.rs, engine/crates/engine/src/registry/cache_control.rs, engine/crates/engine/src/request.rs, engine/crates/engine/src/schema.rs, engine/crates/federated-graph/src/lib.rs, engine/crates/gateway-core/src/cache/key.rs, engine/crates/gateway-v2/src/lib.rs, engine/crates/graphql-extensions/src/runtime_log.rs, engine/crates/integration-tests/src/engine/mod.rs, flake.nix
Improved performance by ~20% (before all the optimizations)
=> feat: plan cache for cli

Cargo.lock, cli/crates/cli/Cargo.toml, cli/crates/cli/src/main.rs, cli/crates/cli/tests/utils/async_client.rs, cli/crates/federated-dev/src/dev.rs, cli/crates/federated-dev/src/dev/gateway_nanny.rs, engine/crates/engine-v2/Cargo.toml, engine/crates/engine-v2/src/engine.rs, engine/crates/federated-graph/src/lib.rs, engine/crates/gateway-v2/src/lib.rs
improved performance by 15-20% by itself, basically for free.
=> feat: Use Mimalloc allocator for the cli

engine/crates/engine-v2/schema/src/builder/mod.rs, engine/crates/engine-v2/schema/src/lib.rs, engine/crates/engine-v2/schema/src/sources/introspection.rs, engine/crates/engine-v2/schema/src/walkers/type.rs, engine/crates/engine-v2/schema/src/wrapping.rs, engine/crates/engine-v2/src/execution/variables.rs, engine/crates/engine-v2/src/plan/planning/collect.rs, engine/crates/engine-v2/src/plan/walkers/mod.rs, engine/crates/engine-v2/src/request/bind.rs, engine/crates/engine-v2/src/request/walkers/variables.rs, engine/crates/engine-v2/src/response/write/deserialize/field.rs, engine/crates/engine-v2/src/response/write/deserialize/selection_set/collected.rs, engine/crates/engine-v2/src/response/write/deserialize/selection_set/runtime_concrete.rs, engine/crates/engine-v2/src/sources/introspection/writer.rs, engine/crates/integration-tests/tests/federation/introspection.rs
Avoids a bunch of clone() and fixes a bug in the introspection. ordering of NonNull & List weren't correct.
=> chore: enigne-v2 make Wrapping Copy

engine/crates/engine-v2/schema/src/builder/mod.rs, engine/crates/engine-v2/schema/src/lib.rs, engine/crates/engine-v2/schema/src/sources/introspection.rs, engine/crates/engine-v2/schema/src/walkers/definition.rs, engine/crates/engine-v2/src/execution/variables.rs, engine/crates/engine-v2/src/plan/collected.rs, engine/crates/engine-v2/src/plan/planning/collect.rs, engine/crates/engine-v2/src/plan/walkers/mod.rs, engine/crates/engine-v2/src/response/value.rs, engine/crates/engine-v2/src/response/write/deserialize/field.rs, engine/crates/engine-v2/src/response/write/deserialize/scalar.rs
=> chore: simplify scalar deserialization in engine-v2

.github/workflows/cli-partial-release.yml
=> ci: announce cli release job start on slack

cli/crates/server/build.rs, cli/nix/cli.nix, cli/nix/udf-wrapper.nix, cli/udf-wrapper/README.md, cli/udf-wrapper/package-lock.json
udf wrapper needs to be packaged
=> nix: fix cli derivation

cli/crates/gateway/src/serving.rs
=> fix: simpler context creation in cli/gateway

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.18.0.md, packages/grafbase-sdk/package.json
=> SDK 0.18.0

cli/crates/cli/tests/introspection.rs, cli/crates/cli/tests/introspection_configuration.rs, cli/crates/cli/tests/kv.rs, cli/crates/cli/tests/utils/environment.rs, engine/crates/engine/src/registry/mod.rs, engine/crates/engine/src/registry/tests.rs, engine/crates/integration-tests/tests/openapi/transforms.rs, engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__array_input_value.snap, engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__conversion.snap, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__flat_output-2.snap, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__petstore_output-2.snap, engine/crates/parser-sdl/src/rules/introspection.rs, engine/crates/parser-sdl/src/snapshots/parser_sdl__tests__schema.snap, engine/crates/parser-sdl/src/snapshots/parser_sdl__tests__test_model_reserved_fields-req-a.snap, engine/crates/parser-sdl/src/snapshots/parser_sdl__tests__test_model_reserved_fields-req-b.snap, flake.lock, flake.nix
- Enables introspection by default
- Fixes typo in introspection directive docs
- Adds tests
- Updates nix flake
=> GB-5995 - Enable introspection by default, test introspection configuration and KV, update nix flake

engine/crates/graphql-extensions/src/authorization.rs
=> fix auth edge case

packages/grafbase-sdk/jest.config.js, packages/grafbase-sdk/package.json, packages/grafbase-sdk/src/auth.ts, packages/grafbase-sdk/src/config.ts, packages/grafbase-sdk/tests/unit/auth.authorizer.test.ts, packages/grafbase-sdk/tests/unit/auth.jwks.test.ts, packages/grafbase-sdk/tests/unit/auth.jwt.test.ts, packages/grafbase-sdk/tests/unit/auth.openid.test.ts, packages/pnpm-lock.yaml
- Fixes the formatting for SDK extend directives
=> Fix formatting for SDK extend directives

cli/crates/backend/src/project.rs, cli/crates/common/src/consts.rs, cli/crates/common/src/environment.rs, cli/crates/server/src/bridge/server.rs, cli/crates/server/src/errors.rs
=> stop creating .grafbase/database directory

cli/crates/cli/tests/federation.rs, cli/crates/federated-dev/src/dev.rs, cli/crates/federated-dev/src/dev/batch_response.rs
As the title says.
Fixes GB-6026
=> feat: batching in engine-v2 in cli

cli/crates/server/src/bridge/udf.rs
- Fixes the leaking of Bun processes when restarting `dev` by explicitly aborting the handle on `Drop`
=> GB-5905  - Fix UDF leak by explicitly aborting on Drop

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.59.0.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
=> cli: release 0.59.0

.github/workflows/cli-partial-release.yml, .github/workflows/cli.yml
=> Use smaller assets

engine/crates/engine/src/resolver_utils/container.rs, engine/crates/graph-entities/src/response/mod.rs, engine/crates/integration-tests/tests/execution/mod.rs
`engine-v1` had an issue when a query came in with overlapping fragments, e.g.:
```graphql
query {
foo {
... {
bar {
baz
}
}
... {
bar {
blorp
}
}
}
}
```
The `foo` object has two different instances of its field `bar` and when inserting these into the response we were overwriting one with the other.  This meant that the response would only have `blorp` in it and not `baz`.  This isn't likely to be an issue for handcrafted queries, but is very likely for anyone using Relay - as it very much encourages you to have overlapping fragments.
The fix I've attempted is just to do a nested merge on duplicate field names when populating the response.  This isn't quite what the spec says you should do: I think there's meant to be a preprocessing step where you collect all the fields from each nested …
=> fix: issues with overlapping fragments in engine-v1

cli/crates/cli/src/start/configuration.rs
For the self hosted engine. Goes hand in hand with WIP doc PR at https://github.com/grafbase/website/pull/2364/files
closes GB-6165
=> cli: add trusted_documents section to TOML config

engine/crates/operation-normalizer/src/lib.rs, engine/crates/operation-normalizer/src/tests.rs
=> fix: operation normalizer failed without operation name

cli/crates/production-server/src/server/graph_updater.rs
304 isn't an error, so the logic was wrong.
=> fix(self-hosted): Fix the handling of 304 in the self-hosted mode

cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, engine/crates/engine-v2/Cargo.toml, engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/execution/coordinator.rs, engine/crates/engine-v2/src/execution/prepared.rs, engine/crates/engine-v2/src/sources/graphql/mod.rs, engine/crates/engine/Cargo.toml, engine/crates/engine/src/schema.rs
=> Add a 'tracing' feature to engine

cli/crates/production-server/src/server/graph_fetch_method.rs, cli/crates/production-server/src/server/graph_updater.rs, engine/crates/integration-tests/Cargo.toml
We should log when we successfully created/updated a new gateway.
=> chore: log info when a gateway is created/updated

engine/crates/composition/src/compose/interface.rs, engine/crates/composition/tests/composition/shareable_is_forbidden_on_interface_fields/federated.graphql, engine/crates/composition/tests/composition/shareable_is_forbidden_on_interface_fields/subgraphs/with_interface.graphql, engine/crates/composition/tests/composition/shareable_is_repeatable/federated.graphql, engine/crates/composition/tests/composition/shareable_is_repeatable/subgraphs/theoone.graphql
=> composition: implement federation 2.2 @shareable validations

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.61.0.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- self-hosted gateway
- tracing
=> chore: bump cli to 0.61.0

cli/crates/server/src/bun.rs
=> GB-6201 - Update bun

Cargo.lock, cli/crates/production-server/Cargo.toml, cli/crates/production-server/src/config.rs, cli/crates/production-server/src/config/cors.rs, cli/crates/production-server/src/config/dynamic_string.rs, cli/crates/production-server/src/server.rs, cli/crates/production-server/src/server/gateway.rs, cli/crates/production-server/src/server/graph_fetch_method.rs, cli/crates/production-server/src/server/graph_updater.rs, engine/crates/parser-sdl/src/lib.rs
See: https://www.notion.so/grafbase/RFC-Self-hosted-Grafbase-Gateway-7cdf2d17d3e343e28341b479e0221b58?pvs=4#e69194a97004413ea676643f619ce7a5
Closes: GB-6202
=> feat: header and subgraph config for self-hosted gateway

.github/workflows/binaries.yml, .github/workflows/gateway-partial-release.yml, .github/workflows/grafbase-partial-release.yml, .github/workflows/sanitize-alert-schedule.yml, Cargo.lock, Cargo.toml, cli/Makefile.toml, cli/changelog/0.63.0-rc.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json, gateway/Makefile.toml, gateway/README.md, gateway/changelog/0.1.0-rc.1.md, gateway/changelog/0.1.0-rc.2.md, gateway/changelog/0.1.0-rc.3.md, gateway/changelog/0.1.0-rc.4.md, gateway/changelog/0.1.0-rc.5.md, gateway/changelog/0.1.0-rc.6.md, gateway/changelog/0.1.0-rc.7.md, gateway/changelog/0.1.0-rc.8.md, gateway/crates/federated-server/Cargo.toml, gateway/crates/gateway-binary/Cargo.toml
Closes: GB-6242
Closes: GB-6240
=> chore: gateway release tasks

.github/workflows/binaries.yml
Too noisy and not very useful anymore.
=> remove GitHub comments for binary releases

Cargo.lock, cli/crates/backend/src/api/graphql/api.graphql, cli/crates/backend/src/api/graphql/types/mutations/submit_trusted_documents.rs, cli/crates/cli/Cargo.toml, cli/crates/cli/src/cli_input.rs, cli/crates/cli/src/cli_input/project_ref.rs, cli/crates/cli/src/cli_input/sub_command.rs, cli/crates/cli/src/cli_input/trust.rs, cli/crates/cli/src/output/report.rs, cli/crates/cli/src/trust.rs
Also un-hide the trust command since we released trusted documents.
closes GB-6205
=> cli: add graph ref support, introduce in `trust`

.github/workflows/binaries.yml, .github/workflows/gateway-partial-release.yml, .github/workflows/grafbase-partial-release.yml, .github/workflows/packages.yml, .github/workflows/prettier.yml, .github/workflows/sanitize-alert-schedule.yml, .github/workflows/sdk.yml
Switch the runners from BuildJet to Ubicloud.
=> chore(ci): Migrate from BuildJet to Ubicloud

engine/crates/composition/src/emit_federated_graph.rs, engine/crates/composition/src/emit_federated_graph/context.rs, engine/crates/composition/src/ingest_subgraph.rs, engine/crates/composition/src/ingest_subgraph/directives.rs, engine/crates/composition/src/lib.rs, engine/crates/composition/src/subgraphs/directives.rs, engine/crates/composition/src/subgraphs/field_types.rs, engine/crates/composition/src/subgraphs/keys.rs, engine/crates/composition/src/validate.rs, engine/crates/composition/tests/composition/requires_with_arguments/federated.graphql, engine/crates/composition/tests/composition/requires_with_arguments/subgraphs/wasabi.graphql, engine/crates/composition/tests/composition/requires_with_arguments_validation/federated.graphql, engine/crates/composition/tests/composition/requires_with_arguments_validation/subgraphs/wasabi.graphql, engine/crates/federated-graph/src/federated_graph/v1.rs, engine/crates/federated-graph/src/federated_graph/v2.rs, engine/crates/federated-graph/src/federated_graph/v3.rs, engine/crates/federated-graph/src/from_sdl.rs, engine/crates/federated-graph/src/render_sdl.rs
=> composition: allow arguments in `@requires` selection sets

engine/crates/engine/src/validation/rules/arguments_of_correct_type.rs, engine/crates/integration-tests/src/lib.rs, engine/crates/log/src/lib.rs, engine/crates/operation-checks/src/check/rules.rs, rust-toolchain.toml
- Updates Rust to version 1.77.0
=> GB-6310 - Update Rust to 1.77.0

.envrc.example, cli/Makefile.toml
- Some leftover cleanup from removing the assets
=> Some leftover cleanup from removing the assets

cli/nix/wrappers.nix
=> chore: Update nix wrappers build

cli/crates/cli/src/upgrade.rs, cli/result
- Fixes `upgrade` for the new tag format
=> CLI new tag format fix

engine/crates/runtime/src/cache/cached.rs
=> use debug cache tracing

cli/crates/common/src/consts.rs
=> turn off info logs

cli/crates/server/src/proxy.rs, cli/crates/server/src/servers.rs
`grafbase dev` starts a few different servers and the federation code path was reporting the port of the "worker" and not the "proxy".  This fixes that.
=> fix: report the correct port in federated dev

cli/crates/server/src/config/parser.rs, engine/crates/integration-tests/src/engine/builder.rs, engine/crates/integration-tests/src/federation/builder.rs, engine/crates/integration-tests/src/postgres.rs, engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/rules/auth_directive/mod.rs, engine/crates/parser-sdl/src/rules/extend_connector_types.rs, engine/crates/parser-sdl/src/rules/extend_field.rs, engine/crates/parser-sdl/src/rules/graphql_directive.rs, engine/crates/parser-sdl/src/rules/model_directive.rs, engine/crates/parser-sdl/src/rules/openapi_directive.rs, engine/crates/parser-sdl/src/rules/operation_limits_directive.rs, engine/crates/parser-sdl/src/rules/postgres_directive.rs, engine/crates/parser-sdl/src/rules/visitor/context.rs
=> parser-sdl: remove database_models_enabled

engine/crates/composition/tests/composition/override_basic/federated.graphql, engine/crates/composition/tests/composition/override_label/federated.graphql, engine/crates/engine-v2/schema/src/builder/graph.rs, engine/crates/engine-v2/src/operation/bind/mod.rs, engine/crates/federated-graph/src/from_sdl.rs, engine/crates/federated-graph/src/render_sdl.rs, engine/crates/integration-tests/tests/federation/subgraphs/mod.rs, engine/crates/integration-tests/tests/federation/subgraphs/overrride.rs
=> feat(engine-v2): add test & fix override support

gateway/LICENSE, gateway/crates/federated-server/Cargo.toml, gateway/crates/gateway-binary/Cargo.toml
=> chore: add MPL license to the gateway

.github/workflows/gateway-partial-release.yml, .github/workflows/grafbase-partial-release.yml, cli/install/gateway, cli/install/upload.sh
- Updates the `grafbase-gateway` install script on releases
=> GB-6267 - Gateway script updater

engine/crates/parser-openapi/src/parsing/v2/mod.rs
We've got a customer that wants to use a drupal with the OpenAPI connector. This fixes a couple of issues in the parser around that:
1. We weren't handling `definitions` at all in v2, simply because I didn't do it.
2. Drupal uses nested refs like `#/definitions/schema_name/properties/data` which no other API I've seen uses, so needed to add support for that.
=> fix: better support for drupal openapi specs

.github/workflows/gateway-partial-release.yml, .github/workflows/grafbase-partial-release.yml
- Expose secrets to script updaters
=> Expose secrets to script updaters

Cargo.lock, gateway/changelog/0.2.0.md, gateway/crates/federated-server/Cargo.toml, gateway/crates/federated-server/src/server.rs, gateway/crates/federated-server/src/server/graph_fetch_method.rs, gateway/crates/federated-server/src/server/graph_updater.rs, gateway/crates/gateway-binary/Cargo.toml, gateway/crates/gateway-binary/src/args.rs, gateway/crates/gateway-binary/src/args/log.rs, gateway/crates/gateway-binary/src/main.rs
=> chore: gateway tweaks

gateway/CHANGELOG.md
=> chore(gateway): missing changes to changelog

Cargo.lock, Cargo.toml, engine/crates/tracing/Cargo.toml
Reverts grafbase/grafbase#1532
=> Revert "Fix (cloudflare) worker crate version"

engine/crates/engine/src/registry/mod.rs
unused interfaces would be removed but the implements relationship was still kept.
=> fix(engine): Fix remove unused types

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.65.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
=> release 0.65.1

.github/workflows/gateway-partial-release.yml, .github/workflows/grafbase-partial-release.yml, cli/install/gateway
-  Attempt to fix GH actions ignoring defined and mentioned secrets by adding them to the workflow level
=> Attempt to fix GH actions ignoring defined and mentioned secrets by adding them to the workflow level

.github/workflows/binaries.yml
=> fix secrets

Cargo.lock, engine/crates/dataloader/src/lib.rs, engine/crates/engine/Cargo.toml, engine/crates/engine/src/context.rs, engine/crates/engine/src/registry/resolvers/graphql.rs, engine/crates/engine/src/registry/resolvers/mod.rs, engine/crates/engine/src/schema.rs
=> fix: replace spawn by a query futures pool executed in the background

engine/crates/tracing/src/span/request.rs
=> chore: remove the query attribute from the request span

.github/actions/test/action.yml, Cargo.lock, gateway/crates/gateway-binary/Cargo.toml, gateway/crates/gateway-binary/data/otel/otel-collector-config.yml, gateway/crates/gateway-binary/docker-compose.yml, gateway/crates/gateway-binary/tests/integration_tests.rs, gateway/crates/gateway-binary/tests/telemetry/mod.rs
=> Add integration tests for otlp + clickhouse

Cargo.lock, gateway/crates/federated-server/src/server.rs, gateway/crates/federated-server/src/server/engine.rs, gateway/crates/federated-server/src/server/graph_updater.rs, gateway/crates/federated-server/src/server/otel.rs, gateway/crates/federated-server/src/server/state.rs, gateway/crates/gateway-binary/src/main.rs
Update the data used on otel reload.
=> fix: reload data

engine/crates/engine/src/registry/resolvers/atlas_data_api/normalize.rs, engine/crates/integration-tests/tests/mongodb/find_many.rs
=> fix(mongo): normalize elemMatch correctly in AND/OR blocks

gateway/crates/gateway-binary/src/main.rs
Prefixes the resources attributes accordingly.
=> feat: prefix resource attributes

Cargo.lock, engine/crates/engine/src/registry/mod.rs, engine/crates/parser-graphql/Cargo.toml, engine/crates/parser-graphql/src/lib.rs, engine/crates/parser-graphql/src/snapshots/parser_graphql__tests__contentful_schema.snap, engine/crates/parser-graphql/tests/contentful.json
=> fix: Keep unused interfaces if any type implements them (fragments)

cli/crates/server/src/bun.rs
=> GB-6433 - Update Bun to 1.1.2

gateway/crates/federated-server/src/server/otel.rs, gateway/crates/gateway-binary/src/main.rs, gateway/crates/gateway-binary/tests/telemetry/mod.rs
=> chore: Do not add any default resource attributes for OTEL

engine/crates/engine/src/validation/visitors/cache_control.rs, engine/crates/integration-tests/tests/caching/mod.rs, engine/crates/parser-sdl/src/rules/cache_directive/global.rs, engine/crates/tracing/src/otel.rs, engine/crates/tracing/src/otel/exporter.rs
=> feat: support caching for interfaces

engine/crates/parser-sdl/src/rules/join_directive.rs
I'd obviously forgotten to update the bit of code that finds variables in the join stirng to handle variables on nested selections.  This meant that the validation code for arguments considered any arguments on nested fields as "unused" even though they clearly were.  Would have affected the implict requires we put on these fields as well, which I imagine nobody would notice, because that barely works with half of our connectors anyway.
=> fix: consider nested variables in join string

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.67.2.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
=> release 0.67.2

Cargo.lock
=> fix cargo.lock

Cargo.lock, engine/crates/engine/src/registry/mod.rs, engine/crates/engine/src/registry/tests.rs, engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__array_input_value.snap, engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__conversion.snap, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__flat_output-2.snap, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__petstore_output-2.snap, engine/crates/parser-sdl/Cargo.toml, engine/crates/parser-sdl/src/lib.rs, engine/crates/parser-sdl/src/rules/cors_directive/mod.rs, engine/crates/parser-sdl/src/rules/mod.rs, packages/grafbase-sdk/src/config.ts, packages/grafbase-sdk/src/cors.ts, packages/grafbase-sdk/tests/unit/cors.test.ts
=> feat: cors directive for managed graphs

cli/crates/server/src/bun.rs
- Update Bun to version 1.1.4 ([changelog](https://bun.sh/blog/bun-v1.1.4))
=> GB-6519 - Update Bun to v1.1.4

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.21.0.md, packages/grafbase-sdk/package.json
=> chore: SDK 0.21.0

engine/crates/federated-graph/src/from_sdl.rs
=> fix: better error on missing type in sdl -> federated graph

cli/crates/backend/src/api/graphql/api.graphql, cli/crates/backend/src/api/graphql/types/mutations.rs, cli/crates/cli/src/check.rs, cli/crates/cli/src/output/report.rs
- `check` now runs lint checks as well
- Tweaks the check output
- Updates the API GraphQL schema
=> GB-6448 - Add lints to check command

engine/crates/engine/Cargo.toml, engine/crates/engine/src/registry/resolvers/logged_fetch.rs
=> chore: add trace for external http request

Cargo.lock, Cargo.toml, engine/crates/engine/src/registry/resolvers/graphql.rs, engine/crates/engine/src/registry/resolvers/http/mod.rs
=> fix: add timeout for graphql and http resolvers

engine/crates/engine/src/registry/resolvers/graphql.rs, engine/crates/engine/src/registry/resolvers/logged_fetch.rs
We should have more info where time is spent when triggering an http request:
- is it connecting
- or loading data from the backend
- or sending logs data
=> fix: add more info to traces for http requests

engine/crates/engine/src/registry/resolvers/logged_fetch.rs, engine/crates/gateway-core/src/lib.rs, engine/crates/gateway-core/src/trusted_documents.rs, engine/crates/gateway-v2/auth/src/lib.rs
=> chore: a bit more tracing

cli/wrappers/package-lock.json, packages/pnpm-lock.yaml
Reverts grafbase/grafbase#1634
=> Revert "Revert "chore(deps): update dependencies-non-major""

Cargo.lock, cli/crates/server/Cargo.toml
Reverts grafbase/grafbase#1632
=> Revert "fix(deps): update rust crate zip to v1"

gateway/crates/federated-server/src/lib.rs, gateway/crates/federated-server/src/server.rs, gateway/crates/federated-server/src/server/graph_updater.rs, gateway/crates/gateway-binary/tests/integration_tests.rs, gateway/crates/gateway-binary/tests/mocks/gdn.rs, gateway/crates/gateway-binary/tests/mocks/mod.rs, gateway/crates/gateway-binary/tests/telemetry/mod.rs
=> gateway: align on GDN terminology

cli/crates/server/src/bun.rs
=> GB-6609 - Update Bun to 1.1.5

engine/crates/engine/src/registry/resolvers/postgres/context/selection.rs, engine/crates/engine/src/registry/resolvers/postgres/context/selection/collection_args.rs, engine/crates/engine/src/registry/resolvers/postgres/request/query/select.rs, engine/crates/integration-tests/tests/postgres/find_many.rs
=> fix: order columns must be in selection, implicit if needed

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.71.0.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
The `branch` and `environment` subcommands.
=> chore(cli): bump to 0.71.0

cli/crates/backend/src/api/types.rs, cli/crates/cli/src/output/report.rs, cli/crates/gateway/src/serving.rs, engine/crates/engine-v2/src/engine.rs, engine/crates/engine/registry-v1/src/registry_impl.rs, engine/crates/engine/src/context/ext.rs, engine/crates/engine/src/registry/builder.rs, engine/crates/engine/src/registry/mod.rs, engine/crates/engine/src/types/merged_object.rs, engine/crates/engine/src/validation/rules/known_type_names.rs, engine/crates/graphql-schema-diff/src/traverse_schemas.rs, engine/crates/integration-tests/src/engine/builder.rs, engine/crates/operation-checks/src/aggregate_field_usage.rs, engine/crates/parser-sdl/src/type_names.rs, rust-toolchain.toml
=> GB-6642 - Rust 1.78

cli/crates/cli/src/cli_input/lint.rs, cli/crates/cli/src/lint.rs
- Allows piping a schema to the lint command
=> GB-6596 - Allow piping to lint

.github/actions/init_rust_job/action.yml
=> fix: try fixing nextest install on windows using pwsh

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.71.2.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Now let's see if we get a good windows build...
=> chore(cli): bump to 0.71.2

Cargo.lock, gateway/changelog/0.3.1.md, gateway/crates/federated-server/Cargo.toml, gateway/crates/gateway-binary/Cargo.toml
=> release gateway 0.3.1

gateway/crates/federated-server/src/server/graph_updater.rs
=> debug log OTEL reload

cli/crates/cli/src/deploy.rs
- Does not redeploy after running create on `deploy`
=> GB-6664 - Fix double deployments on create

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.24.0.md, packages/grafbase-sdk/package.json
Breaking
- The `kv` experimental feature is removed.
Features
- Added jwtClaims to ResolverContext.request (#1700)
=> sdk: release 0.24.0

engine/crates/tracing/src/metrics/mod.rs
=> fix: make grafbase_tracing::metrics::meter public

Cargo.lock, cli/crates/server/Cargo.toml, cli/crates/server/src/introspect_local.rs
- Better formatting for `grafbase introspect --dev`
=> GB-6598 - Format dev introspection

cli/crates/cli/tests/introspection.rs
=> Fix snapshot

Cargo.lock, engine/crates/parser-sdl/Cargo.toml, engine/crates/parser-sdl/src/rules/postgres_directive.rs
=> fix: validate pg connection string

engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/engine/trusted_documents.rs, engine/crates/engine-v2/src/execution/context.rs, engine/crates/engine-v2/src/operation/validation/auth.rs, engine/crates/engine/src/schema.rs, engine/crates/gateway-core/src/lib.rs, engine/crates/tracing/src/grafbase_client.rs, engine/crates/tracing/src/metrics/mod.rs, engine/crates/tracing/src/metrics/operation.rs, gateway/crates/gateway-binary/tests/telemetry/metrics/operation.rs
=> chore(engine): add client name/version in operation metrics

Cargo.lock, Cargo.toml, cli/changelog/0.73.0.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/crates/federated-dev/Cargo.toml, cli/crates/server/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json, engine/crates/engine/registry-v2-generator/Cargo.toml
Improvements
- Print composition errors for subgraphs from TS config in `grafbase dev` (#1727)
- Better validation for postgres connection strings (#1725)
=> cli: release 0.73.0

Cargo.lock, Cargo.toml, engine/crates/tracing/Cargo.toml, engine/crates/tracing/src/otel/layer.rs
A partial downgrade of https://github.com/grafbase/grafbase/pull/1730
=> chore(deps): Downgrade OTEL crates for now as the upgrade has turned out rather complex

engine/crates/parser-sdl/src/rules/extend_query_and_mutation_types.rs
A user was asking about this on discord, and I can't think of any reason not to support it.  Seems like it'd be useful as a way to make convenient aliases for common queries or similar.
=> feat: support `@join` on Query type

engine/crates/engine/registry-upgrade/src/lib.rs, engine/crates/engine/registry-upgrade/src/partial_cache_registry.rs, engine/crates/engine/registry-v1/src/lib.rs, engine/crates/engine/registry-v2/src/lib.rs, engine/crates/engine/registry-v2/src/writer.rs, engine/crates/engine/src/registry/tests.rs, engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__array_input_value.snap, engine/crates/parser-graphql/src/snapshots/parser_graphql__conversion__tests__conversion.snap, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__flat_output-2.snap, engine/crates/parser-openapi/src/tests/snapshots/parser_openapi__tests__petstore_output-2.snap, engine/crates/parser-sdl/src/rules/experimental.rs, packages/grafbase-sdk/src/experimental.ts, packages/grafbase-sdk/tests/unit/experimental.test.ts
Add support for the runtime property to the IR
=> feat(ir): GB-6854: Add support for the runtime property to the IR

engine/crates/engine/validation/src/visitors/cache_control.rs, engine/crates/integration-tests/tests/caching/mod.rs
=> fix cache control computation

Cargo.lock, Cargo.toml, cli/crates/federated-dev/src/dev/gateway_nanny.rs, engine/crates/engine-v2/id-newtypes/Cargo.toml, engine/crates/engine-v2/id-newtypes/src/lib.rs, engine/crates/engine-v2/id-newtypes/src/range.rs, engine/crates/engine-v2/schema/Cargo.toml, engine/crates/engine-v2/schema/build.rs, engine/crates/engine-v2/schema/src/directives/cache_control.rs, engine/crates/engine-v2/schema/src/directives/mod.rs, engine/crates/engine-v2/schema/src/directives/requires_scopes.rs, engine/crates/engine-v2/schema/src/ids.rs, engine/crates/engine-v2/schema/src/input_value/mod.rs, engine/crates/engine-v2/schema/src/lib.rs, engine/crates/engine-v2/schema/src/provides.rs, engine/crates/engine-v2/schema/src/requires.rs, engine/crates/engine-v2/schema/src/resolver.rs, engine/crates/engine-v2/schema/src/sources/graphql.rs, engine/crates/engine-v2/schema/src/sources/introspection.rs, engine/crates/engine-v2/schema/tests/conversion.rs, engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/sources/introspection/writer.rs, engine/crates/gateway-v2/auth-config/src/v2.rs, engine/crates/integration-tests/src/federation/builder.rs, engine/crates/integration-tests/src/federation/builder/bench.rs, engine/crates/integration-tests/src/federation/builder/mock.rs, engine/crates/integration-tests/tests/federation/basic/empty_config.rs, gateway/crates/federated-server/src/server/gateway.rs
Allows us to cache it serialized and re-use it.
=> chore(engine-v2): make Schema serializable

cli/crates/server/src/bun.rs
=> Bun 1.1.13

gateway/CHANGELOG.md, gateway/changelog/0.3.2.md
=> gateway release 0.3.2

Cargo.lock, gateway/crates/federated-server/Cargo.toml, gateway/crates/gateway-binary/Cargo.toml
=> bump gateway version

engine/crates/engine-v2/src/operation/bind/mod.rs, engine/crates/engine-v2/src/operation/build.rs, engine/crates/engine-v2/src/operation/parse.rs, engine/crates/engine/parser/src/lib.rs, engine/crates/engine/src/context.rs, engine/crates/engine/src/lib.rs, engine/crates/engine/src/response/mod.rs, engine/crates/engine/src/schema.rs, engine/crates/integration-tests/tests/tracing/v1.rs, engine/crates/integration-tests/tests/tracing/v2.rs, gateway/crates/gateway-binary/tests/telemetry/metrics/operation.rs
=> feat(engine): generate operation name from first field if none was provided

engine/crates/integration-tests/src/federation/builder/hooks.rs, engine/crates/runtime-local/src/hooks.rs, engine/crates/runtime-noop/src/hooks.rs, engine/crates/runtime/src/hooks.rs, engine/crates/wasi-component-loader/examples/crates/authorization/src/bindings.rs, engine/crates/wasi-component-loader/examples/crates/authorization/src/lib.rs, engine/crates/wasi-component-loader/examples/crates/authorization/wit/world.wit, engine/crates/wasi-component-loader/examples/crates/missing_hook/src/bindings.rs, engine/crates/wasi-component-loader/examples/crates/missing_hook/src/lib.rs, engine/crates/wasi-component-loader/examples/crates/missing_hook/wit/world.wit, engine/crates/wasi-component-loader/examples/wit/world.wit, engine/crates/wasi-component-loader/src/hooks/authorization.rs, engine/crates/wasi-component-loader/src/lib.rs, engine/crates/wasi-component-loader/src/tests.rs
Missed this in the first PR. The authorization hook needs to know the rule.
=> fix: rule parameter to the authorization hook

engine/crates/wasi-component-loader/gateway-hooks.wit
Adds a documented WIT file for guests to use.
=> feat: add an example wit definition for hooks

engine/crates/engine-v2/schema/src/builder/graph.rs, engine/crates/engine-v2/schema/src/builder/mod.rs, engine/crates/engine-v2/schema/src/directives/authorized.rs, engine/crates/engine-v2/schema/src/directives/mod.rs, engine/crates/engine-v2/schema/src/ids.rs, engine/crates/engine-v2/schema/src/input_value_set.rs, engine/crates/engine-v2/schema/src/lib.rs, engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/execution/context.rs, engine/crates/engine-v2/src/execution/hooks.rs, engine/crates/engine-v2/src/execution/mod.rs, engine/crates/engine-v2/src/operation/bind/mod.rs, engine/crates/engine-v2/src/operation/condition.rs, engine/crates/engine-v2/src/plan/mod.rs, engine/crates/engine-v2/src/plan/planning/collect.rs, engine/crates/engine-v2/src/response/error.rs, engine/crates/engine-v2/src/response/write/deserialize/mod.rs, engine/crates/graphql-mocks/src/secure.rs, engine/crates/integration-tests/src/federation/builder.rs, engine/crates/integration-tests/src/federation/mod.rs, engine/crates/integration-tests/tests/federation/auth/authorized/mod.rs, engine/crates/integration-tests/tests/federation/auth/authorized/rule.rs, engine/crates/integration-tests/tests/federation/auth/mod.rs, engine/crates/integration-tests/tests/federation/user_hooks.rs, engine/crates/runtime/src/hooks.rs
Adds the simplest possible `@authorized` support
=> feat(engine-v2): add simplest authorized support

engine/crates/runtime-local/src/hooks.rs, engine/crates/runtime-local/src/lib.rs, gateway/crates/federated-server/src/config.rs, gateway/crates/federated-server/src/server.rs, gateway/crates/federated-server/src/server/gateway.rs
Part of: https://github.com/grafbase/website/pull/2634
=> chore: rename wasi config section to hooks

engine/crates/composition/src/compose.rs, engine/crates/composition/src/compose/context.rs, engine/crates/composition/src/composition_ir.rs, engine/crates/composition/src/emit_federated_graph.rs, engine/crates/composition/tests/composition/authorized_basic/federated.graphql, engine/crates/composition/tests/composition/authorized_basic/subgraphs/bank_account.graphql, engine/crates/federated-graph/src/federated_graph/v3.rs, engine/crates/federated-graph/src/from_sdl.rs, engine/crates/federated-graph/src/render_sdl/display_utils.rs, engine/crates/federated-graph/src/render_sdl/render_federated_sdl.rs
=> composition: implement `@authorized` on objects

cli/crates/gateway/src/serving.rs
Prior to the partial caching defer work encoding streaming transports was done in the executor, with the executor just returning an HTTP response back to the gateway.  Since partial caching needs access to the responses, this is no longer the case.  Instead we need to encode the streaming transports at the http level.  This is arguably a more sensible approach anyway, that'll probably clean up some mess.
This PR takes care of doing that for the CLI, doing that in production will come later.
Fixes GB-6985
=> feat: impl streaming transports in cli gateway

engine/crates/federated-graph/src/from_sdl.rs
Was treated like an arbitrary directive
=> fix(federated-graph): Properly read @authorized from SDL

engine/crates/composition/src/emit_federated_graph/attach_argument_selection.rs, engine/crates/composition/src/ingest_subgraph/directives/authorized.rs, engine/crates/composition/tests/composition/authorized_basic/api.graphql, engine/crates/composition/tests/composition/authorized_basic/federated.graphql, engine/crates/composition/tests/composition/authorized_basic/subgraphs/bank_account.graphql, engine/crates/federated-graph/src/from_sdl.rs
=> composition: implement nested input selections in @authorized 

engine/crates/composition/src/validate.rs, engine/crates/composition/src/validate/selection.rs, engine/crates/composition/tests/composition/authorized_validation/federated.graphql, engine/crates/composition/tests/composition/authorized_validation/subgraphs/bank_account.graphql, engine/crates/federated-graph/src/from_sdl.rs
In addition, fix a test that is broken on main, probably because of a bad
rebase. We didn't handle `@authorized` on objects in from_sdl.
closes gb-6965
=> composition: implement validation of nested selection sets 

engine/crates/composition/src/emit_federated_graph.rs, engine/crates/composition/src/ingest_subgraph/directives/authorized.rs, engine/crates/composition/src/subgraphs/directives.rs, engine/crates/composition/tests/composition/authorized_basic/federated.graphql, engine/crates/engine-v2/schema/src/builder/graph.rs, engine/crates/engine-v2/schema/src/directives/authorized.rs, engine/crates/engine-v2/src/execution/hooks/authorized.rs, engine/crates/engine-v2/src/plan/planning/collect.rs, engine/crates/federated-graph/src/federated_graph/v3.rs, engine/crates/federated-graph/src/from_sdl.rs, engine/crates/federated-graph/src/render_sdl/display_utils.rs, engine/crates/integration-tests/src/federation/builder/hooks.rs, engine/crates/integration-tests/tests/federation/auth/authorized/arguments.rs, engine/crates/integration-tests/tests/federation/auth/authorized/rule.rs, engine/crates/runtime-local/src/hooks.rs, engine/crates/runtime-noop/src/hooks.rs, engine/crates/runtime/src/hooks.rs, engine/crates/wasi-component-loader/examples/crates/authorization/src/bindings.rs, engine/crates/wasi-component-loader/examples/crates/authorization/src/lib.rs, engine/crates/wasi-component-loader/examples/crates/authorization/wit/world.wit, engine/crates/wasi-component-loader/examples/crates/missing_hook/src/bindings.rs, engine/crates/wasi-component-loader/examples/crates/missing_hook/src/lib.rs, engine/crates/wasi-component-loader/examples/crates/missing_hook/wit/world.wit, engine/crates/wasi-component-loader/examples/wit/world.wit, engine/crates/wasi-component-loader/gateway-hooks.wit, engine/crates/wasi-component-loader/src/hooks/authorization.rs, engine/crates/wasi-component-loader/src/lib.rs, engine/crates/wasi-component-loader/src/tests.rs
For the demo. These hooks will change more next week...
=> fix: remove rule from @authorized

engine/crates/engine-v2/src/execution/coordinator.rs, engine/crates/engine-v2/src/plan/planning/collect.rs
I was still requesting them and reading from the JSON response
=> fix(engine-v2): Incorrect handling of field errors

cli/crates/server/src/bun.rs
=> Update Bun to 1.1.17

engine/crates/composition/tests/composition/authorized_basic/subgraphs/bank_account.graphql, engine/crates/composition/tests/composition/authorized_validation/subgraphs/bank_account.graphql
=> composition: finish removal of rule argument on authorized

engine/crates/engine-v2/schema/src/builder/coerce/mod.rs, engine/crates/engine-v2/schema/src/builder/graph.rs, engine/crates/engine-v2/schema/src/builder/input_values.rs, engine/crates/engine-v2/schema/src/builder/mod.rs, engine/crates/engine-v2/schema/src/directives/authorized.rs, engine/crates/engine-v2/schema/src/input_value/mod.rs, engine/crates/engine-v2/schema/src/walkers/definition.rs, engine/crates/engine-v2/schema/src/walkers/entity.rs, engine/crates/engine-v2/src/execution/hooks/authorized.rs, engine/crates/engine-v2/src/operation/bind/mod.rs, engine/crates/engine-v2/src/operation/condition.rs, engine/crates/engine-v2/src/plan/planning/collect.rs, engine/crates/federated-graph/src/from_sdl.rs, engine/crates/graphql-mocks/src/secure.rs, engine/crates/integration-tests/src/federation/builder.rs, engine/crates/integration-tests/tests/federation/hooks/authorize_node_pre_execution.rs, engine/crates/integration-tests/tests/federation/hooks/mod.rs, engine/crates/runtime-local/src/hooks.rs, engine/crates/runtime-noop/src/hooks.rs, engine/crates/runtime/src/hooks.rs, engine/crates/runtime/src/hooks/test_utils.rs
Add support for `authorize_node_pre_exeuction` hook in engine & add more tests
=> feat(engine-v2): Add support for authorize_node_pre_execution

gateway/crates/federated-server/src/server.rs, gateway/crates/gateway-binary/src/main.rs
=> move some logs to debug

Cargo.lock, examples/gateway-hooks/README.md, examples/gateway-hooks/flake.nix, gateway/CHANGELOG.md, gateway/changelog/0.4.1.md, gateway/crates/federated-server/Cargo.toml, gateway/crates/gateway-binary/Cargo.toml
- Add back operation caching (#1854)
- Update wasmtime crates to 22.0.0 (#1840)
- Disable wasm native unwind info (#1858)
- Move some logs to debug (#1860)
=> Gateway 0.4.1

examples/gateway-hooks/flake.lock, examples/gateway-hooks/flake.nix
=> fix: gateway hooks example nix to use a version that has working cache

Cargo.lock, engine/crates/runtime-local/src/hooks.rs, engine/crates/runtime/src/hooks.rs, engine/crates/runtime/src/hooks/test_utils.rs, engine/crates/wasi-component-loader/Cargo.toml, engine/crates/wasi-component-loader/examples/Cargo.lock, engine/crates/wasi-component-loader/examples/crates/authorization/Cargo.toml, engine/crates/wasi-component-loader/examples/crates/authorization/src/bindings.rs, engine/crates/wasi-component-loader/examples/crates/authorization/src/lib.rs, engine/crates/wasi-component-loader/examples/crates/authorization/wit/world.wit, engine/crates/wasi-component-loader/examples/crates/missing_hook/src/bindings.rs, engine/crates/wasi-component-loader/examples/crates/missing_hook/src/lib.rs, engine/crates/wasi-component-loader/examples/crates/missing_hook/wit/world.wit, engine/crates/wasi-component-loader/examples/wit/world.wit, engine/crates/wasi-component-loader/gateway-hooks.wit, engine/crates/wasi-component-loader/src/hooks/authorization.rs, engine/crates/wasi-component-loader/src/names.rs, engine/crates/wasi-component-loader/src/tests.rs
=> feat(wasi): authorize post exec hooks

gateway/crates/federated-server/src/server/graph_updater.rs
Not great, but should be a bit better.
=> fix(gateway): Unclear error when retrieving federated SDL for managed graph

gateway/crates/federated-server/src/config.rs, gateway/crates/federated-server/src/config/health.rs, gateway/crates/federated-server/src/server.rs, gateway/crates/federated-server/src/server/health.rs, gateway/crates/gateway-binary/tests/integration_tests.rs
Please react if you see additional health checks we could do in the handler.
closes GB-7048
=> Add health checks to self-hosted federated gateway

engine/crates/engine-v2/src/lib.rs, engine/crates/engine-v2/src/operation/bind/field.rs, engine/crates/engine-v2/src/operation/bind/mod.rs, engine/crates/engine-v2/src/operation/build.rs, engine/crates/engine-v2/src/operation/ids.rs, engine/crates/engine-v2/src/operation/logical_planner/logic.rs, engine/crates/engine-v2/src/operation/logical_planner/mod.rs, engine/crates/engine-v2/src/operation/logical_planner/selection_set.rs, engine/crates/engine-v2/src/operation/mod.rs, engine/crates/engine-v2/src/operation/walkers/field.rs, engine/crates/engine-v2/src/plan/mod.rs, engine/crates/engine-v2/src/plan/planning/collect.rs, engine/crates/engine-v2/src/plan/planning/mod.rs, engine/crates/engine-v2/src/plan/walkers/field.rs, engine/crates/integration-tests/tests/federation/basic/errors.rs
Somehow didn't got merged: https://github.com/grafbase/grafbase/pull/1869
=> Gb 7058 rename planner to operation solver

packages/grafbase-sdk/src/experimental.ts, packages/grafbase-sdk/tests/unit/experimental.test.ts
=> feat: add experimental partial caching to sdk

engine/crates/engine-v2/schema/src/builder/interner.rs, engine/crates/engine-v2/schema/src/builder/interner/non_ord.rs, engine/crates/engine-v2/schema/src/builder/mod.rs, engine/crates/engine-v2/schema/src/input_value/tests.rs, engine/crates/engine-v2/schema/src/sources/introspection.rs
=> chore(engine-v2): Minor interner improvements

flake.nix
=> chore(nix): gdb only for linux

auth-testing/README.md
=> various auth testing data

engine/crates/wasi-component-loader/README.md, engine/crates/wasi-component-loader/src/hooks.rs, examples/gateway-hooks/README.md
WebAssembly is abbreviated Wasm per https://webassembly.org
=> Wasm casing

engine/crates/wasi-component-loader/examples/wit/world.wit, examples/gateway-hooks/demo-hooks/src/bindings.rs, examples/gateway-hooks/demo-hooks/src/lib.rs, examples/gateway-hooks/demo-hooks/wit/world.wit
=> doc: update hook example

Cargo.lock, gateway/CHANGELOG.md, gateway/changelog/0.6.0.md, gateway/crates/federated-server/Cargo.toml, gateway/crates/gateway-binary/Cargo.toml
=> chore(gateway): bump to 0.6.0

engine/crates/integration-tests/tests/federation/basic/headers.rs, examples/gateway-hooks/grafbase.toml, flake.lock
- Adds a test which shows forward does renaming correctly and moves the header, does not copy
- Clean the hooks example a bit
=> chore: add a test, clean-up the hooks example

engine/crates/engine-v2/src/execution/header_rule.rs, engine/crates/integration-tests/tests/federation/basic/headers.rs
A test case:
```toml
[[headers]]
rule = "forward"
pattern = "^.*$"
[[headers]]
rule = "remove"
pattern = "^x-amzn-mtls-.*"
[[headers]]
rule = "forward"
name = "x-client-auth-ctx"
rename = "x-graph-client-auth-ctx"
```
This would first forward all headers, then forward again `x-client-auth-ctx` with a new name. Not good.
What we do here is that for every forward rule, we _first_ remove the header from the header map and right after that we add the forwarded header.
=> fix(engine-v2): forward header rule should not duplicate

engine/crates/engine-v2/src/engine.rs
The recent addition of timeouts set a timeout of u32::MAX for streaming requests.  I assume this works fine on native, but on [wasm it gets cast to an i32][1], so it ends up negative and we instantly timeout.  Better to just not timeout at all when we get a streaming request.
This is causing e2e failures in the api repo - _hopefully_ this is the last thing that needs fixed before we can finish pulling in the latest grafbase over there.
[1]: https://github.com/rustwasm/gloo/blob/master/crates/timers/src/callback.rs#L66
=> fix: dont set timeout to u32::MAX for streaming requests

engine/crates/engine-v2/src/engine.rs
=> chore(engine-v2): Use INFO for requests with GraphQL errors instead of ERROR

cli/crates/server/src/bun.rs
=> Bun 1.1.21

cli/crates/server/src/bun.rs
Reverts grafbase/grafbase#1946
=> Revert "Bun 1.1.21"

Cargo.lock, gateway/changelog/0.7.0.md, gateway/crates/federated-server/Cargo.toml, gateway/crates/gateway-binary/Cargo.toml
=> gateway release 0.7.0

examples/gateway-hooks/flake.lock, examples/gateway-hooks/flake.nix
=> chore(examples): update nix with latest gateway for hook example

engine/crates/engine-v2/src/sources/graphql/mod.rs, engine/crates/graphql-mocks/src/error_schema.rs, engine/crates/integration-tests/tests/federation/entity_caching.rs
=> fix: dont cache subgraph responses that error

Cargo.lock, Cargo.toml, engine/crates/telemetry/Cargo.toml
A partial import of the updates from https://github.com/grafbase/grafbase/pull/1796 to help it move forward.
=> chore(deps): A partial dependency update

engine/crates/engine-v2/Cargo.toml
=> chore: Add missing "raw_value" feature flag

gateway/crates/gateway-binary/tests/telemetry/metrics/operation.rs
=> chore: fix snapshot

engine/crates/engine-v2/src/operation/metrics.rs, engine/crates/engine/response/src/lib.rs, engine/crates/engine/src/schema.rs, engine/crates/gateway-core/src/cache/partial.rs, engine/crates/gateway-core/src/lib.rs
=> chore: best effort expose used fields for v1

Cargo.lock
=> chore(deps): Another bump of dependencies

gateway/changelog/0.9.0.md
=> doc: update gateway changelog

Cargo.lock, Cargo.toml, engine/crates/telemetry/src/otel/layer.rs, engine/crates/telemetry/src/otel/logs.rs, engine/crates/telemetry/src/otel/traces.rs, gateway/crates/gateway-binary/Cargo.toml, gateway/crates/gateway-binary/src/main.rs
This reverts commit 06653d4b652069c25de8149b1052db127067388d.
=> Revert "chore: switch to mainline otel"

cli/crates/backend/src/api/errors.rs, cli/crates/cli/src/cli_input/sub_command.rs
=> Replace a few occurrences of project by graph in CLI output

cli/crates/backend/src/api/branch.rs, cli/crates/backend/src/api/environment_variables/list.rs, cli/crates/backend/src/api/errors.rs, cli/crates/backend/src/api/graphql/api.graphql, cli/crates/backend/src/api/graphql/types/mutations.rs, cli/crates/backend/src/api/logs.rs, cli/crates/cli/src/branch.rs, cli/crates/cli/src/cli_input/branch.rs, cli/crates/cli/src/logs.rs, cli/crates/cli/src/main.rs, cli/crates/cli/src/output/report.rs
New command to create a branch on a self-hosted graphs.
```
$ gb branch create --help
Create a branch on the linked graph (self-hosted graphs only)
Usage: grafbase branch create <BRANCH_REF>
Arguments:
<BRANCH_REF>  Branch reference following the format "account/project@branch"
Options:
-h, --help  Print help
```
closes GB-7252
=> cli: implement gb branch create

cli/crates/cli/src/branch.rs, cli/crates/cli/src/cli_input/branch_ref.rs
=> cli: rename project to graph in BranchRef

examples/gateway-hooks/README.md
=> examples: typo

Cargo.lock, gateway/CHANGELOG.md, gateway/changelog/0.9.0.md, gateway/crates/federated-server/Cargo.toml, gateway/crates/gateway-binary/Cargo.toml
=> chore: bump gateway to 0.9.0

engine/crates/engine-config-builder/src/from_sdl_config.rs, engine/crates/engine-config-builder/src/from_toml_config.rs, engine/crates/engine-v2/config/src/lib.rs, engine/crates/engine-v2/config/src/v2/mod.rs, engine/crates/engine-v2/config/src/v5.rs, engine/crates/engine-v2/schema/src/builder/mod.rs, engine/crates/engine-v2/schema/src/lib.rs, engine/crates/engine-v2/schema/src/sources/graphql.rs, engine/crates/engine-v2/schema/src/walkers/mod.rs, engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/engine/retry_budget.rs, engine/crates/engine-v2/src/sources/graphql/request/execute.rs, engine/crates/engine-v2/src/sources/graphql/request/execute/record.rs, engine/crates/engine/src/schema.rs, engine/crates/gateway-core/src/lib.rs, engine/crates/parser-sdl/src/federation.rs, engine/crates/parser-sdl/src/rules/all_subgraphs_directive.rs, engine/crates/parser-sdl/src/rules/subgraph_directive.rs, engine/crates/telemetry/src/metrics/operation.rs, gateway/crates/gateway-binary/tests/telemetry/metrics.rs, gateway/crates/gateway-binary/tests/telemetry/metrics/operation.rs, gateway/crates/gateway-binary/tests/telemetry/metrics/operation/subgraph.rs
Implements subgraph request related metrics:
- latencies
- retries
- request body size
- response body size
- inflight requests
=> feat: subgraph metrics

cli/Dockerfile, gateway/Dockerfile
=> bump build images

engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/graphql_over_http/response.rs, engine/crates/engine-v2/src/response/error.rs, engine/crates/runtime-local/src/rate_limiting/redis.rs, engine/crates/telemetry/src/metrics/operation.rs, gateway/crates/federated-server/src/server/gateway.rs, gateway/crates/federated-server/src/server/graph_updater.rs, gateway/crates/gateway-binary/tests/integration_tests.rs, gateway/crates/gateway-binary/tests/telemetry/logs.rs, gateway/crates/gateway-binary/tests/telemetry/metrics.rs, gateway/crates/gateway-binary/tests/telemetry/metrics/gdn.rs, gateway/crates/gateway-binary/tests/telemetry/metrics/operation.rs, gateway/crates/gateway-binary/tests/telemetry/mod.rs
=> feat: various metrics (part 2)

engine/crates/telemetry/src/metrics/operation.rs, engine/crates/telemetry/src/metrics/request.rs, gateway/crates/gateway-binary/tests/telemetry/metrics/request.rs
=> fix: status.code -> status_code

cli/crates/cli/src/cli_input/project_ref.rs, gateway/crates/gateway-binary/src/args/std.rs, graph-ref/src/lib.rs
Getting the branch_id will be done in the telemetry sink now
=> chore(gateway): Send graph ref in to the telemetry-sink

engine/crates/engine-v2/schema/src/builder/graph.rs, engine/crates/graphql-mocks/src/fake_github.rs, engine/crates/integration-tests/tests/federation/introspection.rs, engine/crates/integration-tests/tests/federation/snapshots/integration_tests__federation__introspection__introspecting_with_grafbase_openapi_subgraph.snap, engine/crates/integration-tests/tests/federation/snapshots/integration_tests__federation__introspection__raw_introspetion_output.snap, engine/crates/integration-tests/tests/graphql_connector/transforms.rs
For output field argument defaults and input value field defaults.
=> engine-v2: ensure defaults are part of introspection

cli/crates/cli/src/cli_input/create.rs, cli/crates/cli/src/cli_input/sub_command.rs
When --mode=self-hosted, no grafbase configuration is required anymore
=> cli: make ts config optional for gb create --mode=self-hosted

engine/crates/engine-v2/src/engine.rs, engine/crates/engine-v2/src/engine/execute.rs, engine/crates/engine-v2/src/engine/execute/prepare.rs, engine/crates/engine-v2/src/engine/execute/single.rs, engine/crates/engine-v2/src/engine/execute/stream.rs, engine/crates/engine-v2/src/graphql_over_http/response.rs, engine/crates/engine-v2/src/response/mod.rs, engine/crates/engine-v2/src/sources/graphql/record.rs, engine/crates/engine/src/schema.rs, engine/crates/gateway-core/src/lib.rs, engine/crates/telemetry/src/metrics/operation.rs
The file was getting increasingly big so split it up into separate
modules for clarity.
=> chore(engine-v2): split engine.rs

gateway/CHANGELOG.md, gateway/changelog/0.11.1.md
The actual release will take place in a patch release branch, but the changelog should be on main.
=> gateway: release 0.11.1

engine/crates/graphql-schema-diff/CHANGELOG.md, engine/crates/graphql-schema-diff/src/change.rs
I am going to need that in the API, we're going to store change kinds in postgres.
=> graphql-schema-diff: implement to_str() and FromStr for ChangeKind

Cargo.lock, engine/crates/wasi-component-loader/Cargo.toml, engine/crates/wasi-component-loader/src/hooks.rs, engine/crates/wasi-component-loader/src/lib.rs
=> fix: back to mainline wasmtime

.github/workflows/rust-prs.yml, gateway/crates/federated-server/src/server/access_logs.rs
this was not catched by the pr workflow, but broke the release :(
=> chore: fix an unused import that was not catched by CI

Cargo.lock, engine/crates/engine-v2/Cargo.toml, engine/crates/engine-v2/axum/src/middleware/telemetry.rs, engine/crates/engine-v2/src/engine/execute.rs, engine/crates/engine-v2/src/engine/execute/single.rs, engine/crates/engine-v2/src/engine/execute/stream.rs, engine/crates/engine-v2/src/graphql_over_http/mod.rs, engine/crates/engine-v2/src/graphql_over_http/response.rs, engine/crates/engine-v2/src/lib.rs, engine/crates/engine-v2/src/response/error.rs, engine/crates/engine-v2/src/response/error/code.rs, engine/crates/engine-v2/src/response/mod.rs, engine/crates/engine-v2/src/response/write/mod.rs, engine/crates/engine-v2/src/sources/graphql/request/execute.rs, engine/crates/engine/src/schema.rs, engine/crates/gateway-core/src/lib.rs, engine/crates/telemetry/src/graphql.rs, engine/crates/telemetry/src/span/graphql.rs, engine/crates/telemetry/src/span/http_request.rs, flake.lock
=> feat(telemetry): Add error count by code

.github/workflows/binaries.yml
Fixes the `windows` job in CI of the main branch.
=> Install Nasm in the `windows` job

flake.nix
=> chore(nix): use Node22 for gateway audit

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.27.2.md, packages/grafbase-sdk/package.json
=> Deprecate sdk

packages/grafbase-sdk/CHANGELOG.md, packages/grafbase-sdk/changelog/0.27.3.md, packages/grafbase-sdk/changelog/0.27.4.md, packages/grafbase-sdk/package.json
- Fix the deprecated SDK version
=> Fix deprecated SDK

gateway/crates/gateway-binary/src/args/std.rs
A customer was trying to create their own docker image for running `grafbase-gateway` last week, but they were running into some confusing 401s.  
This turned out to be because they were using our base image, which sets the docker entrypoint to `grafbase-gateway`, but also providing `grafbase-gateway` in the `CMD`.  Essentially running `grafbase-gateway grafbase-gateway ...`.  Normally I'd expect this to complain about a bad CLI argument, but the gateway is set up to accept `GRAFBASE_ACCESS_TOKEN` as a positional argument, so the second `grafbase-gateway` was being taken as the token, and they were getting a 401.
This was quite confusing, and it's not really best practice to accept a token as a CLI argument either for security purposes.  So, this PR switches it to _just_ rely on the …
=> fix: remove gateway access token cli arg

engine/crates/composition/CHANGELOG.md, engine/crates/composition/src/emit_federated_graph/context.rs, engine/crates/composition/src/ingest_subgraph.rs, engine/crates/composition/src/lib.rs, engine/crates/composition/src/subgraphs/directives.rs, engine/crates/composition/tests/composition/null_value/federated.graphql, engine/crates/composition/tests/composition/null_value/subgraphs/filter.graphql
Until this commit, it would cause a panic.
=> composition: fix the ingestion of `null` literals

engine/crates/engine-v2/src/operation/bind/variables.rs
So:
```
query ($bool: Boolean = false)
```
the `$bool` variable is considered to be required.
=> fix(engine-v2): an input variable is considered required if it has non-null default value

Cargo.lock, gateway/CHANGELOG.md, gateway/changelog/0.14.0.md, gateway/crates/config/Cargo.toml, gateway/crates/federated-server/Cargo.toml, gateway/crates/gateway-binary/Cargo.toml, gateway/crates/rolling-logger/Cargo.toml
=> chore: bump gateway to 0.14.0

Cargo.lock, engine/crates/wasi-component-loader/Cargo.toml, engine/crates/wasi-component-loader/src/headers.rs, engine/crates/wasi-component-loader/src/hooks/response.rs, workspace-hack/Cargo.toml
=> chore: update to wasmtime 25

Cargo.lock, workspace-hack/Cargo.toml
Doing a better job than a VC startup on updating our deps.
=> chore: cargo update

engine/crates/engine-v2/src/execution/coordinator.rs, engine/crates/runtime-local/src/hooks.rs, engine/crates/runtime-local/src/hooks/authorized.rs, engine/crates/runtime-local/src/hooks/pool.rs, engine/crates/runtime-local/src/hooks/responses.rs, engine/crates/runtime-local/src/hooks/subgraph.rs, engine/crates/wasi-component-loader/src/hooks.rs, engine/crates/wasi-component-loader/src/hooks/gateway.rs, engine/crates/wasi-component-loader/src/hooks/subgraph.rs, engine/crates/wasi-component-loader/src/lib.rs
=> fix(tracing): track pool get and instance calls as subspans for hook span

engine/crates/composition/src/compose/interface.rs, engine/crates/composition/tests/composition/interfaces_single_subgraph/api.graphql, engine/crates/composition/tests/composition/interfaces_single_subgraph/federated.graphql, engine/crates/composition/tests/composition/interfaces_single_subgraph/subgraphs/main.graphql
We weren't doing this already apparently.
=> fix: compose interface arguments

.github/workflows/binaries.yml
- Remove a remaining reference to the local server
=> Remove a remaining reference to the local server

engine/crates/engine-config-builder/src/from_sdl_config.rs, engine/crates/engine-config-builder/src/from_toml_config.rs, engine/crates/engine-v2/config/src/v2/mod.rs, engine/crates/engine-v2/schema/src/builder/external_sources.rs, engine/crates/integration-tests/tests/federation/config.rs, engine/crates/integration-tests/tests/federation/mod.rs, engine/crates/parser-sdl/src/federation.rs, engine/crates/parser-sdl/src/rules/all_subgraphs_directive.rs, engine/crates/parser-sdl/src/rules/subgraph_directive.rs, gateway/changelog/0.16.0.md, gateway/crates/config/src/lib.rs
=> feat(gateway/config): Allow overriding subgraph URL in TOML config

cli/crates/cli/src/panic_hook/mod.rs
Something didn't show up in PR build, but did show up in main build.
=> fix: build

engine/crates/gateway-v2/auth/src/lib.rs
An empty 0ms span is just no no.
=> fix: no span for authenticate if there's no authorizers

engine/crates/engine-v2/src/sources/graphql/request/execute.rs
I've been using traces to investigate an issue today, and had enabled propagation to see whether it was us or subgraphs that were slow.  But in my tracing view the subgraph HTTP span was marked as a sibling of  our corresponding HTTP span rather than as a child.
This fixes that by propagating the http span to children rather than just using the current span.
Before:
After:
=> fix: propagate the correct span to subgraphs

Cargo.lock, engine/crates/engine-v2/Cargo.toml, engine/crates/engine-v2/src/engine/execute/prepare.rs, engine/crates/engine-v2/src/execution/context.rs, engine/crates/engine-v2/src/execution/planner/mod.rs, engine/crates/engine-v2/src/sources/graphql/federation.rs, engine/crates/engine-v2/src/sources/graphql/root_fields.rs
Wasn't the issue and it adds +30% CPU usage
=> chore(engine): remove spawn blocking

Cargo.lock, engine/crates/engine-v2/codegen/src/loader.rs, engine/crates/partial-caching/src/planning/visitor.rs
So we need this to get API compiling...
=> fix: update to the latest cynic-parser

.dockerignore, .prettierrc.js, .prettierrc.json
=> convert to prettier JSON config

cli/crates/backend/src/api/client.rs
This would be... well would be nice :)
=> chore: add client name and version to api calls from CLI

Cargo.lock, Cargo.toml, cli/CHANGELOG.md, cli/changelog/0.80.1.md, cli/crates/backend/Cargo.toml, cli/crates/cli/Cargo.toml, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json, engine/crates/runtime-local/Cargo.toml, nix/cli-app.nix
Let's get those stats to the dashboard from CLI.
=> chore: bump CLI to 0.80.1

engine/crates/graphql-schema-diff/src/change.rs
=> graphql-schema-diff: add ChangeKind::{Add,Remove}SchemaExtension to FromStr

.github/workflows/rust-prs.yml, gateway/about.toml
This is annoying when it happens only on release.
=> chore: check licenses for every PR

.github/what-rust-changed.toml, gateway/helm/.helmignore, gateway/helm/Chart.yaml, gateway/helm/README.md, gateway/helm/templates/_helpers.tpl, gateway/helm/templates/configmap.yaml, gateway/helm/templates/deployment.yaml, gateway/helm/templates/hpa.yaml, gateway/helm/templates/ingress.yaml, gateway/helm/templates/secrets.yaml, gateway/helm/templates/service.yaml, gateway/helm/templates/serviceaccount.yaml, gateway/helm/values.yaml
=> chore: add gateway helm chart

.github/workflows/sast.yml
=> feat(gateway): Sasts Testing GB-7801

engine/crates/graphql-mocks/src/lib.rs, engine/crates/integration-tests/tests/federation/message_signing.rs, engine/crates/runtime-local/src/fetch/signing.rs
This adds support for signing all the relevant derived components when message singing is enabled.  The implementation of this was trivial, but testing was a bit painful - axum really didn't want to give us the full URL, which made any of the components that require it fail.
Signature parameters will come in the next PR.
Part of GB-7858
=> feat: derived components in message signing

cli/crates/common/src/consts.rs
- Fixes the CLI default API URL
=> Fix the API URL

engine/crates/integration-tests/tests/federation/message_signing.rs
While writing the documentation I realised I hadn't tested these two options
=> test: nonce & expiry in message signatures

engine/crates/engine-v2/codegen/domain/operation_plan.graphql, engine/crates/engine-v2/codegen/domain/schema.graphql, engine/crates/engine-v2/schema/src/builder/graph.rs, engine/crates/engine-v2/schema/src/builder/requires.rs, engine/crates/engine-v2/schema/src/definition.rs, engine/crates/engine-v2/schema/src/generated/field_set.rs, engine/crates/engine-v2/schema/src/input_value/set.rs, engine/crates/engine-v2/src/plan/builder/mod.rs, engine/crates/engine-v2/src/plan/builder/shapes.rs, engine/crates/engine-v2/src/plan/execution/builder/mod.rs, engine/crates/engine-v2/src/plan/execution/mod.rs, engine/crates/engine-v2/src/plan/execution/model/field.rs, engine/crates/engine-v2/src/plan/execution/model/field/data.rs, engine/crates/engine-v2/src/plan/execution/model/field/typename.rs, engine/crates/engine-v2/src/plan/execution/model/mod.rs, engine/crates/engine-v2/src/plan/execution/model/plan.rs, engine/crates/engine-v2/src/plan/execution/model/selection_set.rs, engine/crates/engine-v2/src/plan/execution/modifier/query.rs, engine/crates/engine-v2/src/plan/mod.rs, engine/crates/engine-v2/src/plan/model/field.rs, engine/crates/engine-v2/src/plan/model/generated/field.rs, engine/crates/engine-v2/src/plan/model/generated/field/data.rs, engine/crates/engine-v2/src/plan/model/generated/field/typename.rs, engine/crates/engine-v2/src/plan/model/generated/modifier.rs, engine/crates/engine-v2/src/plan/model/generated/plan.rs, engine/crates/engine-v2/src/plan/model/generated/selection_set.rs, engine/crates/engine-v2/src/plan/model/mod.rs
One of the last commits I can do without breaking everything. Partially creating plans and their dependencies.
=> chore(engine-v2): Partially create execution plans

engine/crates/engine-v2/src/response/value.rs, engine/crates/engine-v2/src/response/write/mod.rs
Merge responses from subgraphs recursively.
=> chore(engine-v2): recursive response merging

engine/crates/engine-v2/codegen/domain/schema.graphql, engine/crates/engine-v2/schema/src/builder/requires.rs, engine/crates/engine-v2/schema/src/field_set/requires.rs, engine/crates/engine-v2/schema/src/generated/field_set.rs, engine/crates/engine-v2/src/execution/coordinator.rs, engine/crates/engine-v2/src/execution/hooks/authorized.rs, engine/crates/engine-v2/src/execution/planner/builder.rs, engine/crates/engine-v2/src/execution/response_modifier.rs, engine/crates/engine-v2/src/operation/logical_planner/selection_set.rs, engine/crates/engine-v2/src/resolver/graphql/federation.rs, engine/crates/engine-v2/src/resolver/mod.rs, engine/crates/engine-v2/src/response/read/mod.rs, engine/crates/engine-v2/src/response/read/old_view/de.rs, engine/crates/engine-v2/src/response/read/old_view/mod.rs, engine/crates/engine-v2/src/response/read/old_view/ser.rs, engine/crates/engine-v2/src/response/read/view/ser.rs
Adjust response view to use the required field set from the schema instead of a custom struct.
=> chore(engine-v2): adjust response view

engine/crates/composition/src/compose/directives.rs, engine/crates/composition/src/composition_ir/directive.rs, engine/crates/composition/src/emit_federated_graph.rs, engine/crates/composition/src/ingest_subgraph/directives.rs, engine/crates/composition/src/ingest_subgraph/directives/consts.rs, engine/crates/composition/src/subgraphs/directives.rs, engine/crates/composition/tests/composition/cost_basic/api.graphql, engine/crates/composition/tests/composition/cost_basic/federated.graphql, engine/crates/composition/tests/composition/cost_basic/subgraphs/a.graphql, engine/crates/engine-v2/schema/src/builder/graph.rs, engine/crates/federated-graph/src/federated_graph/v4.rs, engine/crates/federated-graph/src/from_sdl.rs, engine/crates/federated-graph/src/render_sdl/display_utils.rs, engine/crates/federated-graph/src/render_sdl/render_api_sdl.rs, engine/crates/federated-graph/src/render_sdl/render_federated_sdl.rs
This adds support for the `@cost` demand control directive to composition.  This doesn't actually do anything yet, it just makes sure we validate it during ingestion & output it into the composed SDL.
Part of GB-7642
=> feat: handle cost directive in composition

Cargo.lock, Cargo.toml, engine/crates/federated-graph/src/from_sdl.rs, engine/crates/federated-graph/src/from_sdl/value.rs, engine/crates/graphql-schema-diff/src/state.rs, workspace-hack/Cargo.toml
I want to use some changes I've made, but figured it'd be clearer to do this in a separate commit.
=> chore: update to latest cynic-parser

cli/about.toml
=> Fix ring license detection

gateway/crates/gateway-binary/src/args/log.rs, gateway/crates/gateway-binary/src/args/std.rs
=> chore: use text log style by default in terminal unless debug/trace

.github/CODEOWNERS
=> Update CODEOWNERS to match new repo structure

Cargo.lock, crates/engine-config-builder/Cargo.toml, crates/engine-config-builder/src/from_toml_config.rs, crates/engine-v2/config/src/complexity_control.rs, crates/engine-v2/config/src/lib.rs, crates/engine-v2/schema/src/builder/mod.rs, crates/engine-v2/schema/src/lib.rs, crates/gateway-config/src/complexity_control.rs, crates/gateway-config/src/lib.rs
=> feat: complexity control config

crates/engine/codegen/domain/schema.graphql, crates/engine/codegen/src/domain/record.rs, crates/engine/codegen/src/generation/object/debug.rs, crates/engine/codegen/src/generation/object/struct_.rs, crates/engine/codegen/src/generation/object/walker.rs, crates/engine/codegen/src/loader.rs, crates/engine/schema/src/builder/graph.rs, crates/engine/schema/src/field.rs, crates/engine/schema/src/generated/composite_type.rs, crates/engine/schema/src/generated/definition.rs, crates/engine/schema/src/generated/directive.rs, crates/engine/schema/src/generated/directive/complexity_control.rs, crates/engine/schema/src/generated/entity.rs, crates/engine/schema/src/generated/enum_def.rs, crates/engine/schema/src/generated/field.rs, crates/engine/schema/src/generated/field_set/field.rs, crates/engine/schema/src/generated/header_rule.rs, crates/engine/schema/src/generated/input_object.rs, crates/engine/schema/src/generated/interface.rs, crates/engine/schema/src/generated/object.rs, crates/engine/schema/src/generated/resolver.rs, crates/engine/schema/src/lib.rs, crates/engine/src/operation/solve/model/generated/field/data.rs, crates/engine/src/operation/solve/model/generated/modifier.rs, crates/engine/src/operation/solve/model/generated/query_partition.rs, crates/engine/src/operation/solve/model/generated/selection_set.rs
As the title says.  Had to rework some codegen stuff so it could handle these.
Part of GB-7643
=> chore: pull complexity control into engine schema

crates/integration-tests/tests/federation/basic/headers.rs
These are engine-v2 tests, they should have been ported. (deleted in https://github.com/grafbase/grafbase/pull/2299)
=> Port header tests deleted along with engine v1

crates/engine/src/response/extensions.rs, crates/integration-tests/tests/federation/extensions.rs, gateway/tests/telemetry/tracing.rs
Renaming keys a bit to feel more like GraphQL. To be merged a bit later.
=> fix(engine): response extension renames

Cargo.lock, crates/grafbase-workspace-hack/Cargo.toml, crates/integration-tests/Cargo.toml
Noticed a few things we weren't using anymore
=> chore: clean up integration-tests dependencies a bit

Cargo.lock, crates/engine/src/prepare/error.rs, crates/integration-tests/tests/federation/complexity_control.rs, crates/integration-tests/tests/federation/mod.rs
=> fix: reinstate the complexity control tests

crates/graphql-mocks/src/dynamic/builder.rs, crates/graphql-mocks/src/dynamic/entity_resolvers.rs, crates/graphql-mocks/src/dynamic/mod.rs, crates/graphql-mocks/src/lib.rs, crates/integration-tests/tests/federation/subgraphs/requires.rs
I kinda had something like this in mind when I was writing the dynamic mocks, but I didn't need them so didn't want to spend the time.
Since #2427 has started using entity resolvers now seems as good a time as any to revisit.
=> feat: simpler entity resolvers in dynamic mocks

cli/src/check.rs, cli/src/output/report.rs, crates/grafbase-local-backend/src/api/graphql/api.graphql, crates/grafbase-local-backend/src/api/graphql/types/mutations.rs
=> cli: handle proposal check errors

crates/graphql-schema-diff/tests/patch_tests.rs
somehow slipped through rust-prs.
https://github.com/grafbase/grafbase/actions/runs/12348876352/job/34458583910
=> fix: unnecessary format!

gateway/src/args/std.rs
Needs to be worked out on API too.
=> chore: rename __GRAFBASE_OTEL_URL env var to GRAFBASE_OTEL_URL

Cargo.toml, crates/graphql-composition/Cargo.toml
=> graphql-composition: add explicit report feature to cynic-parser

crates/federated-server/src/server/gateway/gateway_runtime.rs, crates/gateway-config/src/operation_caching.rs, crates/runtime-local/src/lib.rs, crates/runtime-local/src/operation_cache.rs, crates/runtime-local/src/operation_cache/in_memory.rs, crates/runtime-local/src/operation_cache/redis.rs, crates/runtime-local/src/operation_cache/tiered.rs
=> feat: redis operation caching

Cargo.lock, gateway/Cargo.toml, gateway/changelog/0.25.0.md
=> release 0.25.0

crates/grafbase-sdk/README.md
This is preliminary README how things should work. I'm publishing the sdk to crates.io next, so we need some README...
=> feat: grafbase-sdk README

Cargo.lock, crates/engine/Cargo.toml, crates/engine/src/engine/runtime.rs, crates/federated-server/src/server/gateway/gateway_runtime.rs, crates/integration-tests/Cargo.toml, crates/integration-tests/src/federation/builder.rs, crates/integration-tests/src/federation/mod.rs, crates/integration-tests/src/federation/runtime/extension.rs, crates/integration-tests/src/federation/runtime/mod.rs, crates/runtime/src/extension/mod.rs, crates/runtime/src/extension/runtime.rs
Basic test extension implementation
=> chore(extension): initial version of the test extensions

crates/graphql-federated-graph/src/directives/extension.rs, crates/graphql-federated-graph/src/federated_graph.rs, crates/graphql-federated-graph/src/from_sdl.rs, crates/graphql-federated-graph/src/from_sdl/directive.rs
Missed schema directives and wasn't parsing in the right format before.
=> feat(extension): Adding missing federated graph directive support

gateway/helm/values.yaml
make resources defaults smaller
=> make resources defaults smaller

cli/src/extension/build.rs, cli/src/output/report.rs, cli/tests/extension/mod.rs, crates/engine/schema/src/builder/graph.rs, crates/extension-catalog/src/catalog.rs, crates/extension-catalog/src/load.rs, crates/extension/src/id.rs, crates/extension/src/manifest/v1.rs, crates/federated-server/src/server/gateway.rs, crates/graphql-federated-graph/src/federated_graph.rs, crates/graphql-federated-graph/src/from_sdl.rs, crates/integration-tests/src/federation/runtime/extension.rs, crates/integration-tests/tests/federation/extensions/mod.rs
Was a mistake, too complex and useless.
=> chore(extension): Remove origin from extension::Id

Cargo.lock, cli/templates/extension/tests/integration_tests.rs.template, cli/tests/extension/mod.rs, crates/engine/schema/src/builder/coerce/extension.rs, crates/engine/schema/src/subgraph.rs, crates/grafbase-sdk/Cargo.toml, crates/grafbase-sdk/mock/Cargo.toml, crates/grafbase-sdk/mock/src/builder.rs, crates/grafbase-sdk/mock/src/lib.rs, crates/grafbase-sdk/src/test.rs, crates/grafbase-sdk/src/test/config.rs, crates/grafbase-sdk/src/test/runner.rs, crates/runtime-local/src/wasi/extensions.rs, extensions/jwt/Cargo.lock, extensions/rest/Cargo.lock, extensions/rest/Cargo.toml, extensions/rest/definitions.graphql, extensions/rest/src/lib.rs, extensions/rest/src/types.rs, extensions/rest/tests/integration_tests.rs
=> fix: fix the rest extension, add tests to get many

cli/tests/integration/data/Cargo.lock, crates/engine/operation/src/bind/coercion/query.rs, crates/engine/operation/src/bind/coercion/variable.rs, crates/engine/schema/src/builder/coerce/error.rs, crates/engine/schema/src/builder/coerce/extension.rs, crates/engine/schema/src/builder/coerce/path.rs, crates/engine/schema/src/builder/coerce/schema.rs, crates/engine/schema/src/builder/error.rs, crates/engine/schema/src/builder/extension/mod.rs, crates/engine/schema/src/builder/graph/field_set.rs, crates/integration-tests/tests/federation/extensions/mod.rs, crates/integration-tests/tests/federation/extensions/validation/default_value.rs, crates/integration-tests/tests/federation/extensions/validation/definition.rs, crates/integration-tests/tests/federation/extensions/validation/enum_.rs, crates/integration-tests/tests/federation/extensions/validation/fields.rs, crates/integration-tests/tests/federation/extensions/validation/list.rs, crates/integration-tests/tests/federation/extensions/validation/mod.rs, crates/integration-tests/tests/federation/extensions/validation/non_null.rs, crates/integration-tests/tests/federation/extensions/validation/scalar/big_int.rs, crates/integration-tests/tests/federation/extensions/validation/scalar/boolean.rs, crates/integration-tests/tests/federation/extensions/validation/scalar/custom.rs, crates/integration-tests/tests/federation/extensions/validation/scalar/float.rs, crates/integration-tests/tests/federation/extensions/validation/scalar/id.rs, crates/integration-tests/tests/federation/extensions/validation/scalar/int.rs, crates/integration-tests/tests/federation/extensions/validation/scalar/mod.rs, crates/integration-tests/tests/federation/extensions/validation/scalar/string.rs
Various tests for coercion & fixes.
=> fix(engine): Add validation tests & fixes

extensions/jwt/README.md
I will link to this in our docs.
=> chore: add simple README to the JWT extension

.github/workflows/rust-prs.yml, cli/src/backend/dev/extensions.rs, cli/tests/extension/mod.rs, cli/tests/integration/dev.rs, cli/tests/integration/setup.rs
=> Make windows CI run again, skip some tests to ensure it is green

Cargo.lock, cli/CHANGELOG.md, cli/Cargo.toml, cli/changelog/0.84.8.md, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
Re-release of 0.84.7 after release pipeline issues have been resolved.
=> cli: release 0.84.8

crates/graphql-composition/CHANGELOG.md, crates/graphql-composition/src/diagnostics.rs, crates/graphql-composition/src/ingest_subgraph/directives.rs, crates/graphql-composition/src/ingest_subgraph/directives/consts.rs, crates/graphql-composition/src/ingest_subgraph/directives/match_name.rs, crates/graphql-composition/src/ingest_subgraph/schema_definitions.rs, crates/graphql-composition/src/subgraphs.rs, crates/graphql-composition/src/subgraphs/strings.rs, crates/graphql-composition/tests/composition/compose_directive_different_definitions/federated.graphql.snap, crates/graphql-composition/tests/composition/subgraph_defining_join__Graph/federated.graphql.snap, crates/graphql-composition/tests/composition/unknown_directives/api.graphql.snap, crates/graphql-composition/tests/composition/unknown_directives/federated.graphql.snap, crates/graphql-composition/tests/composition/unknown_directives/subgraphs/test.graphql, crates/graphql-composition/tests/composition/unknown_directives/test.md
=> graphql-composition: emit warnings when encountering unknown directives

Cargo.lock, crates/graphql-composition/CHANGELOG.md, crates/graphql-composition/Cargo.toml
Larger changes are coming, so let's do a bug fix release now.
=> graphql-composition: release 0.6.1

cli/src/backend/dev.rs, cli/src/backend/dev/hot_reload.rs, crates/graphql-composition/src/diagnostics.rs
=> cli: show composition warnings in grafbase dev

extensions/rest/README.md, extensions/rest/definitions.graphql, extensions/rest/tests/integration_tests.rs
Let's use the new toys immediately, shall we?
=> feat: default value for rest body input

crates/engine/auth/src/jwt.rs, crates/engine/schema/src/config/auth.rs, crates/gateway-config/src/authentication.rs, crates/gateway-config/src/lib.rs
Any of the configured audiences is accepted, when multiple are provided.
=> gateway: allow multiple audiences in jwks config

crates/federated-server/src/server/gateway.rs
Automerge was faster than me. @tom suggested this in the review.
=> chore: use empty hashmap for ext config, if not defined

extensions/nats/tests/integration_tests.rs
We will need these later, wanted to do the dedup already but we realized it's much more work than expected. Pushing the test already.
=> chore: expand the subscribe test a bit

cli/Cargo.toml, cli/src/main.rs, crates/integration-tests/Cargo.toml, crates/integration-tests/src/lib.rs, extensions/jwt/Cargo.lock, extensions/nats/Cargo.lock, extensions/rest/Cargo.lock, gateway/Cargo.toml, gateway/src/main.rs
https://lobste.rs/s/yclvqy/ring_is_unmaintained
=> fix: switch to aws-lc-rs crypto

Cargo.lock, cli/tests/extension/mod.rs, crates/grafbase-sdk/Cargo.toml, crates/grafbase-sdk/src/host_io/pubsub/nats.rs, crates/grafbase-sdk/wit/world.wit, crates/wasi-component-loader/src/extension/instance.rs, crates/wasi-component-loader/src/extension/types_impl/nats.rs, extensions/jwt/Cargo.lock, extensions/nats/Cargo.lock, extensions/nats/definitions.graphql, extensions/nats/src/config.rs, extensions/nats/src/lib.rs, extensions/nats/src/types.rs, extensions/nats/tests/integration_tests.rs, extensions/rest/Cargo.lock
request: I NEED HELP!!!111
reply: I CAN HELP!!!111
=> feat: nats request/reply

.github/renovate.json
Closes https://github.com/grafbase/grafbase/issues/2750
=> fix: json sucks

Cargo.lock, Cargo.toml, crates/federated-server/Cargo.toml, crates/federated-server/src/server.rs, crates/grafbase-workspace-hack/Cargo.toml, crates/integration-tests/Cargo.toml, crates/integration-tests/tests/federation/basic/headers.rs, crates/integration-tests/tests/federation/compression.rs, crates/integration-tests/tests/federation/mod.rs
Add support for gzip, br, zstd and deflate.
=> feat(gateway): Add client compression support (Accept-Encoding).

extensions/jwt/Cargo.lock, extensions/nats/Cargo.lock, extensions/nats/README.md, extensions/nats/definitions.graphql, extensions/nats/tests/integration_tests.rs, extensions/rest/Cargo.lock, extensions/rest/README.md, extensions/rest/definitions.graphql
Just... take a look how we can utilize jq filters with subscriptions. This is a really powerful feature.
=> docs: nats readme, add a few more tests

extensions/rest/definitions.graphql, extensions/rest/extension.toml, extensions/rest/src/lib.rs, extensions/rest/src/types.rs, extensions/rest/tests/integration_tests.rs
=> chore: make rest directives a bit more lean

extensions/jwt/Cargo.lock, extensions/nats/Cargo.lock, extensions/nats/definitions.graphql, extensions/nats/extension.toml, extensions/rest/Cargo.lock, extensions/rest/definitions.graphql
=> fix: use json templates in selections

Cargo.lock, cli/Cargo.toml, cli/src/backend/api/client.rs, cli/src/backend/api/extension_publish.rs, cli/src/backend/api/graphql/api.graphql, cli/src/backend/api/graphql/mod.rs, cli/src/backend/api/graphql/types/mod.rs, cli/src/backend/api/graphql/types/mutations.rs, cli/src/backend/api/graphql/types/mutations/extension_publish.rs, cli/src/backend/api/mod.rs, cli/src/cli_input.rs, cli/src/cli_input/extension.rs, cli/src/cli_input/sub_command.rs, cli/src/extension.rs, cli/src/extension/build.rs, cli/src/extension/publish.rs, cli/tests/extension/mod.rs, cli/tests/extension/publish.rs, cli/tests/integration_tests.rs, crates/grafbase-sdk/src/test/runner.rs, crates/grafbase-workspace-hack/Cargo.toml, extensions/jwt/Cargo.lock, extensions/nats/Cargo.lock
=> cli: add grafbase extension publish

cli/src/backend/api/extension_versions_by_version_requirement.rs, cli/src/backend/api/graphql/types/mod.rs, cli/src/backend/api/graphql/types/mutations.rs, cli/src/backend/api/graphql/types/mutations/extension_versions_by_version_requirement.rs, cli/src/backend/api/mod.rs, cli/src/cli_input/extension.rs, cli/src/cli_input/sub_command.rs, cli/src/extension.rs, cli/src/extension/publish.rs, cli/src/extension/update.rs, cli/src/output/report.rs, cli/tests/extension/mod.rs, cli/tests/extension/snapshots/integration_tests__extension__update__update_all_extensions.snap, cli/tests/extension/snapshots/integration_tests__extension__update__update_specific_extensions-2.snap, cli/tests/extension/update.rs, crates/extension/src/lib.rs, crates/extension/src/lockfile.rs, crates/extension/src/lockfile/v1.rs
Create and update lockfiles.
closes GB-8578
=> cli: add grafbase extension update

cli/src/cli_input/extension.rs, cli/src/extension.rs, cli/src/extension/install.rs, cli/src/output/report.rs, crates/extension/src/directory.rs, crates/extension/src/lib.rs
=> cli: add grafbase extension install command

.github/workflows/build-gateway-chart.yml, gateway/helm/Chart.yaml, gateway/helm/README.md, gateway/helm/values.yaml
Add gateway documentation and CD pipeline
=> Add gateway documentation and CD pipeline

.github/workflows/build-gateway-chart.yml
Parameterize the username used to login to the helm registry.
=> Parameterize the username used to login to the helm registry

crates/wasi-component-loader/src/extension/instance.rs, extensions/nats/tests/integration_tests.rs
If we subscribe once, then disconnect, then subscribe again we get a poison error.
This fixes it until we get proper dedup and channels, when we can do something smarter.
=> fix: proper stream cancellation without poisoning

cli/src/extension/build.rs, extensions/jwt/Cargo.lock, extensions/jwt/extension.toml, extensions/nats/Cargo.lock, extensions/nats/extension.toml, extensions/rest/Cargo.lock, extensions/rest/extension.toml
=> cli: include readme in manifest in grafbase extension build

extensions/jwt/README.md, extensions/jwt/extension.toml, extensions/nats/README.md, extensions/nats/extension.toml, extensions/rest/README.md, extensions/rest/extension.toml
Also update the examples in the rest extension readme, they don't work anymore.
=> Update extension README install instructions

Cargo.lock
I have no idea who merged something to main without tests complaining. But we can't run any tests on any PRs because the lock file was not updated in main.
=> fix: oh no, a rogue cargo lock that was not merged

extensions/nats/README.md, extensions/nats/extension.toml, extensions/rest/extension.toml
Rest: already published, for debugging.
Nats: remove field_resolvers
=> Release new versions of nats, rest extensions

crates/engine/src/execution/response_modifier.rs, crates/engine/src/prepare/cached/query_plan/field/data.rs, crates/engine/src/prepare/operation_plan/model/field.rs, crates/engine/src/prepare/operation_plan/model/plan.rs, crates/engine/src/resolver/extension/mod.rs, crates/engine/src/resolver/extension/query_or_mutation.rs, crates/engine/src/resolver/extension/subscription.rs, crates/engine/src/resolver/mod.rs, crates/engine/src/response/data.rs, crates/engine/src/response/path.rs, crates/engine/src/response/write/deserialize/object/concrete.rs, crates/engine/src/response/write/mod.rs, crates/integration-tests/src/federation/runtime/extension.rs, crates/integration-tests/tests/federation/extensions/basic.rs, crates/integration-tests/tests/federation/extensions/injection/field_set/arguments/mod.rs, crates/integration-tests/tests/federation/extensions/injection/template/json.rs, crates/integration-tests/tests/federation/extensions/mod.rs, crates/integration-tests/tests/federation/extensions/resolver/errors.rs, crates/integration-tests/tests/federation/extensions/resolver/mod.rs, crates/integration-tests/tests/federation/extensions/validation/mod.rs, extensions/nats/tests/integration_tests.rs, extensions/rest/tests/integration_tests.rs
slightly better error handling and simplified the subscription part
=> chore: Add extra resolver tests + simplifications

gateway/helm/Chart.yaml, gateway/helm/templates/pdb.yaml
=> add PDB for gw

gateway/changelog/helm-0.2.2.md
Publish workflow [fails](https://github.com/grafbase/grafbase/actions/runs/13784944798/job/38552960492) without this
=> add  release notes for the helm release

.github/workflows/gateway-partial-release.yml, .github/workflows/grafbase-partial-release.yml, cli/install/upload.sh
So... The issue was we had a crc command for the s3 ls, which does not exist. We can remove that and custom aws cli installations.
=> fix: aws upload fix for good

.gitignore, crates/wasi-component-loader/examples/Cargo.lock, crates/wasi-component-loader/examples/extensions/auth-08/Cargo.toml, crates/wasi-component-loader/examples/extensions/auth-08/src/lib.rs, crates/wasi-component-loader/examples/extensions/auth-09/Cargo.toml, crates/wasi-component-loader/examples/extensions/auth-09/src/lib.rs, crates/wasi-component-loader/examples/extensions/resolver-08/.gitignore, crates/wasi-component-loader/examples/extensions/resolver-08/Cargo.toml, crates/wasi-component-loader/examples/extensions/resolver-08/definitions.graphql, crates/wasi-component-loader/examples/extensions/resolver-08/extension.toml, crates/wasi-component-loader/examples/extensions/resolver-08/src/lib.rs, crates/wasi-component-loader/examples/extensions/resolver-08/tests/integration_tests.rs, crates/wasi-component-loader/examples/extensions/resolver-09/.gitignore, crates/wasi-component-loader/examples/extensions/resolver-09/Cargo.toml, crates/wasi-component-loader/examples/extensions/resolver-09/definitions.graphql, crates/wasi-component-loader/examples/extensions/resolver-09/extension.toml, crates/wasi-component-loader/examples/extensions/resolver-09/src/lib.rs, crates/wasi-component-loader/src/tests/extensions.rs
We should keep the extensions repo using the latest and greatest, and test the older sdk versions here.
=> chore: add a few smoke tests for older sdk versions

.github/actions/test/action.yml, .github/workflows/binaries.yml, .github/workflows/rust-prs.yml
=> fix(gb-8682): run the release tests with sccache

gateway/Dockerfile
upgrade the package for gateway container
=> upgrade the package for gateway container

crates/engine/error/src/lib.rs, crates/engine/src/execution/request/header_rule.rs, crates/engine/src/execution/request/mod.rs, crates/engine/src/prepare/operation_plan/query_modifications.rs, crates/graphql-mocks/src/lib.rs, crates/integration-tests/tests/federation/extensions/authentication/mod.rs, crates/integration-tests/tests/federation/extensions/authentication/static_token.rs, crates/integration-tests/tests/federation/extensions/authorization/headers.rs, crates/integration-tests/tests/federation/extensions/authorization/mod.rs, crates/integration-tests/tests/federation/extensions/mod.rs
Adding simple tests for headers modifications in authorization extensions & authentication tests
=> chore(extensions): Add integration-tests for authorization headers modifications

crates/wasi-component-loader/src/extension/runtime/subscription/dedup.rs
This was causing new instances to be created if subscribing fast enough. Not anymore.
=> fix(gb-8698): fix race with subscription dedup

cli/src/backend/api/check.rs, cli/src/backend/api/graphql/api.graphql, cli/src/backend/api/graphql/types/mutations.rs, cli/src/check.rs, cli/src/output/report.rs
The API has changed a bit since last update, use the fresher fields too.
closes GB-8734
=> cli: show custom check errors and warnings

Cargo.lock, cli/CHANGELOG.md, cli/Cargo.toml, cli/changelog/0.88.0.md, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
**Features**
- Added support for custom check diagnostics in `grafbase check` (https://github.com/grafbase/grafbase/pull/2898)
=> cli: release 0.88.0

cli/src/backend/api/branch.rs, cli/src/backend/api/check.rs, cli/src/backend/api/client.rs, cli/src/backend/api/create.rs, cli/src/backend/api/extension_publish.rs, cli/src/backend/api/extension_versions_by_version_requirement.rs, cli/src/backend/api/publish.rs, cli/src/backend/api/schema.rs, cli/src/backend/api/subgraphs.rs, cli/src/backend/api/submit_trusted_documents.rs, cli/src/backend/dev/subgraphs.rs, cli/src/cli_input/sub_command.rs, cli/src/common/environment.rs
Extensions are public, the user does not have to be logged in to run that command.
The same goes for `grafbase extension update`.
=> cli: remove requirement to be logged in to run `grafbase extension install`

gateway/helm/Chart.yaml, gateway/helm/templates/deployment.yaml, gateway/helm/values.yaml
add a lifecycle value for the chart
=> add a lifecycle value

gateway/Dockerfile
=> add default user for docker

crates/federated-server/src/server/gateway.rs, crates/federated-server/src/server/gateway/create_extension_catalog.rs, crates/gateway-config/src/extensions.rs, crates/gateway-config/src/lib.rs, crates/integration-tests/src/federation/runtime/extension/builder.rs, crates/runtime-local/src/wasi/hooks.rs, crates/wasi-component-loader/src/config.rs, crates/wasi-component-loader/src/extension/api.rs, crates/wasi-component-loader/src/extension/api/since_0_10_0/mod.rs, crates/wasi-component-loader/src/extension/manager/config.rs, crates/wasi-component-loader/src/extension/manager/instance.rs, crates/wasi-component-loader/src/extension/manager/loader.rs, crates/wasi-component-loader/src/extension/mod.rs, crates/wasi-component-loader/src/lib.rs
They weren't mentioning `grafbase extension install` at all.
=> chore: better error message for extension loading

crates/engine/src/prepare/operation_plan/model/field.rs, crates/engine/src/prepare/operation_plan/model/selection_set.rs, crates/engine/src/resolver/extension/selection_set/mod.rs, crates/grafbase-sdk/src/component/extension.rs, crates/grafbase-sdk/src/component/selection_set_resolver.rs, crates/grafbase-sdk/src/extension/selection_set_resolver.rs, crates/grafbase-sdk/wit/since_0_14_0/selection-set-resolver.wit, crates/integration-tests/src/federation/runtime/extension/impls/selection_set_resolver.rs, crates/runtime/src/extension/selection_set_resolver.rs, crates/wasi-component-loader/src/extension/api/since_0_10_0/instance/selection_set_resolver.rs, crates/wasi-component-loader/src/extension/api/since_0_14_0/instance/selection_set_resolver.rs, crates/wasi-component-loader/src/extension/api/since_0_14_0/mod.rs, crates/wasi-component-loader/src/extension/api/since_0_14_0/wit/mod.rs, crates/wasi-component-loader/src/extension/api/since_0_14_0/wit/resolver_types.rs, crates/wasi-component-loader/src/extension/api/since_0_14_0/wit/schema.rs, crates/wasi-component-loader/src/extension/api/since_0_14_0/wit/selection_set_resolver_types.rs, crates/wasi-component-loader/src/extension/api/since_0_8_0/instance/selection_set_resolver.rs, crates/wasi-component-loader/src/extension/api/since_0_9_0/instance/selection_set_resolver.rs, crates/wasi-component-loader/src/extension/manager/instance/selection_set_resolver.rs, crates/wasi-component-loader/src/extension/runtime/selection_set_resolver.rs
Hook up the selection set resolver in host wasm code
=> feat(wasm): Connect selection set resolver

cli/src/extension/build.rs, crates/grafbase-sdk/src/types/resolver.rs, crates/grafbase-sdk/src/types/schema.rs, crates/grafbase-sdk/src/types/selection_set.rs, crates/integration-tests/data/extensions/Cargo.lock, crates/integration-tests/data/extensions/crates/selection-set-resolver-014/Cargo.toml, crates/integration-tests/data/extensions/crates/selection-set-resolver-014/definitions.graphql, crates/integration-tests/data/extensions/crates/selection-set-resolver-014/extension.toml, crates/integration-tests/data/extensions/crates/selection-set-resolver-014/src/lib.rs, crates/integration-tests/tests/gateway/extensions/selection_set_resolver/backwards_compatibility.rs, crates/integration-tests/tests/gateway/extensions/selection_set_resolver/mod.rs
Add a simple initial test that we can call the wasm extension and a few SDK fixes
=> chore: Add initial selection-set-resolver wasm test + SDK fixes

cli/src/backend/dev.rs, cli/src/cli_input/sub_command.rs, cli/src/output/report.rs
=> CLI output tweaks

crates/federated-server/src/server/mcp/server.rs, crates/integration-tests/tests/gateway/mcp.rs
`query/accessTokens` becomes `accessTokensQuery` etc.
=> suffix MCP tools

Cargo.lock, crates/federated-server/Cargo.toml, crates/federated-server/src/server.rs, crates/grafbase-sdk/src/extension/resolver.rs, crates/mcp/Cargo.toml, crates/mcp/src/lib.rs, crates/mcp/src/server.rs
=> chore: move MCP to separate crate

Cargo.lock, Cargo.toml, crates/grafbase-sdk/wit/since_0_14_0/grpc.wit, crates/grafbase-sdk/wit/since_0_14_0/world.wit, crates/grafbase-workspace-hack/Cargo.toml, crates/wasi-component-loader/Cargo.toml, crates/wasi-component-loader/src/extension/api/since_0_14_0/wit/grpc.rs, crates/wasi-component-loader/src/extension/api/since_0_14_0/wit/grpc/client.rs, crates/wasi-component-loader/src/extension/api/since_0_14_0/wit/grpc/streaming_response.rs, crates/wasi-component-loader/src/extension/api/since_0_14_0/wit/mod.rs, crates/wasi-component-loader/src/lib.rs, crates/wasi-component-loader/src/resources/mod.rs, crates/wasi-component-loader/src/state.rs
Subscriptions implementation is left blank for now.
closes GB-8841
=> gateway: WIT and host support for gRPC

crates/grafbase-sdk/src/host_io.rs, crates/grafbase-sdk/src/host_io/grpc.rs, crates/grafbase-sdk/src/lib.rs
=>  grafbase-sdk: gRPC host io

Cargo.lock, Cargo.toml, crates/engine/schema/src/entity.rs, crates/engine/schema/src/lib.rs, crates/engine/src/engine.rs, crates/grafbase-workspace-hack/Cargo.toml, crates/integration-tests/tests/gateway/mcp/basic.rs, crates/integration-tests/tests/gateway/mcp/mod.rs, crates/integration-tests/tests/gateway/mcp/search.rs, crates/mcp/Cargo.toml, crates/mcp/src/lib.rs, crates/mcp/src/server.rs, crates/mcp/src/tools/mod.rs, crates/mcp/src/tools/search.rs
Adding a search tool to find the relevant context in a big schema for MCP
=> feat(mcp): Add search tool

cli/templates/extension/src/resolver.rs.template, cli/tests/extension/mod.rs, crates/grafbase-sdk/changelog/unreleased.md, crates/grafbase-sdk/src/component/extension.rs, crates/grafbase-sdk/src/extension/field_resolver.rs, crates/grafbase-sdk/src/host_io/grpc.rs, crates/grafbase-sdk/wit/since_0_14_0/grpc.wit, crates/wasi-component-loader/src/extension/api/since_0_14_0/wit/grpc/client.rs, crates/wasi-component-loader/src/extension/api/since_0_14_0/wit/grpc/streaming_response.rs, crates/wasi-component-loader/src/extension/api/since_0_14_0/wit/mod.rs, crates/wasi-component-loader/src/resources/mod.rs
Tested with the extension, the host <> extension contract works now.
closes GB-8895
closes GB-8896
=> extensions: implement grpc streaming responses (host+sdk)

crates/grafbase-sdk/build.rs, crates/grafbase-sdk/src/host_io/postgres.rs, crates/grafbase-sdk/src/host_io/postgres/connection.rs, crates/grafbase-sdk/src/host_io/postgres/query.rs, crates/grafbase-sdk/src/host_io/postgres/types.rs, crates/grafbase-sdk/src/lib.rs, crates/grafbase-sdk/src/types/schema.rs, crates/grafbase-sdk/wit/since_0_14_0/schema.wit, crates/wasi-component-loader/src/extension/api/since_0_14_0/instance/mod.rs, crates/wasi-component-loader/src/extension/api/since_0_14_0/instance/utils.rs, crates/wasi-component-loader/src/extension/runtime/selection_set_resolver.rs
A few things I needed when building the extension side of things.
=> feat(gb-8838): sdk fixes for postgres extension

crates/protoc-gen-grafbase-subgraph/src/render_graphql_sdl/schema_directives.rs, crates/protoc-gen-grafbase-subgraph/tests/snapshots/codegen_tests__graphql file@birds__nested.proto.snap, crates/protoc-gen-grafbase-subgraph/tests/snapshots/codegen_tests__graphql file@echo__echo.proto.snap, crates/protoc-gen-grafbase-subgraph/tests/snapshots/codegen_tests__graphql file@routeguide__route_guide.proto.snap, crates/protoc-gen-grafbase-subgraph/tests/snapshots/codegen_tests__graphql file@taqueria__tacotruck.proto.snap, crates/protoc-gen-grafbase-subgraph/tests/snapshots/codegen_tests__graphql file@well-known-types__wkt.proto.snap
...with what the extension expects.
=> protoc-gen-grafbase-subgraph: align schema directive argument names

crates/protoc-gen-grafbase-subgraph/src/translate_schema.rs, crates/protoc-gen-grafbase-subgraph/tests/snapshots/codegen_tests__graphql file@echo__echo.proto.snap, crates/protoc-gen-grafbase-subgraph/tests/snapshots/codegen_tests__graphql file@routeguide__route_guide.proto.snap, crates/protoc-gen-grafbase-subgraph/tests/snapshots/codegen_tests__graphql file@taqueria__tacotruck.proto.snap
Should be the last fix for the initial release
=> protoc-gen-grafbase-subgraph: make sure service names are qualified in generated code

.github/workflows/protoc-gen-grafbase-subgraph-release.yml
Releases are currently failing: https://github.com/grafbase/grafbase/actions/runs/14493792927
=> ci: align protoc-gen-grafbase-subgraph release job with others

cli/src/backend/dev.rs, cli/src/extension/install.rs, cli/src/output/report.rs
=> less verbose extension installation

Cargo.lock, gateway/CHANGELOG.md, gateway/Cargo.toml, gateway/changelog/0.36.0.md
Let's get this rolling so we can start playing with Postgres.
=> chore: bump gateway to 0.36.0

cli/src/extension/build.rs
=> cli: statically enforce new_command() arg is not user provided

crates/graphql-composition/CHANGELOG.md, crates/graphql-composition/src/subgraphs.rs, crates/graphql-composition/src/subgraphs/definitions.rs, crates/graphql-composition/src/subgraphs/ids.rs, crates/graphql-composition/src/subgraphs/keys.rs, crates/graphql-composition/src/subgraphs/top.rs, crates/graphql-composition/src/subgraphs/unions.rs, crates/graphql-composition/src/subgraphs/walker.rs, crates/graphql-composition/src/validate.rs, crates/graphql-composition/src/validate/selection.rs, crates/graphql-composition/tests/composition/entity_interfaces_with_requires/subgraphs/a.graphql, crates/graphql-composition/tests/composition/entity_interfaces_with_requires/subgraphs/b.graphql, crates/graphql-composition/tests/composition/entity_invalid_key/federated.graphql.snap, crates/graphql-composition/tests/composition/entity_invalid_key/subgraphs/policies.graphql, crates/graphql-composition/tests/composition/entity_invalid_key/test.md
=> graphql-composition: validate the selection sets on @key

Cargo.lock, cli/CHANGELOG.md, cli/Cargo.toml, cli/changelog/0.93.3.md, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json
- Fixed fonts issue in the `grafbase dev` web app.
=> cli: release 0.93.3

Cargo.lock, cli/tests/extension/authorization.rs, cli/tests/extension/mod.rs, crates/grafbase-sdk/Cargo.toml, crates/graphql-composition/CHANGELOG.md, crates/graphql-composition/Cargo.toml, crates/graphql-federated-graph/Cargo.toml
We need this to publish new postgres version.
=> feat(gb-8961): update sdk, composition and federated graph

cli/src/extension/install.rs, cli/src/output/report.rs
=> Update extension installation progress bar style

gateway/helm/Chart.yaml, gateway/helm/values.yaml
Improve the security context for gateway deployment.
=> improve the security context for gateway deployment

cli/src/extension/install.rs
=> cli: make extension downloads lazy in grafbase extension install and dev

Cargo.lock, crates/grafbase-sdk/Cargo.toml, crates/grafbase-sdk/src/types/configuration.rs
Might be relevant in other places, not sure. But it's definitely useful
here as default serde errors aren't very clear and today it's not even
obvious that it's a configuration error.
=> feat(sdk): better config deserialization error

examples/postgres-extension/app.js, examples/postgres-extension/grafbase/federated-graph.graphql, examples/postgres-extension/grafbase/inventory.graphql, examples/postgres-extension/grafbase/postgres-inventory.toml, examples/postgres-extension/grafbase/products.graphql, examples/postgres-extension/index.html, examples/postgres-extension/inventory.sql
Also modify the example to join inventory data in the second table for variants.
=> chore(gb-9066): fix key directive and add a join in postgres example

Cargo.lock, cli/Cargo.toml, cli/changelog/0.96.0.md, cli/npm/aarch64-apple-darwin/package.json, cli/npm/aarch64-unknown-linux-musl/package.json, cli/npm/cli/package.json, cli/npm/x86_64-apple-darwin/package.json, cli/npm/x86_64-pc-windows-msvc/package.json, cli/npm/x86_64-unknown-linux-musl/package.json, crates/grafbase-sdk/mock/src/lib.rs, crates/grafbase-sdk/src/host_io/kafka.rs, crates/grafbase-sdk/src/host_io/kafka/consumer.rs, crates/grafbase-sdk/src/host_io/kafka/producer.rs, crates/grafbase-sdk/src/test/config.rs, crates/grafbase-sdk/wit/since_0_16_0/kafka-client.wit, crates/wasi-component-loader/src/extension/api/since_0_16_0/wit/kafka_client.rs, crates/wasi-component-loader/src/extension/api/since_0_16_0/wit/mod.rs, crates/wasi-component-loader/src/resources/kafka_consumer.rs, crates/wasi-component-loader/src/resources/mod.rs, gateway/Cargo.toml, gateway/changelog/0.39.0.md
We consume all partitions, but do not track offsets yet.
=> feat(gb-9116): host side of the kafka consumer

cli/changelog/unreleased.md, cli/src/api/create.rs, cli/src/api/graphql/types/queries/fetch_organization_by_slug.rs, cli/src/api/graphql/types/queries/mod.rs, cli/src/create.rs
=> cli: make create command work with organization access tokens

crates/graphql-composition/CHANGELOG.md, crates/graphql-composition/src/compose/object.rs, crates/graphql-composition/src/composition_ir/directive.rs, crates/graphql-composition/src/emit_federated_graph/context/used_directives.rs, crates/graphql-composition/src/emit_federated_graph/directive.rs, crates/graphql-composition/src/ingest_subgraph/directives.rs, crates/graphql-composition/src/ingest_subgraph/directives/consts.rs, crates/graphql-composition/src/ingest_subgraph/directives/match_name.rs, crates/graphql-composition/tests/composition/composite_schemas_internal_basic/api.graphql.snap, crates/graphql-composition/tests/composition/composite_schemas_internal_basic/federated.graphql.snap, crates/graphql-composition/tests/composition/composite_schemas_internal_basic/subgraphs/base.graphql, crates/graphql-composition/tests/composition/composite_schemas_internal_basic/subgraphs/origin.graphql, crates/graphql-composition/tests/composition/composite_schemas_internal_basic/test.md, crates/graphql-federated-graph/src/directives/mod.rs, crates/graphql-federated-graph/src/render_sdl/directive.rs, crates/graphql-federated-graph/src/render_sdl/render_api_sdl.rs, crates/graphql-federated-graph/src/render_sdl/render_api_sdl/visibility.rs
=> graphql-composition: implement @internal from composite schemas spec

cli/tests/integration/data/Cargo.lock, crates/engine/src/prepare/trusted_documents.rs, crates/federated-server/src/lib.rs, crates/federated-server/src/server.rs, crates/federated-server/src/server/gateway.rs, crates/federated-server/src/server/graph_fetch_method.rs, crates/federated-server/src/server/graph_updater.rs, crates/federated-server/src/server/graph_updater/gdn.rs, crates/federated-server/src/server/trusted_documents_client.rs, crates/gateway-config/src/trusted_documents.rs, gateway/changelog/unreleased.md, gateway/tests/integration_tests.rs, gateway/tests/mocks/gdn.rs, gateway/tests/mocks/mod.rs, gateway/tests/telemetry/metrics.rs, gateway/tests/telemetry/metrics/gdn.rs
This reverts commit 30e7fbfa7aacc2ded8d9f6bda874e1a87957a210.
=> Revert "gateway: replace GDN with new object storage"

Cargo.lock, Cargo.toml, cli/src/cli_input.rs, cli/src/cli_input/mcp.rs, cli/src/mcp.rs, cli/tests/integration/mcp.rs, crates/federated-server/src/server.rs, crates/gateway-config/src/lib.rs, crates/gateway-config/src/mcp.rs, crates/integration-tests/Cargo.toml, crates/integration-tests/src/gateway/mod.rs, crates/integration-tests/src/gateway/request/mcp.rs, crates/integration-tests/tests/gateway/mcp/api_use_case.rs, crates/integration-tests/tests/gateway/mcp/basic.rs, crates/integration-tests/tests/gateway/mcp/execute.rs, crates/integration-tests/tests/gateway/mcp/introspect.rs, crates/integration-tests/tests/gateway/mcp/search.rs, crates/integration-tests/tests/gateway/mcp/verify.rs, crates/mcp/Cargo.toml, crates/mcp/src/lib.rs
=> mcp: make transport configurable, default to http stream

.github/workflows/binaries.yml, .github/workflows/rust-prs.yml
- **fix(ci): fix binaries workflow**
- **fix(ci): Add proper permissions**
=> fix main workflow 2

Cargo.lock, crates/operation-normalizer/Cargo.toml, crates/operation-normalizer/src/sanitize/value.rs, crates/operation-normalizer/src/tests/normalize.rs, crates/operation-normalizer/src/tests/sanitize.rs, devenv.nix
Use insta instead of expect.
Keep object structure if possible.
=> chore: Improve operation sanitization

crates/engine/schema/src/builder/coerce/field_selection_map/mod.rs, crates/engine/schema/src/builder/coerce/field_selection_map/model.rs, crates/engine/schema/src/builder/coerce/field_selection_map/target.rs, crates/engine/schema/src/builder/graph/directives/composite/derive.rs, crates/engine/schema/src/builder/graph/directives/composite/injection/auto_detect.rs, crates/engine/schema/src/builder/graph/directives/composite/injection/explicit.rs, crates/engine/schema/src/builder/graph/directives/composite/lookup.rs, crates/engine/schema/src/builder/graph/directives/composite/require.rs, crates/engine/schema/src/builder/graph/selections.rs, crates/engine/schema/src/field_set/mod.rs, crates/engine/schema/src/injection/mod.rs, crates/engine/src/prepare/cached/query_plan/field/arguments.rs, crates/engine/src/response/read/view/ser.rs, crates/integration-tests/tests/gateway/composite/derive/is.rs, crates/integration-tests/tests/gateway/composite/lookup/is/batch/mod.rs, crates/integration-tests/tests/gateway/composite/lookup/is/batch/nested_input.rs, crates/integration-tests/tests/gateway/composite/lookup/is/batch/oneof.rs, crates/integration-tests/tests/gateway/composite/lookup/is/single/composite.rs, crates/integration-tests/tests/gateway/composite/lookup/is/single/mod.rs, crates/integration-tests/tests/gateway/composite/lookup/is/single/nested_input.rs, crates/integration-tests/tests/gateway/composite/lookup/is/single/nested_key.rs, crates/integration-tests/tests/gateway/composite/lookup/is/single/oneof.rs
=> fix: Better handling of FieldSelectionMap

.claude/settings.local.json, crates/gateway-config/src/telemetry/mod.rs, crates/telemetry/src/otel/metrics.rs, crates/telemetry/src/otel/traces.rs, gateway/src/args.rs, gateway/src/args/lambda.rs, gateway/src/args/std.rs, gateway/src/config.rs, gateway/src/main.rs
Expose the configuration and effectly adding support for sending telemetry through http rather than grpc.
Fixes: GB-9485
=> feat(gateway): Expose grafbase telemetry config

crates/integration-tests/data/mtls-subgraph/Cargo.lock, crates/integration-tests/data/mtls-subgraph/Cargo.toml, crates/integration-tests/data/mtls-subgraph/src/main.rs
Just super annoying whenever I reboot my Linux.
=> chore: add graceful shutdown to mtls subgraph

crates/graphql-composition/CHANGELOG.md, crates/graphql-composition/src/subgraphs/fields.rs, crates/graphql-composition/src/validate/selection.rs, crates/graphql-composition/tests/composition/entity_invalid_key/diagnostics.snap, crates/graphql-composition/tests/composition/provides/provides_with_invalid_selection_set/diagnostics.snap, crates/graphql-composition/tests/composition/requires_not_providing_required_argument/diagnostics.snap, crates/graphql-composition/tests/composition/requires_with_arguments_validation/diagnostics.snap, crates/graphql-composition/tests/composition/requires_with_invalid_inline_fragment/diagnostics.snap, crates/graphql-composition/tests/composition/unknown_directives/diagnostics.snap
=>  graphql-composition: add subgraph name to selection set errors 

Cargo.lock, cli/tests/extension/types/authentication.rs, cli/tests/extension/types/authorization.rs, cli/tests/extension/types/contracts.rs, cli/tests/extension/types/hooks.rs, cli/tests/extension/types/resolver.rs, crates/grafbase-sdk/Cargo.toml, crates/grafbase-sdk/src/lib.rs, crates/wasi-component-loader/examples/Cargo.lock, examples/authorization/Dockerfile.gateway, examples/authorization/extensions/Cargo.lock, examples/authorization/extensions/Cargo.toml, examples/authorization/extensions/hooks/src/lib.rs
and fix sdk doc, somehow got lost
=> update authorization example

crates/engine/schema/src/builder/graph/directives/cache.rs, crates/engine/schema/src/builder/graph/directives/federation.rs, crates/engine/schema/src/builder/graph/directives/mod.rs, crates/engine/schema/src/builder/graph/directives/resolvers.rs, crates/engine/schema/src/builder/sdl/directives.rs
We spend quite a lot of time parsing the join_type directives as we need at many different places.
=> improve gateway startup time

crates/engine/query-solver/src/post_process/root_typename.rs, crates/engine/query-solver/src/query/mod.rs, crates/engine/query-solver/src/solution_space/builder/mod.rs, crates/engine/query-solver/src/solve/deduplication/map.rs, crates/engine/query-solver/src/solve/deduplication/mod.rs, crates/engine/query-solver/src/solve/mod.rs, crates/engine/query-solver/src/solve/solution.rs
Refactor solution creation with a Builder and separate functions, especially for the somewhat clunky derived field handling and move deduplication to the solve module, it's only relevant there.
=> move deduplication into solve module

crates/graphql-composition/README.md
=> graphql-composition: document what specs we support and extensions
